### ISSUE TITLE
Create Weave topology with info from the Weave router (or equivalent in another topology)

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#100]
So we can display the topology of weave router connections.

**Comment by tomwilkie** [comment]
This is pending #123.

I propose we add a new topology in the probe reports, which contains the weave nodes and their connections, and as much metadata as I can cleave out of weave.  How does that sound?

**Comment by peterbourgon** [comment]
This is done, though we don't have connections. We can open another ticket for that. It would involve modifying the Weave router /status-json to expose that information, somehow.
