### ISSUE TITLE
Node shape spacing to node labels is too small

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1003]
![screen shot 2016-02-22 at 14 48 27](https://cloud.githubusercontent.com/assets/444037/13221462/787e8e78-d973-11e5-876e-2868292ea327.png)

**Comment by foot** [comment]
![anim](https://cloud.githubusercontent.com/assets/22008/13224366/7fab2976-d988-11e5-9d3b-9c3659eaf497.gif)
