### ISSUE TITLE
Implement https://checkpoint-api.weave.works 

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1007]
Following on #907 . It causes errors in the scope logs:

```
<probe> ERRO: 2016/02/23 09:24:28.648003 Error checking version: Unknown status: 400
```

We should probably silence the error until the endpoint is implemented.

**Comment by tomwilkie** [comment]
It is implemented. You'll only see this in Dev versions, as the version
were posting to checkpoint is not a valid semantic version.

**Comment by tomwilkie** [comment]
I'm going to have checkpoint treat dev instances differently, so it doesn't return an error.

**Comment by tomwilkie** [comment]
I've fixed checkpoint so it doesn't error on dev versions
