### ISSUE TITLE
Alarming errors on weaveDNS in deployments without weave

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1008]
Now Scope periodically checks for weave being started as a result of #867 .

However, this results in somehow alarming errors in deployments without Weave Net:

```
$ docker logs weavescope |& grep weaveDNS
<app> ERRO: 2016/02/23 09:24:29.108373 Error updating weaveDNS, backing off 20s: Error running weave expose: exit status 1
<app> ERRO: 2016/02/23 09:24:49.424425 Error updating weaveDNS, backing off 40s: Error running weave expose: exit status 1
<app> ERRO: 2016/02/23 09:25:29.732988 Error updating weaveDNS, backing off 1m0s: Error running weave expose: exit status 1
``` 

I understand those errors are legitimate and that we want to make those checks by default.

You can disable this by doing `--probe.weave.router.addr ""`  but that's not very intuitive (and inconvenient). I would suggest either/or:

* Lowering the alarming tone of those errors.
* Adding an extra more-intuitive flag: `--disable.weave` ?

**Comment by tomwilkie** [comment]
Can do. I'd would add that the errors go away once you hit max back off.
