### ISSUE TITLE
Probe plugins should be able to add controls.

### ISSUE THREAD

**Issue by alban** [weaveworks/scope#1022]
I would like to have control plugins in Weave Scope so users could do more actions on containers from the Scope UI. See also #554 for similar ideas on probe plugins.

My use case is to simulate bad network in containers with the netem queuing discipline. I would like users to be able to configure latency, bandwidth, percentage packet drop on egress and ingress for each connection. The Scope UI would take care of sending the commands to the right node and the actual work of configuring the traffic control rules could be delegated to a control plugin.

I started to write a daemon that receives commands on D-Bus to configure the traffic control rules:
https://github.com/kinvolk/tcd
A traffic control plugin for Scope could either send the D-Bus commands to tcd, or just include the golang code to do the job.

**Comment by tomwilkie** [comment]
I plan on doing this as part of #554.  Maybe get a chance next week.

**Comment by faddat** [comment]
@alban @tomwilkie okay BUT

Can you please call the "bad network" mode "comcast"?

**Comment by tomwilkie** [comment]
We've added plugins in 0.14, but they don't have the ability to respond to control requests yet.

We're probably not going to add it in 0.15 unless the feedback on plugins is very strong.  But its a candidate for 0.16.

**Comment by faddat** [comment]
This isn't something I am in a desperate hurry for, but I do want to say
that it sounds positively awesome :).

**Comment by faddat** [comment]
@ozzadar

**Comment by alepuccetti** [comment]
In the traffic control plugin, we [add controls](https://github.com/weaveworks/scope/blob/master/examples/plugins/traffic-control/report.go) from the plugin into the container details view.
I suppose that this issue can be closed by https://github.com/weaveworks/scope/issues/554 or I am missing something?

**Comment by 2opremio** [comment]
Yes, but it's closed by https://github.com/weaveworks/scope/pull/1837
