### ISSUE TITLE
Simple pause button

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1025]
I would like to explore a curious looking graph I can see, but it keeps evolving and I cannot keep track of the changes occurring.

**Comment by davkal** [comment]
What's your expectation on what will happen when you hit play again? (1) Updates were buffered and are now fast-forwared (2) Updates were dropped and a fresh chart is redrawn

**Comment by errordeveloper** [comment]
#2 will be fine by me, given it's communicated clearly.

**Comment by foot** [comment]
Yeah this would be awesome for debugging sometimes too.

Elements panel keeps getting updated and the node you were inspecting disappears grr.
