### ISSUE TITLE
k8s: Make possible and simple to deploy a Scope probe in master node

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1030]
The current k8s instructions https://github.com/weaveworks/scope#using-weave-scope-with-kubernetes result in Scope probes only deployed in the worker nodes but not on master.

CC @errordeveloper

**Comment by errordeveloper** [comment]
Thanks for raising this, @2opremio. Right now I cannot think of a good solution, but let's think of it.

**Comment by 2opremio** [comment]
After asking in the kubernetes Slack Channel, I was pointed to https://github.com/kubernetes/kubernetes/blob/80ff0cbbda4418ab40a383e08ab6f55244219e52/docs/design/taint-toleration-dedicated.md

Apparently the master node is just a another node marked as `unschedulable`

Full conversation transcript: https://kubernetes.slack.com/archives/kubernetes-users/p1456341662005360

**Comment by 2opremio** [comment]
Also, it seems that after 1.2 Daemon sets will also deployed to master so it may be a matter of waiting.

Another thing we could try is hardcoding the node of a pod to the master node and see if that works.

**Comment by errordeveloper** [comment]
Sounds good, as long as we consider master without kubelet being a rare case, which is probably true for those using vanilla setup. I have considered changing Kubernetes Anywhere to adhere to the self-hosting model, but at least in it's current state, it hardly makes things easy to understand in my opinion. That's off-topic here, I think we need to enable majority of users with an existing cluster.

**Comment by errordeveloper** [comment]
Would be great to confirm GKE will adhere to this.

**Comment by errordeveloper** [comment]
Also, a custom-ish setup, e.g. Kubernetes Anywhere or [kubespray](https://github.com/kubespray/setup-kubernetes), it's not hard to start Scope via whatever provisioning tool used, however authentication to API server requires configuration and it would be good to find out if the API client library respect some environment variables that one can leverage.

**Comment by errordeveloper** [comment]
For the cases where master components are not running as pods, one simply needs to launch the probes in the usual way. However, those probes need to discover the app somehow, which something we need to document, i.e. suggest to expose the app through a load-balancer or use WeaveDNS.

**Comment by 2opremio** [comment]
I haven't found a way to fix this with kubernetes 1.2 . 

On top of the options listed above, there's [`kubectl uncordon`](https://github.com/kubernetes/kubernetes/blob/master/docs/user-guide/kubectl/kubectl_uncordon.md) which would make the master node schedulable, but this doesn't seem available before 1.2 .

**Comment by 2opremio** [comment]
We should confirm this but it seems kubernetes 1.2 will deploy the probes in the master node:

> DaemonSet pods will be created on nodes with .spec.unschedulable=true and will not be evicted from nodes whose Ready condition is false.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md

**Comment by tomwilkie** [comment]
Can confirm, this works:
```
Toms-Mac-Pro:service twilkie$ kubectl patch node gke-twilkie-test-default-pool-b6168979-n7n4  -p '{"spec": {"unschedulable": true}}'
"gke-twilkie-test-default-pool-b6168979-n7n4" patched
Toms-Mac-Pro:service twilkie$ kubectl get nodes
NAME                                          STATUS                     AGE
gke-twilkie-test-default-pool-b6168979-extp   Ready                      13m
gke-twilkie-test-default-pool-b6168979-fquf   Ready                      13m
gke-twilkie-test-default-pool-b6168979-n7n4   Ready,SchedulingDisabled   13m
Toms-Mac-Pro:service twilkie$ kubectl create -f k8s/local/scope/scope-app-rc.yaml
replicationcontroller "weave-scope-app" created
Toms-Mac-Pro:service twilkie$ kubectl create -f k8s/local/scope/scope-app-svc.yaml
service "weave-scope-app" created
Toms-Mac-Pro:service twilkie$ kubectl create -f k8s/local/scope/scope-probe-ds.yaml
daemonset "weave-scope-probe" created
Toms-Mac-Pro:service twilkie$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                                READY     STATUS    RESTARTS   AGE
kube-system   fluentd-cloud-logging-gke-twilkie-test-default-pool-b6168979-extp   1/1       Running   0          14m
kube-system   fluentd-cloud-logging-gke-twilkie-test-default-pool-b6168979-fquf   1/1       Running   0          13m
kube-system   fluentd-cloud-logging-gke-twilkie-test-default-pool-b6168979-n7n4   1/1       Running   0          14m
kube-system   heapster-v1.0.2-574809716-5nobl                                     2/2       Running   0          13m
kube-system   kube-dns-v11-oqyvt                                                  4/4       Running   0          14m
kube-system   kube-proxy-gke-twilkie-test-default-pool-b6168979-extp              1/1       Running   0          14m
kube-system   kube-proxy-gke-twilkie-test-default-pool-b6168979-fquf              1/1       Running   0          13m
kube-system   kube-proxy-gke-twilkie-test-default-pool-b6168979-n7n4              1/1       Running   0          14m
kube-system   kubernetes-dashboard-v1.0.1-d5r6d                                   1/1       Running   0          14m
kube-system   l7-lb-controller-v0.6.0-kqimx                                       2/2       Running   0          14m
kube-system   weave-scope-app-jw67w                                               1/1       Running   0          24s
kube-system   weave-scope-probe-8kjnl                                             1/1       Running   0          12s
kube-system   weave-scope-probe-gne8k                                             1/1       Running   0          12s
kube-system   weave-scope-probe-uuupj                                             1/1       Running   0          12s
```

**Comment by 2opremio** [comment]
Reopening, since we should add this to the k8s documentation

**Comment by 2opremio** [comment]
> Toms-Mac-Pro:service twilkie$ kubectl patch node gke-twilkie-test-default-pool-b6168979-n7n4  -p '{"spec": {"unschedulable": true}}'

`kubectl uncordon gke-twilkie-test-default-pool-b6168979-n7n4`  should be a simpler

**Comment by 2opremio** [comment]
@tomwilkie What version was that cluster running?

It actually seems to work out of the box on gcloud with 1.2. Without any scheduling changes all nodes get a probe:

```
manzanon:weave fons$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
manzanon:weave fons$ kubectl get nodes
NAME                                       STATUS    AGE
gke-fons-test-default-pool-c3a05af1-3m8m   Ready     1d
gke-fons-test-default-pool-c3a05af1-dm34   Ready     1d
gke-fons-test-default-pool-c3a05af1-tjv3   Ready     1d
manzanon:weave fons$ kubectl get pods
NAME                        READY     STATUS    RESTARTS   AGE
auth-2438279588-xoy6r       1/1       Running   0          1d
frontend-3616253037-wvv68   1/1       Running   0          17h
hello-4088345290-37u6i      1/1       Running   0          18h
hello-4088345290-g06aw      1/1       Running   0          18h
hello-4088345290-q86l5      1/1       Running   0          1d
weave-scope-app-2qo94       1/1       Running   0          18h
weave-scope-probe-2yxcl     1/1       Running   0          18h
weave-scope-probe-ktu0m     1/1       Running   0          18h
weave-scope-probe-tf2sy     1/1       Running   0          18h
manzanon:weave fons$ 
```

**Comment by 2opremio** [comment]
Reopening since we should document this will only work for versions >=1.2

**Comment by errordeveloper** [comment]
So am I getting this correct that it's all about putting scope in `kube-system` namespace?

**Comment by tomwilkie** [comment]
> So am I getting this correct that it's all about putting scope in kube-system namespace?

No, the namespace is completely unrelated.

The problem was probes were not being scheduled on unschedulable hosts.  As of kube 1.2 they are.  End of story.

**Comment by errordeveloper** [comment]
@tomwilkie ok, thanks.
