### ISSUE TITLE
Dancing nodes when nodes are added/removed

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1033]
![](http://g.recordit.co/LSN1HfG7lC.gif)

Report: [service_report.json.gz](https://github.com/weaveworks/scope/files/146491/service_report.json.gz)

It would be good if we could reduce the layout impact when removing/adding nodes.

**Comment by rade** [comment]
This is especially visible when there is node churn, i.e. lots of short-lived nodes.

**Comment by rade** [comment]
@davkal so is #1993 supposed to fix this? Looks like we feature-flagged that; what's the follow-up?

**Comment by davkal** [comment]
The followup: @2opremio and @pidster, could you please alert me if you see any more dancing? And then while you see it, we can turn on the new heuristics. This requires a bit of interactivity, I'm afraid.

If nothing comes up in the next 30 days, we should close this issue.

**Comment by 2opremio** [comment]
I haven't seen this in a while. These days I am more concerned about the lack of danceability ( https://github.com/weaveworks/scope/issues/1935 ). In demos systematically find myself pressing the refresh button.

**Comment by rade** [comment]
> If nothing comes up in the next 30 days, we should close this issue.

30 days is up.
