### ISSUE TITLE
Increase 100-node limit

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1034]
<img width="1766" alt="screen shot 2016-02-25 at 14 16 39" src="https://cloud.githubusercontent.com/assets/2362916/13322218/50da4b6e-dbcb-11e5-9294-872bb38f1a68.png">

Report: [service_report.json.gz](https://github.com/weaveworks/scope/files/146491/service_report.json.gz)

**Comment by tomwilkie** [comment]
As per some discussion on twitter, I propose we just remove it.
