### ISSUE TITLE
Kubernetes view breaks UI

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1035]
<img width="1771" alt="screen shot 2016-02-25 at 14 30 12" src="https://cloud.githubusercontent.com/assets/2362916/13322454/5f685d00-dbcc-11e5-9bae-fc5be05e8fd9.png">

Report: [service_report.json.gz](https://github.com/weaveworks/scope/files/146491/service_report.json.gz)

Also, after the error, the UI doesn't recover (switching to other views doesn't work). I had to refresh the browser.

**Comment by foot** [comment]
![screen shot 2016-02-25 at 16 01 33](https://cloud.githubusercontent.com/assets/22008/13323395/8ddadb9c-dbd9-11e5-9cd8-02b9409581a1.png)
