### ISSUE TITLE
Arranging nodes by name

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1036]
In a graph like above it'd be nice to see nodes order on the basis of their names.
<img width="907" alt="screenshot 2016-02-25 13 45 04" src="https://cloud.githubusercontent.com/assets/251467/13322557/e4390430-dbcc-11e5-81b4-c27d90c48cf6.png">

**Comment by tomwilkie** [comment]
Ideally we should detect fully-connected cliques and lay them out in a better way:
![fully connected](https://cloud.githubusercontent.com/assets/444037/13404211/875fa33a-df10-11e5-98a0-36d8fbcc6c09.jpeg)

**Comment by tomwilkie** [comment]
Related to #1299

**Comment by rade** [comment]
As @tomwilkie says, the example given is an instance of #1092.
