### ISSUE TITLE
k8s: Incorrect container count in pod-view

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1044]
The metrics pod (from the service) has 5 containers, not one:

<img width="1707" alt="screen shot 2016-02-26 at 10 02 58" src="https://cloud.githubusercontent.com/assets/2362916/13350104/d46e1b18-dc75-11e5-8877-c0a82cdbd49c.png">

Report: [report_wrong_pod_container_count.json.gz](https://github.com/weaveworks/scope/files/148113/report_wrong_pod_container_count.json.gz)

**Comment by tomwilkie** [comment]
metrics pod != monitoring pod.  Metrics report periodically dumps to BI, monitoring pod containers all the jazz:

![screen shot 2016-02-29 at 18 34 14](https://cloud.githubusercontent.com/assets/444037/13404748/13af359c-df13-11e5-8617-4bf20398e7d4.png)
