### ISSUE TITLE
k8s: Crash in UI when viewing details of service node

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1046]
<img width="1710" alt="screen shot 2016-02-26 at 11 44 38" src="https://cloud.githubusercontent.com/assets/2362916/13351416/68b3a1be-dc7e-11e5-8f09-06540dfda757.png">

Report: [report_service_node_crash.json.gz](https://github.com/weaveworks/scope/files/148120/report_service_node_crash.json.gz)

**Comment by davkal** [comment]
Can reproduce.

**Comment by davkal** [comment]
Fixed via #1047
