### ISSUE TITLE
Add controls and pipes (terminal/logs) for hosts

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1049]
This will greatly simplify administration tasks.

For logs we could use journalctl (or syslog).

**Comment by tomwilkie** [comment]
Dupe of #1016 (tty for host)?

What controls can you think of for a host?

**Comment by 2opremio** [comment]
> Dupe of #1016 (tty for host)?

Partly, I edited the description to include logs too.

**Comment by tomwilkie** [comment]
What are host logs?  Unlike a container, there is very little standardisation here.   I'd say just offer a shell and allow people to `tail -f /var/log/messages` in them.

**Comment by tomwilkie** [comment]
I'm going to close as dupe of #1016 here.

**Comment by 2opremio** [comment]
Please don't close this before at least create a separate ticket for the logs.

> What are host logs? Unlike a container, there is very little standardisation here. I'd say just offer a shell and allow people to tail -f /var/log/messages in them.

I think we can potentially do better than that.
