### ISSUE TITLE
All pseudo nodes are grouped together in the "grouped" view

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#105]
This seems undesirable, implying relationships between unrelated services.

Whats more, they don't have a label in the UI.

Options to fix this include:
- just group by IP
- apply same grouping logic as in #99
- don't show them

**Comment by peterbourgon** [comment]
> implying relationships between unrelated services.

The relationship is that they don't share a defined grouping characteristic. Exactly the same as the Internet node — i.e. a collection of nodes that we don't know much about beyond mere existence.

That said, happy to use the same grouping logic as #99, or simply not show them, as long as we document the decision in the code.

**Comment by tomwilkie** [comment]
I'll take a stab at apply the logic from #99 to this, and see what happens.
