### ISSUE TITLE
terminals: use bash instead of /bin/sh if available 

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1053]
I always find myself frustrated with the limitations of sh (no history, no edition ...) and the first thing I do is run bash.

Other options instead of prioritizing bash specifically:
* Check /etc/passwd (I am not sure this makes a lot of sense for containers)
* Somehow make it a user-configuration option

In my opinion, considering its widespread use, trying to default to bash sounds sane.

**Comment by tomwilkie** [comment]
> Somehow make it a user-configuration option

We don't really have a mechanism for user configuration right now, other than command line flags.  I think it would be weird to put this there...

> Check /etc/passwd (I am not sure this makes a lot of sense for containers)

This might work:
```
Toms-MacBook-Pro:scope twilkie$ docker run --rm alpine /bin/sh -c 'getent passwd root | cut -d: -f7'
/bin/ash
Toms-MacBook-Pro:scope twilkie$ docker run --rm ubuntu /bin/sh -c 'getent passwd root | cut -d: -f7'
/bin/bash
Toms-MacBook-Pro:scope twilkie$ docker run --rm debian /bin/sh -c 'getent passwd root | cut -d: -f7'
/bin/bash
```

And then just fork that.

**Comment by 2opremio** [comment]
> This might work:

Good! We also need a fallback scenario in case it doesn't work.

```/bin/sh -c "TERM=xterm exec $(getent passwd root | cut -d: -f7 2>/dev/null || echo /bin/sh)"```

**Comment by rade** [comment]
How does `docker attach` do this?

**Comment by 2opremio** [comment]
> How does `docker attach` do this?

Uhm, it doesn't. This is docker exec.
