### ISSUE TITLE
Docker changed the format of image IDs

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1058]
<img width="428" alt="screen shot 2016-02-29 at 12 04 57" src="https://cloud.githubusercontent.com/assets/250199/13394064/791dbaec-dedd-11e5-86fa-251ce108449d.png">

Inspecting it still works, but the truncation is a bit short now.

**Comment by davkal** [comment]
@paulbellamy is the prefix part of the ID (as in it can be copied and pasted into docker CLI)? What are the implications of removing the prefix in the BE?

**Comment by paulbellamy** [comment]
docker prepends `sha256:` in certain circumstances (i.e. as part of `docker inspect)`. You can query with or without it. Both work the same.

Removing it in BE should be fine.

**Comment by paulbellamy** [comment]
Per discussion elsewhere, removing the prefix in the BE should be fine, but truncating in the BE means no full-text in the tooltip.
