### ISSUE TITLE
Improvements to the display of truncated text in the detail panel

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1059]
In the context of the detail panel:
- [ ] A truncated text field must be indicated by appending a triple dot '...'
- [ ] The tooltip of a truncated text field must contain only the un-truncated text
- [ ] When clicking a truncated text field, the un-truncated text must be copied to the clipboard
- [ ] When clicking a truncated text field, user feedback should indicate that something happened (flash the bg, perhaps?)

**Comment by davkal** [comment]
Are there any instances where tooltip-contains-untruncated-text is violated?

Was there any user feedback that it's hard to get text data out of the scope UI?

**Comment by pidster** [comment]
> Are there any instances where tooltip-contains-untruncated-text is violated?

Yes. Container view, detail panel, Info section, field ID contains the truncated text version of the ID rather than the untruncated.

**Comment by davkal** [comment]
> Yes. Container view, detail panel, Info section, field ID contains the truncated text version of the ID rather than the untruncated, also Image ID.

Only getting the 12-letter ID from the backend.

@pidster could you break out the 12-letter ID limitation into a new issue? this issue feels like a mixed bag.

**Comment by pidster** [comment]
> Was there any user feedback that it's hard to get text data out of the scope UI?

This issue is about consistency of approach for truncated text fields, not about particular user feedback, and it is no less valid because of it.

**Comment by davkal** [comment]
> This issue is about consistency of approach for truncated text fields, not about particular user feedback, and it is no less valid because of it.

Looks like we're pretty consistent in the UI code. I'd consider copy on click a new feature. Close this issue?

**Comment by pidster** [comment]
> could you break out the 12-letter ID limitation into a new issue? this issue feels like a mixed bag.

Filed https://github.com/weaveworks/scope/issues/1139.

**Comment by davkal** [comment]
Closing this issue, because:

* mixed issues
* UI rendering is not inconsistent

If copy-on-click sounds like a good feature, please open a separate issue.

**Comment by davkal** [comment]
For completeness: imageID render issues will be handled in #1058
