### ISSUE TITLE
Details disappear from the details pane

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1064]
See video: http://recordit.co/tDmK67mnx5

Report: [report_details_disappear.json.gz](https://github.com/weaveworks/scope/files/151321/report_details_disappear.json.gz)

Tentatively labelled as a UI-bug although it may be the backend's fault.

**Comment by 2opremio** [comment]
As you can see in the video, this was in a k8s cluster.

**Comment by davkal** [comment]
Yup, the child tables are missing in the response from the backend.

**Comment by davkal** [comment]
We think it's fixed (shortcut reports werent tagged correctly). Needs verification.

**Comment by 2opremio** [comment]
I just verified this is fixed:
* I could reproduce it again with 0.13.1
* The problem went away when deploying #1300
