### ISSUE TITLE
Weaveworks logo in downloaded graph SVG is yuge.

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1071]
The logo is excessively large, it should be small enough that it is a discrete addition to the image.

**Comment by pidster** [comment]
Further info & correction. This feature works as expected in Chrome, Firefox.

In Safari, when the button is clicked the browser opens a URL similar to: "blob:http://192.168.99.100:4040/a57d0b50-82a5-409d-aa79-01f0a7d5d727"
(note the "blob:" prefix)

An example of the result:

<img width="1280" alt="safari-is-weird" src="https://cloud.githubusercontent.com/assets/303151/13424998/fc45c87e-df9b-11e5-9ca8-be2f8eb6275c.png">

**Comment by davkal** [comment]
The logo is weavescope. Should we mention weaveworks too, @pidster ?

**Comment by pidster** [comment]
Scope is fine for now, for the record.
