### ISSUE TITLE
Scope runs weave ps a little aggressively...

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1078]
Every 10s backing off to 1min...

Also `weave expose` invocation should be done with --local.

**Comment by bboreham** [comment]
The implementation of `weave ps` is mostly in Go now, at https://github.com/weaveworks/weave/blob/master/prog/weaveutil/addrs.go

`weave ps` in the script calls that code with a list of container IDs obtained from `docker ps`, plus `"weave:expose"` which is the bridge address (if any).
