### ISSUE TITLE
Child tables disappear in Host view 

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1079]
Child tables appear initially, but disappear within a second.

<img width="1280" alt="host-child-tables-gone" src="https://cloud.githubusercontent.com/assets/303151/13427767/1ac7ed88-dfae-11e5-82b2-9569046e63f9.png">

Seems to only happen in an environment where Kubernetes is present - I can't replicate it with other apps.

(Scope 0.13, browser Chrome)

**Comment by davkal** [comment]
@pidster got a report? I cant reproduce.

**Comment by 2opremio** [comment]
Dupe of #1064 . @davkal there's a report and video there.
