### ISSUE TITLE
Make node outer border stroke consistent width

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1080]
Single node borders are thicker than the border on a stack.
The single node should use the same smaller value for border width as the stack.

<img width="653" alt="thick" src="https://cloud.githubusercontent.com/assets/303151/13427938/237f9a38-dfaf-11e5-98f8-8f1820a41560.png">

<img width="634" alt="thin-stack" src="https://cloud.githubusercontent.com/assets/303151/13427939/239cc130-dfaf-11e5-8c87-e43d8917442e.png">

**Comment by davkal** [comment]
Just tried it. They look too heavy.

Single:
![screen shot 2016-03-01 at 16 18 57](https://cloud.githubusercontent.com/assets/859729/13431332/52a40ed8-dfc9-11e5-8325-0de6ba19cc5a.png)

Stack original:

![screen shot 2016-03-01 at 16 21 20](https://cloud.githubusercontent.com/assets/859729/13431424/a6760dd6-dfc9-11e5-8a66-b6e6f1be36c5.png)


Stack 1px thicker, spacing increased by 2px:
![screen shot 2016-03-01 at 16 19 32](https://cloud.githubusercontent.com/assets/859729/13431354/65db010a-dfc9-11e5-99e1-264d1a9d6a4d.png)

Visually, I'd vote against it. 
WDYT @foot ?
Is there another aspect? @pidster
