### ISSUE TITLE
Tags in header of Container view detail panel erroneously shows all hosts with container

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1081]
The image shows the detail panel of a container, where the tags listed include all of the hosts in which the container image is present (or possibly just all of the hosts), instead of only the host in which this container is running.

<img width="425" alt="ping-tags" src="https://cloud.githubusercontent.com/assets/303151/13428037/be714f28-dfaf-11e5-9ff1-171a8e1d165d.png">

**Comment by tomwilkie** [comment]
This is the same k8s bug as #1093
