### ISSUE TITLE
nodes layed out on top of each other

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1089]
![screenshot from 2016-03-01 22 07 25](https://cloud.githubusercontent.com/assets/109109/13443713/39850e80-dffa-11e5-892c-3b28e9b33f98.png)

This happened after I clicked the 'SHOW stopped containers' button. Before that it looks like this:
![screenshot from 2016-03-01 22 15 07](https://cloud.githubusercontent.com/assets/109109/13443890/1b628d50-dffb-11e5-85d9-e84afea5bc4b.png)

Clicking show/hide toggles between these two views; it's totally stable.

And here's it what the first view looks like after clicking the 'redraw' button:

![screenshot from 2016-03-01 22 18 45](https://cloud.githubusercontent.com/assets/109109/13443988/a9e41d00-dffb-11e5-94f6-b192489bc2ed.png)

**Comment by davkal** [comment]
Fixed in #1159
