### ISSUE TITLE
`docker rename` not reflected in the UI

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1091]
1. launch scope
2. `docker run --name=foo -dti ubuntu` -> 'foo' shows up in scope
3. `docker rename foo bar` -> no change, even after waiting for a few minutes, clicking redraw, switching views etc

Note that the host details panel also shows the container as 'foo' instead of 'bar':
![screenshot from 2016-03-01 23 24 37](https://cloud.githubusercontent.com/assets/109109/13445568/e004518a-e004-11e5-884e-35daee24f7b6.png)

but it's definitely (now) called 'bar':
```
$ docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS               NAMES
8f1fc8133014        ubuntu                    "/bin/bash"              5 minutes ago       Up 5 minutes                            bar
d6ef255fe439        weaveworks/scope:latest   "/home/weave/entrypoi"   5 minutes ago       Up 5 minutes                            weavescope
```

Restarting scope didn't solve the problem either! However, reloading the page (or just clicking 'redraw') afterwards did.

**Comment by foot** [comment]
Mmm, we are not propagating these changes into the canvas very well atm, we have a fix in the metrics-on-canvas stuff.

**Comment by rade** [comment]
@tomwilkie was speculating that renames perhaps do not trigger docker events, and that docker events are the *only* thing that would currently prompt the probe to look at a container again.

**Comment by tomwilkie** [comment]
Yes this is a backend issue, although you're welcome to come play in goland @foot!

**Comment by foot** [comment]
hahah cheers @tomwilkie I will take you up on that one day.

Give us a shout if it doesn't propagate all the way through the JS layer though (w/out reloading the page).

**Comment by paulbellamy** [comment]
Am debating if we should also handle the `oom` event. There's no docker docs on when it is emitted, but I assume it is emitted when the container is oom-killed... Possibly it emits a destroy/die even also, though...
