### ISSUE TITLE
Distinguish between reporting hosts and containing hosts

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1093]
<img width="427" alt="screen shot 2016-02-26 at 02 06 28" src="https://cloud.githubusercontent.com/assets/2362916/13341148/e62a6836-dc2d-11e5-9589-2a24f99892d4.png">

The screenshot above is from #1043 . The Container is incorrectly attributed to 3 three hosts because the probes in those 3 hosts report kubernetes information about that same container.

**Comment by tomwilkie** [comment]
This is a bug in the kubernetes reporter: it generates container nodes which should not be tagged with the local probe host id.
