### ISSUE TITLE
Resizing the window and zooming in/out can confuse window size

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1096]
<img width="474" alt="screenshot 2016-03-02 15 45 18" src="https://cloud.githubusercontent.com/assets/251467/13465674/a2f57a6e-e08e-11e5-8397-9f0c8a8114bc.png">
<img width="934" alt="screenshot 2016-03-02 15 47 56" src="https://cloud.githubusercontent.com/assets/251467/13465675/a349cb78-e08e-11e5-8a4c-f07e504be0eb.png">

**Comment by errordeveloper** [comment]
I've only got this to happen after opening and closing Chrome inspector pane.

**Comment by foot** [comment]
Can repro.

1. Make browser window tiny.
2. reload
3. make browser window big.
4. hover on the tiny nodes to trigger redraw
5. poof
