### ISSUE TITLE
stopped/system containers hard to spot in sea of containers

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1116]
at the moment one can choose between
- showing system container or not
- showing stopped containers or not

However, if you have loads of running/non-system containers, then if you want to look at stopped/system containers they get lost in the sea of containers.

Suggestion: make the switches three-way:
- system - both - user (defaulting to 'user')
- stopped - both - running (defaulting to 'running')

**Comment by rade** [comment]
We could also have some distinct graphical element for stopped/system containers so even when they are shown in a sea of others they can still be picked out.

**Comment by tomwilkie** [comment]
Related: #1073

**Comment by rade** [comment]
I don't think visual cues are sufficient. Essentially what I was kinda looking for is being able to toggle between the system("behind the scenes") and application view, depending on whether I am monitoring/fiddling-with the former or the latter.

**Comment by rade** [comment]
sliders and three-way toggles:

![img_20160311_143922267](https://cloud.githubusercontent.com/assets/109109/13710577/314aad00-e7b2-11e5-966e-2da3a8a9ac0e.jpg)

Note in particular that the Function Selector. Cool to the left, Heat to the right, and Auto in the middle, since it's a mix of both.
