### ISSUE TITLE
Put pseudo nodes back into the container's view 

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1123]
Makes more sense to show connections now we have shapes.

Some work is needed to resolve pseudo nodes for long lived connections (where we don't see a pid for both ends).

**Comment by rade** [comment]
Won't this end up like the hybrid view of #552? If not, what's the difference?

**Comment by rade** [comment]
@tomwilkie ping

**Comment by tomwilkie** [comment]
It could be considered a step towards a Hybrid view, but I think it separate. We removed the pseudo nodes due to connection tracking issues.

**Comment by rade** [comment]
*how* does this differ from hybrid view? The pseudo nodes you mention would be for processes, correct? So this would end up showing containers and processes in the same view. Which is the hybrid view of #552.

**Comment by rade** [comment]
closing in favour of #552.
