### ISSUE TITLE
"uncontained" nodes clutter container view

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1129]
![screenshot from 2016-03-05 10 07 32](https://cloud.githubusercontent.com/assets/109109/13547068/2f476b3a-e2ba-11e5-9995-bec66af70dae.png)

If I was to draw the structure of that service on the whiteboard, I certainly would not be including any of the "uncontained" nodes. I might include the Internet, if my service was accessible from / talking to that. And I might include some uncontained processes if they are interacting with my service.

Possible fix: add a show/hide for Uncontained.

**Comment by 2opremio** [comment]
Related: #552

**Comment by 2opremio** [comment]
@rade Is it fair to phrase it as _As a user, I only want to see Uncontained nodes (probably expanded as processes) when they are communicating with my service components_?

If that's the case, we need a way to identify your service components.

> Possible fix: add a show/hide for Uncontained.

Do you want to hide them even if they are talking to your service or are part of your  service (this will happen in hybrid services)?

**Comment by rade** [comment]
>  Is it fair to phrase it as: _As a user, I only want to see Uncontained nodes (probably expanded as processes) when they are communicating with my service components_?

Yes.

> If that's the case, we need a way to identify your service components.

"all containers in the current view" is a good approximation.

> Do you want to hide them even if they are talking to your service or are part of your service.

For the show/hide, yes. But I really only proposed that as a quick fix. Doing the showing/hiding automatically along the lines you suggest would probably work better.

**Comment by 2opremio** [comment]
> "all containers in the current view" is a good approximation.

This assumes that services are fully containerized, which may not be the case.

**Comment by rade** [comment]
The hybrid view of #552 might well be *the* solution to this, effectively eliminating the notion of "Uncontained" from the UI altogether.

**Comment by pidster** [comment]
I think the hybrid view should be the default one and the other views be straightforward filters.

**Comment by pidster** [comment]
We're seeing this in the reference application too.

<img width="1167" alt="reference-app-noise" src="https://cloud.githubusercontent.com/assets/303151/15937614/8703c974-2e67-11e6-8f84-cf8f231d9e50.png">
