### ISSUE TITLE
Pseudo nodes in containers view should be "uncontained", surely?

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#113]
Its weird for the containers view to have three types of nodes - containers, everything not in a container, and hosts.

I think pseudo nodes in containers should either be hidden of uncontained.  I'm guessing the whole pseudo node thing is going to have to become a little more sophisticated - maybe a per-topology pseudo node factory (ie callback)?

**Comment by peterbourgon** [comment]
We can definitely extend the [topology registry](https://github.com/weaveworks/scope/blob/8a735b4d8de8a94d4c67ea15a856800071867ca8/app/router.go#L43-52) to parameterize the treatment of pseudonodes. But I don't quite follow your goals. Can you explain a bit further what you want to accomplish?

**Comment by tomwilkie** [comment]
(This is a bit of a thought-in-progress) I think psuedo nodes should be the same "kind" as the topology we're injecting them into,

- process topology - pseudo nodes should be our best approximation of processes (see #99)
- container topology - pseudo nodes should be hidden, or grouped into "uncontained"
- host topology - pseudo nodes should be hosts (we can do this very well)
- process name (process grouped) - maybe hidden? definitely not all grouped into one.
- container image (container grouped) - hidden; no way to know what image they're running

What do you think?

**Comment by tomwilkie** [comment]
This is basically fixed.
