### ISSUE TITLE
scope ate all my memory and filled the logs with pipe smoke

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1131]
my scope app (not running any probes, but having three remote probes connected to it) grew from ~100M of memory to 4GB in a few minutes.

Looking at the logs, it got filled with entries like this:
```
<app> INFO: 2016/03/05 13:26:22.300462 Error copying to pipe pipe-7056809847050908959 (1) websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> INFO: 2016/03/05 13:26:22.302325 Pipe success pipe-7056809847050908959 (1)
<app> INFO: 2016/03/05 13:26:22.302803 Error copying to pipe pipe-7056809847050908959 (1) websocket: websocket: close 1006 (abnormal closure): unexpected EOF
<app> INFO: 2016/03/05 13:26:22.304774 Pipe success pipe-7056809847050908959 (1)
```
at a rate of ~450 per second!

I don't know whether those two symptoms are related.

**Comment by 2opremio** [comment]
Related to #1114 ?

**Comment by 2opremio** [comment]
I think this should be fixed. @rade Have you seen this again after reporting it?

**Comment by rade** [comment]
I haven't seen it recently, but I haven't been doing much with scope.

**Comment by rade** [comment]
Let's just assume it's fixed. -> closing.
