### ISSUE TITLE
inclusion of overlay connections in Hosts view is confusing

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1132]
Say I have three hosts which can only connect in a "chain" like...
![screenshot from 2016-03-05 17 44 14](https://cloud.githubusercontent.com/assets/109109/13549277/0b54825e-e2fa-11e5-861c-61a63956fac0.png)

But since I am running weave, the connectivity between containers does not have to follow this constrained topology, and instead might look like...
![screenshot from 2016-03-05 17 39 54](https://cloud.githubusercontent.com/assets/109109/13549285/2482ea7c-e2fa-11e5-8c8a-a3a078742759.png)

But when you do this, the Hosts view changes to...
![screenshot from 2016-03-05 17 45 08](https://cloud.githubusercontent.com/assets/109109/13549292/38a9d894-e2fa-11e5-9576-323bf1d3c320.png)

which is rather surprising and IMO confusing since the connectivity between hosts hasn't actually changed.

**Comment by tomwilkie** [comment]
Weave is fully meshed in this example, right?

**Comment by rade** [comment]
No. The weave peers are connected in a chain.

**Comment by tomwilkie** [comment]
I see. We've discussed / considered an 'overlay' view for this which I
think would be pretty straight forward to implement.

**Comment by rade** [comment]
> We've discussed / considered an 'overlay' view for this

Isn't it the other way round? i.e. the current 'Hosts' view is an overlay view, but what I really want is an 'underlay' view.

**Comment by tomwilkie** [comment]
This is more of a backend issue.
