### ISSUE TITLE
Error when parsing kernel version in proc background reader

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1136]
```
<probe> ERRO: 2016/03/07 12:20:57.204694 getNamespacePathSuffix: cannot get kernel version: Malformed version: 4.3.5-300.fc23.x86_64
```

Full logs https://gist.github.com/janwillies/54083a50358718a4fb21

**Comment by paulbellamy** [comment]
From [semver.org](http://semver.org/#spec-item-9), `4.3.5-300.fc23.x86_64` is not a valid version, as the pre-release section contains the `_` character. Based on googling, I'm assuming this is for [Fedora 23](http://www.crc.nd.edu/~sbogol/kmod/)?

**Comment by 2opremio** [comment]
I have no idea, this came from user jcw on scope-public: https://weaveworks.slack.com/archives/scope-public/p1457352064000743

I am getting a similar error in the Weaveworks ECS AMI:

```
<probe> ERRO: 2016/03/11 13:49:24.314985 getNamespacePathSuffix: cannot get kernel version: Malformed version: 4.1.17-22.30.amzn1.x86_64
```

My bad, for not looking into more version examples (and not adding a unit tests).
