### ISSUE TITLE
Container view, detail panel, info table, ID & IMAGE ID fields contain truncated text as tooltip

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1139]
Per https://github.com/weaveworks/scope/issues/1059.
The truncated text is not indicated with '...' and the tooltip is truncated text rather than untruncated text.
Same applies to the image id field.

<img width="416" alt="truncated-tooltip" src="https://cloud.githubusercontent.com/assets/303151/13576327/13c3ce22-e485-11e5-8b7d-6c496ed3d511.png">

**Comment by davkal** [comment]
The ID was truncated in the backend after it was agreed that we show container IDs in the same format as `docker ps` does.

Please reopen if new reasons exist why we should change this again.

**Comment by davkal** [comment]
For completeness: imageID render issues will be handled in #1058

**Comment by rade** [comment]
> The ID was truncated in the backend after it was agreed that we show container IDs in the same format as docker ps does.

What was the basis of the decision to have the field truncated *in the tooltip*? And where was that decision recorded? I have searched the issues and PRs but cannot find it. #924 and #930, which introduced this, don't even mention the truncation, let alone the rationale.

> Please reopen if new reasons exist why we should change this again.

Unless there is a very good reason, whenever we truncate information, the complete information should be contained in the tooltip.

Btw, note that `docker ps` has a `--no-trunc` option.

**Comment by davkal** [comment]
> What was the basis of the decision to have the field truncated in the tooltip? And where was that decision recorded?

There was no decision. The backend provides one value per field. The frontend renders that value, the browser provides the ellipsis if there is not enough space. The tooltip shows the same field value, but is not shortened by the browser because there is no space restriction.

> Unless there is a very good reason, whenever we truncate information, the complete information should be contained in the tooltip.

It's been decided in the last scop sync to remove the backend truncation. Then the full value will appear in the backend again.

**Comment by foot** [comment]
I know the commit/issue/pr where the truncation was introduced?

**Comment by rade** [comment]
> Anyone know the commit/issue/pr where the truncation was introduced?

See my comment above from a few months ago.
