### ISSUE TITLE
Pull data from docker stats

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#114]
Its seems to offer memory and cpu on a per-container basis.

Perhaps pulling memory and cpu from proc on a per-process basis would be better?

**Comment by peterbourgon** [comment]
We don't have a way to associate metadata to processes *or* containers at this stage, as they're both emergent entities from the underlying topologies. See my comments on #115. If we did what I proposed there, we could solve this issue, too. Shall I merge them and create a new issue?

**Comment by peterbourgon** [comment]
Merged to #120

**Comment by peterbourgon** [comment]
Re-opening as a supplementary ticket after for #123.

**Comment by peterbourgon** [comment]
This is merged and done.
