### ISSUE TITLE
More meaningful maximum value for metrics

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1149]
raised in https://github.com/weaveworks/scope/pull/1105#issuecomment-194216241

For CPU it should be based on number of cores (as it is now), but for memory we could get system memory available, and for fds we could check ulimit.

**Comment by paulbellamy** [comment]
If a container has a limit set on it's ram usage we should set that as the max, otherwise it should be the host max

**Comment by foot** [comment]
host.memory.max shows the correct value (memory that the host has).
