### ISSUE TITLE
navigation action from details panel to topology is non-obvious

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1151]
It took me ages to discover that there was a way to navigate back from the details panel to the topology, via the '<-->' button next to the close button.

Can we think of a more obvious way of perform this action?

One, perhaps too radical (and quite possibly already dismissed) approach would be to automatically update the topology view, so what you are seeing in the topology always corresponds to the top details panel.

**Comment by tomwilkie** [comment]
> One, perhaps too radical (and quite possibly already dismissed) approach would be to automatically update the topology view, so what you are seeing in the topology always corresponds to the top details panel.

We initially dismissed this as too intrusive, but given the back button works and node shape make the change so much more obvious, I think its worth reconsidering.

**Comment by foot** [comment]
Played w/ the details-panel-in-sync-with-topo behaviour
 1. it felt a little bit unintuitive and busy to me: navigation in a sub-view updating the whole UI, a lot of things changing in reaction to following a link.
 2. A bit slow on larger topos (though this could be eased w/ ui tricks: loading only the selected node and the data we have on it, into the topo while we wait for the topo to fully load etc)...

I played w/ less radical solution by bringing the shapes into the details panel (which is quite nice by itself), but then making them look more clickable when it is possible to click on them and jump-to-topo: (cursor transitions which help a lot here are not captured by my screen capturer: recordit)

![image](http://g.recordit.co/NBQA8ITxbw.gif)

**Comment by rade** [comment]
IMO it's not obvious that the shape is a control. Let alone what that control will do.

**Comment by 2opremio** [comment]
I think that the shape is a nice solution! I agree in clicking on it being controversial, so I would remove it for now.
