### ISSUE TITLE
Service running on Kubernetes doesn't render any expected edges

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1154]
[See report](https://www.dropbox.com/s/ho9cjhg5dnifqak/scope-report-kubecon-demo.json?dl=0).

**Comment by rade** [comment]
@errordeveloper a screenshot and explanation of what, specifically, you were expecting to see, would help.

**Comment by tomwilkie** [comment]
@errordeveloper ping?  We'll close this otherwise.

**Comment by tomwilkie** [comment]
I suspect the following was happening:
- kube proxy was running in a container
- this container was not associated with a pod
- non-pod containers were being filtered out.

Since #1350 this is no longer the case, so you should no see edges to 'Unmanaged' here.
