### ISSUE TITLE
Newline in terminal isn't functioning correctly

### ISSUE THREAD

**Issue by danpilch** [weaveworks/scope#1158]
New lines do not appear to be working in the terminal. When you get to the end of a line it wraps back onto the same line and overwrites existing text. See attached screenshot (bottom line):

![v2pslcn](https://cloud.githubusercontent.com/assets/4631652/13670336/307e6250-e6c1-11e5-8794-e9d5d1f9e20f.png)

**Comment by tomwilkie** [comment]
@foot is this something you could take a look at please?

**Comment by foot** [comment]
Yes! I'm having a bit of a play.

@danpilch 
- Which version of scope are you running?
- Does the wrapping issue happen in `sh`/`bash` as well as `cqlsh`?

That would help a lot! Ta

**Comment by danpilch** [comment]
Version 0.13.0

Yep it happens in `sh/bash` too.

**Comment by foot** [comment]
Thanks! Managed to repro.

A temp workaround is to prepend `TERM=dumb` to commands, e.g.

`TERM=dumb bash` and then `cqlsh` etc,

or 

`TERM=dumb cqlsh`.

I'm looking into how we can come up w/ a more general fix in scope.
