### ISSUE TITLE
Service only shows probes when they are disconnected 

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#1177]
Launched the sample app used in this guide: https://www.weave.works/guides/monitor-docker-containers/  using 'stand-alone mode'. 

then stopped scope, rm'ed container and downloaded scope using: 

Changed the url for scope to read: https://github.com/weaveworks/scope/releases/download/v0.13.1/scope  (instead of latest_release)

Then launched Scope using token. 

<img width="385" alt="disconnected-probes" src="https://cloud.githubusercontent.com/assets/13420383/13815579/0a34b060-eb83-11e5-8b28-615aff065177.png">

**Comment by tomwilkie** [comment]
I've moved this to the service repo.
