### ISSUE TITLE
Create a more typical application stack example

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#118]
The current example is great for playing around with Scope, but I think it would be a little confusing at a meetup or demo. Let's create a more typical example, with 2 load balancers, 3–5 application instances, and a database.

**Comment by tomwilkie** [comment]
I've got a branch with a few more application containers; just in the processes of adding load balancers.

**Comment by tomwilkie** [comment]
Here you go: https://github.com/weaveworks/scope/commit/e8da5903f1df20f39af24ff10864d1b4560e29d8

It has 2 go app and 3 elastic searches.

What needs doing:
- rewrite the curl load generator, so its not forking loads of processes.
- add some nginx or haproxy
- fix #111

**Comment by peterbourgon** [comment]
If you make a PR as a branch on this repo, I'll contribute some commits to convert the curl load generator to a Go version.

**Comment by tomwilkie** [comment]
Ah I just pushed that straight to master - its in experimental.

I'd say go ahead with a go load gen, and push it to master.

**Comment by peterbourgon** [comment]
Oh, OK.

**Comment by peterbourgon** [comment]
This ticket is about creating a different example, with a fewer number of types of containers.

**Comment by tomwilkie** [comment]
No!  More container types is better!  A typical app has loads of services.

**Comment by peterbourgon** [comment]
We can have multiple examples. But I want an example that's immediately understandable for demos and meetups.

**Comment by tomwilkie** [comment]
Isn't scope's job making complicated topologies easy to understand? ;-)

**Comment by peterbourgon** [comment]
> Isn't scope's job making complicated topologies easy to understand? ;-)

![image](https://cloud.githubusercontent.com/assets/114509/7836433/60ee68f0-0480-11e5-9c5d-96cf5e32db2a.png)

**Comment by tomwilkie** [comment]
The whole complicated container topology -> group by image is really quite compelling...

**Comment by peterbourgon** [comment]
We'll also use this for the tutorial doc.

**Comment by peterbourgon** [comment]
Consider it done.
