### ISSUE TITLE
Hide Kubernetes topologies in the frontend, not the backend

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1181]
When we go multitenant, the way we hide the kubernetes topologies won't work, as its shared state in the backend.

I'd like to be able to put a flag on the topology (hiddenIfEmpty or something) and have the frontend implement this.

Thoughts?

**Comment by paulbellamy** [comment]
For bonus points it might be worth adding a short-expiry cookie in the browser, so the views persist when refreshing.
