### ISSUE TITLE
Pipe websocket leak in Scope App

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1189]
Profile: [inuse_objects.inuse_space.001.pb.gz](https://github.com/weaveworks/scope/files/182398/inuse_objects.inuse_space.001.pb.gz)

![scope_app_heap](https://cloud.githubusercontent.com/assets/2362916/13921729/8563b752-ef36-11e5-9ee3-6a83eb678eb3.png)

492MB worth of sockets may indicate some other problem with connections (e.g. infinite reconnection loop).

Context: https://weaveworks.slack.com/archives/scope-public/p1458051757000002

**Comment by 2opremio** [comment]
From the user:

> lots of Error copying to pipe pipe-2448387299974790848 (1) websocket: websocket: close 1006 (abnormal closure): unexpected EOF

https://weaveworks.slack.com/archives/scope-public/p1458570896000146

**Comment by rade** [comment]
Same as #1131?

**Comment by 2opremio** [comment]
Most probably. @rade can you easily reproduce? It would be useful to run `weaveworks/scope:latest` to see if https://github.com/weaveworks/scope/pull/1172 fixes it.

**Comment by rade** [comment]
> @rade can you easily reproduce?

Nope :(

**Comment by 2opremio** [comment]
The user (@janwillies) deployed `weaveworks/scope:latest` hoping that #1172 would have resolved it and the results are positive so far. It has only been running for 7 hours but there are no signs of the leak

[pprof.localhost_4040.inuse_objects.inuse_space.001.pb.gz](https://github.com/weaveworks/scope/files/186286/pprof.localhost_4040.inuse_objects.inuse_space.001.pb.gz)


![app_heap_profile](https://cloud.githubusercontent.com/assets/2362916/13990397/5d81c4e4-f0d1-11e5-8722-f08e03565349.png)

```
$ go tool pprof --focus 'websocket\.newConn' -png pprof.localhost_4040.inuse_objects.inuse_space.001.pb.gz > app_heap_profile_newConn.png
Focus expression matched no samples: websocket\.newConn
```

**Comment by davkal** [comment]
Positive is good enough.
