### ISSUE TITLE
Topology > Containers > Grouped is broken

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#119]
Containers is good..

![screen shot 2015-05-27 at 12 21 40](https://cloud.githubusercontent.com/assets/114509/7833925/f7ddb42a-046a-11e5-81cd-3ae00cd0ea95.png)

But if you switch to grouped view, it breaks.

![screen shot 2015-05-27 at 12 21 44](https://cloud.githubusercontent.com/assets/114509/7833930/ff9424b0-046a-11e5-855e-f97d24c20f11.png)

**Comment by tomwilkie** [comment]
Weird, this works for me...

**Comment by peterbourgon** [comment]
Oh! Let me try a rebuild, then...

**Comment by peterbourgon** [comment]
PEBKAC
