### ISSUE TITLE
Inbound/Outbound connection rows/counts/ports not being calculated correctly

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1218]
Seems like maybe, in particular on internet node.

Could be related to recent changes there.

**Comment by rade** [comment]
It's also happening on the 'Uncontained' node.

Symptoms are that you get a "+<n>" marker, but when you click on it then it just disappears, with no extra rows showing up.

**Comment by paulbellamy** [comment]
Also that some expected node/port rows are missing.

**Comment by rade** [comment]
> Also that some expected node/port rows are missing.

Is that the same problem?

FTR, what I am seeing is that my thunderbird connections to gmail:993 are shown in the thunderbird process details panel, but not the "Uncontained" details panel.

**Comment by paulbellamy** [comment]
My hunch is it is related.

**Comment by tomwilkie** [comment]
This bug seems to contain three issues:
1. Uncontained node details panel is missing connections to the internet?
2. Some other things are missing.
3. Sometimes the row expansion widget is shown when there is nothing to expand

I can't reproduce (1) or (2) of these issues, and without a report (or at least a screenshot) there is very little else I can do.

I'll open a separate issue for (3)

**Comment by tomwilkie** [comment]
Filed #1240 for (3).

@paulbellamy / @rade do you have a repro / more details for (1) or (2)?

**Comment by rade** [comment]
![screenshot from 2016-04-07 11 54 59](https://cloud.githubusercontent.com/assets/109109/14348995/df247874-fcb7-11e5-882d-778a558786f8.png)
![screenshot from 2016-04-07 11 55 33](https://cloud.githubusercontent.com/assets/109109/14349000/e8aa40ae-fcb7-11e5-87fa-0e1147e3710c.png)
[report](https://gist.github.com/rade/cfea68a782be8aed692e01a535d503fc)

**Comment by rade** [comment]
connections from my thunderbird to internet:993:
![screenshot from 2016-04-07 12 10 29](https://cloud.githubusercontent.com/assets/109109/14349305/e7876f56-fcb9-11e5-979f-3c10c6a878ae.png)
uncontained shows no connections to internet:993:
![screenshot from 2016-04-07 12 11 17](https://cloud.githubusercontent.com/assets/109109/14349309/ec52bc3e-fcb9-11e5-89f8-871239cb0eb8.png)
