### ISSUE TITLE
Report if there is a newer version available in the UI

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1227]
I'll add the info to /api.

**Comment by davkal** [comment]
What info is available?

**Comment by tomwilkie** [comment]
We can tell if there is a new version, what version is it, and a link to the release notes.

**Comment by davkal** [comment]
I'm imagining something like

```
VERSION 0.14 (new version available: <a>0.15</a>)
```

With a tooltip: 
```
[New version available. Click on the link to see the release notes.]
```

**Comment by tomwilkie** [comment]
Sounds good, although we're starting to overload the bottom-right corner quite a log (cf plugins)

**Comment by tomwilkie** [comment]
Dupe #914
