### ISSUE TITLE
Hotkeys for metrics are not working in FF and are hard to find

### ISSUE THREAD

**Issue by davkal** [weaveworks/scope#1228]
@rade found in #1226:

> Neither the arrow keys nor the less/greater-than keys do anything for me in either FF or Chrome.
 How was I supposed to know that there are keyboard shortcuts?

@foot said:
> KB shortcuts do have a lot of potential here. I'm not 100% w/ `<` / `>`.
They do feel a tad awkward. Arrow keys? I like vim :). hjkl ftw.

**Comment by davkal** [comment]
I feel like the the arrow keys should be reserved for something arrow-y, like navigation. I'm very happy with the *top* keys, they also have dev appeal.

**Comment by foot** [comment]
Some short

![screen shot 2016-04-07 at 14 25 26](https://cloud.githubusercontent.com/assets/22008/14351128/da6daace-fccd-11e5-9854-337282d615ec.png)
![screen shot 2016-04-07 at 14 24 26](https://cloud.githubusercontent.com/assets/22008/14351129/da6f0ec8-fccd-11e5-8185-a20348ba7195.png)
