### ISSUE TITLE
Layout center shared between layouts.

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#1238]
1) Click processes topo
2) Click containers topo
3) Pan layout
4) Back to processes
5) Note processes has also been panned.

**Comment by foot** [comment]
Solutions:

1. Reset the layout onShow
  - Bad for big layouts if you were focusing on an area.
2. Save position in layout and reload it onShow
  - Bad if you zoomed in to some section, forgot about, came back, confused as to what you're looking at.
  - No easy way to reset the layout if you make a mess (though switching from topo and back is not perfect either).

**Comment by foot** [comment]
Nice! Works really well, might be nice to have a reset button too but I'm not sure where to put that.

LGTM

**Comment by tomwilkie** [comment]
Can still reproduce with this report:

[report.json.zip](https://github.com/weaveworks/scope/files/223566/report.json.zip)

I was using the code from https://github.com/weaveworks/scope/pull/1326

1. Start from a fresh browser (no state in the hash fragment)
2. Click on processes
3. Pan to the far right
4. Client on processes by name
5. _Blank screen_
6. Pan to the far left, there are your nodes.

**Comment by davkal** [comment]
Yup, found the issue. The old pan state is not cleared. Fixing...
