### ISSUE TITLE
K8s views have an uncontained node

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1246]
Should we drop it for this view?

![screen shot 2016-04-07 at 15 45 49](https://cloud.githubusercontent.com/assets/444037/14355140/d71c249a-fcd7-11e5-8410-3e5390ded76b.png)

**Comment by paulbellamy** [comment]
We should definitely not have a node full of processes on this view. Maybe an "Unmanaged" one full of containers which are outside pods? Or maybe nothing?

**Comment by tomwilkie** [comment]
> Maybe an "Unmanaged" one full of containers which are outside pods? Or maybe nothing?

Yes.  Lets do this.
