### ISSUE TITLE
ELB should show up as Internet node

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1256]
I have a container behind ELB (`errordeveloper/identiorca`). It's running on ECS and the container port 9090 is mapped to port 80 on the host and that's where ELB is pointed at.

For the reference, here is [CloudFormation template](https://github.com/weaveworks/integrations/blob/cd2eb1f7e7a62f45ae5f591a5ca0322c9a1682cd/aws/ecs/cloudformation-identiorca.json) I'm using.

[Scope report](https://raw.github.com/errordeveloper/scope-report-store/master/report-2016-04-11-11-29-01.json).

<div>
<img width="1166" alt="screenshot 2016-04-11 12 01 53" src="https://cloud.githubusercontent.com/assets/251467/14425180/3717d710-ffdd-11e5-98f3-23e947b8858a.png">
</div>

There is also an uncontainerised node talking to Redis, which I'm not able to identify...

**Comment by paulbellamy** [comment]
Shows up in master. But shows up consistently when only one application replica, but sporadically when there are multiple. conntrack related?

**Comment by paulbellamy** [comment]
Seems like the ELB is only routing to 0-2 replicas at a time...
