### ISSUE TITLE
Ordering of metrics is not as expected

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1267]
The order of metrics in the Host view is:
  ... Load (15m), Load (1m), Load (5m) ... 

not as expected:
  ... Load (1m), Load (5m), Load (15m) ...

<img width="346" alt="metric-ordering" src="https://cloud.githubusercontent.com/assets/303151/14463000/56552634-00c1-11e6-92a9-ebfbf9856400.png">

**Comment by davkal** [comment]
Let's use this issue to get rid of the different loads. One load to rule them all:

* in metrics on canvas
* in node metrics (sparklines details panel)
