### ISSUE TITLE
Plugins UI should have some indicator when plugins are broken

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1271]
Raised in: https://github.com/weaveworks/scope/pull/1126#issuecomment-208873500

**Comment by foot** [comment]
![screen shot 2016-04-13 at 10 20 50](https://cloud.githubusercontent.com/assets/22008/14487181/6dc5abfe-0161-11e6-864c-2298934fb433.png)

**Comment by foot** [comment]
Run and 
![screen shot 2016-04-13 at 10 24 22](https://cloud.githubusercontent.com/assets/22008/14487267/ff28bf1e-0161-11e6-87f6-d5aac3353a7b.png)
