### ISSUE TITLE
Mismatching metrics on canvas and sparklines

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1278]
It may be justified by some transformation made by the sparklines, but it should be consistent on the canvas, otherwise it's very confusing for the end user.

<img width="1749" alt="screen shot 2016-04-13 at 03 50 47" src="https://cloud.githubusercontent.com/assets/2362916/14481466/0dcd7514-012b-11e6-964c-2d59a7c4ee1e.png">

<img width="1749" alt="screen shot 2016-04-13 at 03 50 18" src="https://cloud.githubusercontent.com/assets/2362916/14481470/13daf076-012b-11e6-9169-d09c4accd5a1.png">

**Comment by paulbellamy** [comment]
Could be caused by different polling intervals?

**Comment by paulbellamy** [comment]
MoC are sent via websockets every second, while the sparklines are updated with the details panel (every 30s).

**Comment by 2opremio** [comment]
> MoC are sent via websockets every second, while the sparklines are updated with the details panel (every 30s).

Do they come from different data sources or just different polling intervals? Can we use the same data source/interval the metrics in the details panel in MoC?

**Comment by foot** [comment]
Yeah, this needs reconciling the UI really.

**Comment by foot** [comment]
Switch to details data source when available.
