### ISSUE TITLE
ProcessRenderer and other renderers disagree on whether a process is linkable

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1295]
Probably due to repeated usage of ColorConnected, at different layers (which is additive).

**Comment by rade** [comment]
@paulbellamy err, what? What's the impact on users?

**Comment by paulbellamy** [comment]
We show different processes in the children tables, vs the topology, because we filter out unconnected processes in the topology view.

**Comment by paulbellamy** [comment]
One upside of this behaviour is that you get more accurate sorting of processes-by-cpu.

**Comment by 2opremio** [comment]
I've been discussing this with Paul offline and I am having trouble to see this as a problem.

For instance, according to this issue, the table below shouldn't show the `/pause` process, which isn't right.

<img width="1614" alt="screen shot 2016-09-27 at 18 12 47" src="https://cloud.githubusercontent.com/assets/2362916/18882158/61a78c24-84de-11e6-846e-99d411d1dd7a.png">

I understand the point of unconnected processes not being shown making it confusing.

I think that this would be less of a problem if we didn't apply that limitation to the table view (As I understand it, we do it in the graph view for performance reasons) @foot thoughts?

**Comment by 2opremio** [comment]
I propose to close this as a non-bug. @paulbellamy seems to be OK with it.
