### ISSUE TITLE
It is difficult to find nodes with a specific attribute

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1299]
e.g. I'm trying to find the container with ip `172.16.0.31`, and have to click through all the containers to find it.

**Comment by davkal** [comment]
I like this issue a lot. It drives us closer to a search functionality.

I can imagine a search bar that does not only check visible labels, but also matches metadata and maybe overlays the matches per node below the current labels.

**Comment by tomwilkie** [comment]
Search is one solution, for sure.

A table, with multiple columns you can sort on, is another.  People are good at searching through sorted lists.

I think the problem is more general - finding a node by name is equally as difficult.

**Comment by paulbellamy** [comment]
Could highlight matching nodes as you "search"... That would be GoodEnough for me in this situation
