### ISSUE TITLE
Somehow internet node goes missing, yet edges are there

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1304]
<img width="906" alt="screenshot 2016-04-14 16 58 08" src="https://cloud.githubusercontent.com/assets/251467/14534718/5275d660-0262-11e6-89bb-fdf7131ff77a.png">

[Report](https://raw.github.com/errordeveloper/scope-report-store/master/report-2016-04-14-16-58-26.json).

On refresh, the edges go away.

**Comment by paulbellamy** [comment]
I've seen this happen on non-pseudo nodes as well, when the layout changes.
![screen shot 2016-04-20 at 10 33 44](https://cloud.githubusercontent.com/assets/250199/14670061/6f134d22-06e3-11e6-84ed-abd8fe4c3185.png)

**Comment by tomwilkie** [comment]
I too see this:

![screen shot 2016-04-20 at 11 35 22](https://cloud.githubusercontent.com/assets/444037/14671850/113850ea-06ec-11e6-8f3e-28e5d8da4058.png)

I'm on a branch off master (8f3402f3)

**Comment by davkal** [comment]
Introduced in 5cedfad.

**Comment by rade** [comment]
Here's another one for you

![screenshot from 2016-04-21 14 23 20](https://cloud.githubusercontent.com/assets/109109/14710366/04704e3a-07cd-11e6-97fd-f2c97a00e64e.png)
