### ISSUE TITLE
Container entrypoint doesn't parse arguments correctly

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1312]
Here's an example.

This is how the scope container launched due to a typo in a kubernetes resource (from docker inspect):

```
        "Cmd": [
            "--no-app",
            "--probe.docker.bridge=cbr0",
            "--probe.docker=true",
            "--probe.kubernetes=true",
            "--probe.weave.addr=",
            "--probe.http.listen :4041",
            "10.0.168.121:4040"
        ],
```

And these are the arguments passed to he probe:

```
scope-probe probe -docker.bridge=cbr0 -docker=true -kubernetes=true -weave.addr= -http.listen :4041=10.0.168.121:4040
```

Note how the entrypoint passes `:4041=10.0.168.121:4040` to `--probe.http.listen` instead of complaining about `--probe.http.listen :4041` not being a valid flag.

**Comment by tomwilkie** [comment]
I would like to move the argument parsing into go; this will also help with #768.
