### ISSUE TITLE
Node IDs with / leads to redirect loop when scope is mounted under a path with slash redirect

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1335]
Components you need are:

1) A load balancer in front of scope, which mounts it on a subdirectory, and redirects to add a trailing slash to scope's root url.
2) A node with a / in it's id (or label?) `docker run -dit -e MARATHON_APP_ID=a/foo --name foo alpine /bin/sh`
3) open a terminal on that node
4) close the terminal
5) observe redirect loop

**Comment by paulbellamy** [comment]
Also, just opening details panel and refreshing.

**Comment by foot** [comment]
Is https://github.com/visionmedia/page.js/issues/187

it fails to match either `page('/'...` or `page('/state/:state'...`, (because of the slash in the state). and the default fallback strips out the slash for some reason and makes a redirect mess.

but double uri encoding does work!

```patch
diff --git a/client/app/scripts/utils/router-utils.js b/client/app/scripts/utils/router-utils.js
index df39d11..8bcddf7 100644
--- a/client/app/scripts/utils/router-utils.js
+++ b/client/app/scripts/utils/router-utils.js
@@ -14,12 +14,12 @@ function shouldReplaceState(prevState, nextState) {

 export function updateRoute() {
   const state = AppStore.getAppState();
-  const stateUrl = JSON.stringify(state);
+  const stateUrl = encodeURIComponent(encodeURIComponent(JSON.stringify(state)));
   const dispatch = false;
   const urlStateString = window.location.hash
     .replace('#!/state/', '')
     .replace('#!/', '') || '{}';
-  const prevState = JSON.parse(decodeURIComponent(urlStateString));
+  const prevState = JSON.parse(decodeURIComponent(decodeURIComponent(urlStateString)));

   if (shouldReplaceState(prevState, state)) {
     // Replace the top of the history rather than pushing on a new item.
```

**Comment by errordeveloper** [comment]
In b9d93fb, clicking on anything on the details panel while having the terminal open gets it into a redirect loop.

**Comment by errordeveloper** [comment]
Ok, turns out we fixed the issue for nodes with a leading slash, but ones with more slashed (like `/monsterz/apps/dnm`) still break it.
