### ISSUE TITLE
irrelevant views clutter the UI

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1364]
If I am not running k8s, I have no use for the 'Pods' view, or any other k8s views we are contemplating. They just become a distraction and might even confuse users who know nothing about k8s.

The same applies to any other platform-specific views we might add.

Suggestion: we should be able to detect fairly accurately whether we have any k8s/etc in a report, and limit the views we show accordingly.

**Comment by paulbellamy** [comment]
The kubernetes view should only be shown if k8s is detected by the probe.

**Comment by rade** [comment]
> The kubernetes view are only shown if k8s is detected by the probe.

Since when? I *always* see 'Pods - By Service', and I sure am not running k8s.

**Comment by tomwilkie** [comment]
What version are you running @rade?

We did a bunch of work to make what paul said the case, we might have missed something.

Please include a report.

**Comment by paulbellamy** [comment]
![screen shot 2016-04-21 at 14 50 28](https://cloud.githubusercontent.com/assets/250199/14711221/6c3a83c0-07d0-11e6-8761-dd38828eaab2.png)

**Comment by tomwilkie** [comment]
Hmpf.  Thats post 0.14 at least.

**Comment by rade** [comment]
> Hmpf. Thats post 0.14 at least.

I said I was running current master!

**Comment by tomwilkie** [comment]
@paulbellamy I think I might propagate a kubernetes flag in the report in kubernetes is enabled, and filter all nodes from the view if this flag is not set.  Thoughts?

**Comment by paulbellamy** [comment]
I'm a bit puzzled why `FilterEmpty(report.Pod, ...)` Isn't removing the managed node, maybe we need to do a `FilterUnconnectedPseudo` on it?

**Comment by tomwilkie** [comment]
> I'm a bit puzzled why FilterEmpty(report.Pod, ...) Isn't removing the managed node, maybe we need to do a FilterUnconnectedPseudo on it?

The unmanaged nodes is connected to itself in this instance, so therefore is not unconnected.

But in general it could be pointing to the internet (or the internet pointing at it) so I don't think its enough to rely on hiding the view if there are no nodes - hence the idea to propagate the flag.
