### ISSUE TITLE
`basename: missing operand` when launching scope when weavedns is running

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#137]
````
$ weave launch
476e00691ca1a5d9423f03377f0b18527478aff716e1ff867c70cec6724a8c17
$ weave launch-dns 10.2.0.1/24
e572552f539cd417d10e7c656b4854d65a752921498b27a733e83c65bcdff81a
$ ./scope launch
basename: missing operand
Try 'basename --help' for more information.
73f80066456faeb694ff119fa1de4dd3604f7b731d3fd8bb65a05e0a46cb96a1
````

This is with version 2e8df4a8e2521c9005a66dd93d0fd514b8ae6e4a, built according to the [instructions](https://github.com/weaveworks/scope#build).

tracing the exeuction with `sh -x` produces
````
...
+ dns_running
+ docker inspect --format={{.State.Running}} weavedns
+ status=true
+ [ true = true ]
+ return 0
+ + xargs -n1 basename
find /sys/class/net -name eth*
+ grep inet
+ + xargsgrep echo
 -oE [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}
+ + awkxargs { print $2 } -n1 ip
 addrbasename: missing operand
Try 'basename --help' for more information.
 show
...
````

Looking at this and the code, I think the issue is that the script doesn't cope with my machine not having an `eth*` interface.

**Comment by peterbourgon** [comment]
Via my own educational archaeology, the [offending block](https://github.com/weaveworks/scope/blob/2e8df4a8e2521c9005a66dd93d0fd514b8ae6e4a/scope#L135-139)

```bash
		if dns_running; then
			IP_ADDRS=$(find /sys/class/net -name eth* | xargs -n1 basename | xargs -n1 ip addr show |
				grep inet | awk '{ print $2 }' | grep -oE "$IP_REGEXP" | xargs echo)
			tell_dns_fqdn PUT $CONTAINER $FQDN $IP_ADDRS
		fi
```

Compare against the [weave script's invocation](https://github.com/weaveworks/weave/blob/b86ead27374f2a421d1e4474266c8d68253acb21/weave#L977)

```bash
    dns-add)
        collect_ip_args "$@"
        shift $IP_COUNT
        [ $# -ge 1 ] || usage
        CONTAINER_ID="$1"
        if [ $# -eq 1 ] ; then
            tell_dns PUT $CONTAINER_ID $IP_ARGS
        else
            [ $# -eq 3 -a "$2" = "-h" ] || usage
            FQDN="$3"
            tell_dns_fqdn PUT $CONTAINER_ID $FQDN $IP_ARGS # <== here
        fi
        ;;
```

Where [collect_ip_args takes from the commandline](https://github.com/weaveworks/weave/blob/master/weave#L120-131)

```bash
collect_ip_args() {
    IP_ARGS=""
    IP_COUNT=0
    while is_ip "$1" ; do
        IP_ARGS="$IP_ARGS $1"
        IP_COUNT=$((IP_COUNT + 1))
        shift 1
    done
    if [ $IP_COUNT -eq 0 ] ; then
        [ $# -gt 0 ] && validate_ip "$1" || usage
    fi
}
```

I guess we can do the same, if there's not a smarter way?

**Comment by tomwilkie** [comment]
This is because @rade doesn't have any eth devices, only vlan devices.

Alternatives:
- do reverse dns on hostname to find our IP(s) - downside is that on my vagrant VM, this doesn't work:

```
$ host $(hostname)
Host ubuntu-14 not found: 3(NXDOMAIN)
``` 

- include vlan (or all, except the docker bridge) devices in this advertisement.  The app and probe are listening on everything anyway...

- add a command line option for when this doesn't work, and make it fail gracefully.

- use ifconfig (basically doing the same as above)

```
$ ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'
172.17.42.1
10.0.2.15
172.16.0.3
```

I don't feel like I know the best answer.  In the meantime I'll make this fail less spectacularly.
