### ISSUE TITLE
k8s: Add views for Deployments and ReplicaSets

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1372]
Kubernetes 1.2 comes with [Deployments](http://kubernetes.io/docs/user-guide/deployments/) and [ReplicaSets](http://kubernetes.io/docs/user-guide/replicasets/) (similar to ReplicationControllers but enable declarative changes/rollouts and use hashing for versioning), we should add views for them.

See http://blog.kubernetes.io/2016/04/using-deployment-objects-with.html for a friendly example.

For Deployments we probably want some sort of log view to see the changes which were made to the deployment (it would require a similar view to https://github.com/weaveworks/scope/issues/1329 )

**Comment by rimusz** [comment]
👍

**Comment by errordeveloper** [comment]
Can you do a Deployment of a DaemonSet? ...I seem to recall there was a limitation, but not too sure.

**Comment by rimusz** [comment]
Deployment is replication controller replacement and does nothing to DaemonSets

**Comment by errordeveloper** [comment]
Ok, sorry, I confused, thought this was in the context of scope manifest.

**Comment by 2opremio** [comment]
No, this is for adding views in Scope (hence the title :) )
