### ISSUE TITLE
k8s: Remove App->Probe deployment ordering restriction

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1373]
The Scope kubernetes resources require creating the Scope App service before the Scope Probe DaemonSet. This ordering restriction is inconvenient, and a showstopper for k8s package managers like [helm](http://helm.sh/), which don't include any support for ordering.

From https://github.com/TheNewNormal/kube-charts/blob/master/weavescope/manifests/scope-probe-ds.yaml#L28-L40 :

```yaml
        # We cannot refer to the Scope App with its Kubernetes Service
        # DNS name (weave-scope-app) directly because Docker doesn't
        # allow customizing the DNS servers (the Kubernetes DNS add-on
        # server in this case) of a container when it runs in the
        # host's network namespace (see
        # https://github.com/docker/docker/issues/10384#issuecomment-72069550
        # ). Instead, we use variable expansion on its service
        # environment variables.
        #
        # NOTE: Unfortunately this imposes a specific creation
        # ordering since the Scope App Service needs to be created first for
        # the service environment variables below to be accesible.
        - "$(WEAVE_SCOPE_APP_SERVICE_HOST):$(WEAVE_SCOPE_APP_SERVICE_PORT)"
```

Also, this has the disadvantage of the probes not picking up a new service IP if it's recreated.

We could fix this by somehow obtaining the IP of Kubernetes Cluster DNS Service IP and use Scope's [custom resolver](https://github.com/weaveworks/scope/blob/619c63a0a5f088ca6c25354da1e5627e35052dbc/probe/appclient/resolver.go#L59-L78) to resolve the App's service (`weave-scope-app`).

I don't see a simple immediate way to obtain the Cluster DNS Service IP (it normally lives in the separate system namespace so it won't appear in the environment variables). One option would be moving Scope to the system namespace.

**Comment by errordeveloper** [comment]
> I don't see a simple immediate way to obtain the Cluster DNS Service IP (it normally lives in the separate system namespace so it won't appear in the environment variables). One option would be moving Scope to the system namespace.

You have it already, it's in your `/etc/resolve.conf`.

**Comment by errordeveloper** [comment]
> You have it already, it's in your `/etc/resolve.conf`. 

Ok, you said that cluster DNS server is not set on containers in host netns... But I am not too sure whether it was the case for Kubernetes, I thought it overrides the DNS setting.

**Comment by errordeveloper** [comment]
> it normally lives in the separate system namespace so it won't appear in the environment variables

Yes, but you can fetch it via the API, which you are going to access anyway. However, there are other good reasons for putting scope into `kube-systems` namespace, it just generally makes sense.

**Comment by 2opremio** [comment]
> Yes, but you can fetch it via the API, which you are going to access anyway. However, there are other good reasons for putting scope into kube-system namespace, it just generally makes sense.

I would like to avoid adding code in Scope to do this.

**Comment by 2opremio** [comment]
Related https://github.com/kubernetes/kubernetes/issues/17406
