### ISSUE TITLE
k8s: PODs show-up in 'By container' filter 

### ISSUE THREAD

**Issue by nitin-amp** [weaveworks/scope#1383]
<img width="1200" alt="screen shot 2016-04-26 at 4 26 05 pm" src="https://cloud.githubusercontent.com/assets/14815419/14839949/fbfe69ec-0be3-11e6-9456-1effa7449642.png">

k8s' PODs show-up in the scope's main view when containers are selected. Technically, these are a group of containers so should not be shown in this view (see screenshot).

**Comment by 2opremio** [comment]
That's not a pod but a container named POD (apparently that's how the root containers of a pod are named by kubernetes see https://github.com/weaveworks/scope/issues/1384#issuecomment-215128771 ). 

I understand this can be confusing but Kubernetes is causing this. We should make sure they are filtered as system containers though (let's follow up on https://github.com/weaveworks/scope/issues/1384 )
