### ISSUE TITLE
We could have the semi-opaque outline on node labels all the time

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1385]
We show it on hover, but it's more legible when there are labels over top of edges, so maybe it's worth showing it all the time.

Current with the background, on hover:
![screen shot 2016-04-27 at 11 06 33](https://cloud.githubusercontent.com/assets/250199/14848934/23711090-0c68-11e6-936a-1bb8d81e4f02.png)

Current without the background without hover:
![screen shot 2016-04-27 at 11 06 36](https://cloud.githubusercontent.com/assets/250199/14848933/236f5af2-0c68-11e6-87b6-e1af8f351d1f.png)

**Comment by rade** [comment]
I cannot make sense of this issue. The node labels look the same to me in the two screenshots. @paulbellamy please explain.

**Comment by paulbellamy** [comment]
In the first picture above I'm hovering over the weavescope-probe-... node and it has the semi-opaque background on the label where it crosses the edges. In the second one (when not hovering), it doesn't have the background, and the text is less legible.

**Comment by rade** [comment]
This appears to be fixed already:
![screenshot_2017-01-10_23-43-04](https://cloud.githubusercontent.com/assets/109109/21829557/9dcdf686-d78e-11e6-8a2a-6f2143e3442f.png)

closing. @davkal @paulbellamy if I've missed something then please re-open.
