### ISSUE TITLE
Multi-host setup completely undocumented

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#139]
The readme makes no mention of how to get scope to monitor processes/containers across multiple hosts. I gather one should launch weave and weavedns, but it doesn't say that anywhere.

**Comment by tomwilkie** [comment]
NB this won't work with weave 0.11 yet; the required DNS changes didn't make it in.

Beyond that, there is no "easy" way to make it work, you have to build and run the app and probe yourself.

I'll see if we can add some command line options to make this work with 0.11.

**Comment by tomwilkie** [comment]
There is now a relatively easy way to make this work, documented in docs/scope.md
