### ISSUE TITLE
Terminals are unusable when typing long lines/ control commands

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1402]
Typing long lines and/or searching  (e.g. `^r`, `^a`,  up, ) mess up the terminal every time, making it unusable. The `reset` commands doesn't help.

<img width="1696" alt="screen shot 2016-04-28 at 20 00 56" src="https://cloud.githubusercontent.com/assets/2362916/14897948/3801c40e-0d7c-11e6-939d-22bb49058a96.png">

**Comment by foot** [comment]
Can you do a `echo $TERM` on the mis-behaving machine? a normal alpine seems to be behaving alright, I'll try and play w/ other term combos.

**Comment by foot** [comment]
`docker run --name=zing -dti redis /bin/sh` gives a container that will have some funky line issues. poking...

**Comment by foot** [comment]
Do you get better line behaviour if you
`TERM=dumb bash`
and then type the long commands?

**Comment by foot** [comment]
There is a new and maintained term.js fork that we should test out https://github.com/sourcelair/xterm.js

**Comment by foot** [comment]
So it seems it is the responsibility of the terminal emulator to handle the line wrapping.

If you have x11 installed on osx you can fire up an xterm w/ `xterm +aw` to disable auto-wrapping then type out a big line and notice it wrapping around.

term.js is the terminal emulator here and doesn't support line wrapping at the moment. A workaround is to tell the shell that the TERM is `dumb`, then the shell may try and handle the line wrapping itself. However it seems that ncursey apps like top will then break.

#1158 is related.

I'll open an issue w/ xterm.js but it might be slow for us to implement this ourselves.

**Comment by foot** [comment]
Note: If you get frustrated w/ an older scope instance you can resize your window so the terminal is exactly 80 chars (check terminal title bar), and it should wrap correctly.
