### ISSUE TITLE
Terminals don't support quote characters from intl keyboard layouts 

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1403]
Users with an international keyboard layout cannot type any quote characters on the terminals (e.g. `"` `'` ``  `  `` etc ...). This makes it impossible to type any complex shell commands.

<img width="686" alt="screen shot 2016-04-28 at 20 10 59" src="https://cloud.githubusercontent.com/assets/2362916/14898166/5e4f32a8-0d7d-11e6-9776-1c1e85942f3e.png">

See http://www.starr.net/is/type/intlchart.html

This was reproduced on Chrome under OSX

**Comment by foot** [comment]
Interesting! Investigating.

**Comment by foot** [comment]
<kbd>'</kbd> is a super special key on us-intl that lets you get all your accents. I'm not sure how to get the full behaviour of this key going in term.js et.

I've put in a fix so we treat it as a normal '/" for now, allow single and double quotes.
