### ISSUE TITLE
Lingering edges when nodes or network connections go away

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1420]
Only happens intermittently.  Running a very recent master (9eaac25).

![screen shot 2016-05-03 at 16 06 21](https://cloud.githubusercontent.com/assets/444037/14987821/0baecb06-1149-11e6-9542-46cbbcd73aa6.png)

**Comment by 2opremio** [comment]
I also see lingering edges when the connections are gone, even if the nodes being connected don't go away.

**Comment by davkal** [comment]
Probably fixed by #1429 (removes edges when either source or target is missing)

**Comment by davkal** [comment]
Fixed via #1429
