### ISSUE TITLE
Filter by multiple Kubernetes namespaces at the same time

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1421]
Requested by @bboreham 

So we can view the set of pods/services in 2+ namespaces at once (but not in _all_ namespaces).

**Comment by paulbellamy** [comment]
Might apply to other filters as well.

**Comment by jpellizzari** [comment]
@fbarl expressed some interest in this and may have more cycles to complete it in time for Kubecon. Would you like to take this one @fbarl?

**Comment by bboreham** [comment]
Just to fill in the motivating use-case: if you use namespaces as a mechanism to organise your system - e.g. presentation tier / business tier / data tier - then you can't see the connections between tiers except with all namespaces shown.

Another example (though you might special-case this): you would typically want to turn off the kube-system namespace where things like kube-dns live.

**Comment by rade** [comment]
> Another example (though you might special-case this): you would typically want to turn off the kube-system namespace where things like kube-dns live.

That would be #1423 :)

I think @2opremio's mixer control idea in that issue is a promising all-encompassing solution. Though perhaps only DJs will be able to operate it.

**Comment by errordeveloper** [comment]
I'd find it fairly intuitive if to get there I had to alt-click on a namespace button at the left hand side in the bottom...

**Comment by pidster** [comment]
If the existing buttons were just toggle on/off, that would solve the problem from the user point of view in a very simple way.

**Comment by rade** [comment]
> If the existing buttons were just toggle on/off, that would solve the problem from the user point of view in a very simple way.

No, it wouldn't. See https://github.com/weaveworks/scope/issues/1423#issue-152816165: "selecting all but the system namespace would be an incredible tedious way to show k8s application namespaces only". Hence @2opremio's mixer control idea.

**Comment by jpellizzari** [comment]
The first iteration will probably look something like what @pidster suggested, given our short time frame. It might be possible to add the options listed in #1423 to avoid forcing the user to click a lot to clear application namespaces.
