### ISSUE TITLE
show k8s application namespaces only

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1423]
ATM it is possible to filter by individual namespace, or show all namespaces. This leaves out one important use-case, I reckon: showing all except the system namespace. i.e. the selector should work similar to the existing selector for containers... 'system | application | both'.

Related to #1421 though note that selecting all but the system namespace would be an incredible tedious way to go about the above.

**Comment by 2opremio** [comment]
I see a general solution for this. We could do something similar to Mute and and Solo in mixing desks: http://mixere.sourceforge.net/Help/Tracks/Mute-Solo.htm

**Comment by 2opremio** [comment]
@rade I think we support this usecase now. Closing, please re-open if you don't agree.
