### ISSUE TITLE
View should have an indicator of where you are

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#1424]
I found where the indicator is missing (in Tom's sample app): 
1. click on container view
2. then select one of the containers to view its metrics
3. then select scopetastic from the metrics panel and click 'view scopetastic hosts' 

you'll noticed that the 'Hosts' tab is not selected.

**Comment by abuehrle** [comment]
Noticed that this is just in the case of "host" view being drilled down on.

**Comment by abuehrle** [comment]
I can't recreate this consistently. If I see it again. I will reopen it.

**Comment by tomwilkie** [comment]
This is intentional - the button in the top right of the details panel will take you two the view.  See #1151.  Closing as dupe.
