### ISSUE TITLE
metrics: container view environment variable is truncated

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#1425]
Should provide a way to see the whole path, when the environment variable is truncated: 

![environment-variable-cuttoff](https://cloud.githubusercontent.com/assets/13420383/14997097/9801f364-1142-11e6-97ca-301c82fa57e2.png)

**Comment by 2opremio** [comment]
@abuehrle You should be able to hover on it to show the whole path. Please let me know if that worked.

**Comment by abuehrle** [comment]
Yes, there is a tooltip.
