### ISSUE TITLE
Filter GKE system containers

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1430]
There are too many containers which should be classified as system ones, we just need to go through those and add them to the list of know systems containers.

- [report 1](https://raw.github.com/errordeveloper/scope-report-store/master/report-2016-05-04-17-59-51.json)
- [report 2](https://raw.github.com/errordeveloper/scope-report-store/master/report-2016-05-04-20-06-55.json)

**Comment by errordeveloper** [comment]
I'm happy to do this tomorrow, so we can present a short post of using 0.15 on GKE.

**Comment by tomwilkie** [comment]
Better yes, filter container with the label `IO.KUBERNETES.POD.NAMESPACE=kube-system`

**Comment by errordeveloper** [comment]
Oh, are we not filtering `kube-system` already?
