### ISSUE TITLE
App high memory consumption

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1441]
Reported by @janwillies on Slack after testing `:latest`. He used to set a 128MB limit with which the app used to work just fine, now he claims it's consuming 2.5 GB (VM I presume ,the profile below shows 1.25 GB).

I think the environment hasn't increased in size (@janwillies, can you confirm and give details on the number of probes?).

Profile: [pb.gz](https://github.com/weaveworks/scope/files/251994/pb.gz)

![app_memory](https://cloud.githubusercontent.com/assets/2362916/15071146/57d5fdc6-1381-11e6-935a-312262dd47ee.png)

**Comment by tomwilkie** [comment]
This will be the 1k report cache in smarterMerger.

We can (a) make this a command line switch, service probably wants it to be bigger and/or (b) remove entries from the cache when they are older than the reporting window.

**Comment by 2opremio** [comment]
We could also limit the cache size based on memory consumed instead of report cardinality. Although it may be hard to estimate the size of the reports.

**Comment by tomwilkie** [comment]
> We could also limit the cache size based on memory consumed instead of report cardinality.

How?

**Comment by 2opremio** [comment]
> How?

Rough estimation from the entry/node count sum from all topologies? It's still not accurate but it gets us closer than simply a report count.

Note that I also wrote:

> Although it may be hard to estimate the size of the reports.

**Comment by 2opremio** [comment]
We could also adjust the size to the incoming report rate so that Apps with a small amount of probes don't consume a lot of memory unnecessarily.

**Comment by tomwilkie** [comment]
So by my calculations, with 1 host reporting every 3 seconds, there will be 5 reports involved in every merge.  So ~10 intermediate, cached nodes.  Every 3 seconds, 5 of these will be invalidated, so it will take 600s for the 1000 node cache up.

I added a timeout on the cache and reduce it to 200 entries, and after 10mins my scope app was using...

**Comment by tomwilkie** [comment]
103.8MB

**Comment by 2opremio** [comment]
Maybe we can adjust the cache size based on the number of connected probes?
