### ISSUE TITLE
Add view for DaemonSets

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1444]
Just like we have for PODs, Services, ReplicaSets and Deployments.

**Comment by rade** [comment]
We are now running quite a few DaemonSets in Weave Cloud, which are currently invisible.

Related, I do wonder whether we need a hybrid view that shows everything at the "highest level of abstractions", i.e. show both Services and DaemonSets, plus individual pods that do not belong to either.

**Comment by rade** [comment]
I think we should have *one* view for deployments and daemonsets. AFAIK a pod can never be part of more than one of these. Call that view 'replicas', perhaps. The different types should of course be represented by visually distinct shapes.

The idea here is that we want to look at our system at a level of abstraction that collapses replicas, w/o having to care about / choose / filter-by the specific kind of abstraction that gave rise to the replicas.

I think ultimately we should include replicasets in this view as well, *if they are not part of a deployment*. But we can add that later; this would go in the direction of some of the hybrid view ideas from #552.

**Comment by ekimekim** [comment]
I concur. We can preserve the existing behaviour by adding a multi-select
option group for deployments/daemonsets/'bare replicasets'/'bare pods',
with the default being 'All Types'

**Comment by rade** [comment]
> We can preserve the existing behaviour by adding a multi-select

TooManyKnobsException. YAGNI.
