### ISSUE TITLE
Expose scope app & probe version in the API, and show in the UI.

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#145]

**Comment by davkal** [comment]
I think a need a bit more convincing about this feature. Why is this useful?

**Comment by tomwilkie** [comment]
Its useful to make it super easy for users to see what version they are using; for instance, when they report bugs.

Come to think of it, we should have a "send feedback" link in the UI which opens a bug on github.

I don't mind where we put this information in the UI; it doesn't have to be as prominent as #148.  But I think it needs to be exposed and easy to get to.
