### ISSUE TITLE
nodes overlap

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1450]
Before hitting redraw manually:
![](https://www.dropbox.com/s/hfiffmxd946mtyl/Screenshot%202016-05-09%2013.22.34.png?dl=1)
After hitting redraw button:
![](https://www.dropbox.com/s/vw3975xsksqb5ah/Screenshot%202016-05-09%2013.22.51.png?dl=1)

[Report](https://raw.github.com/errordeveloper/scope-report-store/master/report-2016-05-09-13-26-40.json)

**Comment by errordeveloper** [comment]
Ok, I think this is a more general issue with bottom-left buttons:
![](https://www.dropbox.com/s/krp1sacqpjvp6dx/Screenshot%202016-05-09%2019.08.48.png?dl=1)
[Report](https://raw.github.com/errordeveloper/scope-report-store/master/report-2016-05-09-19-09-06.json)

**Comment by tomwilkie** [comment]
Dupe #671?

**Comment by foot** [comment]
Bad caching keys i think, fixed in search by https://github.com/weaveworks/scope/commit/ee3aafad0313ddfd295fe9704169ef6517567f84

**Comment by davkal** [comment]
Yup, before that fix, they all shared the same layout cache.
