### ISSUE TITLE
High CPU consumption in probes

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1454]
On the three worker machines of the service the CPU consumption of the 0.15 candidate is over the roof

<img width="1418" alt="screen shot 2016-05-09 at 3 17 35 pm" src="https://cloud.githubusercontent.com/assets/2362916/15115958/49dfaff8-15f9-11e6-9941-1c6a1f7950dd.png">

Also, reports are being dropped. Probably for the same reason:

```
<probe> WARN: 2016/05/09 14:22:16.781555 Docker reporter took longer than 1s
<probe> ERRO: 2016/05/09 14:22:23.174719 Dropping report to 10.0.26.13:4040
<probe> WARN: 2016/05/09 14:22:25.812799 Docker reporter took longer than 1s
<probe> ERRO: 2016/05/09 14:22:27.388793 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:22:29.333923 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:22:32.135056 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:22:38.283660 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:22:41.262928 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:22:44.862768 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:22:50.425897 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:22:53.383612 Dropping report to 10.0.26.13:4040
<probe> WARN: 2016/05/09 14:22:55.870504 Docker reporter took longer than 1s
<probe> ERRO: 2016/05/09 14:22:57.934171 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:22:59.411752 Dropping report to 10.0.26.13:4040
<probe> WARN: 2016/05/09 14:23:01.011165 Docker reporter took longer than 1s
<probe> WARN: 2016/05/09 14:23:02.742918 Docker reporter took longer than 1s
<probe> ERRO: 2016/05/09 14:23:03.517608 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:23:06.190370 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:23:08.418448 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:23:11.232937 Dropping report to 10.0.26.13:4040
<probe> ERRO: 2016/05/09 14:23:14.856745 Dropping report to 10.0.26.13:4040
```

Resulting in a half-assed visualization of the service:

<img width="1571" alt="screen shot 2016-05-09 at 3 44 09 pm" src="https://cloud.githubusercontent.com/assets/2362916/15116852/e6370506-15fc-11e6-91c5-38732d621496.png">

Note how an app-mapper, a frontend and the ui-servers are missing

Profile: 
[pprof.localhost:4041.samples.cpu.001.pb.gz](https://github.com/weaveworks/scope/files/255180/pprof.localhost.4041.samples.cpu.001.pb.gz)
![probe_cpu](https://cloud.githubusercontent.com/assets/2362916/15116485/70649434-15fb-11e6-80ab-648faf5a25d0.png)

**Comment by 2opremio** [comment]
There are ~200 containers per machine from which less than 100 are running.

In order to tweak this, kubelet's arguments need to be adjusted http://kubernetes.io/docs/admin/garbage-collection/ so it seems we should be able to support that number of containers.

**Comment by 2opremio** [comment]
Here's  the output of `go tool pprof -focus 'GetNode' -png pprof.localhost\:4041.samples.cpu.001.pb.gz` 

![getnode](https://cloud.githubusercontent.com/assets/2362916/15118275/64911166-1603-11e6-9f20-49c363d78d7b.png)

**Comment by 2opremio** [comment]
It seems we are building the nodes for the report in every reporter iteration which, for containers which didn't change are wasted CPU cycles.

I will try caching the nodes and only regenerating then when they are affected by a docker event.

**Comment by tomwilkie** [comment]
The "Dropping report" is a new logging line added this release; it will be dropping reports due to the app being slow, not the probe.

**Comment by 2opremio** [comment]
> The "Dropping report" is a new logging line added this release; it will be dropping reports due to the app being slow, not the probe.

Good to know, then that's #1457
