### ISSUE TITLE
Overlapping node labels

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1460]
<img width="1637" alt="screen shot 2016-05-10 at 12 18 13" src="https://cloud.githubusercontent.com/assets/2362916/15144781/871a7e56-16a9-11e6-81d8-9ed302c14921.png">

Report: [report_overlapping_names.json.gz](https://github.com/weaveworks/scope/files/257033/report_overlapping_names.json.gz)

This seems to be a regression with 0.14 in which they were truncated.

**Comment by davkal** [comment]
Introduced by #1429, fixing there.
