### ISSUE TITLE
Weavescope manifest json & yml for k8s throwing 404

### ISSUE THREAD

**Issue by StephenCharles** [weaveworks/scope#1470]
While following the [k8s guide](https://github.com/weaveworks/scope/blob/master/site/installing.md#installing-scope-on-kubernetes) I got 404 on the following urls:

https://scope.weave.works/k8s-gen/weavescope.json
https://scope.weave.works/k8s-gen/weavescope.yaml

**Comment by errordeveloper** [comment]
@StephenCharles thanks for reporting this, the docs went out before URL became operational. Please hangon, we are going to fix it shortly.

**Comment by errordeveloper** [comment]
Closed via #1464.

**Comment by errordeveloper** [comment]
@StephenCharles the URL has changed slightly, please refer to the updated docs.

**Comment by StephenCharles** [comment]
Thank you!

**Comment by aanm** [comment]
@errordeveloper New URL still doesn't work

**Comment by errordeveloper** [comment]
If you check the docs, the URL is ***`https://scope.weave.works/launch/k8s/weavescope.json`***.

**Comment by aanm** [comment]
It was not working due maintenance. Thanks for checking it out :-)
