### ISSUE TITLE
Uncontained/unmanaged show up as a separate graph when connected to each other

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1478]
Which is a bit odd, and clutters the view.

Maybe we should do a "reachability" walk from each of the containers/pods and eliminate graphs of only pseudo-nodes?

Raised by @rade

**Comment by tomwilkie** [comment]
Had a think, and I can't see a O(n) solution here.

**Comment by rade** [comment]
How about only showing the pseudo nodes that are *directly* connected to the containers/pods? To look beyond that, the user can switch to the process view.

**Comment by rade** [comment]
Isn't this the same as #1129?

**Comment by paulbellamy** [comment]
> ... same as #1129

Looks the same, yes.
