### ISSUE TITLE
k8s: Missing instructions to launch Scope in Service mode

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1482]
In the recent docs refactor those instructions were lost:

https://github.com/weaveworks/scope/blob/master/site/installing.md#installing-scope-on-kubernetes

(CC @abuehrle @errordeveloper )

**Comment by 2opremio** [comment]
Also _we should mention that Daemon Sets are enabled by default from Kubernetes 1.2 onwards.

Ref: https://github.com/weaveworks/scope/commit/b624df63d3ea1043f8fb4fe077dd38ff4fa604d5

**Comment by rade** [comment]
@2opremio What do you mean by 'lost'? Your link points to master and the instructions are clearly there. And they are [on the website](https://www.weave.works/docs/scope/latest/installing/#k8s) too.

**Comment by 2opremio** [comment]
@rade This was about b624df6 which only mentions the token parameter on the side and explicitly says

> To install Scope on a Kubernetes cluster in Standalone Mode ...

but, unlike the previous documentation, there are no explicit instructions to launch it on service mode (now Weave Cloud). AFAICT that's still the case.

@abuehrle , maybe you can fix it as part of https://github.com/weaveworks/scope/pull/1586 ?

**Comment by abuehrle** [comment]
I have done that, please take a look and let me know if it needs any more details:  #1586

**Comment by davkal** [comment]
Fixed by #1586
