### ISSUE TITLE
Differences between search and filter

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#1488]
`Command` is not being included in the pinned filter, i think.

![screen shot 2016-05-12 at 15 16 33](https://cloud.githubusercontent.com/assets/22008/15215843/d38813e6-1854-11e6-97ae-cf4f0ee3189a.png)
![screen shot 2016-05-12 at 15 16 10](https://cloud.githubusercontent.com/assets/22008/15215844/d38bee44-1854-11e6-81fe-03c6cff3a424.png)

**Comment by davkal** [comment]
Cannot reproduce.

Pinned searches (filters) and normal search queries use the same matchers. Fields are not saved in the pinned searches, unless they are part of the query, e.g. `command:probe`.

**Comment by foot** [comment]
I can only repro on very large topos.
