### ISSUE TITLE
Remote IPs get truncated in the internet view

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1492]
It's not terribly useful, as you can't select them. The column should probably be wide enough for an IP.
![screen shot 2016-05-12 at 16 02 17](https://cloud.githubusercontent.com/assets/250199/15219258/ffcf29a2-185a-11e6-81db-120448659360.png)

**Comment by bboreham** [comment]
It seems odd to me that it is truncating these strings when there is loads of white space to the right of them.
