### ISSUE TITLE
Pods with > 1 container making connections do not show any connections

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1494]
I believe this is because they share a network namespace, so the endpoint cannot be attributed to a container, and [we drop it](https://github.com/weaveworks/scope/blob/master/render/container.go#L212).

Report attached [report.zip](https://github.com/weaveworks/scope/files/261686/report.zip)

**Comment by tomwilkie** [comment]
So given a pod has a unique IP, we could do another conntracked edge join on the pod topology to fix this.

I was previously against doing this, but with the recent improvements to conntrack, it might be worth it.

**Comment by tomwilkie** [comment]
We're hitting this visualising Weave Cloud, and just had reports from a third party that they are also hitting this and they want to use scope in their Dockercon demo.  So I'd like to try and get a fix in for 0.16 tomorrow.
