### ISSUE TITLE
Text collision in properties panel on FF 38.0

### ISSUE THREAD

**Issue by awh** [weaveworks/scope#150]
![screenshot from 2015-06-02 12 58 24](https://cloud.githubusercontent.com/assets/1504438/7935233/2b2a023c-0927-11e5-9934-1dab0e2407b5.png)

**Comment by davkal** [comment]
Reasons for using FF:
:fallen_leaf:

**Comment by awh** [comment]
> Reasons for using FF

Monocultures are unhealthy? :wink:

**Comment by davkal** [comment]
Looks ok in FF35

![screen shot 2015-06-11 at 11 20 17](https://cloud.githubusercontent.com/assets/859729/8103820/dd7c4818-102b-11e5-94c2-37e134bf6284.png)

**Comment by davkal** [comment]
And in FF 38. 

![screen shot 2015-06-11 at 11 21 10](https://cloud.githubusercontent.com/assets/859729/8103846/0775a754-102c-11e5-960b-3c665b1f964f.png)

Closing this one.

Maybe you tested an old release?
