### ISSUE TITLE
Wrong host labels on container nodes

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1501]
<img width="1577" alt="screen shot 2016-05-12 at 7 39 51 pm" src="https://cloud.githubusercontent.com/assets/2362916/15226219/bf1ab4e8-1879-11e6-9532-f633f0cb9178.png">

Note how the container node label reads `ip-172-31-0-5` (in fact all containers do) but the details panel shows (correctly) `ip-172-31-0-6`

I believe this is a regression (it at least worked on 0.13.1, see the screenshots at https://github.com/weaveworks/scope/issues/1162 )

Tentatively marked as ui bug

**Comment by 2opremio** [comment]
Report: [report_wrong_node_labels.json.gz](https://github.com/weaveworks/scope/files/262051/report_wrong_node_labels.json.gz)

**Comment by tomwilkie** [comment]
I don't think its the UI, as the events from the backend have the wrong labels.

**Comment by tomwilkie** [comment]
Yeah, in fact if you hit a node endpoint and refresh, you get two different hostnames.

**Comment by tomwilkie** [comment]
This definitely doesn't affect the process topology.

**Comment by tomwilkie** [comment]
And has nothing to do with k8s.

**Comment by 2opremio** [comment]
> And has nothing to do with k8s.

This is ECS
