### ISSUE TITLE
better screenshots for docs

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1502]
The images in the docs are sub-optimal. The font size of the ones in http://dev-weavewww.pantheonsite.io/docs/scope/master/introducing/ is too small to clearly read labels, some don't show anything interesting whatsoever (e.g. the 2nd image at http://dev-weavewww.pantheonsite.io/docs/scope/master/introducing/), and some illustrate rendering glitches (notice the label/node overlap in http://dev-weavewww.pantheonsite.io/docs/scope/master/features/#topology-mapping).

**Comment by abuehrle** [comment]
We should close this issue, as this is an internal dev server.  I will fix images @rade
