### ISSUE TITLE
Filter by kubernetes namespace in CONTAINERS view

### ISSUE THREAD

**Issue by janwillies** [weaveworks/scope#1504]
With scope-0.15 it's possible to filter by namespace in the PODS view which is great when having lots of namespaces. From there however it's difficult to get to the right container as all containers are listed in the sidebar, not just the ones belonging to the filtered namespace:

![scope-ns-issue](https://cloud.githubusercontent.com/assets/2564820/15250437/0d943d00-1925-11e6-8972-1ca9d46a969f.png)

A namespace filter in the CONTAINERS view would allow to directly jump into the container and e.g. open a shell.

@2opremio suggested making the namespace filter global

**Comment by rade** [comment]
The issue with k8s view detail panels showing pods/containers/processes belonging to a different namespace was actually a bug - see #1824 - and got fixed in #1832.

**Comment by ekimekim** [comment]
Should the container by image and container by dns topologies also have this filter?

**Comment by rade** [comment]
Yes.

**Comment by rade** [comment]
PR #2285 got reverted in #2348, so re-opening this.
