### ISSUE TITLE
TCP connections, bytes ingress/egress -- what do these mean?

### ISSUE THREAD

**Issue by squaremo** [weaveworks/scope#151]
It's not clear what "TCP connections" corresponds to (sometimes it's in the hundreds, not sure why).
Bytes ingress and egress appear to always be zero.

**Comment by peterbourgon** [comment]
"TCP connections" indeed represents the number of TCP connections that are attached to the thing you've clicked on. More specifically, it's the maximum number of observed TCP connections for every core node that composes the rendered node. Can you think of a better way to express that? "Active TCP connections"?

Bytes ingress and egress are indeed always zero (for now) and will be hidden in an upcoming point release.

**Comment by squaremo** [comment]
> "TCP connections" indeed represents the number of TCP connections that are attached to the thing you've clicked on.

Hmm, well I guess the numbers were surprising then, so perhaps the lesson is that being able to find out what those connections represent would be useful.

> Bytes ingress and egress are indeed always zero (for now)

Oh OK. I can imagine those being quite useful -- "not done yet" is an understandable answer though.

**Comment by peterbourgon** [comment]
Filed #158 for that enhancement.
