### ISSUE TITLE
Highlighting is unpredictable

### ISSUE THREAD

**Issue by squaremo** [weaveworks/scope#1520]
The hit boxes seem to be a bit off -- sometimes things will highlight when the pointer is nowhere near them, or not highlight when the pointer is right on them.

![screenshot from 2016-05-18 13-16-19](https://cloud.githubusercontent.com/assets/62033/15358216/1425306e-1cfb-11e6-869a-1b59ae10fe95.png) (an artist's impression of the pointer position has been added)

This is an accidentally zoomed-in view, but the same problem is present when not zoomed.

Firefox 46, Ubuntu 15.10.

**Comment by rade** [comment]
I get this all the time by going to the default (container) view of our [dev admin scope](http://frontend.dev.weave.works/admin/scope/):

![screenshot_2016-07-15_20-04-38-clipped](https://cloud.githubusercontent.com/assets/109109/16885768/1300eb38-4ac8-11e6-9376-84b2852de311.png)

*but only in firefox, not in chrome*.
