### ISSUE TITLE
Duplicate stack in "by image" view

### ISSUE THREAD

**Issue by squaremo** [weaveworks/scope#1521]
![screenshot from 2016-05-18 13-16-19](https://cloud.githubusercontent.com/assets/62033/15358326/b538d9ba-1cfb-11e6-9591-554e2e5a6ae5.png)

Why are there two stacks of weaveworks/hello-world?

**Comment by squaremo** [comment]
Ah, the images are genuinely different, but have the same tag. A bit confusing that they look identical.

**Comment by tomwilkie** [comment]
This is a real bug; we very much try and dedupe different version of the 'same' image in this view.
