### ISSUE TITLE
enable use of plugins on kubernetes

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1522]
We should be doing something like `-v /var/run/scope/plugins:/var/run/scope/plugins`

**Comment by rade** [comment]
@errordeveloper This is not a Scope but a Service issue, isn't it?

**Comment by errordeveloper** [comment]
Yes, this is a bug, but simply providing host path in the pod doesn't help the user with install any plugins.

**Comment by errordeveloper** [comment]
@rade I think this is generally a Scope bug.

**Comment by rade** [comment]
> @rade I think this is generally a Scope bug.

How so? The scope script does mount the plugin dir. And the summary specifically talks about the yaml generator. Is the summary too specific? What is the real problem we are trying to solve here? Enabling users to install scope plugins when deploying scope using k8s?

**Comment by errordeveloper** [comment]
> Enabling users to install scope plugins when deploying scope using k8s?

Yes, I think that is the real problem. Simply bind-mounting a directory on the host is not going to help the user at all, they would still need to put a plugin in that path somehow, and I think it'd be best if we had a clear answer to that. Perhaps we could document simple plugin development workflow with single-node kubernetes cluster, or document what plugin pod definition would have to look like.

**Comment by ephur** [comment]
Are there any updates on this? It would be great if we could enable plugins in kubernetes. Scope is great, and would like to be able to extend even further.

**Comment by bboreham** [comment]
Hi @ephur, as was hinted above, if you have plugins in `/var/run/scope/plugins` on the host and use our install script, they will be mapped into the Scope pod.

**Comment by bboreham** [comment]
The [example config](https://github.com/weaveworks/scope/blame/b07bfb294bbf4cf09a17e98194fa0c7ac7af3910/examples/k8s/ds.yaml#L46) maps the plugins directory (extended in #3717); closing.
