### ISSUE TITLE
Cannot port-forward app from kubernetes with command in documentation

### ISSUE THREAD

**Issue by rothgar** [weaveworks/scope#1526]
I'm running weave scope in kubernetes and followed the [documentation steps](https://www.weave.works/docs/scope/latest/installing/#k8s) to get it running.

When trying to port forward weave scope to my localhost host using the command

```
kubectl port-forward $(kubectl get pod --selector=weavescope-component=weavescope-app -o jsonpath={.items..metadata.name}) 4040
```

It doesn't work because kubectl complains 'error: name cannot be provided when a selector is specified'
With debug output `--v=9` it looks like the problem is in helpers.go line 107. I didn't dig into the code but wanted to raise the issue with documentation.

If I remove the output formatting `-o jsonpath=...` the command works and shows me the proper name. An alternative command could also be
```
kubectl port-forward $(kubectl get pod --selector=weavescope-component=weavescope-app | grep -v '^NAME' | awk '{print $1}' | head -n 1) 4040
```
obviously not as elegant but uses kubectl pod NAME instead of parsing the json.

I'm using kubernetes 1.2.3 with kubectl 1.2.3.

**Comment by tomwilkie** [comment]
Hi @rothgar sorry for the delay in getting back to you!

I've just tried it and it worked for me:

```
Toms-MacBook-Pro:service twilkie$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.3", GitCommit:"882d296a99218da8f6b2a340eb0e81c69e66ecc7", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Toms-MacBook-Pro:service twilkie$ kubectl create -f 'https://cloud.weave.works/launch/k8s/weavescope.yaml' --validate=false
replicationcontroller "weavescope-app" created
service "weavescope-app" created
daemonset "weavescope-probe" created
Toms-MacBook-Pro:service twilkie$ kubectl port-forward $(kubectl get pod --selector=weavescope-component=weavescope-app -o jsonpath={.items..metadata.name}) 4040
I0624 09:56:50.653731   85457 portforward.go:213] Forwarding from 127.0.0.1:4040 -> 4040
I0624 09:56:50.654230   85457 portforward.go:213] Forwarding from [::1]:4040 -> 4040
I0624 09:57:05.138140   85457 portforward.go:247] Handling connection for 4040
```

Would you mind pasting the equivalent output including your error?

Thanks
Tom

**Comment by nitin-amp** [comment]
Not sure if others encountered this - I had a similar problem port-forwarding app to localhost using the command. The root cause was missing 'socat' on the nodes and installing it fixed the issue. It seems to be a known k8s issue ([#19765](https://github.com/kubernetes/kubernetes/issues/19765)).

kubectl 1.2.4/ k8s 1.2.4. 2-node (fedora23) vagrant setup on Mac OSX.

**Comment by tomwilkie** [comment]
@nitin-amp thanks for the input!  I'll add a mention to the docs.

If you're having trouble accessing scope, you can set it up to use Weave Cloud; I've just opened a PR with instructions on how: https://github.com/weaveworks/scope/pull/1611

**Comment by rothgar** [comment]
I'll have access to the nodes again on Monday and will try then.

@nitin-amp thanks for the tip about socat. I was able to port-forward once I changed the way the pod name was filtered.

**Comment by rothgar** [comment]
@tomwilkie Here's the output on my system

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}

$ kubectl create -f 'https://cloud.weave.works/launch/k8s/weavescope.yaml' --validate=false
replicationcontroller "weavescope-app" created
service "weavescope-app" created
daemonset "weavescope-probe" created

$ kubectl port-forward $(kubectl get pod --selector=weavescope-component=weavescope-app -o jsonpath={.items..metadata.name}) 4040
error: name cannot be provided when a selector is specified
error: at least 1 PORT is required for port-forward
See 'kubectl port-forward -h' for help and examples.
```

**Comment by tomwilkie** [comment]
Thanks @rothgar; could you try `kubectl get pod --selector=weavescope-component=weavescope-app -o jsonpath={.items..metadata.name}` and send me the output please?

**Comment by rothgar** [comment]
```
kubectl get pod --selector=weavescope-component=weavescope-app -o jsonpath={.items..metadata.name}
error: name cannot be provided when a selector is specified
```

**Comment by 2opremio** [comment]
> Not sure if others encountered this - I had a similar problem port-forwarding app to localhost using the command. The root cause was missing 'socat' on the nodes and installing it fixed the issue. It seems to be a known k8s issue (#19765).

Thanks for reporting it, but that's a different issue, for @rothgar the command to obtain the pod name is nor working.

**Comment by 2opremio** [comment]
@rothgar Can you still reproduce? I've tried with different kubectl versions (1.2.2, 1.2.3, 1.2.4) but still can't.

I can only reproduce it when providing an explicit name in the command line:

```
kubectl --kubeconfig=infra/local/kubeconfig get pod --selector=weavescope-component=weavescope-app foo
error: name cannot be provided when a selector is specified
```

So, could it be that your shell is somehow passing a name to kubectl? Maybe the ending 4040? What shell are you using?

To be sure, can you try running the following?

```
$ printargs() { echo begin; for A in $@; do echo \'$A\'; done; echo end; }
$ echo kubectl port-forward $(printargs kubectl get pod --selector=weavescope-component=weavescope-app -o jsonpath={.items..metadata.name}) 4040
kubectl port-forward begin 'kubectl' 'get' 'pod' '--selector=weavescope-component=weavescope-app' '-o' 'jsonpath={.items..metadata.name}' end 4040
```

Maybe the configuration issue? Can you try removing the `~/.kube`?

I am sure this entirely depends on the client since I can reproduce with:

```
kubectl -s doesntexist.local get pod --selector=weavescope-component=weavescope-app foo
error: name cannot be provided when a selector is specified
```

**Comment by rothgar** [comment]
I was upgrading to 1.3.0 and was going to test when @2opremio made me realize zsh has a built in to expand (usually numbers) inside { }
Just opened #1651 with quotes to fix it. Tested on bash and zsh. Thanks for the help debugging everyone, sorry for the trouble.

**Comment by Van-Tien** [comment]
I have issue with UI when run port-forward to localhost then use the nginx to access by hostname but it can not load the topology, Does anyone get this issue ?
Here is my nginx config:
server {
    listen 80;
    server_name myhostname.com;
    location / {
        proxy_pass http://10.0.0.215:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

**Comment by 2opremio** [comment]
@Van-Tien nginx doesn't handle websockets out of the box, you will need to enable upgrades in the websocket routes, see https://nginx.org/en/docs/http/websocket.html

I will try to get you a specific configuration.

**Comment by 2opremio** [comment]
@Van-Tien See the configuration from https://github.com/weaveworks/scope/issues/2287
