### ISSUE TITLE
Allow user to override app and probe default port

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#153]

**Comment by peterbourgon** [comment]
Why?

**Comment by tomwilkie** [comment]
Just in case port 4040 and 4030 are already in use locally.

I think it came up in conversation when I was encouraging people to give
feedback, but I don't remember who mentioned it.

**Comment by peterbourgon** [comment]
Gotcha. How would you change that, via the scope script?

**Comment by tomwilkie** [comment]
With the scope script, any extra arguments are just passed to the
container's entrypoint.sh script.

I'm thinking in entrypoint.sh, munging any arguments starting with -probe.
into a file /etc/weave/probe-args, and similar for the app.  Then in
run-app and run-probe, read these files and tack them onto the command,
similar to how we handle having hosts passed right now.

What do you think?

**Comment by peterbourgon** [comment]
I like the idea of using a flag prefix and parsing it in the scope script, but there's got to be a nicer way than dumping them to text files in the container and dumping them out again in the run scripts?

**Comment by tomwilkie** [comment]
Depends on what runit supports. Dumping the flags to a file seems the
easiest to me.

**Comment by davkal** [comment]
Definitely need to change UI dev server port from 3000 to 404x.
:3000 is just too common.

**Comment by peterbourgon** [comment]
I guess I'm wondering if there's a better way to pass information through the host—Docker membrane. Environment variables? Probably too finicky. Yeah, maybe files are the least-bad option.

**Comment by tomwilkie** [comment]
The command line is used for the "host—Docker membrane".  Its within the container, passing variables from entrypoint.sh to the run-foo scripts that requires the file.

**Comment by peterbourgon** [comment]
Sorry, yes, that's what I meant.
