### ISSUE TITLE
Connections-table columns should be able to fit an ipv4 address

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1532]
Right now they are truncated, which is really frustrating for users.

I saw this myself a couple of weeks ago but wasn't sure it was a problem, now we have confirmation from a user.

Context: https://weaveworks.slack.com/archives/weave-users/p1463732653000585

**Comment by tomwilkie** [comment]
Also see #1492, #927

**Comment by rade** [comment]
@2opremio is this any different from #1492?
