### ISSUE TITLE
Allow users to inspect connections

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#154]
Some confusion has arisen from the number of active connections we should in the details panel.

We could potentially allow users to click this number, and see a table of (src, dst, time observed) connections.

**Comment by tomwilkie** [comment]
I think it would be nice to, instead of showing a bunch of endpoint tables in the details panel, we should a single table of all the connections:

```
host:port -> host':port', timestamp
```

We could try and show the amount of time this connection has been open for.

**Comment by paulbellamy** [comment]
afaict, on linux you only get "local" and "remote" addresses, not the directionality of the connection. So, procspy will have to check which ports/interfaces each container is listening on, and use that to infer which end is the initiator.

**Comment by tomwilkie** [comment]
@paulbellamy whats left here?

**Comment by paulbellamy** [comment]
Nothing! :+1:
