### ISSUE TITLE
Edges broken with k8s < 1.2

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1558]
It would seem the containers aren't being associated with pods correctly:

![screen shot 2016-06-08 at 10 49 52](https://cloud.githubusercontent.com/assets/444037/15890318/cfe8a76a-2d66-11e6-9335-83a993cd6a13.png)

**Comment by tomwilkie** [comment]
This only affect k8s 1.1 - it doesn’t label container with the pod uid...

**Comment by rade** [comment]
I don't think we care enough about older k8s. -> closing
