### ISSUE TITLE
Running containers not visible in Containers, only in "By X" sub-views

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#1561]
I have 3 hosts running 7c4b7a5 (latest master) and start an Ubuntu container on each with

```
$ docker run --net=weave -ti ubuntu
```

In Scope, if I show both System+Application containers, but only Running containers, and go to Containers view, I don't see them. If I go to Containers by DNS name or image, I see them grouped appropriately.

[report.txt](https://github.com/weaveworks/scope/files/304524/report.txt)

**Comment by peterbourgon** [comment]
I closed the Scope tab and re-opened it some minutes later, without changing anything in my infrastructure, and everything is working as expected. Which is unexpected. I'll leave the issue open in case somebody wants to dive deeper, but I think it's probably also OK to close.

**Comment by peterbourgon** [comment]
Annnd it's back. I don't know if it's related, but here's an error I get in the JS console.

[console.log.txt](https://github.com/weaveworks/scope/files/304614/console.log.txt)

**Comment by peterbourgon** [comment]
Notably the Containers view shows a blank canvas, despite System+Application being selected.

**Comment by peterbourgon** [comment]
And when I closed the tab and opened it again, everything is back to normal.

**Comment by foot** [comment]
I think @davkal may have resolved this w/ https://github.com/weaveworks/scope/commit/2267a79be88f77009b3026ea08c778d03683af75

**Comment by peterbourgon** [comment]
Oh! I bet so!

**Comment by davkal** [comment]
Yes, that fixed it. (2267a79 LGTM'd by @foot in Slack)

**Comment by peterbourgon** [comment]
Can't reproduce the error anymore either, so 🎉

**Comment by tomwilkie** [comment]
I'm worried this might have been pushed to prod, so reopening until I can confirm.

**Comment by davkal** [comment]
This was introduced with the network views.

**Comment by tomwilkie** [comment]
Service is on 38af5e0, which has the fix.  Thanks!
