### ISSUE TITLE
scope command line has two distinct modes

### ISSUE THREAD

**Issue by jml** [weaveworks/scope#1562]
The scope command line has two distinct modes (AFAIK): standalone & probe-only.

If you run `scope launch` or `scope launch <peer>`, it will go into stand-alone mode, hosting a web service that you can browse to and see awesome graphs. e.g.

```
$ ./scope launch ======
a956627a1d03d711973bfd130f600f26e54e3c9e8391a86b27c6ae3bf381da78
Weave Scope is reachable at the following URL(s):
  * http://192.168.1.83:4040/
  * http://172.19.0.1:4040/
  * http://10.32.0.1:4040/
  * http://172.18.0.1:4040/
```

If you run `scope launch --service-token <token>`, it will launch in probe-only mode, and just print a container ID (#1560) and not give any clue about what to do next. Because of #1559, this is very suspicious -- how do I know that it worked? was it supposed to do that? has it connected? did it connect to the right thing?

One way to fix this is to provide more output in `scope launch` when running in probe-only mode. Another way to mitigate is to have a separate sub-command. If we do that, the sub-command should probably have more informative output than a container ID.

**Comment by rade** [comment]
> One way to fix this is to provide more output in `scope launch` when running in probe-only mode.

We did do that in #2077.
