### ISSUE TITLE
Dropping report should be logged as warning, not error

### ISSUE THREAD

**Issue by jml** [weaveworks/scope#1565]
Currently dropped reports are logged like this:

```
<probe> ERRO: 2016/06/08 12:55:46.924838 Dropping report to <hostname>:<port>
```

However, a dropped report is part of the normal operation of scope. Instead, this should be logged as a WARNING. This frees up ERROR to be for things that actually require external intervention.

**Comment by rade** [comment]
I fixed this as part of #2756.
