### ISSUE TITLE
Container in multiple networks not showing all connections

### ISSUE THREAD

**Issue by idcrosby** [weaveworks/scope#1573]
We have service which is connected to two networks, so has two IPs (as seen here via docker inspect)
<img width="735" alt="screen shot 2016-06-09 at 14 52 32" src="https://cloud.githubusercontent.com/assets/1084449/15932060/237ef4ec-2e52-11e6-81ac-1b5fd52b81a0.png">

On Scope, it is only showing one IP:
<img width="390" alt="screen shot 2016-06-09 at 14 53 52" src="https://cloud.githubusercontent.com/assets/1084449/15932100/42a7306e-2e52-11e6-84cc-082709cd4361.png">
 
Attaching reports file. Affected service is "front-end"
[report_09_06_json.zip](https://github.com/weaveworks/scope/files/307018/report_09_06_json.zip)

**Comment by 2opremio** [comment]
To clarify this further, there were short-lived connections from 10.32.0.2 which weren't being displayed as edges in Scope because the container was only attributed IP 10.40.0.8
