### ISSUE TITLE
Probe reporter stuck

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1576]
The user (blaines at #weave-users Slack channel) is running Scope version 0.14 and the report publisher in one of his probes  seems to be stuck.

Full context: https://weaveworks.slack.com/archives/weave-users/p1465510035000191

Scope probe logs: https://gist.github.com/blaines/db726bf232c411a863a5faab74f24b56
Scope probe goroutine dump: https://gist.github.com/2opremio/1fe38671faf74c59b248aba03ed40051

**Comment by 2opremio** [comment]
Related? #881

**Comment by 2opremio** [comment]
At a first look, it seems like the deadlock is happening at the multiclient's (multi_client.go) mutex

**Comment by blaines** [comment]
Nice! Thanks for looking into it.

**Comment by 2opremio** [comment]
Yep, that's the problem, we are double locking a mutex:

``` 
goroutine 42 [semacquire, 4132 minutes]:
sync.runtime_Semacquire(0xc82212309c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc822123090)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/weaveworks/scope/probe/appclient.(*appClient).Stop(0xc822122fc0)
	/go/src/github.com/weaveworks/scope/probe/appclient/app_client.go:137 +0x1ac
github.com/weaveworks/scope/probe/appclient.(*multiClient).Set(0xc82032b320, 0xc821a736e0, 0x16, 0xc821a501c0, 0xe, 0xe)
	/go/src/github.com/weaveworks/scope/probe/appclient/multi_client.go:119 +0x76a
``` 

`(*multiClient).Set()` locks the mutex and invokes `(*multiClient).Stop()` which tries to lock it again.

All 0.15, 0.14 and master are affected. It's been present since at least ffa955a21b91a11a517dc0c0ef3b4567fea3541e

**Comment by 2opremio** [comment]
Having https://github.com/weaveworks/scope/issues/943 would had made the diagnosis much easier

**Comment by 2opremio** [comment]
@blaines Thank you for your patience and help!

**Comment by 2opremio** [comment]
I may have spoken too soon. Multiclient invokes `Stop()` from each individual client not itself. I will look at it more carefully tomorrow.

**Comment by 2opremio** [comment]
My initial analysis was wrong, now I think that there's something wrong with the goroutine wait when stopping a client. https://github.com/weaveworks/scope/blob/v0.14.0/probe/appclient/app_client.go#L137

```
goroutine 42 [semacquire, 4132 minutes]:
sync.runtime_Semacquire(0xc82212309c)
    /usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc822123090)
    /usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/weaveworks/scope/probe/appclient.(*appClient).Stop(0xc822122fc0)
    /go/src/github.com/weaveworks/scope/probe/appclient/app_client.go:137 +0x1ac
github.com/weaveworks/scope/probe/appclient.(*multiClient).Set(0xc82032b320, 0xc821a736e0, 0x16, 0xc821a501c0, 0xe, 0xe)
    /go/src/github.com/weaveworks/scope/probe/appclient/multi_client.go:119 +0x76a
```

Maybe the client gets stuck here https://github.com/weaveworks/scope/blob/v0.14.0/probe/appclient/app_client.go#L170 not releasing goroutine.

**Comment by 2opremio** [comment]
This is what I believe happened:

1. A probe http client [got stuck](https://gist.github.com/2opremio/1fe38671faf74c59b248aba03ed40051#file-goroutines-txt-L77-L119) in a publish request to an app (most probably related due to the  Spot instance where the app was running going down, see https://weaveworks.slack.com/archives/weave-users/p1465513276000257 )
2. The multiclient [rightfully tried to Stop the client for the app in that host](https://github.com/weaveworks/scope/blob/v0.14.0/probe/appclient/multi_client.go#L117-L122) for which it acquired its mutex.
3. The invocation of `Stop()` [blocked forever](https://gist.github.com/2opremio/1fe38671faf74c59b248aba03ed40051#file-goroutines-txt-L333-L349) since it involves waiting for goroutines to end and one of them was stuck in (1). Due to the multiclient having taking it's lock in (2) [no reports cloud be published anymore](https://github.com/weaveworks/scope/blob/v0.14.0/probe/appclient/multi_client.go#L169-L180)

To solve this:

1. We should definitely set a timeout for publish requests in client_app since an app not responding shouldn't block the clients to the other apps. However, if this really happened due to (1) I don't understand why the go http client didn't return after hours.
2. Maybe we should go as far as using `net/context` to cancel the latest request or saving the latest request for cancellation with https://golang.org/pkg/net/http/#Transport.CancelRequest
3. We should make sure this cannot happen with the control/pipe connections.

**Comment by 2opremio** [comment]
After a conversation with @tom , looking at the app_client pointer `0xc822122fc0` confirms my theory (the goroutine calling `Stop()` and the goroutine calling `publish()` are accessing the same client)

**Comment by 2opremio** [comment]
> Now the question is, why did the http request in `publish()` didn't return once it's connection was closed by `Stop()`?

Because the client's connection is never registered only the pipe and control connection :)
