### ISSUE TITLE
Graph rendering is non-deterministic

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#160]
Makes it difficult to track/compare when changing views.

**Comment by davkal** [comment]
This might be a bigger project since we're using a third-party layout engine called Dagre. We'd have to fork and remove the random initialisers.

**Comment by tomwilkie** [comment]
[14:49] Bryan Boreham: It's fun to click around on this page, but you might want to put some thought into making it more deterministic, so when I flip from Applications to Containers and back I get the same screen each time.

**Comment by squaremo** [comment]
There's another aspect to this that may be easy to overlook. Laying the graph out consistently given a constant data set is one thing; however, some of the unpredictability comes from flipping things around when the data set changes momentarily (e.g., there has been no data over a connection for a few seconds, so it disappears).
