### ISSUE TITLE
Different networks can have the same color

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#1601]
Too much purple

![demonstrated](https://cloud.githubusercontent.com/assets/114509/16180719/a747a1be-3642-11e6-8dc1-6f1438448a66.png)

**Comment by peterbourgon** [comment]
This may be fixed in 0.16 and I'm only hitting it because Cloud is running an older version. If so, please close and accept my apologies.

**Comment by rade** [comment]
dup of #1592.
