### ISSUE TITLE
view-only mode

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1605]
[Some users](https://weaveworks.slack.com/archives/weave-users/p1466510817000440) want to share their scope with others but don't allow them to modify anything.

**Comment by rade** [comment]
I am guessing this is more of a Weave Cloud feature than scope app feature.

**Comment by tomwilkie** [comment]
OSS doesn't really have the concept of users, so yes I think this is a weave cloud thing.

Would be straight forward to disable controls and pipes for certain users.

**Comment by 2opremio** [comment]
I think we should also provide a read-only mode for OSS, through a start flag. I will get this done.
