### ISSUE TITLE
Enable task-switching in the GUI 

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1617]
An application has been launched.
A shell has been opened into a container that is part of the application.

As a user, I want to temporarily switch back into the topology view to check some information or find a new piece of information, before returning to the shell so I can execute another command (while debugging an application).

Currently the only way to do this is to close the terminal and re-open it - but then the user loses any command history or output I've established.

**Comment by rade** [comment]
you can extract the terminal, i.e. turn it into a proper window.

**Comment by rade** [comment]
@pidster ping

**Comment by pidster** [comment]
I'm sure that wasn't clear to me at the time...

**Comment by rade** [comment]
File an issue: "terminal extraction control is obscure"
