### ISSUE TITLE
Restarting scope results in leftover "probe" nodes in the graph

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#162]
Not really a problem, just seems a bit weird. Nodes are cleared when going to a different view and back.

```bash
sudo scope launch
open http://localhost:4040
sudo scope stop
sleep 5
sudo scope launch
```

After a few restarts:
![screen shot 2015-06-02 at 16 23 30](https://cloud.githubusercontent.com/assets/250199/7939652/e7e403b6-0943-11e5-8e48-7bf93c667507.png)

**Comment by peterbourgon** [comment]
I've also noticed this behavior, on other things. Nodes are "stuck" in the UI, but aren't represented in /api/topology/x. It's possible the websocket isn't sending the Delete diff, but I'd say unlikely, as that code is pretty well-tested... @davkal I'd like to make this a bug for the next milestone, do you think you have enough to reproduce?

**Comment by davkal** [comment]
Yeah, I get leftover app nodes when restarting.
Have not seen the 'stuck' behaviour. How to reproduce?

**Comment by peterbourgon** [comment]
By stuck I just meant leftover.

**Comment by davkal** [comment]
The Disconnected alert is currently not showing, should be fixed with this.
