### ISSUE TITLE
Time travel support

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1620]
Allow users to go back in time and show the UI as it was at any given point in the past.

Note that this is related but different to #1619

**Comment by rade** [comment]
I envisage video player like controls here.

Scope controls - terminals, logs, etc - won't work, but that's ok.

**Comment by rade** [comment]
@fbarl has developed some [mockups](https://docs.google.com/presentation/d/1E7agb2N_ZSWIM81IIC_S64V1FP0_VWR0CF6Z65ZfShU/edit#slide=id.p) and there's a prototype in #2524
