### ISSUE TITLE
Alerting brainstorm

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#1643]
Following on from DockerCon we have some ideas about the kind of alerting that Scope could do.
- Alert to low-impact channels 
  - e.g. Make a node red
  - e.g. Growl-style notification in UI
  - e.g. Slack integration with deep link to affected entity
  - Notably NOT PagerDuty etc.
  - This gives us freedom to experiment without being disruptive
- Keep Scope zero-configuration
  - Implies we will decide what constitues alertable condition
  - e.g. Process/container/... file descriptor limit reached
  - e.g. Host load above num CPU for X minutes
  - e.g. Above some threshold of zombie processes
  - e.g. Kubernetes entity reports error condition
  - Application alerting incl. config/thresholds/etc. can come when we have better L7 introspection

**Comment by rade** [comment]
When talking to external systems we'd need to address the fact that in its default configuration there can be many apps looking at the same probes.

**Comment by peterbourgon** [comment]
The Prometheus fellows have solved this problem in their Alert Manager (via Mesh, natch). But it is not a trivial thing.

**Comment by bboreham** [comment]
Nowadays we would recommend the use of Prometheus, or the multi-tenant version https://github.com/weaveworks/cortex, for alerting.

The ideas for zero-configuration are interesting, but I don't forsee them ever making it into Scope.
