### ISSUE TITLE
topology layout consumes too much horizontal space

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1688]
I've looked at various systems with scope in the past few days and in many of them not all the nodes fit on the screen at a readable zoom level, due to too much horizontal space being consumed. https://cloud.weave.works/demo is one example.

To my eyes, there is too much horizontal space being wasted - there is too much space between nodes, more than in the vertical dimension. I reckon it could be reduced by ~30% to about the same as the vertical spacing.

**Comment by rade** [comment]
@davkal @foot where in the code is horizontal node spacing determined?

**Comment by davkal** [comment]
Context: node spacing was increased to accommodate search results, changes to that factor should modify the search results widths too.

Node spacing: https://github.com/weaveworks/scope/blob/master/client/app/scripts/charts/nodes-layout.js#L15
(it's a factor that is multiplied by shape size, 3 means 3 * shape size)

Results width:
https://github.com/weaveworks/scope/blob/master/client/app/scripts/charts/node.js#L88

**Comment by rade** [comment]
> Context: node spacing was increased to accommodate search results

right, I remembered that but thought it was just the vertical spacing that had been increased.

**Comment by rade** [comment]
What extra items do pop up in search results? I've noticed that 'Command' does, but not env var entries (they do get searched, but the node just pulsates & highlights on match, rather than showing the matching item).

**Comment by rade** [comment]
I've played with setting this from 3 to 2, and the labelWidth scaleFactor multiplier from 4 to 3 (btw, would be nice if that wasn't necessary, i.e. the labelWidth should be a function of the node separation factor). Here is the result:

![screenshot_2016-07-17_16-20-31](https://cloud.githubusercontent.com/assets/109109/16901408/c1e7dba2-4c3a-11e6-8d2f-1b692e9c3df6.png)

Which looks ok to me.

**Comment by rade** [comment]
Incidentally, I didn't realise that the horizontal node spacing is variable. Notice how the left column is a bit further apart, presumably because one of the nodes has a "duck bill". Is this deliberate?
