### ISSUE TITLE
unmangaged/uncontained clutter view by default

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1689]
By default we show uncontained/unmanaged containers in the topology. In many cases this clutters the view and makes for a bad first impression. See [our public demo](https://cloud.weave.works/demo/) for an example.

Hence I reckon we should hide unmanaged/uncontained by default.

**Comment by rade** [comment]
@davkal @foot any clues where in the code the default is determined? I can't even work out whether it's f/e or b/e.

**Comment by foot** [comment]
In the BE!

https://github.com/weaveworks/scope/blob/c80eb42/app/api_topologies.go#L56

**Comment by rade** [comment]
@foot see PR #1694 :)
