### ISSUE TITLE
Host shells should be login shell

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1698]
I wanted to use `ip` command in ECS, and discovered that it (`/sbin/ip`) is not in the path.

After some investigation I recalled that on RedHat derivative  only root login shells get `/sbin` and `/usr/sbin` prepended to the path.

Here is the proof:

```
[root@ip-172-31-1-156 /]# echo $PATH                                            
/usr/local/bin:/bin:/usr/bin                                                    
[root@ip-172-31-1-156 /]# bash -c 'echo $PATH'                                  
/usr/local/bin:/bin:/usr/bin                                                    
[root@ip-172-31-1-156 /]# bash -l -c 'echo $PATH'                               
/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/bin:/usr/bin:/bin               
[root@ip-172-31-1-156 /]# bash -l -c 'echo $PATH; which ip'                     
/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/bin:/usr/bin:/bin               
/sbin/ip                                                                        
[root@ip-172-31-1-156 /]#  
```

**Comment by thatsk** [comment]
You have to compromise in Your dockerfile not in weave terminal code.
its not correct

**Comment by bboreham** [comment]
I'm unclear what this has to do with RedHat derivatives or ECS.  Wouldn't the path be under control of the Docker container you are exec-ing into?

**Comment by thatsk** [comment]
Define the path or env in dockerfile or create profile and add into
dockerfile build new image
