### ISSUE TITLE
installation docs are missing instructions for plain, local cluster

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1704]
https://www.weave.works/docs/scope/latest/installing/#docker only mentions running a single instance, and the sub-sections all have extra requirements, like Weave Net or Weave Cloud. Well, on the surface they do. If you read carefully, the instructions are actually buried in the Weave Net section: "If you don’t want to use weaveDNS, then Scope can be instructed to cluster with other Scope instances on the command line. Hostnames and IP addresses are acceptable, both with and without ports".

**Comment by rade** [comment]
And the instructions need to be better too.

See [weave-users slack](https://weaveworks.slack.com/archives/weave-users/p1469025448000045) for an example of a user tripping over all this.

**Comment by faddat** [comment]
Are these docs in the repository?  I've set up plain local clusters a gazillion times and I'd be happy to document the process.

**Comment by rade** [comment]
> Are these docs in the repository?

[Yes](https://github.com/weaveworks/scope/blob/master/site/installing.md).

> I'd be happy to document the process.

Go for it.

**Comment by rade** [comment]
This is actually reasonably covered by https://www.weave.works/docs/scope/latest/installing/#cluster-no-net now. -> closing.
