### ISSUE TITLE
Add a note to docs about logging out

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#1706]
Need to add a small note somewhere about what happens when you log out of Weave Cloud, and ways to log back in.

**Comment by rade** [comment]
I think the bit that isn't obvious for the email-based authentication is

a) clicking on the link in the email stores credentials in the browser, so from then on that browser will be authenticated unless the cookies are cleared.

b) it follows that to access scope from another device/browser, you need to ask scope to send you another email with a link, so you can repeat the process there. This has no effect on the already authenticated browsers - they continue to have access to scope.

c) logging out removes the credentials from the browser. Again, this has no effect on the other browsers with which the user may have authenticated.

**Comment by abuehrle** [comment]
All those things, yes, and that every time you log out of Weave Cloud, and you log back in with your email address, you must wait for a new link in an email <-- this instead of the user setting up a password.

**Comment by rade** [comment]
The logout button has moved to the account page. We have some space there or in a tooltip to explain what this does.

**Comment by rade** [comment]
This is a service issue, not a scope issue.
