### ISSUE TITLE
details panel truncates port to four digits

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1711]
ports can be five digits, so truncating at four is just mean

![screenshot_2016-07-21_19-47-26](https://cloud.githubusercontent.com/assets/109109/17034763/fed64816-4f7b-11e6-953f-3d8d7b3fc1d3.png)

**Comment by foot** [comment]
Cannot repro on osx+chrome/firefox with varying browser zooms.

Which is a bummer, guess linux+firefox renders slightly differently, unless I'm not thinking of other variables here, @davkal any idea?

**Comment by rade** [comment]
Hmm. I cannot reproduce this now in *either* FF or Chrome.

However, I do see another annoying truncation in the details panel: on IP addresses. In both FF and Chrome:

![screenshot_2016-08-03_18-20-58](https://cloud.githubusercontent.com/assets/109109/17375024/326222e2-59a7-11e6-8784-8f9a479777e2.png)

**Comment by foot** [comment]
Ack, will buffer the columns a little more for these cases.
