### ISSUE TITLE
Deleting a cluster causes processes to still hang around 

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#1712]
Not sure exactly what's going on here, but I had two separate clusters running with three multitask demos running in each.  I deleted one of the clusters, but yet its containers are still visible and somehow running, according to Scope Cloud. 

If you need more info, I will leave my instance up in weave cloud.  (All of the stray tasks show that they are in the Singapore region.) 

Here's a screen capture of the AWS console: 

![baseline-cluster-with-four-running-tasks](https://cloud.githubusercontent.com/assets/13420383/17035008/d64b7190-4f4a-11e6-9a2a-1a785527dd6e.png)

**Comment by rade** [comment]
How long did you wait?

Please a) capture a screen shot showing the erroneously displayed containers, and b) send us the json report ("</>" button in bottom right corner).

**Comment by rade** [comment]
@abuehrle gave me access to the instance. All the containers shown by scope are real - you can get logs, shells and metrics for them; so they are very much alive. The erroneous/confusing info appears to be what is shown in ECS.
