### ISSUE TITLE
show me the connections!

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1713]
Scope collects heaps of information about connections, and uses it to lay out the topology graphs, yet it is remarkably difficult to actually get hold of even the most basic details of these connections. For example, I frequently find myself wondering "Why is my container X talking to the Internet? It shouldn't! *What* is it talking to?"

- clicking on the edge between my container and the "Internet (outbound)" node does precisely nothing. That would be the most obvious place to show connection information. See #1636 
- clicking on the node for my container brings up the details panel, with lovely lists of inbound and outbound connections... but this just gives me node names, ports and connection counts, *not IP addresses* or DNS names. So in case of outbound connections to the Internet, I am just being told that there 37 connections to the Internet on port 443. Marvellous.
- clicking on the "Internet (outbound)" node *does* show me IP addresses / DNS names for all the outbound connection destinations; but this is for *all* containers, so to find the connections for my container I have to search for my container name in a long list that isn't searchable and has the name truncated.

**Comment by mjlodge** [comment]
MTU for an interface would also be good to know when troubleshooting...

**Comment by hamid-elaosta** [comment]
Agreed, I'm looking at scope right now for a set of microservices one of which should absolutely not be connecting to the internet, It's possible it's _not_ since it's communicating with a service outside of a container, but I can't confirm this from the information available.
