### ISSUE TITLE
Search icon is above text

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1715]
<img width="147" alt="screen shot 2016-07-22 at 14 22 59" src="https://cloud.githubusercontent.com/assets/250199/17058339/c9f4a826-5017-11e6-8ad5-68156bdc7a28.png">

This is on OSX, Chrome: Version 52.0.2743.82 (64-bit)

**Comment by errordeveloper** [comment]
@paulbellamy do you mind closing this, as #1716 states the same problem plus a bit more?

**Comment by rade** [comment]
#1716 reports *two* problems. I would rather keep this issue focused and let #1716 deal with the remaining problem only.

**Comment by tomwilkie** [comment]
@juliusv just reported this to me on slack.

**Comment by davkal** [comment]
This happens in Chrome >48.
