### ISSUE TITLE
top controls overlap with topology on initial layout

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1716]
Here is what it looks like in Safari

![Safari](https://www.dropbox.com/s/50gqlwl5tjgl8fg/Screenshot%202016-07-22%2014.21.33.png?dl=1)

And in latest Chrome it's like this
![Chrome 52](https://www.dropbox.com/s/fv58ttz2phfo8e8/Screenshot%202016-07-22%2014.21.06.png?dl=1)

Also, "By Image" overlaps with "The Internet" node...

**Comment by errordeveloper** [comment]
In both test I've simply loaded https://cloud.weave.works/demo.

**Comment by rade** [comment]
The first issue is a dup of #1715.

**Comment by rade** [comment]
I cannot reproduce this. @errordeveloper can you?

**Comment by errordeveloper** [comment]
This is probably out of date, let's close.
