### ISSUE TITLE
Allow filtering "uncontained"

### ISSUE THREAD

**Issue by hamid-elaosta** [weaveworks/scope#1717]
I'm currently working on a piece of code which requires a bunch of microservices. During testing, I run this particular code outside of a container, I can see in scope that the other services are communicating nicely but my "uncontained" service is lumped in with all the other things my machine is doing.

It'd be nice to have the ability to cull everything I don't need from uncontained and focus specifically on the service I'm working on there, with the ability, perhaps to name it to something more pertinent.

It's prettier for me, but it also makes showing the output to a non-techie more clear too.

Also, I'm unable to confirm but because my code connects to the other services using my local IP, in the graph is is displayed as connecting *through* "The internet".

**Comment by rade** [comment]
could you perhaps name your uncontained services in DNS?

**Comment by hamid-elaosta** [comment]
I'm not sure what you're suggesting. If I'm running a service that is bound to say https://127.0.0.1:8000 And let's say it's a process on this machine, I'd like to group it visually separate from the unconstained processes such as apt which is accessing the internet and other things on this machine.

I'm not sure of the inner workings of scope but how does DNS solve this?

**Comment by rade** [comment]
The idea with DNS would be that if scope finds an IP in DNS it could represent it as a different node.

Looks like in your case the IP is localhost though; These should always show up as 'Uncontained' nodes, and not be lumped in with the Internet node. Is that not happening for you?

Would #552 do what you want?

**Comment by hamid-elaosta** [comment]
On your second point, It is behaving as designed, apologies if my description was unclear.

Yes, I believe #552 would solve my issue. Thanks.

**Comment by rade** [comment]
So I think a combination of #552, #1082 and #1121 (the latter is done already) would take care of this issue. -> closing as a dup.
