### ISSUE TITLE
automatically switch to table on high node/connection count

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1721]
Until we have a dedicated high-node-count mode (#1614), the table mode is a pretty good substitute...

scope with a thousand connected processes created with

```
nc -lk 1122 &
for i in $(seq 1 1000) ; do nc localhost 1122 & done
```

topology visualisation - this takes a while to render and is rather unusable:
![screenshot_2016-07-26_08-20-25](https://cloud.githubusercontent.com/assets/109109/17129307/2a75ac0a-530a-11e6-899a-854f3dd3cb27.png)
topology table (from #1673) - this renders quite quickly and is perfectly usable:
![screenshot_2016-07-26_08-21-04](https://cloud.githubusercontent.com/assets/109109/17129335/5464564c-530a-11e6-94db-58a07e774dc6.png)

I therefore propose that we automatically switch to the table for high node/connection count. As noted in  https://github.com/weaveworks/scope/issues/1614#issuecomment-230343329, this should be done on a hysteresis.

**Comment by rade** [comment]
So I think the behaviour we are looking for here is:

Whenever a UI action takes you to a visualisation that exceeds the complexity threshold, we switch to table mode instead. Except when that UI action was "switch to visualisation mode" - this is mainly because our heuristics for what is "too complex" aren't perfect; we don't want to prevent users from seeing the visualisation when it does in fact work.

I don't think we need to automatically switch from the visualisation mode to table mode when complexity increases due to extra nodes and edges being added. Hence we don't need a hysteresis either.

So the automatic switch to table mode is *always* triggered by a UI action. Such as selecting a different view or changing filters.

That leaves the question what the threshold should be. Something like node_count + 2*edge_count < 500? Or should there be some ^2 in there somewhere? We probably don't want to get too clever here, at least to begin with.

**Comment by jpellizzari** [comment]
@davkal and @rade, I would like to give this issue a try. The way I am understanding this, we would switch the to the table view if the graph view exceeds a complexity threshold when the user does an action.
 
My first inclination is to figure out which of the [action-types](https://github.com/weaveworks/scope/blob/master/client/app/scripts/constants/action-types.js) would need this behavior, then apply the "threshold" logic to each (using some sort of white-list so its easy enable/disable this behavior for individual actions).

@davkal can you think of a more clever way of doing this than listing the individual actions manually? Should I look to do something further downstream in a component instead?

**Comment by jpellizzari** [comment]
@davkal talked about this issue and decided it would be good to implement this behavior on page load. That way, the user can still switch to graph mode if they want.
