### ISSUE TITLE
weaveDNS warnings in deployments without Weave Net still too alarming

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1726]
It causes questions from users, see https://weaveworks.slack.com/archives/weave-users/p1469675356000173

We had an issue covering this ( #1008 ) but the solution (downgrading the errors to warnings) doesn't make the user think that the messages are harmless.

**Comment by rade** [comment]
suggestion: make the message less alarm, and include something like "if you are not running Weave Net, you may wish to suppress this warning by launching scope with the 'blah' option."

**Comment by Bregor** [comment]
I run WeaveNet as deployment in Kubernetes, but still got those errors:
    <app> WARN: 2016/10/01 18:05:41.845701 Error updating weaveDNS, backing off 20s: exit status 1
    <app> WARN: 2016/10/01 18:06:01.868001 Error updating weaveDNS, backing off 40s: exit status 1
    <app> WARN: 2016/10/01 18:06:41.888623 Error updating weaveDNS, backing off 1m0s: exit status 1

weavescope-app running with:

          - '--no-probe'
          - '--probe.weave.addr ""'

WeaveNet running without DNS (is it necessary when it is kube-dns in cluster?..)

**Comment by Bregor** [comment]
And weavescope-app has no endpoint...
Manifest:

    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: weavescope-app
      namespace: kube-system
      generation: 1
      labels:
        app: weavescope
        weavescope-component: weavescope-app
        kubernetes.io/cluster-service: "true"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: weavescope
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 1
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: weavescope
        spec:
          containers:
          - name: weavescope
            image: weaveworks/scope:0.17.1
            imagePullPolicy: IfNotPresent
            args:
              - '--no-probe'
              - '--probe.weave.addr ""'
            ports:
            - containerPort: 4040

Pods:

    $ kubectl get po --namespace=kube-system -o wide
    NAME                                    READY     STATUS    RESTARTS   AGE       IP              NODE
    ...
    weavescope-app-1507971020-c50xm         1/1       Running   0          16m       192.168.128.2   10.83.8.200
    ...

Endpoints:

    $ kubectl get ep --namespace=kube-system
    NAME                      ENDPOINTS                                                        AGE
    ...
    weavescope-app            <none>                                                           15m
