### ISSUE TITLE
Table-mode: Move selector position

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#1743]
Probably up to the top w/ search and topologies.

**Comment by rade** [comment]
I reckon we should do this soon, before users get used to the current position.

Of the [options discussed](https://github.com/weaveworks/scope/pull/1673#issuecomment-236619316) my order of preference is exactly as shown there. IMO the last one makes search too dominant *and* loses precious vertical space. The 2nd one consumes precious horizontal space - it will be impossible to expand-on-click the search box (as we currently do) in all but very wide browser windows.
