### ISSUE TITLE
Table-mode: 'container' table does not filter by image name

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1749]
It should be clear how user can filter things out in table view, e.g. by image name.

**Comment by rade** [comment]
I reckon this is a bug. The 'containers-by-image' column in the 'containers' table mode appears not be searched.

**Comment by rade** [comment]
There are a few other cases where search does not appear to search a column:
- containers-by-image view: hosts(*)
- process view: containers-by-image
- pods view: hosts(*)

(*) curiously 'hosts' does get searched in other views

**Comment by errordeveloper** [comment]
Sounds like a serious bug... Although I was more thinking of "what should I type into the search box to omit certain images?", and it would be good to have some suggestions around that.

**Comment by rade** [comment]
Ah, you were after a negation? Is that even possible? If not, please file a feature request.

**Comment by errordeveloper** [comment]
> Ah, you were after a negation?

Yes, that's what I'm after. Will take a look when I get a chance.
