### ISSUE TITLE
Table-mode: do we need the k8s id columns?

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1759]
All the k8s views have an ID column. But AFAICT it's just namespace/name, i.e. the composition of two fields we already show. So can we ditch this?

Somebody with knowledge of k8s and what these fields actually mean needs to chime in here please.

**Comment by 2opremio** [comment]
> Somebody with knowledge of k8s and what these fields actually mean needs to chime in here please.

I've had a quick look and I think it's redundant and not useful externally (AFAIK the namespace and name are never appended explicitly like that in k8s)

**Comment by foot** [comment]
@2opremio Do you think this field is redundant enough that we could remove it from the details panel too?

**Comment by rade** [comment]
yes. I gather #1774 will do that.
