### ISSUE TITLE
Do not log service tokens

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1779]
We log all of Scope's comnand line arguments ... including the service token and users share logs to diagnose problems, which is a horrible combination (security wise).

**Comment by rade** [comment]
NB: this issue was prompted by a user posting their weavescope logs on a public slack channel.

**Comment by rade** [comment]
Weave Net logs command line args too but [filters out sensitive info](https://github.com/weaveworks/weave/blob/master/prog/weaver/main.go#L347).
