### ISSUE TITLE
pause logs

### ISSUE THREAD

**Issue by jml** [weaveworks/scope#1786]
I tried to use scope to view the logs for a container in a pod by attaching to the container. The logs just kept streaming, and there was no way for me to pause them, filter them, or search them. I ended up switching back to `kubectl`, because I can do all of these things in my terminal.

**Comment by foot** [comment]
https://github.com/sourcelair/xterm.js/issues/216 to allow you to scroll back up

**Comment by rade** [comment]
You can already scroll back. But the terminal always jumps back to the newest output.

This is actually a dup of #1481.
