### ISSUE TITLE
collector shouldn't decode & re-encode reports

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1789]
Currently all received reports are decoded. That is fine for the standalone app, but totally unnecessary for the collector, which stuffs reports into memcache and S3, re-encoding them in the process.

We know encoding/decoding is expensive, so this is a significant waste of resources. It also increases latency of reports from probes reaching the app.

There is one gotcha: the collector needs to know whether the report is a shortcut report. We could fix that by sending short-cut reports to a different URL. To maintain backward compatibility with old probes, we'd probably have to add a second new URL, for non-shortcut reports, so we can continue to process reports the old way on the current URL.

**Comment by jml** [comment]
Another gotcha: the Decode / Encode step acts as validation, reducing the amount of garbage we put in our stores. Maybe it's OK to drop that, maybe not.

**Comment by tomwilkie** [comment]
Maybe we shouldn't resersialise them?  That will save some CPU.

**Comment by rade** [comment]
> Maybe we shouldn't resersialise them?

i.e. we always decode, but then pass on the original?

> That will save some CPU.

Yes, though the bulk is used by the decoding. Still, it's a good intermediate steps, especially since it will also work for existing probes.

**Comment by 2opremio** [comment]
Fixed via #1819

**Comment by rade** [comment]
No this hasn't been fixed. We are still *de-coding* the report. Which is unnecessary.

**Comment by 2opremio** [comment]
> Which is unnecessary.

Uhm, that's questionable I see value in decoding to catch problems early. Otherwise probes (or ill-intentioned clients) could happily push invalid reports without any feedback.

**Comment by rade** [comment]
That is discussed above. The cost of fully decoding a report is *massive*. And it's a cost we pay even when nobody is ever even looking at the data. So, on balance I reckon it is better to save that cost than validate. And it certainly would be far simpler to implement that than the next best thing, which is...

(as suggested by @tomwilkie) a streaming/low-memory validator, perhaps just a json parser.

**Comment by rade** [comment]
> a streaming/low-memory validator, perhaps just a json parser

https://golang.org/pkg/encoding/json/#Decoder.Token might do the trick.

**Comment by tomwilkie** [comment]
Reports aren't JSON.

On Thu, Sep 8, 2016 at 5:46 PM, Matthias Radestock <notifications@github.com

**Comment by 2opremio** [comment]
> https://golang.org/pkg/encoding/json/#Decoder.Token might do the trick.

Probes encode reports in msgpack (although json is also supported for debugging: `api/report`+fixprobe).

**Comment by rade** [comment]
d'oh. good luck finding a streaming/low-memory msgpack validator.

**Comment by rade** [comment]
Now that we are extracting things like number of hosts and containers - for billing purposes - in the collector, we have no choice but to decode the reports. -> closing.
