### ISSUE TITLE
numeric values in details panel tables should be right aligned

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#1794]
![screen shot 2016-08-15 at 19 05 53](https://cloud.githubusercontent.com/assets/22008/17672175/519f3f82-631b-11e6-9979-0a2d47ec5a8d.png)

**Comment by rade** [comment]
memory too, no?

**Comment by rade** [comment]
AFAICT there is code to right-align columns that are marked as numeric. But for some reason that doesn't seem to take effect.

**Comment by rade** [comment]
This patch corrects the alignment for port and count:
```patch
diff --git a/render/detailed/connections.go b/render/detailed/connections.go
index fd75284..2f86b8e 100644
--- a/render/detailed/connections.go
+++ b/render/detailed/connections.go
@@ -21,13 +21,13 @@ const (
 // Exported for testing
 var (
        NormalColumns = []Column{
-               {ID: portKey, Label: portLabel},
-               {ID: countKey, Label: countLabel, DefaultSort: true},
+               {ID: portKey, Label: portLabel, DataType: "number"},
+               {ID: countKey, Label: countLabel, DataType: "number", DefaultSort: true},
        }
        InternetColumns = []Column{
                {ID: "foo", Label: "Remote"},
-               {ID: portKey, Label: portLabel},
-               {ID: countKey, Label: countLabel, DefaultSort: true},
+               {ID: portKey, Label: portLabel, DataType: "number"},
+               {ID: countKey, Label: countLabel, DataType: "number", DefaultSort: true},
        }
 )
 
diff --git a/render/detailed/summary.go b/render/detailed/summary.go
index ae95a39..344480a 100644
--- a/render/detailed/summary.go
+++ b/render/detailed/summary.go
@@ -37,6 +37,7 @@ type NodeSummaryGroup struct {
 type Column struct {
        ID          string `json:"id"`
        Label       string `json:"label"`
+       DataType    string `json:"dataType"`
        DefaultSort bool   `json:"defaultSort"`
 }
 ```

That is because, AFAICT, the f/e detail panel table renderer is expecting the data type to be set on the columns, not the individual cells (aka `MetaDataRow`). @paulbellamy @foot any clues as to whether the b/e is wrong here (and hence a patch along the above lines is correct), or the f/e?

**Comment by foot** [comment]
I like this patch! FE might be wrong, its not superDRY having dataType in both value and column right now but makes life easy.

At the mo:
 - column.dataType:
  - determining default sort direction (desc for number, asc for strings)
  - text-alignment
 - value.dataType:
  - determine whether we should try and parse it into a number to do numeric sorting. (could ofc be read from column header)

Unless we wanna move towards have different dataTypes in the same column I like having it in the col header.

**Comment by rade** [comment]
> value.dataType ... could ofc be read from column header

I went through the code with @paulbellamy the other day and it looks like for table mode, which uses the same `MetadataRow` type, we need the data type on the value, since there are no pre-determined columns as such. Correct?

>  its not superDRY having dataType in both value and column

Exactly. I guess I could just leave `MetadataRow.Datatype` blank. It does have an 'omitempty' annotation, so shouldn't appear in the json in that case.
 
The cleaner option would be to create a separate type for detail panel table rows.

Incidentally, how does table mode determine sort-direction?

**Comment by foot** [comment]
> we need the data type on the value, since there are no pre-determined columns as such. Correct?

Yep! It would be nice to keep `node.metadata.dataType` as `node.metadata` doesn't specify columns and as you say we use that info when generating the column list for the gridMode.

For other sections like `connections` and `children` that do specify `columns` we could strip `dataType` from the values. Ah but they use a common type? I see..

> The cleaner option would be to create a separate type for detail panel table rows.

Yep, or add columns section to `node.metadata` if you wanna go the other way and keep data structure more uniform.

> Incidentally, how does table mode determine sort-direction?

- `if (dataType === 'number')`: sort it descending (user wants to focus on larger numbers more often than not).
- `else`: (prob. string), then sort ascending as you're probably reading labels alphabetically.

**Comment by rade** [comment]
my question re sort order concerned how table mode determines sort order for a *column* given that the data type is associated with a *cell*.

**Comment by foot** [comment]
Ah hah. We scan all node.metadata and create a unique set of {id, label, dataType} column tuples. 

If 2 nodes have diff dataTypes for the metadata we get two columns. (I haven't seen this happen in the wild, though it could potentially happen w/ diff probe versions reporting, e.g. with our recent pid.dataType = "number" transition.)

**Comment by foot** [comment]
Applied @rade's patch + made more columns numbers too (k8s stuff mainly).
