### ISSUE TITLE
Show which image a container is running

### ISSUE THREAD

**Issue by jml** [weaveworks/scope#1800]
In order of importance:
- image name
- image label
- link to where image is from (e.g. dockerhub, quay.io URL)

Secondarily:
- size
- age
- other stuff

Ideally also directly on pod, replication controller, and deployment views too, since it should be the same on all of them.

Kubernetes views should highlight if pods in the same rc, deployment, etc. differ (they really never should, but if they _do_, then that's very interesting).

**Comment by rade** [comment]
See also #925.

We *do* show the image name in the details panel. But not the version/label.

**Comment by 2opremio** [comment]
> Ideally also directly on pod, replication controller, and deployment views too, since it should be the same on all of them.

This requires showing multiple images in the details panel (i.e. #925) since pods can have multiple images (in fact they always do due to the pause container).

**Comment by 2opremio** [comment]
@jml To be completely clear, do you expect the image details to be shown in the container details panel **directly** or in the details panel of the associated image topology node?

**Comment by jml** [comment]
In the container details panel. Most of the stuff that's on there isn't interesting to me. 

Note that at the time I filed this bug I wasn't even aware there was an image panel:

<img width="405" alt="screen shot 2016-10-04 at 17 08 08" src="https://cloud.githubusercontent.com/assets/125674/19082238/34c76f18-8a55-11e6-8772-6d80d0b465a2.png">

How is someone unfamiliar with Scope supposed to figure out what image is running, or how to get said information? 

This one is from browsing containers by image:

<img width="392" alt="screen shot 2016-10-04 at 17 12 09" src="https://cloud.githubusercontent.com/assets/125674/19082402/e79e9332-8a55-11e6-9d7e-1c9615b97739.png">

How do I know where that image came from or how I would run that same image locally? What version is it running? Are they all running the same version?

I guess I'm saying that I'm not recommending a particular solution, just pointing out that:
- image is very, very important to what a container is, and there should be more information about it when viewing a container
- I don't really know what the container details panel is for otherwise

Hope this helps.

**Comment by 2opremio** [comment]
@jml, thanks that helps. I will show an image table directly in the container details, which is what the user expects.

I am thinking that the image topology won't be very useful if we include all the image information directly in the container node. That said, it doesn't need to be useful, maybe we could even remove it in the future. 

To make the implementation efficient and avoid making reports event larger I think I will include the table in the image topology and inject it in the container nodes when rendering.
