### ISSUE TITLE
#1682 broke controls for old probes connecting to Weave Cloud

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1806]
Controls have disappeared in Weave Cloud.

The following *do* show controls
- pointing a current-master (revision 21cfc83) scope probe at one of my instances in Dev or Prod
- running current-master, v0.17, v0.16.2 locally
- pointing a revision 6e2fe78 - the merge of #1682 - probe at one of my instances in Dev
- pointing a v0.17 probe at a local current-master app

The following *do not* show controls
- admin scope in Dev and Prod (NB: this is curious since I am quite sure I did see controls in these just after we first noticed the problem today)
- pointing a revision 0525a2a probe - the same version as the dev/prod probes - at one of my instances in Dev
- doing the same with v0.17, v0.16.2
- doing the same with a self-built v0.17.0 branch
- pointing a revision 33d5d37 - just before the merge of #1682 - probe at one of my instances in Dev.

Conclusion: #1682 broke compatibility with old probes in multi-tenant scope.

**Comment by rade** [comment]
I reckon the problem is that https://github.com/weaveworks/scope/pull/1682/files#diff-96a3c91da3b2f0220e24b6fb4a3b44beL121 does not appear in the `aws_collector`.

**Comment by 2opremio** [comment]
CC @krnowak
