### ISSUE TITLE
make 'pods' the initial view, when available

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1809]
@jml pointed out that when running k8s, the container view is rarely what one wants to look at. So perhaps we should make the 'pods' view the default initial view, if available.

**Comment by jml** [comment]
TBH, I'd start at "Services", which is the highest level view.

**Comment by foot** [comment]
Implemented on client w/ 'services' as default if available.

**Comment by rade** [comment]
> Implemented

where? PR?

**Comment by foot** [comment]
To quick for me
