### ISSUE TITLE
pod counts and details panel lists do not respect namespace

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1824]
In Weave Cloud (Dev) we have a memcached service in the default namespace and one in the frankenstein namespace. But when the view has either namespace selected, the "# pods" shown for the service is the aggregate of the two, and when bringing up the details panel, the pods for both services are listed. When selecting 'All Namespaces', two memcached nodes are shown, both containing the aggregrate set of pods.

**Comment by rade** [comment]
Looks like a pod's parents are set without regard to the namespace. So, for example, each of the memcached pods in our Weave Cloud Dev cluster has two replica-sets and two deployments as a parent - one in the default namespace and one in the frankenstein namespace.

I suspect the problem is in [kubernetes.Reporter.podTopology](https://github.com/weaveworks/scope/blob/v0.17.1/probe/kubernetes/reporter.go#L349).

@2opremio @paulbellamy am I on the right track? Any clues you can offer?

**Comment by 2opremio** [comment]
Yep, you seem to be the right track, I will have a look at the code later (
probably we are not using the ids correctly or the ids don't contain the
namespace)
