### ISSUE TITLE
IOwait plugin causes `undefined` status in the UI

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1825]
Seen in Scope 0.17.1

<img width="1280" alt="screen shot 2016-08-23 at 5 59 37 pm" src="https://cloud.githubusercontent.com/assets/2362916/17901479/79691d30-695b-11e6-9e31-257fc88f61af.png">

**Comment by rade** [comment]
The plugin was compiled from master. According to the user, compiling it from the v0.17.1 tag did produce a working plugin.

**Comment by 2opremio** [comment]
> The plugin was compiled from master. According to the user, compiling it from the v0.17.1 tag did produce a working plugin.

However, note that even compiling for 0.17.1 causes the _undefined_ status in the UI.

**Comment by 2opremio** [comment]
I think this is a problem with the UI (or with an unpredicted format change in the format of the `/api` endpoint).

Here's what I get from `/api`, which seems to be correct:

```
{"hostname":"vagrant-ubuntu-wily-64","id":"6f8778167e6c5ddc","plugins":[{"api_version":"1","description":"Adds a graph of CPU IO Wait to hosts","id":"iowait","interfaces":["reporter"],"label":"iowait","status":"ok"}],"version":"cffcddf"}
```
