### ISSUE TITLE
conntrack not used even though it's working

### ISSUE THREAD

**Issue by nicolnx** [weaveworks/scope#1826]
Hello

I am trying a simple install with following docker-compose.yml:

version: '2'

services:
 container1:
   image: nginx:latest

 container2:
   image: nginx:latest

 weavescope:
   image: weaveworks/scope:0.17.1
   privileged: true
   network_mode: "host"
   pid: "host"
   labels:
     - "works.weave.role=system"
   volumes:
     - "/var/run/docker.sock:/var/run/docker.sock"
   command:
     - "--probe.conntrack=true"
     - "--probe.docker=true"

For test, I am using nc -l -p 1300 / nc containerIP 1300
The connection is established since I can see an echo without problems

However, instead of connection between containers, I see http://puu.sh/qLCEQ/b8115764b9.jpg

As we can see from http://puu.sh/qLDcQ/489f20f96b.jpg - Scope can see them, but possibly can no determine that they are between 2 containers, not host local

https://github.com/weaveworks/scope/files/433143/report.gz

Thanks
Nikolay

**Comment by 2opremio** [comment]
This is on Windows for Mac.

**Comment by nicolnx** [comment]
Yes

$ docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 32
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.95 GiB
Name: moby
ID: 3NTQ:IQ6E:C4RT:4GFR:H4US:QD6M:7VDI:C2YC:ENFE:CAXP:3MUQ:4OUK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by nicolnx** [comment]
report attached:

[report.gz](https://github.com/weaveworks/scope/files/433143/report.gz)

**Comment by 2opremio** [comment]
Interestingly, the connection shows in the process view:

<img width="1612" alt="screen shot 2016-08-23 at 6 48 20 pm" src="https://cloud.githubusercontent.com/assets/2362916/17903127/3cf4c0d2-6962-11e6-94b0-8ed3037a2719.png">

**Comment by nicolnx** [comment]
Yes, but instead of name of container this processes are running on - there's 'moby' which is docker host hyper-v instance

**Comment by 2opremio** [comment]
I think I know what's happening.

The netcat processes are not being correctly attributed to the containers. Note how they are missing in the details panel (only the nginx processes are present).

<img width="1616" alt="screen shot 2016-08-23 at 7 03 31 pm" src="https://cloud.githubusercontent.com/assets/2362916/17903713/633d8d76-6964-11e6-9557-a74062f9b96f.png">

Specifically, this is because the [docker tagger](https://github.com/weaveworks/scope/blob/v0.17.1/probe/docker/tagger.go#L85-L89) is not providing a `docker_container_id` in the LatestMap of the process nodes:

<img width="221" alt="screen shot 2016-08-23 at 7 07 26 pm" src="https://cloud.githubusercontent.com/assets/2362916/17903953/41a6db12-6965-11e6-9b99-122f17c791bb.png">

**Comment by 2opremio** [comment]
This is process tree:

```
/home/weave # pstree -p
init(1)-+-acpid(1252)
        |-containerd(1582)
        |-diagnostics-ser(1613)
        |-dockerd(1442)---docker-containe(1449)-+-docker-containe(5966)---runsvinit(5980)---runsvdir(5993)-+-runsv(599+
        |                                       |                                                          `-runsv(599+
        |                                       |-docker-containe(6008)---nginx(6049)---nginx(6190)
        |                                       |-docker-containe(6014)---nginx(6063)---nginx(6218)
        |                                       |-docker-containe(6460)---sh(6479)---bash(6537)---nc(6711)
        |                                       |-docker-containe(6766)---sh(6783)---bash(6957)---nc(7053)
        |                                       `-docker-containe(8578)---sh(8599)---pstree(9009)
        |-getty(1925)
        |-hv_kvp_daemon(1304)
        |-hv_vss_daemon(1866)
        |-klogd(1082)
        |-proxy-vsockd(1341)
        |-syslogd(1143)
        |-tap-vsockd(1006)
        |-udhcpc(1043)
        `-vsudd(1225)
/home/weave #
```

**Comment by 2opremio** [comment]
In addition, short-lived connections cannot be tracked because conntrack cannot run (`module not present`)

```
$ docker-compose.exe up
Pulling weavescope (weaveworks/scope:windows-pids)...
windows-pids: Pulling from weaveworks/scope
ce2d0f539e6c: Already exists
bef36f076c73: Already exists
d874c8a78194: Pull complete
b8e5c537a426: Pull complete
2d8a41afbd49: Pull complete
6a34931d5b06: Pull complete
8602971b0fb4: Pull complete
1957c41afea3: Pull complete
376ca2b2ffed: Pull complete
Digest: sha256:cb97c2f5e5fec4b48dbdf719275cc910f3c718f57a11f8049db1a79244662e6b
Status: Downloaded newer image for weaveworks/scope:windows-pids
Starting 7_container2_1
Starting 7_container1_1
Recreating 7_weavescope_1
Attaching to 7_weavescope_1, 7_container2_1, 7_container1_1
weavescope_1  | <probe> INFO: 2016/08/23 18:53:17.378276 command line args: --logtostderr=true --mode=probe --probe.conntrack=true --probe.docker=true
weavescope_1  | <probe> INFO: 2016/08/23 18:53:17.378417 probe starting, version 32edfc9, ID 3b80406c2d246dd4
weavescope_1  | <probe> INFO: 2016/08/23 18:53:17.378427 publishing to: localhost:4040
weavescope_1  | <probe> ERRO: 2016/08/23 18:53:17.391571 Error fetching app details: Get http://127.0.0.1:4040/api: dial tcp 127.0.0.1:4040: getsockopt: connection refused
weavescope_1  | <app> INFO: 2016/08/23 18:53:17.395864 app starting, version 32edfc9, ID 67f498c7f15b3b08
weavescope_1  | <probe> ERRO: 2016/08/23 18:53:17.395992 conntrack: failed to find module nf_conntrack
weavescope_1  | <probe> INFO: 2016/08/23 18:53:17.396010 Not using conntrack: module not present
weavescope_1  | <probe> ERRO: 2016/08/23 18:53:17.396026 conntrack: failed to find module nf_conntrack
weavescope_1  | <app> INFO: 2016/08/23 18:53:17.396159 command line args: --logtostderr=true --mode=app --probe.conntrack=true --probe.docker=true
weavescope_1  | <probe> INFO: 2016/08/23 18:53:17.396327 Not using conntrack: module not present
weavescope_1  | <app> INFO: 2016/08/23 18:53:17.425152 listening on :4040
weavescope_1  | <probe> ERRO: 2016/08/23 18:53:17.519356 plugins: problem loading: no such file or directory
weavescope_1  | <probe> WARN: 2016/08/23 18:53:17.543008 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
weavescope_1  | <probe> WARN: 2016/08/23 18:53:17.554674 Cannot resolve scope.weave.local.: dial tcp 172.17.0.1:53: getsockopt: connection refused
weavescope_1  | <probe> INFO: 2016/08/23 18:53:18.395110 Control connection to 127.0.0.1:4040 starting
weavescope_1  | <probe> INFO: 2016/08/23 18:53:20.595485 Publish loop for 127.0.0.1:4040 starting
weavescope_1  | <probe> WARN: 2016/08/23 18:53:27.544603 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
weavescope_1  | <probe> INFO: 2016/08/23 18:53:35.128706 Success collecting weave ps
weavescope_1  | <app> WARN: 2016/08/23 18:53:35.172532 Error updating weaveDNS, backing off 20s: Error running weave expose: exit status 7
weavescope_1  | <probe> WARN: 2016/08/23 18:53:47.547310 Error collecting weave status, backing off 40s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
weavescope_1  | <app> WARN: 2016/08/23 18:53:55.948323 Error updating weaveDNS, backing off 40s: Error running weave expose: exit status 7
```

**Comment by 2opremio** [comment]
So, there are two problems:
1. conntrack doesn’t work due to a missing module (so, short-lived connections won’t show)
2. some processes are not properly tagged with their containers (making persistent connections not to show, like in the netcat example)

**Comment by 2opremio** [comment]
For (2), what happens is that the processes resulting from `docker exec` are not children of the Pid of the parent container (which happens in vanilla Linux not just Docker for Windows), causing scope not to attribute them to the correct container. In fact we were alreadu tracking this in https://github.com/weaveworks/scope/issues/668

In other words, I believe that if the container itself (without `docker exec`) was creating a persistent connection it would work without problems.

**Comment by 2opremio** [comment]
As for (1), the problem is that that `conntrack` can work without the `nf_conntrack` module being present (in fact it could be built in the kernel) but [our code enforces it being present](https://github.com/weaveworks/scope/blob/v0.17.1/probe/endpoint/conntrack.go#L89-L91) even if conntrack could work.

I should look for a more precise way to make conntrack work.

**Comment by rade** [comment]
@2opremio please file a separate issue for the conntrack module stuff.

**Comment by rade** [comment]
oh, I see #688 already tracks the `docker exec` issue.

**Comment by rade** [comment]
> I should look for a more precise way to detect whether conntrack is usable.

Could we just run it, with a backoff on error?

**Comment by 2opremio** [comment]
> Could we just run it, with a backoff on error?

That's another option, yeah.
