### ISSUE TITLE
Metrics on canvas get stuck

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1829]
They don't seem to refresh properly when hovering on them. Clicking on the node to show the details panel seems to _refresh_ them.

![](http://g.recordit.co/GrzQ2HXSng.gif)

I would expect the metrics to refresh while hovering and between hovers.

**Comment by rade** [comment]
hover or not, the metrics are completely stuck for me. unless I reload the page.

**Comment by foot** [comment]
Yeah i think some layout caching stuff must have crept in, they update on a force-layout-refresh

**Comment by davkal** [comment]
I reckon it has to do with redux's `connect` short-circuiting because a metrics-only change is not considered as an update.

**Comment by davkal** [comment]
Ah, just saw in #1831, we're doing the short-circuiting in `nodes-chart:shouldComponentUpdate`.
