### ISSUE TITLE
Upgrade go version in CircleCI

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1834]
Right now it uses go 1.5.3, which doesn't use vendoring by default and causes problems like https://github.com/weaveworks/build-tools/issues/38

```
vagrant@vagrant-ubuntu-wily-64:~/tools$ ssh -p 64625 ubuntu@54.226.44.25
Last login: Fri Aug 26 12:58:01 2016 from 10.186.216.70
ubuntu@box848:~$ go version
go version go1.5.3 linux/amd64
```

**Comment by rade** [comment]
@2opremio we've done this, haven't we?

**Comment by bboreham** [comment]
It's on 1.9.1 per https://circleci.com/docs/1.0/language-go/
Only used for `make deps` - goveralls etc.
Closing.
