### ISSUE TITLE
Image details panel shows truncated image name instead of ID

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1835]
![screenshot_2016-08-27_00-02-27](https://cloud.githubusercontent.com/assets/109109/18022766/91400776-6be9-11e6-9c81-882ce1771fe2.png)

Clearly showing a truncated image name makes no sense.

I suspect this is a remnant from the time before we coalesced images with the same name, and that this was showing the actual image ID then. Given the coalescing, it doesn't actually make sense to show a single ID here. See also #925.

**Comment by foot** [comment]
So, we could remove the `imageId` for now and re-introduce `imageIds` soon?

**Comment by rade** [comment]
yes
