### ISSUE TITLE
details panel connection counts are too high

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1842]
To reproduce
```
$ scope launch
1c41ae18a677d54463e23e3adc5e63516b7409688634db79a9d8df5dcc9d635e
Weave Scope is reachable at the following URL(s):
  [...]
$ google-chrome http://localhost:4040
$ docker run --rm --name=foo -ti alpine /bin/sh
/ # IP=$(getent hosts cloud.weave.works | cut -d ' ' -f 1)
/ # echo $IP
52.3.116.14
/ # nc $IP 80
```
Wait for the 'foo' container and connection to the Internet node to show up in scope and then bring up the details panel on the 'foo' node. You should see something like
![screenshot_2016-09-01_22-43-19](https://cloud.githubusercontent.com/assets/109109/18185509/e6b813a0-7095-11e6-8b50-87d4a66e077b.png)

Notice that it says there are *two* connections from the node to the Internet, when in reality there is only one.

This doesn't happen all the time, unfortunately, though right now for me it happens more often than not. Sometimes I initially see a count of 1 and it then increases to 2. And then sometimes it drops back to 1.

**Comment by rade** [comment]
I ran into this in the process of investigating #1495. The fix for that in #1843 doesn't cure this issue but has the effect that the Internet node details panel too shows a count of 2. At least it's wrong consistently.

**Comment by rade** [comment]
I've added some instrumentation to `detailed.outgoingConnectionsSummary`. This reveals that the 'foo' container node has exactly one adjacent node, "out-theinternet". So far so good. However, it has *two* local endpoints: ";192.168.1.65;39120" and "xps;172.17.0.2;39120". The former is my host's WLAN IP, the latter is the container's docker-assigned IP. And the adjacency of both these endpoints apparently contains the ";52.3.116.14;80" endpoint. Hence it is counted twice.

@paulbellamy I'd appreciate a clue as to whether the data is wrong (e.g. the 'foo' container should only have one local endpoint, or only one of the two endpoint's adjacency should have an intersection with the "out-theinternet" remotes), or the algorithm (i.e. we are missing some additional filtering).

**Comment by paulbellamy** [comment]
I would have expected `probe/endpoint/nat.go` to have handled that, and converted the first endpoint to the second (or the other way, maybe)

**Comment by rade** [comment]
`nat.go` does no such thing, AFAICT; it simply *adds* extra endpoints.

Note that the count is wrong in the process topology too, i.e. in the above example the Internet node in the process topology shows the 'nc' process as having two connections.

**Comment by rade** [comment]
I've looked into this some more. The 2nd endpoint is definitely added by `natMapper.applyNAT`, and since that copies the original endpoint, the edge/adjacency gets copied too.

We could detect such duplicate edges in the renderer, since the 2nd endpoint has a `copy_of` reference to the original endpoint. But to me that seems wrong - there is just one connection here, so surely there should only be one edge. Or am I reading too much into the semantics of edges / adjacency in scope?

@tomwilkie @peterbourgon you wrote/discussed this code, and the decision to copy endpoints was made in https://github.com/weaveworks/scope/issues/245#issuecomment-113821171. Edges aren't mentioned explicitly, though it does talk about copying metadata. So is the edge duplication an intended outcome?

The alternative here would be to "move" the edge from the original to the copied node. But that is a non-monotonic operation, which I am guessing is bad.

**Comment by peterbourgon** [comment]
While I discussed the implementation, the code is all @tomwilkie IIRC.

**Comment by rade** [comment]
> While I discussed the implementation, the code is all @tomwilkie IIRC.

Yep, I am aware of that. However, AFAICT the implementation is very much a reflection of the design, for which there was some back-and-forth between you and tom.

**Comment by peterbourgon** [comment]
From what I can read and remember, the code in question copied endpoints (nodes) but gave them different identifiers. That necessarily means duplicate edges; edges are defined in terms of nodes. So in that sense it was an intended outcome, though likely one that wasn't going to be noticed, because edge coalescing is a thing that happens, both in the merge steps in the backend as well as (IIRC) the UI.

**Comment by rade** [comment]
Here's how to get a triple count:
1. `desktop$ scope launch`
2. `vmhost1$ scope launch --no-app $DESKTOP_IP`
3. `desktop$ docker run -p 1122:1122 --rm -ti alpine nc -l -p 1122`
4. `vmhost1$ docker run --rm -ti alpine nc $DESKTOP_IP:1122`

conntrack shows the following entries:
- desktop: `tcp      6 428551 ESTABLISHED src=192.168.48.11 dst=192.168.48.1 sport=41277 dport=1122 src=172.17.0.2 dst=192.168.48.11 sport=1122 dport=41277 [ASSURED] mark=0 use=1`
- vmhost1: `tcp      6 431669 ESTABLISHED src=172.17.0.5 dst=192.168.48.1 sport=41277 dport=1122 src=192.168.48.1 dst=192.168.48.11 sport=1122 dport=41277 [ASSURED] mark=0 use=1`

where
- 192.168.48.1 is the desktop IP
- 192.168.48.11 is the vmhost1 IP
- 172.17.0.2 is the desktop container IP
- 172.17.0.5 is the vmhost1 container IP (I cheated here and started a bunch of other containers first so the IP would be distinct from the desktop container IP and hence easier to track)

The report contains the following endpoints and associated edges
- desktop;172.17.0.2;1122
- ;192.168.48.1;1122
  - copy_of desktop;172.17.0.2;1122
- vmhost1;172.17.0.5;41277 -> ;192.168.48.1;1122
- ;192.168.48.11;41277   -> [;192.168.48.1;1122, desktop;172.17.0.2;1122]
  - copy_of vmhost1;172.17.0.5;41277

I am guessing the first two endpoints get associated with the desktop container, and the last two with the vmhost1 container.

**Comment by rade** [comment]
@2opremio suggested simply dropping the copy endpoints in `MapEndpoint2Process`, but if we do that in the above then we are left with:
* desktop container having endpoint desktop;172.17.0.2;1122
* vmhost1 container having endpoint vmhost1;172.17.0.5;41277 -> ;192.168.48.1;1122

which leaves the latter's edge going nowhere and hence we see no edge at all in the graph (I've confirmed this by patching the code).

**Comment by rade** [comment]
Converting the endpoint to the original kinda works, i.e. calling
```go
func dedupEndpoint(n report.Node) report.Node {
	if copyNodeID, _, ok := n.Latest.LookupEntry("copy_of"); ok {
		if _, addr, port, ok := report.ParseEndpointNodeID(copyNodeID); ok {
			n = n.WithID(copyNodeID).WithLatests(map[string]string{endpoint.Addr: addr, endpoint.Port: port})
			n.Latest = n.Latest.Delete("copy_of")
		}
	}
	return n
}
```
in `MapEndpoint2Process`.

This effectively gives us the following endpoints in the previous scenario:

- desktop container has endpoint desktop;172.17.0.2;1122
- vmhost1 container has endpoint vmhost1;172.17.0.5;41277 -> [;192.168.48.1;1122, desktop;172.17.0.2;1122]

However, this does result in "flickering" in the details panel, i.e. rows coming and going. In my original observations I said "Sometimes I initially see a count of 1 and it then increases to 2. And then sometimes it drops back to 1.".  This is consistent with sometimes only seeing edges to ;192.168.48.1;1122, and not desktop;172.17.0.2;1122.

Curiously though there is no flickering in the rendered graph, only in the details panel. Which is mysterious.

**Comment by rade** [comment]
> Curiously though there is no flickering in the rendered graph, only in the details panel. Which is mysterious.

The process/container adjacency still has the edges, and that is what the graph renderer cares about. By contrast, the connection counting code needs to look at endpoints, and since we've dedup'ed the endpoints, it can no longer find the other end for some of the edges.

What I don't know is why the process/container adjacency still has the edges. Need to look into the rendering code a bit more.

**Comment by rade** [comment]
> What I don't know is why the process/container adjacency still has the edges. Need to look into the rendering code a bit more.

Figured it out. `render.Render` calculates adjacency by tracking which input nodes (in this case endpoints) got mapped to which output nodes (in this case processes). Endpoint de-duping has no effect on that.

**Comment by rade** [comment]
De-duping endpoints just isn't going to work. Consider a container listening on a published port, e.g. the desktop container in my example above. We can have connections to that container at both the container IP - from other containers on the same host - and external IP - from elsewhere. If we eliminate either endpoint, then one of the connections is left with a dangling destination.

We could de-dup edges, but this requires a walk of the entire topology post the rendering stage. Do-able, but a lot of work and somewhat outside my comfort zone.

So in #1860 I instead decided to de-dup connections in the counting stage, hence addressing the subject of this issue quite directly.
