### ISSUE TITLE
connection count in details panel has visually duplicate rows

### ISSUE THREAD

**Issue by davkal** [weaveworks/scope#1844]
After #1843 is merged:

When you have multiple containers of the same name connect to the Internet, you easily get to this:

```
Inbound Remote Port Count
X    IP1       PortA    2
Y    IP2       PortB   2
Y    IP2       PortB   2
Y    IP2       PortB   2
X    IP3       PortA    2
```

Having multiple rows with all values identical looks confusing. 

UX remedies:

* aggregate counts to one row if all other fields are the same (would lose clickability for drilldown)
* add a column for a field that varies across the rows (IDs are usually wide and pretty useless to see)
* add a hover over the name with a field that distinguishes the rows
* add a column for IDs or a distinguishing field, but keep it really narrow (maybe dont even show the value, only on hover)

**Comment by rade** [comment]
This isn't specific to the Internet node, surely. e.g. two containers with the same name, connected to a third will show up as two identical rows in that container's inbound connection list, no?

**Comment by rade** [comment]
> This isn't specific to the Internet node

indeed it isn't:
![screenshot_2016-09-02_15-28-38](https://cloud.githubusercontent.com/assets/109109/18207194/f55a8fb4-7121-11e6-9a40-83d8bddc9931.png)

The obvious discriminator would be the sub-label, which is how these nodes are distinguishable in the graph view. (except that isn't sufficient there either)

**Comment by rade** [comment]
Of the options listed by @davkal, "add a hover over the name with a field that distinguishes the rows" seems like the least worst and presumably is also the easiest. And I suggest the tooltip is "label (sub-label)".

Not perfect, but a definite improvement.
