### ISSUE TITLE
process topology shown with partial container filters, after restart

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1848]
1. `scope launch`
2. switch to process topology; wait for stuff to show up
3. `scope stop`
4. `scope launch`

The screen shows the "nothing to see here" circle for a bit and then this:

![screenshot_2016-09-02_18-44-36](https://cloud.githubusercontent.com/assets/109109/18212935/c26ef43e-713d-11e6-9a96-7a7b927f1d2e.png)

Notice how the filters in the bottom left are mostly container filters - even though we are in the process view - except for 'Unconnected nodes hidden'. Switching to the container view and back does not fix this. Reload does.

**Comment by rade** [comment]
I do see this on 0.17.1. I am not seeing this anymore on master. @davkal @foot any idea what PR fixed this?

**Comment by davkal** [comment]
My guess is #1823.
