### ISSUE TITLE
Feature request: Allow to see per-pod CPU/memory usage

### ISSUE THREAD

**Issue by jeroenvisser101** [weaveworks/scope#1851]
It would be nice to be able to see—just as with hosts and processes—their CPU and memory usage.

**Comment by rade** [comment]
dup of #1257

**Comment by jeroenvisser101** [comment]
@rade completely, thanks, will track that one.

**Comment by rade** [comment]
actually, it might be more a dup of #1635 since #1257 is specifically about aggregating process metrics, so we get extra metrics not available directly for containers.

**Comment by jeroenvisser101** [comment]
@rade tracking that one as well. For me, having the CPU display on the hexagons would already solve a lot. btw: scope is great, keep up the good work :)

**Comment by rade** [comment]
> having the CPU display on the hexagons would already solve a lot.

That should already be happening provided your pods only contain one container, and you are running on Docker 1.12.
