### ISSUE TITLE
Time format in table and details panel is weird

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#1866]
`02 Aug 16 10:47 UTC` is OK in isolation, but harder to quickly parse in a list. Let's try a readable ISO format.

![screen shot 2016-08-16 at 20 54 13](https://cloud.githubusercontent.com/assets/859729/17713601/a90460da-63f3-11e6-8e58-27403eac7f04.png)

**Comment by jpellizzari** [comment]
Fixed by PR #1927
