### ISSUE TITLE
Internet connection detail remotes not sorted correctly 

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1869]
![screenshot_2016-09-15_19-36-07](https://cloud.githubusercontent.com/assets/109109/18562513/e3c039a2-7b7b-11e6-80a4-02f0e8c21726.png)

This is meant to be in descending order but clearly isn't.

That is because the b/e tells the f/e that this column is numeric. The f/e converts the value to a float, which in case of an IP address catches the first two octets, but in case of a DNS name just returns "NaN".

**Comment by rade** [comment]
for table mode we decided to sort alphabetically to begin with, and filed #1746 to do better. I suggest we do the same here.

**Comment by rade** [comment]
I think this got fixed by #1877. @foot pls confirm

**Comment by foot** [comment]
Correct, #1877 removed dataType: number from remote and thus the attempt at numeric sorting.
