### ISSUE TITLE
URLs should capture open detail windows

### ISSUE THREAD

**Issue by ekimekim** [weaveworks/scope#1870]
This is a really nice feature for showing people what you're talking about.
Currently the urls capture the current topology view (and filters?), but not the current detail windows

**Comment by ekimekim** [comment]
Hmm. it seems this already works...but only sometimes? trying to pin down a repro now.

**Comment by ekimekim** [comment]
Nevermind, it was an issue with the url getting cut off in the process of testing

**Comment by rade** [comment]
The problem was my slack client, which helpfully added some (presumably incorrect) escaping to the URL - clicking on the URL didn't show the detail panel, but c&p-ing it did! And clicking in the slack web ui worked fine too.
