### ISSUE TITLE
Need means to reset localStorage view state

### ISSUE THREAD

**Issue by davkal** [weaveworks/scope#1872]
Aftermath of #1853 

This is a bit edge casey but do you think we need some kind of localStorage recovery story? If you have a terminal open, notice some bug we've introduced which crashes the app...

refresh will reload that bad state from the url
clearing the url will now also load the app into a bad state from localStorage

**Comment by jpellizzari** [comment]
@davkal how about another little icon in the bottom right that would clear localStorage's viewState then reload the page without any state in the URL. 

Something like this: 
![1872](https://cloud.githubusercontent.com/assets/2802257/19912309/c57e98d0-a056-11e6-843e-a6ed71a25d41.png)
It could say "Clear UI State" on hover maybe.

Or, we could add a keyboard shortcut that would have the same behavior.

**Comment by davkal** [comment]
I would put the Clear UI state button in the help window. Of all the icons, it will be used the least often, by orders of magnitude. Maybe create a new section in the lower part of the help window?
