### ISSUE TITLE
Allow filtering by multiple namespaces

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#1878]
Recent dogfooding experience of moving scope into its own namespace away from default has raised the observation that it would be nice to be able to see `default+scope` namespaces.
- Not sure if there's any trickiness on the BE impl.
- Current FE radio selection of namespace is nice and simple, checkbox style which this would move us towards is more fiddly.

> perhaps allow pinning of selections?
> "press twice to make it stick"
> -- @rade 

Think think.

**Comment by rade** [comment]
Related to #1871.

**Comment by rade** [comment]
> Not sure if there's any trickiness on the BE impl.

I don't think so. Probably needs a little bit of extra code, but should slot nicely into the existing filter functionality. @2opremio do you agree?

**Comment by 2opremio** [comment]
> @2opremio do you agree?

I do

**Comment by rade** [comment]
Isn't this a dup of #1421?

**Comment by rade** [comment]
@foot @2opremio ping

**Comment by rade** [comment]
@foot @2opremio ping again

**Comment by foot** [comment]
yes this appears to be a dup of #1421
