### ISSUE TITLE
node names in connection list truncated unnecessarily

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1882]
Compare
![screenshot_2016-09-22_20-45-20](https://cloud.githubusercontent.com/assets/109109/18763623/1806ccaa-8106-11e6-9644-cc47fe9da24f.png)
which looks lovely post #1874 - no space wasted, no unnecessary truncation - with
![screenshot_2016-09-22_20-47-15](https://cloud.githubusercontent.com/assets/109109/18763670/4290720a-8106-11e6-8e4e-7e6881eb2ce2.png)
which has a bunch of truncated names in the connection list even though there is acres of space. Furthermore, horizontal space is wasted by the count column taking up way more space than necessary - it should be no wider than in the Internet node.

**Comment by rade** [comment]
@simon it might be worth tackling this now, while your memory of #1874 is still fresh.

**Comment by foot** [comment]
Good catch, FF behaving a bit differently here.
