### ISSUE TITLE
Table-mode: tooltip for "The Internet" is missing minor label

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1884]
The part about 'O...' and 'I...' is very unclear, also I am not sure why should it be included in list view, and details pane doesn't revile any visual clues to what 'O' and 'I' stand for, only graph view does.

![](https://www.dropbox.com/s/wpt70dtla8mynxu/Screenshot%202016-09-23%2008.56.12.png?dl=1)

![](https://www.dropbox.com/s/r7c5mt6qkeye81i/Screenshot%202016-09-23%2008.56.08.png?dl=1)

**Comment by rade** [comment]
The full text should be revealed on hover, but only the major label ("The Internet") is, not the minor label. Which is a bug.
