### ISSUE TITLE
Wrong sorting order for processes inside a container 

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1885]
We seem to sort in ascending order, which means that processes with higher CPU usage are hidden.

Default:
![](https://www.dropbox.com/s/l8e0bjkitu1tkon/Screenshot%202016-09-23%2009.01.24.png?dl=1)

What user wants to see:
![](https://www.dropbox.com/s/f9wyo0fytgfgrs6/Screenshot%202016-09-23%2009.01.28.png?dl=1)

**Comment by rade** [comment]
This got fixed in #1877; you can see the fix on dev but it hasn't landed in prod yet.
