### ISSUE TITLE
build is flaky

### ISSUE THREAD

**Issue by ekimekim** [weaveworks/scope#1911]
I'm seeing a signifigant % of builds fail with one of two causes:
- Build time out after the build hangs trying to talk to `docker.io` to download images
- Build failure after `npm install` reports an error `ECONNRESET`

The former is possibly just due to issues with docker hub, the latter I'm mystified.
For now retrying every 3rd or 4th build seems to be working, but this is a really crappy workaround.

**Comment by rade** [comment]
not happening anymore -> closing.
