### ISSUE TITLE
Goroutine leak in scope app?

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1916]
![screen shot 2016-10-10 at 14 08 51](https://cloud.githubusercontent.com/assets/444037/19251221/1868add0-8ef3-11e6-9fb2-8b591fadb85b.png)

**Comment by rade** [comment]
What service is this, i.e. collection, query, etc? Or is it the admin scope app?

**Comment by tomwilkie** [comment]
`job="kube-system/scope"`

[dump.txt](https://github.com/weaveworks/scope/files/520438/dump.txt)

**Comment by tomwilkie** [comment]
Looks like we need to set some timeouts on the server

https://golang.org/pkg/net/http/#Server

**Comment by rade** [comment]
What has happened to the underlying TCP connections?

**Comment by tomwilkie** [comment]
> What has happened to the underlying TCP connections?

No idea.  You're probably more equipped to tell than I am.

**Comment by ekimekim** [comment]
@tomwilkie @paulbellamy I seem to recall you saying you fixed something related to this, and I can't see this same graph in current dev. Is this fixed?

**Comment by ekimekim** [comment]
apparently not. still happening in prod, though not visibly in dev.
interestingly, it seems to also be happening in `scope/control` in both envs.
prod: (larger sawtooth is kube-system/scope, smaller is control)
![prod graph](https://cloud.githubusercontent.com/assets/570052/19865151/4d847b1e-9f58-11e6-8320-b964023b36a3.png)
dev: (the brown sawtooth is control. note the much shorter timespan and smaller vertical axis)
![dev graph](https://cloud.githubusercontent.com/assets/570052/19865229/8e75c240-9f58-11e6-8605-14c1a3ffeb56.png)
dev `kube-system/scope`:
![dev graph 2](https://cloud.githubusercontent.com/assets/570052/19865265/b5c94948-9f58-11e6-8913-59929440c11d.png)

**Comment by ekimekim** [comment]
ok, so I took a goroutine dump of scope app in prod.
the reported metric of number of goroutines at the time was 6993, but oddly only 571 greenlets were present in the dump. The vast majority were in IO wait and looked like:
```
goroutine 12974 [IO wait, 407 minutes]:
net.runtime_pollWait(0x7f83bc238d90, 0x72, 0x11c)
        /usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc421af40d0, 0x72, 0xc426bbd730, 0xc420016150)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc421af40d0, 0x217a100, 0xc420016150)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc421af4070, 0xc425514000, 0x1000, 0x1000, 0x0, 0x217a100, 0xc420016150)
        /usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4220a8a70, 0xc425514000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:173 +0x70
net/http.(*connReader).Read(0xc424c6fe80, 0xc425514000, 0x1000, 0x1000, 0x4b4f29, 0x2162cd0, 0x0)
        /usr/local/go/src/net/http/server.go:586 +0x144
bufio.(*Reader).fill(0xc420340f00)
        /usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadSlice(0xc420340f00, 0xa, 0x0, 0x1e, 0x6, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:330 +0xb5
bufio.(*Reader).ReadLine(0xc420340f00, 0xc421cfe870, 0xf0, 0xf0, 0x1557be0, 0xc420498c01, 0x17f83c0e2be10)
        /usr/local/go/src/bufio/bufio.go:359 +0x37
net/textproto.(*Reader).readLineSlice(0xc4218f0900, 0xc426bbda28, 0xc426bbda28, 0x41c848, 0xf0, 0x1557be0)
        /usr/local/go/src/net/textproto/reader.go:55 +0x5e
net/textproto.(*Reader).ReadLine(0xc4218f0900, 0xc421cfe870, 0xc, 0x0, 0x4371ac)
        /usr/local/go/src/net/textproto/reader.go:36 +0x2f
net/http.readRequest(0xc420340f00, 0xc42006e100, 0xc421cfe870, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:793 +0xa5
net/http.(*conn).readRequest(0xc425066300, 0x21811c0, 0xc42243f600, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:765 +0x10d
net/http.(*conn).serve(0xc425066300, 0x21811c0, 0xc42243f600)
        /usr/local/go/src/net/http/server.go:1532 +0x3d3
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
```
ie. it's trying to read the http request and never timing out.

I can confirm the connections do still exist:
```
# ls -l /proc/1/fd|wc -l                
7067
```
(note: some time passed between gathering above info, there may be discrepancies)

We should be able to fix this just by putting a timeout on serving http requests

**Comment by tomwilkie** [comment]
https://github.com/weaveworks/scope/pull/1917 should fix it.
