### ISSUE TITLE
probe sends timestamps with precision of one minute

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1928]
The probe sends timestamps as a string formatted with `t.Format(time.RFC822)`, which only has minute precision.

AFAIK the probe data currently contains timestamps in just four places:
- docker container creation timestamp
- k8s 'created' metadata
- report timestamp
- metrics first/last timestamp

The former two user `time.RFC822`, the latter use `time.RFC3339Nano`.

Poking around our vendored code, `RFC3339Nano` is quite popular, so is `RFC3339` and `RFC1123Z`.

I suggest we switch to `RFC3339Nano` throughout. It will cost us a few more bytes; if we are concerned about that then RFC3339.

And we should leave the user-friendly formatting to the f/e; see #1866.

**Comment by 2opremio** [comment]
> The probe sends timestamps as a string formatted with t.Format(time.RFC822), which only has minute precision.

Thanks for the investigation!
