### ISSUE TITLE
Scope graph doesn't re-org itself to show structure of containers and flow of connections

### ISSUE THREAD

**Issue by mjlodge** [weaveworks/scope#1935]
Running Sock Shop demo app, Scope's container view does not change as network traffic begins to flow, resulting in edges drawn across nodes, with little information about the structure of the application.

Hitting refresh will cause the graph to be re-drawn with structure. Otherwise the layout does not change.

To reproduce on Docker Mac: start Docker, follow instructions to clone sockshop github repo, cd to docker-only directory. Edit last line of compose yaml file to be "-r 100000". Do `docker-compose up -d`

Wait about 30s for the traffic generator container to start. Observe that a few containers show connections between them, but the layout does not change.

Do `docker-compose scale user-sim=6`. Note that you will have to hit the refresh icon several times to get the graph to change.

cc @pidster

**Comment by mjlodge** [comment]
The graph is also drawn "upside down" in this screen shot -- not showing top-to-bottom left-to-right flow:
<img width="1178" alt="screenshot 2016-10-17 13 23 57" src="https://cloud.githubusercontent.com/assets/2354066/19487524/20af9a28-9518-11e6-91d1-4cd0e49434a9.png">

**Comment by 2opremio** [comment]
@mjlodge This is a tricky one, since it's hard to find the right balance to avoid dancing nodes.

**Comment by mjlodge** [comment]
I can see that. But the layout yesterday was moribund in the extreme. It hardly ever changed. I think the current setting is way to soporific :-)
