### ISSUE TITLE
Can pause container be updated with some new configuration?

### ISSUE THREAD

**Issue by ankur22388-huawei** [weaveworks/scope#1936]
If we want to do some operation on all the containers running inside the pod, rather than doing it one by one on all conatiners running can it be done directly from pause container only?

**Comment by 2opremio** [comment]
Just to be clear, you want a control to pause all the containers from a pod at once?

**Comment by 2opremio** [comment]
> can it be done directly from pause container only?

Why from the pause container and not from an additional pause button in the pod details panel?

**Comment by 2opremio** [comment]
Also, can you provide us with details about your usecase?

**Comment by rade** [comment]
@ankur22388-huawei please elaborate on your use case.

**Comment by rade** [comment]
closing due to lack of further info. please re-open if/when more details are available.
