### ISSUE TITLE
Weave Net peers view

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1938]
Users of Weave Net expect to see properties of that product in Scope, which has no special handling of it.

As a user I want...
- … to see Weave Net peers in Scope so I can verify they have started and are connected so I can debug network issues
- … to see Weave Net peers in Scope so I can verify whether peer connections are using Fast Datapath or encryption so I can debug network issues

Information similar to the `status` and `report` outputs from the `weave` script can presented in Scope.

**Comment by 2opremio** [comment]
Reopening, since the connections table is still missing.
