### ISSUE TITLE
UI says "Trying to reconnect..." forever

### ISSUE THREAD

**Issue by tskinn** [weaveworks/scope#1939]
![image](https://cloud.githubusercontent.com/assets/6225757/19528168/347a00ae-95e8-11e6-850b-ce98f8fa1199.png)

Console logs this error:
`WebSocket connection to 'wss://api.k8s-dev.kyanisecure.com/api/v1/proxy/namespaces/monitoring/servic…opology/containers/ws?t=5s&&system=application&stopped=running&pseudo=hide' failed: WebSocket opening handshake was canceled`

I am running weavescope on a kubernetes cluster with 3 masters and 6 nodes. I could be wrong but it seems like this happens whenever there is a change to the cluster like a new node spinning up or down. If I completely destroy all of the weavescope pods and create them again it starts to work again.

If I try the same page in incognito it works fine. 

Looking at the probe logs I see two errors:
Error fetching app details...
Error doing publish for...

**Comment by 2opremio** [comment]
@tskinn How are you connecting to the UI? Is the UI publicly accesible? are you using `kubectl port-forward`? are you using `kubectl proxy`?

**Comment by rade** [comment]
@tskinn what browser were you using?

**Comment by tskinn** [comment]
I am using chrome Version 53.0.2785.143 (64-bit).
I connect to the UI through the kubernetes api which requires basic auth.
For example the url is `https://mykubernetescluster.com/api/v1/proxy/namespaces/default/services/weavescope-app:app/`

**Comment by 2opremio** [comment]
What kubernetes version are you using?

We've found problems connecting through `kubectl proxy` ( https://github.com/kubernetes/kubernetes/issues/25126 ) and I vaguely recall that we had the same problem when connecting directly.

Can you try to connect using `kubectl port-forward` ?

**Comment by tskinn** [comment]
Kubernetes version 1.4.1
Connecting through kubectl port-forward is flaky. It connects but doesn't show all nodes/info and is very slow.
Going through the k8s api is much faster and accurate when it isn't "trying to reconnect". I will try to get better steps to recreate the problem.

**Comment by 2opremio** [comment]
> Going through the k8s api is much faster and accurate when it isn't "trying to reconnect". I will try to get better steps to recreate the problem.

Thanks. Would you be willing to try testing open access to Scope to discard a problem with the API server? (using whatever extra security measures you need to make you comfortable to do it, I suggest `--probe.no-controls` when launching the probes).

> If I try the same page in incognito it works fine.

That's odd, can you try removing the scope cookies and see if that helps? Are you connecting to other Scope sites?

**Comment by tskinn** [comment]
I haven't experienced this issue again. I've since set up an AWS ELB over tcp and it works like a charm. When I was experiencing the issue I was accessing two different k8s clusters each running scope at the same time. Maybe that had something to do with it. Anyways I think we can close this issue.
