### ISSUE TITLE
Goroutine leak in app?

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1949]
![screen shot 2016-10-25 at 14 06 33](https://cloud.githubusercontent.com/assets/444037/19687148/450bb3f8-9abc-11e6-8ca6-bdb7b154e123.png)

**Comment by rade** [comment]
dup of #1916?

**Comment by ekimekim** [comment]
@tomwilkie @paulbellamy I seem to recall you saying you fixed something related to this, and I can't see this same graph in current dev. Is this fixed?

**Comment by ekimekim** [comment]
instead of cross-posting everything, i'm just going to close this as a dupe of #1916
