### ISSUE TITLE
Improve plugin documentation

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1963]
We should improve the plugin documentation to encourage people to write plugins and get started quickly.

We could do several things:
- Improve the current documentation
- Write a guide
- Explain the data structures better

**Comment by 2opremio** [comment]
@abuehrle This work is going to be done by the Kinvolk guys, probably @alepuccetti but it would be really helpful if you could oversee it and provide guidelines on how to extend https://www.weave.works/documentation/scope-latest-plugins/

**Comment by davkal** [comment]
The GH org is great for hosting the plugin code, but we still need some kind of Yahoo-ish directory for plugins that makes it easier to browse them. It would be great to have that as a separate page to the guide.
I’d like to get people thinking in terms of categories, like datasource plugins, or metrics plugins, or decorator plugins, or control plugins. These categories are just a proposal.

**Comment by alepuccetti** [comment]
This is a first step redirecting users to the new plugin organization.

https://github.com/weaveworks/scope/pull/1906

**Comment by alepuccetti** [comment]
> https://www.weave.works/documentation/scope-latest-plugins/

Is this page generated from this file https://github.com/weaveworks/scope/blob/master/examples/plugins/README.md? So I should start my work from there?

**Comment by 2opremio** [comment]
> Is this page generated from this file https://github.com/weaveworks/scope/blob/master/examples/plugins/README.md? S

No, it comes from https://github.com/weaveworks/scope/blob/master/site/plugins.md . Please coordinate the changes under `site/` with @abuehrle
