### ISSUE TITLE
Cannot copy/paste out of a scope terminal

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1964]
Highlight goes away when releasing mouse-button.

**Comment by jpellizzari** [comment]
@paulbellamy Was this working before? We recently changed the terminal library.

**Comment by rade** [comment]
> @paulbellamy Was this working before?

Yes, as you can see for yourself by running the latest released version of Scope.

**Comment by foot** [comment]
Ooops, seems to the focusing stuff, I'm remove it in #1966 and that should fix this.

**Comment by foot** [comment]
Fixed in #1966
