### ISSUE TITLE
Allow text selection on a scrolled up terminal.

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#1969]
Terminals now "scroll lock", they retain their scrolled back position if new data comes in.

However, new incoming data will still clear the current text selection making it awkward to highlight and copy and paste logs.

**Comment by foot** [comment]
This is more of an upstream issue in xterm.js for which a PR exists.

**Comment by foot** [comment]
This issues is left over from #1932

**Comment by rade** [comment]
This is quite annoying.

@foot have you got a reference for the upstream PR?

**Comment by foot** [comment]
https://github.com/sourcelair/xterm.js/pull/336 which looks to be fixed in 2.1!

Will make an issue for that..

**Comment by foot** [comment]
Sorry I got my issues confused here, losing selection is still an issue for now. https://github.com/sourcelair/xterm.js/issues/468

**Comment by rade** [comment]
The issue in the xterm lib has been fixed. upgrade! cc @foot

**Comment by rade** [comment]
Hmm. We did actually update to the latest xterm.js (2.9.2) in #2900. But this issue still exists, even though the upstream issue is closed :(

**Comment by rade** [comment]
Hmm. I've just tried it again, and now it _does_ work. Tried container shell, container logs and pod logs, in both FF and Chrome, both locally and in Weave Cloud.
