### ISSUE TITLE
Add control icon to top corner of the terminal window

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1982]
Once you have triggered a control you may not be able to tell what control it was by looking at the terminal window alone.

See for instance: https://github.com/weaveworks/scope/pull/1979

**Comment by jpellizzari** [comment]
@2opremio I'm trying to understand the requirement. When a control is activated, there should be an icon on the terminal to indicate what happened, like this?
![screen shot 2016-11-08 at 1 18 19 pm](https://cloud.githubusercontent.com/assets/2802257/20117559/03e17e1c-a5b6-11e6-92c2-2d3089f8be66.png)
Or maybe:
![screen shot 2016-11-08 at 1 18 29 pm](https://cloud.githubusercontent.com/assets/2802257/20117567/0ac4ab28-a5b6-11e6-8393-8475253badb5.png)

**Comment by 2opremio** [comment]
I am not a designer but I was thinking the second option but with the icon
on the top left corner (instead of the top right corner)

**Comment by jpellizzari** [comment]
@2opremio Do you think we should represent all of the controls statuses, or just the ones related to the terminal (attach and exec)? For example, does showing the 'stop' icon make sense?:
<img width="780" alt="screen shot 2016-11-15 at 2 16 24 pm" src="https://cloud.githubusercontent.com/assets/2802257/20309018/43865d98-ab3e-11e6-9e55-5d515414fe1b.png">

**Comment by 2opremio** [comment]
I would say just attach and exec. Happy to answer these questions by I am not the expert.  @bowenli @davkal or @pidster are much more knowledgable in UX than I am :)
