### ISSUE TITLE
Conntrack XML parsing is consuming a lot of CPU

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1991]
See https://github.com/weaveworks/scope/pull/1985#issuecomment-258826860

**Comment by 2opremio** [comment]
@alban Suggests replacing the conntrack command (and in turn parsing it's XML output) by talking to the kernel directly through a Netlink socket.

**Comment by 2opremio** [comment]
Found https://github.com/typetypetype/conntrack but the status is not really reassuring ...

**Comment by 2opremio** [comment]
Using netlink is going to be a bit more work than I originally expected due to the incomplete Golang support and my almost total ignorace about netlink until yesterday.

* https://github.com/vishvananda/netlink doens't support Conntrack directly (I created https://github.com/vishvananda/netlink/issues/171)
* https://github.com/typetypetype/conntrack/ is in dubious state (I tested it and seems to work though) and doesn't fully support flows either. There's [`Follow()`](https://github.com/typetypetype/conntrack/blob/72c92241b390ad6ce8ca1078268153537901a952/client.go#L103) which reads flows into [Conn](https://github.com/typetypetype/conntrack/blob/master/client.go#L174-L182). However `Conn` [lacks the `Orig` side of the flow](https://github.com/typetypetype/conntrack/blob/72c92241b390ad6ce8ca1078268153537901a952/client.go#L226-L230) and there is no simple or public way to send commands to conntrack.

My plan is to fork https://github.com/typetypetype/conntrack/ to reuse all the parsing but it may be more sensible to bite the bullet and implement https://github.com/vishvananda/netlink/issues/171 (which I think would take a much longer time). @awh Thoughts?

**Comment by 2opremio** [comment]
After an offline discussion with @awh I've confirmed that implementing a netlink protocol is a non-trivial task and that we should instead try improving parsing first. I will proceed in the following order, reevaluating performance after each step:

* Try to find a better performing XML library
* Try parsing the textual output of conntrack (i.e. without `-o xml`)
* Use netlink

**Comment by 2opremio** [comment]
> Try to find a better performing XML library

I have failed to find an alternative XML library at all. Moving on to parse the conntrack text manually.

**Comment by tomwilkie** [comment]
Huh, I thought codec did it, but it doesn't.

https://godoc.org/github.com/ugorji/go/codec

**Comment by 2opremio** [comment]
Parsing the line-based output of conntrack is a pain in the ass because some (at least 4) fields are optional. This means I cannot simply use Scanf. 

I started coding a manual parser for it, but I am not sure it's worth the effort compared to spending time on https://github.com/vishvananda/netlink

**Comment by tomwilkie** [comment]
Does https://github.com/lucsky/go-exml help?  Do you know what bit of the
xml parsing is the overhead?

**Comment by rade** [comment]
> Do you know what bit of the xml parsing is the overhead?

IIRC string allocation/gc is the issue. Due to golang's lack of interns or a proper generational GC.

**Comment by tomwilkie** [comment]
If that is the case, you could parse the IPs straight into unit32s (or
net.IPs), and the Proto, Direction and State into a enum etc

**Comment by tomwilkie** [comment]
Note that in previous cases of encoding / decoding overhead, its been the
reflection thats the problem, not allocations (cf report structure).

**Comment by rade** [comment]
As I understand it, for the xml parsing the string allocation/gc happens mainly due to tags and attribute keys, e.g. if you have a document containing 500 \<meta\> tags, that's 500 allocations, and 500 items of garbage, not one.

**Comment by tomwilkie** [comment]
How dumb: https://golang.org/src/encoding/xml/xml.go?s=6817:6857#L1146

**Comment by 2opremio** [comment]
I could create a parser with something like https://github.com/prataprc/goparsec 

Maybe I could also give https://github.com/moovweb/gokogiri a try

**Comment by 2opremio** [comment]
> Does https://github.com/lucsky/go-exml help?

It doesn't promise any performance improvements plus _sits on top of a standard Go encoding/xml/Decoder_  so I am doubtful
