### ISSUE TITLE
Replace conntrack by ebpf

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1992]
It can potentially save us quite some CPU, see #1991 

This implies gathering NATting information directly through ebpf

**Comment by alban** [comment]
We should check if we can get the conntrack info from golang directly with a Netlink socket, instead of forking a conntrack process. That would remove the time spend in XML encoding and decoding. I expect that it will be easier than eBPF, and a more stable kernel API.

**Comment by 2opremio** [comment]
We decided not to replace conntrack, since it gives us all the NAT information we need and getting it from ebpf doesn't really offer an advantage (after fixing #1991 performance seems reasonable).
