### ISSUE TITLE
Nothing to show on cluster

### ISSUE THREAD

**Issue by Maximophone** [weaveworks/scope#2000]
Weave scope was working fine until yesterday, but it now displays an empty cluster even though nothing has changed on our side.
Even the weave scope pods do not appear anymore.

The setup is pretty simple. First I start a cluster using the following command:

```
gcloud container --project "project-name" clusters create "cluster-name" \
    --zone "europe-west1-b" --machine-type "n1-standard-4" \
    --scopes "https://www.googleapis.com/auth/compute","https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly" \
    --num-nodes "1" --network "default" --enable-cloud-logging --no-enable-cloud-monitoring \
    --image-type=container_vm
```

Then I start weave scope using:

`kubectl create -f 'https://scope.weave.works/launch/k8s/weavescope.yaml?k8s-service-type=LoadBalancer' --validate=false`

When I go to the external IP address of the weave-scope-app service I get the empty weave scope front end, with the message "Nothing to show ..." and no Pods tab.

The version of kubernetes is the following:

Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.7", GitCommit:"a2cba278cba1f6881bb0a7704d9cac6fca6ed435", GitTreeState:"clean", BuildDate:"2016-09-12T23:15:30Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

Any help much appreciated.

**Comment by 2opremio** [comment]
Can you please:

1. Verify that the Scope Probe Daemon Set (`weave-scope-agent`) is running
2. Verify that the Scope App Service (`weave-scope-app`) is created
3. Verify that the Scope App Deployment (`weave-scope-app`) is created
4. Paste the logs of a Scope probe in the Daemon Set (1)
5. Paste the logs of the Scope App (3)

@errordeveloper Could any recent changes in launch-generator broken deployments of Scope on k8s?

**Comment by Maximophone** [comment]
Thanks for the fast answer. 

I can confirm that the daemon is running, and the service and the deployment are created.

Here are the logs of the weave-scope-agent pod:

time="2016-11-09T16:38:19Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:19Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:20Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:20Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:21Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:21Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:22Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:22Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:23Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:23Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:25Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:25Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:26Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:26Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:27Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:27Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:28Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:28Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:29Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:29Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:30Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:30Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:32Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:32Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:33Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:33Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:34Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:34Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:35Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:35Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:36Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:36Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:37Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:37Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:38Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:38Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:40Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:40Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:41Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:41Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:42Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:42Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:43Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:43Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:44Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:44Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:45Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:45Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:47Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:47Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:48Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:48Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:49Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:49Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:50Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:50Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:51Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:51Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:52Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:52Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:53Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:53Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:55Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:55Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:56Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:56Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:57Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:57Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:58Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:58Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:38:59Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:38:59Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:00Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:00Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:01Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:01Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:03Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:03Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:04Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:04Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:05Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:05Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:06Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:06Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:07Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:07Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:08Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:08Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:10Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:10Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:11Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:11Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:12Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:12Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:13Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:13Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:14Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:14Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:15Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:15Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:16Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:16Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:18Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:18Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:19Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:19Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:20Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:20Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:21Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:21Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:22Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:22Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:23Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:23Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:24Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:24Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:26Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:26Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:27Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:27Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:28Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:28Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:29Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:29Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:30Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:30Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:31Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:31Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 
time="2016-11-09T16:39:32Z" level=info msg="publishing to: $(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)" 
time="2016-11-09T16:39:32Z" level=fatal msg="Invalid targets: strconv.ParseInt: parsing \"$(WEAVESCOPE_APP_SERVICE_PORT)\": invalid syntax" 

And the logs of the weave-scope-app pod:

<app> INFO: 2016/11/09 16:38:20.314939 app starting, version 1.0.0, ID 397bf2c4dea50a4a
<app> INFO: 2016/11/09 16:38:20.315073 command line args: --logtostderr=true --mode=app --no-probe=true
<app> INFO: 2016/11/09 16:38:20.349220 listening on :4040
<app> WARN: 2016/11/09 16:38:20.404019 Error updating weaveDNS, backing off 20s: exit status 1
<app> WARN: 2016/11/09 16:38:40.450695 Error updating weaveDNS, backing off 40s: exit status 1
<app> WARN: 2016/11/09 16:39:20.490856 Error updating weaveDNS, backing off 1m0s: exit status 1

**Comment by 2opremio** [comment]
The problem is that the service was created after the probe pod and the service IP is not filled in (i.e. the probe is trying to talk to  invalid host `$(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)`)

Note how the variables are not filled in in the probe logs `$(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)`

As a workaround, making sure that the service exists before the probe is created should do the trick. Let me know if you need further guidance for this.

According to @errordeveloper, kubernetes respects the order in the yaml list, so in principle this shouldn't happen, but after your problem we should revisit this. Did you do something else other than the `kubectl create -f` command to deploy scope?

@errordeveloper we really really need to fix https://github.com/weaveworks/launch-generator/issues/13 to prevent this type of issues.

**Comment by Maximophone** [comment]
No I only run the commands I have pasted above. Do you suggest splitting the yaml in 2 parts and running them consecutively or do you know a better way of enforcing the order?

**Comment by 2opremio** [comment]
> Do you suggest splitting the yaml in 2 parts and running them consecutively or do you know a better way of enforcing the order?

That would be an option. Another option may be deleting the daemon set manually (making sure the service and app deployment still exist) and then type `kubectl create -f 'https://scope.weave.works/launch/k8s/weavescope.yaml?k8s-service-type=LoadBalancer'` again (to re-create the Daemonset).

Sorry for the inconvenience, we are being hit by https://github.com/kubernetes/kubernetes/issues/17406 , but we have a better work around which doesn't have the problem you are experiencing. We will update `https://scope.weave.works/launch/k8s/weavescope.yaml` ASAP.

**Comment by Maximophone** [comment]
I have tried your solution but still run into the same problem.

I create the cluster and run the yaml file. 

I then run:

` kubectl delete daemonset weave-scope-agent-[code]`

To delete the probe, and finally I rerun the yaml file, which outputs:

daemonset "weave-scope-agent" created
Error from server: deployments.extensions "weave-scope-app" already exists
Error from server: services "weave-scope-app" already exists

as expected.

However the problem stays the same (the placeholders in the logs are not filled).

**Comment by 2opremio** [comment]
We've just realized it's not an ordering problem. The problem is that `WEAVESCOPE_APP_SERVICE_PORT` should be `WEAVE_SCOPE_APP_SERVICE_PORT` and `WEAVESCOPE_APP_SERVICE_HOST` should be `WEAVE_SCOPE_APP_SERVICE_HOST` (note the extra underscore)

**Comment by 2opremio** [comment]
We will be fixing it shortly

**Comment by Maximophone** [comment]
Great I can confirm that it works again! Thanks for your help.

**Comment by 2opremio** [comment]
Thank you for reporting, it was an unfortunate oversight on our part.

**Comment by 2opremio** [comment]
@Maximophone `https://scope.weave.works/launch/k8s/weavescope.yaml` is now fixed
