### ISSUE TITLE
Add unit tests for the ECS reporter

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2036]
Leftover from https://github.com/weaveworks/scope/pull/2026

**Comment by 2opremio** [comment]
Fixing this should include  removing the following TODO:

```go
		// TODO: add ECS nodes in report fixture
		if topology.Name == "Tasks" {
			continue
		}
```

https://github.com/weaveworks/scope/blob/9c7282231f78797647f4d8991cbade9f55abbe89/app/api_topologies_test.go#L47-L50

**Comment by ekimekim** [comment]
fixed by https://github.com/weaveworks/scope/pull/2065
