### ISSUE TITLE
Move ECS AMI documentation to Scope website

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2039]
https://github.com/weaveworks/integrations/blob/master/aws/ecs/README.md documents the Scope ECS AMIs . 

This information is not on Scope's website (but we link to it) https://github.com/weaveworks/scope/blob/master/site/installing.md#installing-scope-on-amazon-ecs , we should consider moving it or including it there.

**Comment by pidster** [comment]
Is this something for @weaveworks/docs ?

**Comment by abuehrle** [comment]
I've added these in after installing.md:  https://github.com/weaveworks/scope/pull/2307

What versions should be listed for Scope and Net?

**Comment by 2opremio** [comment]
> What versions should be listed for Scope and Net?

What do you mean? The versions included in the AMI are listed here: https://github.com/weaveworks/integrations/tree/master/aws/ecs#whats-in-the-weave-ecs-amis

**Comment by abuehrle** [comment]
I mean should these be updated to the most recent versions? They are listing ancient versions of Net and Scope.

**Comment by 2opremio** [comment]
Yes, they need. But the images themselves should be updated before the
documentation is.

**Comment by abuehrle** [comment]
Obviously :)

**Comment by abuehrle** [comment]
PR here for reference: 

https://github.com/weaveworks/scope/pull/2307

**Comment by abuehrle** [comment]
updated
