### ISSUE TITLE
ECS: Missing link to task on container details panel

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2040]
Leftover from #2026 

Here's an example: In the Socks shop demo, the rabbitmq container links to its host and its container by image but not to its ECS task.

<img width="1145" alt="screen shot 2016-11-29 at 7 11 37 am" src="https://cloud.githubusercontent.com/assets/2362916/20715675/cabff23a-b604-11e6-90d9-a7c8f9ecb398.png">

**Comment by ekimekim** [comment]
I'm looking through the report, but I don't understand what field causes that top link to appear?

**Comment by ekimekim** [comment]
for posterity: that top link is populated from the `parents` field of the returned `node` in detail view, which is a `render.detailed.Node`, NOT a `report.Node`, the conversion between the two for the parents field explicitly describes behaviour for each topology type, and didn't list ECS topologies, so they were ignored despite being in the report's parent field.
