### ISSUE TITLE
ECS: prioritize Service/Task view if available

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2042]
Leftover from #2026 

Just like in K8s, we should prioritize showing the ECS views if available

See https://github.com/weaveworks/scope/blob/master/client/app/scripts/utils/topology-utils.js

The ECS topologies are called `ecs-tasks` and `ecs-services` at the time of writing this.

**Comment by jpellizzari** [comment]
@2opremio I assume by "prioritize", you mean we should send the user to those views by default when the page loads (if available)?

**Comment by rade** [comment]
yes, modulo anything in their view state that says otherwise.

**Comment by 2opremio** [comment]
Yep, what @rade said
