### ISSUE TITLE
Support Swarmkit services

### ISSUE THREAD

**Issue by lukemarsden** [weaveworks/scope#2044]
Presumably in the same way as ECS and Kubernetes tasks/services/etc are visible.

From a user on Docker Community Slack:
> hey man :slightly_smiling_face: have one question .. is weave SCOPE app able to visualize services in swarm mode ?

my reply:
> hey! we don't support swarm mode services yet... but we'd like to!
> we just added ECS support

his reply:
> ok :slightly_smiling_face: it would be nice to have such a tooling .. at least all the business guys want to see fancy visualizations :slightly_smiling_face:

cc @pidster @rade

**Comment by rade** [comment]
@lukemarsden @2opremio isn't this a dup of #1618?

**Comment by 2opremio** [comment]
Yep, I will mark that one as a duplicate though

**Comment by rade** [comment]
> Yep, I will mark that one as a duplicate though

I much prefer going the other way. Marking the old issue as a dup misrepresents history and rewards bad behaviour (such as not looking for existing issues).

**Comment by jaredcnance** [comment]
So, I know the title specifically references SwarmKit. Would this support extend to the Swarm Mode released in Docker 1.12?

**Comment by lukemarsden** [comment]
They're the same thing, so yes

**Comment by ekimekim** [comment]
This was closed by https://github.com/weaveworks/scope/pull/2444
