### ISSUE TITLE
Scope metrics fill displayed to the side

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#2047]
<img width="195" alt="fill" src="https://cloud.githubusercontent.com/assets/303151/20728935/d977a306-b634-11e6-886b-d30d8818381c.png">

The metrics fill is appearing at the right hand side, instead of the bottom.

**Comment by 2opremio** [comment]
@pidster Please add more information on how to reproduce

**Comment by rade** [comment]
both dev and prod show this. Works fine for processes and hosts, but not containers and pods.

**Comment by pidster** [comment]
I am running a Sock Shop which you are now invited to @2opremio.

**Comment by errordeveloper** [comment]
I have also seen this, I thought it was intentional...

**Comment by foot** [comment]
:), no, back to vertical for now.
