### ISSUE TITLE
Graph/table buttons don't resize nicely 

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2056]
For presentation/demos I get a better result by zooming in (<kbd>⌘</kbd>+<kbd>+</kbd>) rather than using contrast mode.

However, when doing that the Graph/table buttons get a strange vertical alignment, with an odd surrounding border.

<img width="1256" alt="screen shot 2016-12-05 at 14 09 38" src="https://cloud.githubusercontent.com/assets/2362916/20886097/9b5bf6c0-baf4-11e6-916a-36f7a66e2517.png">

**Comment by 2opremio** [comment]
Actually it happens without zooming when making the window small enough.

<img width="864" alt="screen shot 2016-12-05 at 14 30 28" src="https://cloud.githubusercontent.com/assets/2362916/20886677/8424b890-baf7-11e6-9919-86ef4ad38162.png">

**Comment by jpellizzari** [comment]
Working in prod. Closing.
