### ISSUE TITLE
Weave scope can not show any container in web browser

### ISSUE THREAD

**Issue by arixling** [weaveworks/scope#2099]
I installed weave scope to my virtualized instance whose GuestOS is Ubuntu (14.04.4 TLS/64bit) based on https://www.weave.works/install-weave-scope/. I ran some container in this VM. But weavescope client (web browser) can't show anything. The version of scope is 1.1.0.

**Comment by 2opremio** [comment]
@arixling what do you mean by "can't show anything"? What were you expecting to see and what do you see? Can you send us the ligs? (`docker logs weavescope`)

**Comment by arixling** [comment]
Hi Alfonso,

I ran following containers in AWS.
[cid:image002.jpg@01D25A23.AEAC0530]

I have ever saw my containers in weave scope client in very short time.
[cid:image003.jpg@01D25A23.AEAC0530]
But it is very difficult in seeing detailed information.
[cid:image004.jpg@01D25A23.AEAC0530]

After that, I cannot see any container forever. So I try to deploy my container to Aliyun.
I installed weave scope to my virtualized instance whose GuestOS is Ubuntu (14.04.4 TLS/64bit) based on https://www.weave.works/install-weave-scope/.
I ran containers in this VM. But weavescope client (web browser) can't show anything. The version of scope is 1.1.0.
Attachment is docker logs weavescope.
I really think scope is very wonderful. But it seems it is very difficult to use.

Thanks,

Siwer Johnson
发件人: Alfonso Acosta [mailto:notifications@github.com]
发送时间: 2016年12月19日 17:52
收件人: weaveworks/scope
抄送: Fuxihua (Siwer Johnson); Mention
主题: Re: [weaveworks/scope] Weave scope can not show any container in web browser (#2099)


@arixling<https://github.com/arixling> what do you mean by "can't show anything"? What were you expecting to see and what do you see? Can you send us the ligs? (docker logs weavescope)

**Comment by 2opremio** [comment]
Hi @arixling 

Thanks for your answer but I cannot see any of the images or the logs. Would you mind adding them to https://github.com/weaveworks/scope/issues/2099 instead of as email attachments?

Also, using Slack may be a better option to help you debug this. Go to https://slack.weave.works/ and follow the instructions (my username is fons there).

**Comment by arixling** [comment]
I reboot my AWS instance and ran scope first. After that I ran docker logs weavescope. It show following info:
root@ip-172-31-29-180 ec2-user]# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
[root@ip-172-31-29-180 ec2-user]# scope launch
7ea1a0ddb17f9112fd9c32235919376773f2beafa760cf353269bc95d929521a
Weave Scope is reachable at the following URL(s):
  * http://172.19.0.1:4040/
  * http://172.31.29.180:4040/
  * http://172.18.0.1:4040/
[root@ip-172-31-29-180 ec2-user]# docker logs weavescope
<app> INFO: 2016/12/19 15:38:33.136011 app starting, version 1.1.0, ID 21d56c67fbb2d287
<app> INFO: 2016/12/19 15:38:33.138100 command line args: --logtostderr=true --mode=app --probe.docker=true
time="2016-12-19T15:38:33Z" level=info msg="publishing to: localhost:4040"
<probe> INFO: 2016/12/19 15:38:33.138629 command line args: --logtostderr=true --mode=probe --probe.docker=true
<probe> INFO: 2016/12/19 15:38:33.138697 probe starting, version 1.1.0, ID d8ead9e98917102
<app> INFO: 2016/12/19 15:38:33.184213 listening on :4040
<probe> WARN: 2016/12/19 15:38:33.460460 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> WARN: 2016/12/19 15:38:33.465245 Cannot resolve 'scope.weave.local.': dial tcp 172.17.0.1:53: getsockopt: connection refused
<probe> INFO: 2016/12/19 15:38:33.468610 Success collecting weave plugin status
<probe> INFO: 2016/12/19 15:38:33.468811 Success collecting weave proxy status
<probe> ERRO: 2016/12/19 15:38:33.524638 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
<probe> INFO: 2016/12/19 15:38:33.536272 Control connection to localhost starting
<probe> ERRO: 2016/12/19 15:38:33.537421 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
<app> WARN: 2016/12/19 15:38:34.877350 Error updating weaveDNS, backing off 20s: exit status 1
<probe> WARN: 2016/12/19 15:38:35.170767 Error collecting weave ps, backing off 20s: exit status 1
<probe> ERRO: 2016/12/19 15:38:35.170945 Error processing event for container ccc6d70ee32aeb7ea35d109dbe8ce5291b285eb40cb6056263a11e2291765420: API error (500): devmapper: Unknown device 4fb426ca7905c2f6a724b0d0bae7ccbb2a77a731a18b26fee42d04022a552e4b

<probe> INFO: 2016/12/19 15:38:36.480537 Publish loop for localhost starting
<probe> WARN: 2016/12/19 15:38:43.490771 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused

**Comment by arixling** [comment]
Then I ran docker-compose to run some containers. I ran docker logs weavescope again and I got following info:
[root@ip-172-31-29-180 clearwater-docker]# docker-compose -f minimal-distributed.yaml up -d
Starting clearwaterdocker_homer_1
Starting clearwaterdocker_etcd_1
Starting clearwaterdocker_ellis_1
Starting clearwaterdocker_cassandra_2
Starting clearwaterdocker_chronos_2
Starting clearwaterdocker_ralf_1
Starting clearwaterdocker_bono_1
Starting clearwaterdocker_sprout_2
Starting clearwaterdocker_homestead_1
Starting clearwaterdocker_memcached_2
Starting clearwaterdocker_cassandra_1
Starting clearwaterdocker_sprout_1
Starting clearwaterdocker_memcached_1
Starting clearwaterdocker_chronos_1
[root@ip-172-31-29-180 clearwater-docker]# docker logs weavescope
<app> INFO: 2016/12/19 15:38:33.136011 app starting, version 1.1.0, ID 21d56c67fbb2d287
<app> INFO: 2016/12/19 15:38:33.138100 command line args: --logtostderr=true --mode=app --probe.docker=true
time="2016-12-19T15:38:33Z" level=info msg="publishing to: localhost:4040"
<probe> INFO: 2016/12/19 15:38:33.138629 command line args: --logtostderr=true --mode=probe --probe.docker=true
<probe> INFO: 2016/12/19 15:38:33.138697 probe starting, version 1.1.0, ID d8ead9e98917102
<app> INFO: 2016/12/19 15:38:33.184213 listening on :4040
<probe> WARN: 2016/12/19 15:38:33.460460 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> WARN: 2016/12/19 15:38:33.465245 Cannot resolve 'scope.weave.local.': dial tcp 172.17.0.1:53: getsockopt: connection refused
<probe> INFO: 2016/12/19 15:38:33.468610 Success collecting weave plugin status
<probe> INFO: 2016/12/19 15:38:33.468811 Success collecting weave proxy status
<probe> ERRO: 2016/12/19 15:38:33.524638 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
<probe> INFO: 2016/12/19 15:38:33.536272 Control connection to localhost starting
<probe> ERRO: 2016/12/19 15:38:33.537421 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
<app> WARN: 2016/12/19 15:38:34.877350 Error updating weaveDNS, backing off 20s: exit status 1
<probe> WARN: 2016/12/19 15:38:35.170767 Error collecting weave ps, backing off 20s: exit status 1
<probe> ERRO: 2016/12/19 15:38:35.170945 Error processing event for container ccc6d70ee32aeb7ea35d109dbe8ce5291b285eb40cb6056263a11e2291765420: API error (500): devmapper: Unknown device 4fb426ca7905c2f6a724b0d0bae7ccbb2a77a731a18b26fee42d04022a552e4b

<probe> INFO: 2016/12/19 15:38:36.480537 Publish loop for localhost starting
<probe> WARN: 2016/12/19 15:38:43.490771 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<app> WARN: 2016/12/19 15:38:55.509338 Error updating weaveDNS, backing off 40s: exit status 1
<probe> WARN: 2016/12/19 15:38:56.089368 Error collecting weave ps, backing off 40s: exit status 1
<probe> WARN: 2016/12/19 15:39:03.491733 Error collecting weave status, backing off 40s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<app> WARN: 2016/12/19 15:39:36.174574 Error updating weaveDNS, backing off 1m0s: exit status 1
<probe> WARN: 2016/12/19 15:39:36.781824 Error collecting weave ps, backing off 1m0s: exit status 1
<probe> WARN: 2016/12/19 15:39:43.492698 Error collecting weave status, backing off 1m0s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> WARN: 2016/12/19 15:45:53.491949 Docker reporter took longer than 1s
<probe> WARN: 2016/12/19 15:45:55.214947 Docker reporter took 2.729595756s (longer than 1s)
<probe> WARN: 2016/12/19 15:46:09.262159 Endpoint reporter took 1.337042494s (longer than 1s)
<probe> WARN: 2016/12/19 15:46:09.365539 Host reporter took longer than 1s
<probe> WARN: 2016/12/19 15:46:09.365735 Process reporter took longer than 1s
<probe> WARN: 2016/12/19 15:46:09.365864 Endpoint reporter took longer than 1s
<probe> WARN: 2016/12/19 15:46:09.435560 Docker reporter took longer than 1s
<probe> WARN: 2016/12/19 15:46:09.523668 Process reporter took 1.624790947s (longer than 1s)
<probe> WARN: 2016/12/19 15:46:09.739332 Host reporter took 1.944043935s (longer than 1s)
<probe> WARN: 2016/12/19 15:46:10.073581 Docker reporter took 2.128076665s (longer than 1s)

**Comment by rade** [comment]
Are these micro instances? If so they are perhaps being throttled.

**Comment by arixling** [comment]
You mean my VM instance can not support so many micro instances. There were 14 containers running in my AWS EC2.
[root@ip-172-31-29-180 clearwater-docker]# docker ps | grep clearwater
9e93215d470d        clearwaterdocker_cassandra   "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        7001/tcp, 9042/tcp, 9160/tcp, 0.0.0.0:32769->22/tcp                                                                                                       clearwaterdocker_cassandra_2
4c35284133e0        clearwaterdocker_chronos     "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        7253/tcp, 0.0.0.0:32773->22/tcp                                                                                                                           clearwaterdocker_chronos_2
0f38c2787b7e        clearwaterdocker_memcached   "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        11211/tcp, 0.0.0.0:32772->22/tcp                                                                                                                          clearwaterdocker_memcached_2
b8a91265718a        clearwaterdocker_sprout      "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        5052/tcp, 5054/tcp, 0.0.0.0:32771->22/tcp                                                                                                                 clearwaterdocker_sprout_2
9ce635688311        clearwaterdocker_bono        "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        0.0.0.0:3478->3478/tcp, 0.0.0.0:3478->3478/udp, 0.0.0.0:5060->5060/tcp, 0.0.0.0:5062->5062/tcp, 0.0.0.0:5060->5060/udp, 5058/tcp, 0.0.0.0:32779->22/tcp   clearwaterdocker_bono_1
cb47e458459b        clearwaterdocker_homestead   "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        8888-8889/tcp, 0.0.0.0:32774->22/tcp                                                                                                                      clearwaterdocker_homestead_1
041e5bc71b2f        clearwaterdocker_cassandra   "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        7001/tcp, 9042/tcp, 9160/tcp, 0.0.0.0:32776->22/tcp                                                                                                       clearwaterdocker_cassandra_1
8446c2f914f1        clearwaterdocker_sprout      "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        5052/tcp, 5054/tcp, 0.0.0.0:32777->22/tcp                                                                                                                 clearwaterdocker_sprout_1
ca34e99366b4        clearwaterdocker_memcached   "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        11211/tcp, 0.0.0.0:32778->22/tcp                                                                                                                          clearwaterdocker_memcached_1
58b2c0783aae        clearwaterdocker_ellis       "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:32775->22/tcp                                                                                                                 clearwaterdocker_ellis_1
fd3417c158b4        clearwaterdocker_ralf        "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        10888/tcp, 0.0.0.0:32770->22/tcp                                                                                                                          clearwaterdocker_ralf_1
77f1d5a173d3        clearwaterdocker_chronos     "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        7253/tcp, 0.0.0.0:32780->22/tcp                                                                                                                           clearwaterdocker_chronos_1
42d48069a523        quay.io/coreos/etcd:v2.2.5   "/etcd -name etcd0 -a"   2 weeks ago         Up 6 minutes        2379-2380/tcp, 4001/tcp, 7001/tcp                                                                                                                         clearwaterdocker_etcd_1
a34d60621063        clearwaterdocker_homer       "/usr/bin/supervisord"   2 weeks ago         Up 6 minutes        7888/tcp, 0.0.0.0:32768->22/tcp                                                                                                                           clearwaterdocker_homer_1

**Comment by rade** [comment]
I am referring to the EC2 instance type.

**Comment by arixling** [comment]
I put docker engine, scope and 14 containers in my EC2 VM instance.

**Comment by rade** [comment]
What EC2 instance type is that VM?

**Comment by arixling** [comment]
t2.micro. It is minimum VM instance as it is free for one year.

**Comment by rade** [comment]
t2.micro are prone to throttling, which is very bad for Scope. I suggest you try a different instance type. Or reduce the load; ince your original report is about not showing any containers, running a single container should suffice to demonstrate and track down the problem.

**Comment by arixling** [comment]
Why scope can not show any information? The limited resource should not be the reason that scope could not probe containers.

**Comment by rade** [comment]
> Why scope can not show any information? 

There are various time-window related heuristics in scope, which can have that effect.

**Comment by 2opremio** [comment]
Related: https://github.com/weaveworks/guides/issues/181

**Comment by 2opremio** [comment]
@arixling Can you try to temporarily run larger instances to see if the problem goes away?

**Comment by 2opremio** [comment]
Also, if Ubuntu is not a hard requirement I would suggest using the Weaveworks ECS AMIs: https://github.com/weaveworks/integrations/tree/master/aws/ecs

**Comment by arixling** [comment]
I reinstall scope with latest version and it can work now. But there is still a problem.
I found that if I connect weave scope client web browser to my VM instance via proxy, it can not show any thing. But if I doesn't use proxy, that is Ok. Why?

**Comment by 2opremio** [comment]
I'm surprised that simply switching to the latest version fixed the problem when the logs show that the probes are likely in need of more CPU, e.g:

```
reporter took 1.944043935s (longer than 1s)
```

As for the proxy, we've encountered problems with proxies not supporting websockets. Scope makes extensive use of websockets so please make sure it supports them.

What browser and proxy are you using? 

Can you paste a screenshot of the Networking panel off the Chrome inspector after showing what happens when you try to connect? https://developers.google.com/web/tools/chrome-devtools/#network

**Comment by rade** [comment]
@arixling any more info on this?

**Comment by ryc8889** [comment]
was there ever anymore info on this? I'm having a similar issue.
