### ISSUE TITLE
Terminals garble wrapped lines

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2111]
It happens both when typing and editing long lines. See the following videos for examples:

Creating long (wrapping) command:

![](http://g.recordit.co/UMXxtUiV27.gif)

Editing a long command:

![](http://g.recordit.co/AkN2ePQW3U.gif)

I haven't been able to find a matching issue [upstream](https://github.com/sourcelair/xterm.js/issues)

**Comment by foot** [comment]
Interesting!

Are those probes fairly up to date? (Have the new resizing stuff from mid-nov).

**Comment by 2opremio** [comment]
Yep, they are version 0.17.1

**Comment by jpellizzari** [comment]
@2opremio I am not able to reproduce. As far as I can tell, you are just typing a command that wraps, correct?

Is anyone else able to reproduce this?

**Comment by rade** [comment]
I cannot repro this either on Dev-in-Dev and Prod-in-Prod.

**Comment by foot** [comment]
Classically these issues popped up w/ containers that were started w/ funny
args, e.g. combinations of `docker run -ti`, (tty, or interactive) + bash
vs sh vs ash (alpine).

**Comment by rade** [comment]
But the screen cap is from a host terminal, isn't it?

**Comment by foot** [comment]
Can't markdown comments flagged as coming from email. Yes it appears to be a host terminal so something else.

**Comment by 2opremio** [comment]
I don't seem to be able to reproduce myself

**Comment by 2opremio** [comment]
Closing, will reopen if I see it again
