### ISSUE TITLE
Upgrade xterm.js to 2.2.3

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#2121]
~Should fix some more terminal niggles like #1969~ - not fixed by upgrading to 2.2.3 yet.

Nice to stay up to date though.

**Comment by jpellizzari** [comment]
@foot Looks like master is already on 2.1:
https://github.com/weaveworks/scope/blob/master/client/package.json#L42

There are some new improvements in the most recent 2.2.3 release:
https://github.com/sourcelair/xterm.js/pull/379/files

**Comment by rade** [comment]
> Looks like master is already on 2.1

So why am I still seeing #1969?

**Comment by jpellizzari** [comment]
Closed by #2126
