### ISSUE TITLE
Investigate using Scope as a UI component

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/scope#2133]
It would be super sweet if we could include scope as a dependency in other projects, such as service-ui.

Notes:
* Scope has to be loaded via service-ui's router instance, so having Scope maintain its own render lifecycle is probably not going to work
* `dispatch` and `getState` are used all over the place in components, actions and utils, so those functions from `redux` will need to be intercepted
* `redux-thunk` middleware also has access to `dispatch` and `getState`

**Comment by rade** [comment]
> It would be super sweet

why?

**Comment by jpellizzari** [comment]
@rade This will open the door for lots of integrations with other projects. Scope's application state and user actions, such as controls, will be usable by any project that mounts scope in the UI.

**Comment by rade** [comment]
Do you have an example of such an integration that we are contemplating?

**Comment by jpellizzari** [comment]
Some ideas:

* Lock, release or automate a k8s service from the scope UI
* Show Flux history of a service in Scope's service's details panel
* Change a configuration option (such as a service env variable) and have it propagate back to version control

**Comment by rade** [comment]
got it. thanks.

**Comment by jpellizzari** [comment]
Implemented by #2144
