### ISSUE TITLE
High-contrast mode not working

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/scope#2138]
No high-contrast stylesheets are being loaded on master. Clicking on the high-contrast mode does nothing. 

- [x] Debug
- [x]  Add a step to the scope release validation doc

**Comment by rade** [comment]
works fine in scope 1.1.0.

**Comment by rade** [comment]
broken on current master. For a moment I thought it worked fine, but that looks like it was because it had some stuff cached from my 1.1.0 run - a shift-reload broke it.

**Comment by rade** [comment]
> Add a step to the scope release validation doc

It would be good to find out when this broke and what reasonable steps, if any, we could take to catch this sort of stuff earlier - adding a step to the release validation is pretty much a last resort and I am not convinced actually would be worth for this particular issue.

**Comment by jpellizzari** [comment]
Root cause was a the change of an import statement:

https://github.com/weaveworks/scope/commit/26b3e9ef#diff-4d661728241a2342af58f2e2738a2fb7L2

**Comment by jpellizzari** [comment]
There is already a step for 'contrast mode' in our release validation

**Comment by jpellizzari** [comment]
PR merged
