### ISSUE TITLE
New version available notice in GUI

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#2139]
"As a user I want to see a notice in the GUI when a new version of Scope is available."

When* a new version of Scope is available, the GUI should display an indicator that a new version is available. The user may interact with the indicator to discover more information about the new version, or read a small additional notice. Once the user has read the notice, the indicator is cleared.

* At some point after release (in the order of hours)

Further questions to consider:
- Should the indicator appear again periodically?
- Are user-facing notifications like this a more general feature, or is this a special case?

**Comment by rade** [comment]
Too much design here. Let's leave that to the experts :)

To add my $0.02... I wouldn't do a notice/confirmation dance. Instead simply highlight the current version (in flashing red, ha ha), and display details of the available upgrade on hover.

**Comment by pidster** [comment]
I'm sure the team will improve on the above, or correct us. :)

**Comment by bowenli** [comment]
Notification feels a bit heavy handed. Usually non-breaking version notices are handled as 'warning' types: 
![screen shot 2017-02-06 at 13 54 08](https://cloud.githubusercontent.com/assets/915421/22667985/d283ed46-ec73-11e6-88fd-3827f1bc6af4.png)

And we could have clicking link out to release notes, etc.

**Comment by rade** [comment]
I quite like that.

re links to release notes etc. I can't actually remember what data we stick into our version checking db, so this may already be there. If not it would be easy to add a few more fields.

**Comment by rade** [comment]
We actually already have this feature, since #1366, except it is broken. See #2716.

**Comment by pidster** [comment]
Should this appear via: https://github.com/weaveworks/cortex/issues/420 ?
