### ISSUE TITLE
Image label missing from view

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2150]
Running the Sock Shop in Kubernetes and noticed that the image label is missing from cart-db in both the container views (graph and table) as well as the details panel.   

See screen shot: 

![screen shot 2017-01-24 at 12 05 42 pm](https://cloud.githubusercontent.com/assets/13420383/22261893/550e2578-e234-11e6-8a9d-ed1206522556.png)

**Comment by abuehrle** [comment]
This came up in training today, when a person was looking for the newly deployed image from Flux.

**Comment by abuehrle** [comment]
@rade

**Comment by rade** [comment]
@abuehrle can you reproduce this?

**Comment by abuehrle** [comment]
I'm not seeing this anymore with a new deploy from git:  

```kubectl apply -n sock-shop -f deploy/kubernetes/manifests```

But I will try updating the sock-shop from a private repo with Flux.

**Comment by rade** [comment]
closing this for now; @abuehrle if you see this again please re-open and capture a report.
