### ISSUE TITLE
Document flags

### ISSUE THREAD

**Issue by carlpett** [weaveworks/scope#2157]
Currently `scope --help` outputs this usage text:
```
Usage:
scope launch [<peer> ...]
scope stop
scope command

scope <peer>    is of the form <ip_address_or_fqdn>[:<port>]
```

However, there are a few flags (`--no-app`, `--app-only`, `--no-probe`, `--probe-only`, `--service-token`, `--probe.token`), available for at least launch, as seen [here](https://github.com/weaveworks/scope/blob/master/docker/entrypoint.sh).

It would be great to have them in the `--help` text, as well as in the "Installing" section of the documentation, or a new "Operational guide" as is available for Weave Net.

**Comment by 2opremio** [comment]
> However, there are a few flags (`--no-app`, `--app-only`, `--no-probe`, `--probe-only`, `--service-token`, `--probe.token`), available for at least launch, as seen [here](https://github.com/weaveworks/scope/blob/master/docker/entrypoint.sh).

Those flags are part fo the `launch` subcommand, try `scope launch --help`

**Comment by 2opremio** [comment]
@carlpett What would had made it easier to find the flags documentation?

**Comment by carlpett** [comment]
Expanded from the discussion on Slack:

I think the thing that made me not even test `scope launch --help` was that there is _some_ invocation help already on the first `--help`, which, in combination with the lack of mention in the docs, made me assume that those were the only available options.

So, it might actually be more intuitive (to me at least) if the top level help hadn't show anything, or somehow indicated that there were many (many many) flags available. Maybe just `scope launch [...]`? I'm on a phone now so I can't easily look around for good examples, but something along those lines.

**Comment by rade** [comment]
perhaps just change the first line of the usage to
```
scope launch --help | <opts> [<peer> ...]
```
That would be the Minimal Viable Improvement, I think ;)

Beyond that, I find it mighty odd that `scope --help` reports
```
Unknown scope command '--help'
Usage:
scope launch [<peer> ...]
scope stop
scope command

scope <peer>    is of the form <ip_address_or_fqdn>[:<port>]
```
whereas `scope help` reports
```
Usage:

scope help     - Print this

scope launch   - Launch Scope
Usage of /home/weave/scope:
  -alsologtostderr
    	log to standard error as well as files
  -app-only
    	Only run the app
  -app.aws.create.tables
    	Create the tables in DynamoDB
...
```

Alas this is with 1.1.0; the latest master does things quite differently. Alas I am unable to build it. grrr.

**Comment by carlpett** [comment]
>perhaps just change the first line of the usage to
> `scope launch --help | <opts> [<peer> ...]`

This would looks good to me!

**Comment by ekimekim** [comment]
As @rade mentioned, this is already "fixed" (or at least, changed) on master, see https://github.com/weaveworks/scope/pull/2077
Basically, the new behaviour is for `scope --help` to be the same as `scope help`, and the latter has some readability improvements.
The launch options described under the actual launch script are a subset* of those listed in `scope help` (since the launch script passes the args through to the raw binary).
There's an argument to be made that the list of options could be edited for clarity so important options (app vs probe) are at the top.

*or at least is meant to be, see https://github.com/weaveworks/scope/issues/2104
