### ISSUE TITLE
Filtering causes all nodes to appear erratically

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2168]
I am filtering using the search function, and there seems to be some inconsistent behaviour. 

I have kubernetes running sock shop in DO: 

1. Search on cart
2. flip through the views. 
3. In the Pods view the tool tip tells me there are 2 matches of the term in services and replicas, but then nothing appears on the screen. 

![screen shot 2017-01-30 at 3 40 42 pm](https://cloud.githubusercontent.com/assets/13420383/22443032/06e1a644-e703-11e6-926f-eedcc63cd495.png)

and then after some time, I get overlapping screens, as shown here: 

![screen shot 2017-01-30 at 3 45 35 pm](https://cloud.githubusercontent.com/assets/13420383/22442968/c8d7bf00-e702-11e6-85b5-e5598bc141b8.png)

**Comment by 2opremio** [comment]
> but then nothing appears on the screen.

That may be because of your filters. Have you tried relaxing them?

If that's the problem, the search results should be consistent with current filters though.

**Comment by abuehrle** [comment]
One of my hosts just flat out crashed, and also crashed the demo app,  so let me reproduce this again on a new deployment.  Also, I did notice that the URL was retaining the search query, but let me verify that.

**Comment by abuehrle** [comment]
I think this had to do with my CPU being overloaded. I have not seen this behaviour since I re-deployed the instances.  I will leave them up, though, and see if the same CPU problem occurs.
