### ISSUE TITLE
Removing Search term from field causes Pods view to disappear

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2169]
To reproduce: 

1. Search on a term for example, Cart. 

2.  Click Pods.

3.  Then click on Hosts and remove the search term.  

Note that deployments and Services from Pods are now located beneath Hosts: 

![screen shot 2017-01-30 at 3 49 42 pm](https://cloud.githubusercontent.com/assets/13420383/22443243/dca7c9de-e703-11e6-987b-9f24e4461844.png)

**Comment by fbarl** [comment]
I wasn't able to reproduce this now, neither from the current `master` nor from `dev`. @abuehrle are you still able to reproduce? If yes, on which system does it happen and which topology were you viewing when you did the search in step 1? @2opremio were you also able to reproduce when you were assigning the labels?

**Comment by abuehrle** [comment]
Let me try to reproduce this again.  The CPU on all three of my hosts was maxed out and so this could have been the cause. I have reconfigured the scenario and see if it's still there  (also, will profile scope for you later this week).

**Comment by abuehrle** [comment]
I'm not seeing this anymore and things seem much solid. I will close this and if I see it again will reopen.
