### ISSUE TITLE
Scope token doesn't refresh after losing hosts

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2196]
When an instance was connected to hosts and then loses that connection, the Token doesn't refresh when going to the (now empty) instance. To reproduce: 

1. Create an instance and connect some probes to the host. 
2. Disconnect the hosts.
3. Switch to another instance.  
4. Flip back to the instance that has no connectivity and view the setting page. 

You'll notice that the scope token field is blank as show below.  This is fixed by reloading the browser, but I think the token should refresh without user intervention: 

![screen shot 2017-02-06 at 10 10 57 am](https://cloud.githubusercontent.com/assets/13420383/22655091/95305732-ec54-11e6-82f7-bf690db9faa4.png)

**Comment by 2opremio** [comment]
@abuehrle Would you mind moving this issue to service-ui (just copy it there and close this one)? This repository is for the scope related part of the service (not the wrapper UI).

**Comment by abuehrle** [comment]
moved
