### ISSUE TITLE
How can I classify external nodes?

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#2201]
Some users have configurations where certain nodes appear under "The Internet" node, but are actually internal. It's hard to detect such cases automatically, but there should be a way for use to configure it, e.g. by providing a list of DNS names used internally. Some such example involve external LBs.

**Comment by rade** [comment]
Isn't this a dup of #1876?

**Comment by 2opremio** [comment]
> Isn't this a dup of #1876?
I would say it is. 

@errordeveloper Please extend #1876 any of your needs are not already covered there.
