### ISSUE TITLE
Popped out terminal styles don't quite align with in-scope terminal styles

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#2209]
Font size is bit bigger, missing style sheet?

**Comment by 2opremio** [comment]
If fixing this before 1.2 please target the #2203 branch

**Comment by foot** [comment]
The global styles like base font-size are delcared in `.scope-app` now, which `.terminal-app` doesn't have.

**Comment by rndstr** [comment]
@foot was this fixed in #2217?

**Comment by foot** [comment]
Most likely!
