### ISSUE TITLE
Weave Net resource usage not shown in pod or net view

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2213]
Noted in: VERSION f8cf32c ON service

When I filter by memory or CPU and look for Weave in the container view, I see the visual cue, as shown below: 

![screen shot 2017-02-08 at 9 47 31 am](https://cloud.githubusercontent.com/assets/13420383/22744800/1d7f96c6-ede4-11e6-849f-59642d28941a.png)

But in Pods, the cue is missing: 
![screen shot 2017-02-08 at 9 46 23 am](https://cloud.githubusercontent.com/assets/13420383/22744838/37ca5822-ede4-11e6-94fa-c82c2ebc0d6f.png)

and in Weave Net view, the filtering options are completely absent:

![screen shot 2017-02-08 at 9 47 02 am](https://cloud.githubusercontent.com/assets/13420383/22744882/5573928a-ede4-11e6-8143-03262d9c53be.png)

**Comment by 2opremio** [comment]
There are no CPU/memory metrics for pods show we cannot show anything.

For the Weave Net topology I guess we could show the CPU/memory metrics of the hosts.

**Comment by rade** [comment]
> There are no CPU/memory metrics for pods show we cannot show anything.

Umm. We *do* show them. but only when the pod has just one "proper" (i.e. non-infra) container. Weave Net has two. See #1257.

**Comment by rade** [comment]
> For the Weave Net topology I guess we could show the CPU/memory metrics of the hosts.

I am not convinced this makes sense.

**Comment by 2opremio** [comment]
> Umm. We do show them. but only when the pod has just one "proper" (i.e. non-infra) container. 

Ah! So we don't do aggregation but we propagate the metrics if there's a single (non-pause) container? I wasn't aware of this.

**Comment by rade** [comment]
Yep. A smart little trick/hack that @paulbellamy implemented.

**Comment by 2opremio** [comment]
[True](https://github.com/weaveworks/scope/blob/529759b6036f8fc871a7f77a0b5e312220fb2923/render/pod.go#L30)

**Comment by rade** [comment]
So this really is a dup of #1257.
