### ISSUE TITLE
Create `latest_release` Docker image tag during release process

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2216]
It should point to the latest release. To be used when integrating with third-party projects (and make sure they don't bitrot).

**Comment by rade** [comment]
To be clear, we are talking about image tags on dockerhub et al, rather than git tags, right? Since we already have a latest_release for the latter.

**Comment by 2opremio** [comment]
> To be clear, we are talking about image tags on dockerhub et al, rather than git tags, right?

Yep. Sorry I wasn't specific enough
