### ISSUE TITLE
Failing asset hashing?

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2218]
I think it's more common that meters go from left to right, rather than right to left. 

![screen shot 2017-02-08 at 12 25 15 pm](https://cloud.githubusercontent.com/assets/13420383/22751425/f19be526-edf9-11e6-873d-1085a29ca701.png)

(screen captures in docs are also now not up to date-- minor issue, but please tag me as those take a lot of time to update unfortunately.)

**Comment by 2opremio** [comment]
@abuehrle Where did you get that screenshot? Seems like an outdated Scope version suffering an old bug (can't find it right now)

**Comment by rade** [comment]
> old bug 

#2047 

I don't think that was ever broken in a released version.

**Comment by abuehrle** [comment]
I updated the script with the test build, i.e. ```weaveworks/scope               release-1.2-9e33e7e   b56cc5c43e11        27 hours ago        88.4 MB```

(I also cleaned off my machine of old images, etc.)
and I am still seeing it: 

![screen shot 2017-02-08 at 3 25 35 pm](https://cloud.githubusercontent.com/assets/13420383/22758123/f3340cec-ee12-11e6-9c51-ea1e43be93fc.png)

**Comment by 2opremio** [comment]
What does the version on the bottom right corner say? 

Have you tried a hard reload on your browser? 

What browser are you using?

**Comment by abuehrle** [comment]
I actually reinstalled it and it was _still_ there.  Shift-reload did make it go away.  Persistent!  But that is the first time I'd seen that.

**Comment by 2opremio** [comment]
This means we have a problem with asset hashing

**Comment by abuehrle** [comment]
I deleted the script and downloaded the new release: /usr/local/bin/

Browser version: Chrome Version 56.0.2924.87 (64-bit)

Scope Version: VERSION1.2.0 ON 11a3fce9aebb

Local standalone version running in Docker for Mac.

**Comment by rade** [comment]
AFAIK we've never seen this problem again. -> closing.
