### ISSUE TITLE
Feature request: option to hide environment variables

### ISSUE THREAD

**Issue by mikebryant** [weaveworks/scope#2222]
We'd like to make weave scope available to all of our developers.
Many of the pods have secrets injected as environment variables. We'd like to be able to either have the scope app not show these, or have the probe not report them in the first place.

**Comment by 2opremio** [comment]
> have the probe not report them in the first place

I would go for this

How about a flag for the probes (e.g. `--probe.omit.env-vars`)

How about command line arguments? Could that be an issue?

**Comment by mikebryant** [comment]
A flag on the probe would be reasonable.
I'm personally less worried about command line arguments, but depending on how people use the cluster that could definitely be a problem too. Another flag?

**Comment by 2opremio** [comment]
> Another flag?

Sure, that would make sense.

That's not high priority at this point, but if you want to give it a try I will be more than happy to guide you through it (it should be reasonably easy).

**Comment by mikebryant** [comment]
I'm going to work on this, pretty sure I know how to make it work
