### ISSUE TITLE
Pods logs for Weave Net gives warning and no logs

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2233]
Kubernetes
Packet.net
Ubuntu 16.04
Chrome:  56.0.2924.87 (64-bit)
Cloud Version: VERSION35182c8 

Tried to view the logs for one of the Weave Net pods and it gives me a warning: "container name must be specified for pods, choose one of ..." it truncated the message, so it's difficult to read the whole thing. 

Here's a recording: 

http://recordit.co/U0yOXQq77G

**Comment by rade** [comment]
That is the expected behaviour. See #2234.
