### ISSUE TITLE
clicking help button beneath search field causes out of order events 

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2235]
Setup: Kubernetes with Sockshop on Ubuntu
Browser: chrome version 56.0.2924.87 (64-bit)

To reproduce: 

1. Select Container view
2. Type zipkin into the search field (don't press return) 
3. Click the help button. 

Note that help does not appear. 

4. click on the container and the details screen does not appear. 

5. click on the help button in the lower right hand corner and the details screen appears. 

Here's a recording: 

http://recordit.co/O44Ck1x7AM

**Comment by abuehrle** [comment]
I should add also that the WC UI freezes after you perform those steps.

**Comment by jpellizzari** [comment]
@abuehrle Could you re-check this in production? I merged a bug fix for the 'help' icon a few days ago.

**Comment by abuehrle** [comment]
@jpellizzari one really minor thing.  It opens nicely when you click the ? beneath the search field, but then you can't make it go away by clicking the ? again beneath the search.  Although, this works from the help icon in the lower right hand corner. 

Other than that the help looks really good. I should also add that to the guide for the website and expand on it. 

http://recordit.co/nC3JtXkXrx
