### ISSUE TITLE
View showing hierarchal relationship of things consuming resources

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#2242]
As a user I want to:
- see resource utilisation (memory/CPU/file descriptor) metrics for each Host, so that I can compare how containers on different hosts are consuming resources
- see resource utilisation vs limits vs capacity on each Host, so that I can tune the limits assigned per container
- visualise a hierarchical relationship between hosts, containers & processes (and threads?) so I can so that I can quickly identify the source of a (problem caused by resource utilisation).

Types of resources for consideration:
- CPU
- RAM
- File handles
- Disk space

**Comment by pidster** [comment]
See also: http://www.brendangregg.com/blog/2017-02-06/flamegraphs-vs-treemaps-vs-sunburst.html

**Comment by fbarl** [comment]
Here are my initial [mockups](https://docs.google.com/presentation/d/1nQwy5UoICwPNSnzAcQscethsecLEKBHZ9oFzVRO_jic) accompanied by a [design doc](https://docs.google.com/document/d/1421CytU3c6BisQsyy1xVL2OhCgBPtFABq7D6AH7cut4).

I think I've come up with a layout that would be able to capture all the important aspects mentioned above **per resource**, but showing all the hierarchical layers with the info for all the resources in one view seemed like a difficult task, so I'd propose having a heuristics that would combine all the resources info into one metric for the *general view* (as opposed to selecting particular *resource views*).

There are two very similar layout variations in my mockups: _flame graph_ and _sunburst_. The central question that should decide between the two would be how important the edges i.e. node connections are for the resource view (I'd personally slightly prefer keeping them and make it a _sunburst_ layout).

@davkal @jpellizzari @bowenli @pidster @2opremio I'd appreciate your feedback with some comments/questions/suggestions and perhaps giving your opinion on the questions I raised in the docs.

**Comment by monadic** [comment]
+1 for the flame graph

**Comment by fbarl** [comment]
I just made separate slides with [slightly refined mockups](https://docs.google.com/presentation/d/123NzxsPJDUFtsTxiH0kRFj6uc7Bq3CPnv4vK7i9XPgQ/edit#slide=id.p), focusing only on the flame graph variation that we decided to go with. Also, check out the changes to the [ideas doc](https://docs.google.com/document/d/1421CytU3c6BisQsyy1xVL2OhCgBPtFABq7D6AH7cut4/edit) that are now reflecting all the feedback I got, as well as with some notes on what backend can provide the backend part of the story.

**Comment by rade** [comment]
We've done this. Any follow up ideas should be represented be separate issues.
