### ISSUE TITLE
Pod restarts not showing up in details

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2259]
When I run `kubectl get pods --all-namespaces` in the terminal on the master host in Scope, I see a number of container in the sockshop have restarted: 

![screen shot 2017-02-17 at 1 10 33 pm](https://cloud.githubusercontent.com/assets/13420383/23079482/af64dfee-f512-11e6-909d-569e1dbe493f.png)

But this information is not displayed on the container and says 0: 

![screen shot 2017-02-17 at 1 11 01 pm](https://cloud.githubusercontent.com/assets/13420383/23079541/ecb9a406-f512-11e6-833e-0a9643069915.png)

**Comment by rade** [comment]
surely the fact that it says 0 is a bug. -> changing labels.

**Comment by rade** [comment]
When pods restart, do their containers get re-*created* or re-*started*?

**Comment by 2opremio** [comment]
Good question. I would say they are restarted. I think that the restart count is obtained from docker and  I would doubt we have a bug specifically for the kubernetes case.

**Comment by rade** [comment]
Hmmm.

```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: false
$ docker run --name test -dti alpine /bin/sh
b70426355549d77aeb632ae38982e06328324a228a56ca5c7835684e2d0efc65
$ docker inspect -f '{{.RestartCount}} {{.State.StartedAt}}' test
0 2017-05-18T14:07:31.877338973Z
$ docker restart -t 0 test
test
$ docker inspect -f '{{.RestartCount}} {{.State.StartedAt}}' test
0 2017-05-18T14:07:40.494411989Z
```

This suggests to me that k8s is counting something different.

**Comment by abuehrle** [comment]
Docker doesn't seem to have a state 'restarted' but rather they have 'restarting' - in the act of restarting.  And Kubernetes has a restart policy that determines if the container is restarted or not: 

https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/

**Comment by 2opremio** [comment]
I think there has been a mix-up here. The details pane shown by @abuehrle (with `restart # = 0`) corresponds to a container whereas the command-line output corresponds to a kubernetes pod. We don't currently show restart counts for pods in the UI (and as far as I have been able to see, we never had).

The [restart counts of  containers](https://godoc.org/github.com/fsouza/go-dockerclient#Container) (based on how many times a specific container been restarted) are totally different to [those of a container in a pod](https://godoc.org/k8s.io/api/core/v1#ContainerStatus) (based on the number of different dead containers that have not yet been removed). 

To be even more precise, `kubectl get pods` shows the [sum of the restart for all the containers of the pod](https://github.com/kubernetes/kubernetes/blob/bb4854665879a9dcd0412e450e040ccefb019e2e/pkg/printers/internalversion/printers.go#L451) ([init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/) make it a bit more complicated but let's not get into that).

So, this is really a new feature, which should be fairly easy to implement.
