### ISSUE TITLE
Publish to Docker Store

### ISSUE THREAD

**Issue by awh** [weaveworks/scope#2262]
We have an opportunity to get the Scope probe (a.k.a 'Weave Cloud Agent') into Docker's store for its official launch if we move quickly. The technical requirements are slight (extracted from [Docker Store Vendor Agreement](https://drive.google.com/drive/u/0/folders/0B89A-_obDDlleXlzT2xhZjdlTWs), page 11):

```
Prequisite 
a) You must distribute application as containers. 
b) Your container must be tested and supported on Docker CS Engine 1.12 or later
c) Your drivers require 1.13 plugin framework or later and swarm mode compatibility
```
Requirement (c) does not appear to apply, as the probe is not a driver; there also does not appear to be a signing requirement or any restriction on `--privileged`.

The only obvious wrinkle at this point is that the [publishing process](https://success.docker.com/Store) mentions that images are to be staged in a private repository - presumably this is so that Docker can run their security scans before promoting the images to the store. It's not clear if this means that you must stop publishing your images in a public Dockerhub repo, and if so, what the migration is for existing public images.

See discussion here https://weaveworks.slack.com/archives/scope/p1487629547002511

**Comment by awh** [comment]
CC @rade @2opremio @ekimekim @lukemarsden

**Comment by Futurile** [comment]
General information, and a folder with the documents they've provided:

[Docker Launch Notes](https://docs.google.com/document/d/1R3mI07S7iq4nDj97e7Ft3uoCZIY19A0GsRsTI2Z_25I/edit)
[Gdrive folder](https://drive.google.com/drive/u/0/folders/0B89A-_obDDlleXlzT2xhZjdlTWs)

**Comment by 2opremio** [comment]
>  if we move quickly

@awh Can you elaborate? Is there a formal deadline?

**Comment by rade** [comment]
> Is there a formal deadline?

1st March.

**Comment by pidster** [comment]
Can we name this container: `weaveworks/cloud-agent:version`?

**Comment by 2opremio** [comment]
> Can we name this container: `weaveworks/cloud-agent:version`?

Why? Why is the current name  ( `weaveworks/scope:version` ) not good enough? Having different images will be confusing.

**Comment by pidster** [comment]
I would like to differentiate the container in the store.

**Comment by 2opremio** [comment]
Why? That's not an advantage by itself

**Comment by rade** [comment]
Eventually we want this to run just the probe, connected to Weave Cloud, with a simple-as-possible "docker run". And (also eventually) we want this to grow to be more than scope.

**Comment by 2opremio** [comment]
Thanks, that's a reasonable explanation.

**Comment by 2opremio** [comment]
We can simply make it an alias during releases to start with.

**Comment by rade** [comment]
By far the most important thing is to get something into the certification pipeline asap. I am concerned there will be hidden gotchas. So IMO the starting point is literally to publish the most recent release (or current master; I don't care) under the aforementioned image name, and get the certification process kicked off.

**Comment by 2opremio** [comment]
To move this forward, as part of our release process I am simply going to:
1. Create `weaveworks/cloud-agent:version`, for now simply an alias of `weaveworks/scope:version`
2. Push`weaveworks/cloud-agent:version` to  a _private repository_, as required by the Docker Store.

For (2) I am assuming it's a Docker Hub private repository and not new Docker-Store-specific-one. https://success.docker.com/Store only states _specify a product name and image source from a private repository._ but not which private repository. 

This BTW, requires making `weaveworks` a paying account, which I am setting up with @apperly

**Comment by 2opremio** [comment]
`weaveworks/cloud-agent:1.2.1` is already pushed and can be submitted

**Comment by 2opremio** [comment]
We still have a long way to release Scope 1.3 so I will hold off from automating the push in releases until we get confirmation that `weaveworks/cloud-agent:1.2.1` is acceptable.

**Comment by frg415** [comment]
I pinged the docker team yesterday to let them know that we'd be doing scope, instead. Once we have this up, I'll be pushing for the certification process. The PR announcements happen on March 1st, we  ned this up beforehand to give them time to scan and approve. Let me guess: you'd want to know how much time beforehand...Not sure yet.

**Comment by 2opremio** [comment]
I have pushed `weaveworks/cloud-agent:master-0ebc0b` (built from 0ebc0b) which fixes https://github.com/weaveworks/scope/issues/2276 

@pidster Please resubmit ASAP, I will happily release 1.2.2 later on if having standard versioning for tags is a requirement.

**Comment by 2opremio** [comment]
@pidster Please submit weaveworks/cloud-agent:master-98395bb

**Comment by 2opremio** [comment]
I think we can close this. I will make sure to update the store instructions once 1.3 is released.
