### ISSUE TITLE
lint sometimes try to check .git/ directory

### ISSUE THREAD

**Issue by alepuccetti** [weaveworks/scope#2269]
On CircleCI, sometimes happen that `lint` tries to check the `.git/` directory. When this fluke occurs, rebuilding will fix it. An example: https://circleci.com/gh/weaveworks/scope/6553

This is a flaky behavior, so we should fix it

**Comment by alban** [comment]
I wonder if the `cp -r` in circle.yml sometimes copies the `.git` directory but not the `.gitignore` file for some reason.
