### ISSUE TITLE
Invert default of '--probe.docker' to match typical usage

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#2279]
When launching the Scope probe, we set the following:

    --probe.docker=true

In the majority of cases, it's set to `true`. We should flip the default from `false` and reduce the config params needed to launch a typical probe.

https://github.com/weaveworks/scope/blob/master/prog/main.go#L283

**Comment by rade** [comment]
flags that default to true are a pain. So I'd prefer a `probe.nodocker`. Just as we have `noprobe`. I don't know whether we care about backward comp here - `probe.docker` is not a documented flag, AFAIK (haven't checked).. If we do then some fiddling is required, but that's ok, and we already have a few examples of that.
