### ISSUE TITLE
Scope integration test VMs compromised

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#2282]
Probably due to the docker daemon listening without authentication.

I've disabled the integration tests: https://github.com/weaveworks/scope/commit/fe7ec8f133fb2d757ac1f1c5c83eb48eb6ced2e7

I've got no reason to suspect the any confidential data was leaked or the attackers go access to the GCP account.

**Comment by 2opremio** [comment]
I have sent the appeal, to Google Cloud, I don't know why garbage collection stopped working.

**Comment by 2opremio** [comment]
I don't know if it's worth trying to fix this or simply move to the new testing infrastructure @marccarre created for https://github.com/weaveworks/weave .

We probably should wait until the ebpf work is merged though

**Comment by bboreham** [comment]
The new test infrastructure runs instances on a more locked-down network and [creates run-specific firewall rules](https://github.com/weaveworks/build-tools/blob/efcf9d21e09ccd52e00f973a42c78ad08b33e92c/provisioning/gcp/main.tf#L55) to open the Docker port.

Previously this was done in a script, which you might find easier to integrate: https://github.com/weaveworks/weave/commit/fd34dda6c1fde3f0bd5fdb84211f9811c415ef3a

**Comment by 2opremio** [comment]
I am not familiar with how GC works (I just learned it's handled by https://github.com/weaveworks/build-tools/tree/master/scheduler). I am going to diagnose why machines weren't garbage-collected but I don't want to hinder development, so in the meantime I will revert fe7ec8f and watch closely for leaked machines.

**Comment by 2opremio** [comment]
Done 5516f7b7d04b1f434dfd50615973b75cb72f09e6

**Comment by 2opremio** [comment]
This happened again yesterday:

<img width="1211" alt="screen shot 2017-03-02 at 14 26 30" src="https://cloud.githubusercontent.com/assets/2362916/23509022/993b1f3e-ff54-11e6-8597-d6b8b1c51a2e.png">

<img width="2053" alt="screen shot 2017-03-02 at 14 27 22" src="https://cloud.githubusercontent.com/assets/2362916/23509023/9d2c16c0-ff54-11e6-9676-e0f05fceeb84.png">


It seems to be related to cancelled CircleCI builds, see https://circleci.com/gh/weaveworks/scope/6637

I will manually delete them and keep investigating.

**Comment by 2opremio** [comment]
Interestingly there are a bunch of other cancelled builds before 6337 which seem to have been successfully garbage collected:

<img width="2027" alt="screen shot 2017-03-02 at 14 32 03" src="https://cloud.githubusercontent.com/assets/2362916/23509162/240409b4-ff55-11e6-8990-ae2f435e164c.png">

**Comment by alban** [comment]
Do you have the auto-cancel feature enabled in CircleCI (build settings / advanced settings)?

![image](https://cloud.githubusercontent.com/assets/27575/23705014/e0b021cc-0407-11e7-8102-06297c51cb59.png)

I see it is enabled for https://circleci.com/gh/kinvolk/scope but if I remember correctly it was not cancelling builds before.

**Comment by 2opremio** [comment]
It's enabled (I don't think this would cause the problem though)

**Comment by schu** [comment]
Sometimes CircleCI retries builds ("Looks like we had a bug in our infrastructure ... We should have automatically retried this build ...") which would also leave running VMs behind, if it happens in between integration tests.

**Comment by alban** [comment]
`./gce.sh destroy` is in the "post" section of circleci but it will not be executed in case of cancellation, see
https://discuss.circleci.com/t/cancelled-build-post-hook-commands/5995

**Comment by tomwilkie** [comment]
We have a VM garbage collector to catch this.

Either way, this is not the solution.  You need to secure the VMs properly.
