### ISSUE TITLE
Docker Store cloud-agent:  don't run 'runsvinit'

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#2283]
Per the Docker Store feedback/report, Docker do not approve of `runsvinit`.

> Appears to use runsvinit (process manager utility).  The processes are spawned from the same binary within the image.  Please consider if there are architecture changes that could reduce this extra layer of indirection.

See also: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/each-container-should-have-only-one-concern

**Comment by 2opremio** [comment]
To be clear, this is only a requirement for the Docker Store image. The normal Scope image still needs it (until we split the images if we do) since it runs both the app and probe processes.

**Comment by 2opremio** [comment]
This is s requirement of #2262

**Comment by rade** [comment]
I don't think removal of runsvinit is a requirement. Not using it is. i.e. it should be ok to have it in the image as long as it's not being used.
