### ISSUE TITLE
Two flags have identical descriptions

### ISSUE THREAD

**Issue by bboreham** [weaveworks/scope#2304]
thus making it hard for users to understand which flag they want:

	flag.StringVar(&flags.probe.token, serviceTokenFlag, "", "Token to use to authenticate with cloud.weave.works")
	flag.StringVar(&flags.probe.token, probeTokenFlag,   "", "Token to use to authenticate with cloud.weave.works")

https://github.com/weaveworks/scope/blob/master/prog/main.go#L262

also "to use to" seems to contain some redundancy.

**Comment by rade** [comment]
Both flags do the same thing. It is not worth breaking backward compatibility by removing one of them.

**Comment by rade** [comment]
(I removed the "to use")
