### ISSUE TITLE
instrument probes with some prometheus metrics

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2318]
In running probes in our Weave Cloud clusters, we have had a few incidents of entire probes or data going missing from the app. The probe logs usually indicate a problem, but we - and other scope users - would really benefit from some metrics here.

- count of report sending attempts, labelled by destination
- count of failed report sending attempts, labelled by destination
- count of conntrack errors (e.g. because buffer is too small)

**Comment by pidster** [comment]
Also, metrics for each of the functions that are timed, such as procspy would be good.

**Comment by n0rig** [comment]
+1
