### ISSUE TITLE
zoom control not obvious

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2321]
@lukemarsden watched a user struggling to work out how to zoom in scope. They used the browser zoom, which only zooms everything *except* the graph. And they didn't realise that mousewheel zoomed at all.

I wonder whether a) browser zoom should zoom everything, and) we should add some google maps style zoom control in the bottom right corner.

**Comment by fbarl** [comment]
+1 for google maps style zoom controls

Browser zooming also zooms into the graph on my Chrome, but I don't think we should have people think that's the right way to do graph zooming :)
