### ISSUE TITLE
pod details show all hosts as parents/related

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2323]
Each pod runs on a host. So it's very confusing that the 'parents' / 'related' links at the top of pod detail panels show links to multiple (all?) hosts:
![screenshot_2017-03-11_10-50-05](https://cloud.githubusercontent.com/assets/109109/23822641/be0f55be-0648-11e7-8d05-37939b1ec3c3.png)

**Comment by rade** [comment]
In the report obtained from the UI I see the following kind of parent entries for a pod:
```
        "parents": {
          "host": [
            "ip-172-20-1-230;<host>",
            "ip-172-20-1-68;<host>",
            "ip-172-20-2-110;<host>",
            "ip-172-20-2-118;<host>",
            "ip-172-20-2-90;<host>",
            "ip-172-20-3-211;<host>",
            "ip-172-20-3-76;<host>"
          ],
          "replica_set": [
            "01f02c9e-03fb-11e7-9b48-0a97ed59c75e;<replica_set>"
          ],
          "service": [
            "14e2fb54-a01e-11e6-921b-0a97ed59c75e;<service>"
          ]
```
(this is from an old report, so ignore the fact that the hostnames differ)

The question is why that lists all the hosts.

**Comment by rade** [comment]
I cannot work out where the host parents come from at all. [probe/kubernetes.Reporter.podTopology](https://github.com/weaveworks/scope/blob/v1.2.1/probe/kubernetes/reporter.go#L335 only appears to add replica set and service parents.

**Comment by 2opremio** [comment]
Where are you seeing this? It may be fixed by
https://github.com/weaveworks/scope/pull/2309

**Comment by rade** [comment]
I've looked at some reports and what appears to be happening is that a single pod shows up in reports from multiple probes - in one with complete details, and in the others w/o any details.

I reckon one reason for this behaviour is the code fixed in #2309, which isn't deployed in our clusters yet. That causes the reporter to include all pods in a node's report.

However, with that fix in place, I suspect the broken behaviour can still occur when we hit the fallback case for not being able to talk to the local kubelet.

Perhaps the host parents info for a pod should be determined by the host of its containers.

**Comment by rade** [comment]
Deploying #2309 to our dev cluster has indeed resolved the problem there.

So that just leaves the fallback case to worry about.

**Comment by 2opremio** [comment]
> Perhaps the host parents info for a pod should be determined by the host of its containers.

Good point, although a pod can exist without its containers existing (e.g. pull image error).

**Comment by rade** [comment]
>  a pod can exist without its containers existing

even w/o the 'pause' container?

**Comment by 2opremio** [comment]
Yes, probably the number of cases is narrower though.

**Comment by rade** [comment]
TBH, I don't think this issue is worth worrying about until we hear complaints from users. One would hope that most installs have access to the local kubelet and hence don't hit the fallback case.
