### ISSUE TITLE
hide k8s pause containers from k8s details

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2324]
It is really quite distracting to see the 'pause' processes / 'POD' containers that kubernetes adds to every pod.

A user can already hide them in the container topology by selecting the 'Application Containers' filter. But there is no way to omit them from container and process lists in the detail panels of pods, replica sets, deployments and services.

**Comment by 2opremio** [comment]
I have given some thought to this and I am not sure we should be treating them so specially (more so than other _system containers_).

It will feel strange to show them in the container topology (when system containers are enabled) and not show them in the detail panels.

That said, its true that their details don't add anything ...

**Comment by rade** [comment]
I should have added that I filed this issue based on user feedback (which I happen to agree with ;). Alas I also struggle to work out how exactly to achieve the desired outcome, given that we don't want to always hide the pause containers everywhere.

**Comment by 2opremio** [comment]
> I also struggle to work out how exactly to achieve the desired outcome

It's actually much easier than I thought, see #2338

**Comment by rade** [comment]
Right, but does it make sense? Or is it misleading?

**Comment by 2opremio** [comment]
Uhm, given than pause containers:
* Consume close to 0 resources
* Don't explicitly appear on the k8s graph/table view
* They also get filtered as system containers

I don't think it hurts.

To normalize it, we could add a Application/System selector to the k8s views  (like we have in the containers view) but I am not sure it's worth it.

**Comment by 2opremio** [comment]
> To normalize it, we could add an Application/System selector to the k8s views (like we have in the containers view) but I am not sure it's worth it.

Note that this would probably conflict with https://github.com/weaveworks/scope/issues/1423

**Comment by rade** [comment]
> I don't think it hurts.

Maybe. We are breaking @davkal's rules from #1864 here though, namely that filters do not apply to detail panels.

**Comment by 2opremio** [comment]
Then we (I) already completely broke it on https://github.com/weaveworks/scope/pull/1904

**Comment by rade** [comment]
> Then we (I) already completely broke it on #1904

on balance, I think I approve.
