### ISSUE TITLE
replica set scale up/down doesn't work

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2325]
I've just tried scaling up/down the query service replicas in Weave Cloud Dev by clicking on the +/- buttons in the details panel. I can see the "observed gen" increase by 2 - so some action is clearly being taken - but the pod count remains the same.

**Comment by rade** [comment]
Is there perhaps some magic daemon in our Weave Cloud install that undoes my change because it diverges from our k8s yamls?

**Comment by rade** [comment]
I think I've figured out why this is. The query service is part of a deployment. I am guessing that direct modification of the replica set is undone by the deployment. Increasing the replica count on the deployment itself works fine.

**Comment by 2opremio** [comment]
Yes, that's correct.
