### ISSUE TITLE
ebpf: fall back to proc parsing when we detect a late event

### ISSUE THREAD

**Issue by iaguis** [weaveworks/scope#2334]
There is a kernel bug introduced by https://github.com/torvalds/linux/commit/27727df240c7cc84f2ba6047c6f18d5addfd25ef (see [bcc's report](https://github.com/iovisor/bcc/issues/728)) that makes timestamps be wrong and results in messages like this in scope's logs:

```
<probe> ERRO: 2017/03/13 12:33:19.623907 ERROR: late event!
```

Moreover, this can result in `connect`events closely followed by `close` events to be in reverse order, causing the connection to never disappear from scope.

This bug was [introduced in 4.8](https://github.com/torvalds/linux/commit/27727df240c7cc84f2ba6047c6f18d5addfd25ef) but was backported to older kernels by distros. The fix was [included in 4.9](https://github.com/torvalds/linux/commit/58bfea9532552d422bde7afa207e1a0f08dffa7d#diff-03ab89da17a203808142f6a1f0272153) and also backported. For example, in Ubuntu, the bug [was introduced in kernel `4.4.0-42`](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1624037) and it's not fixed [until kernel `4.4.0-51`](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1634153).

We should fall back to proc parsing when we detect a late event.

cc @alban @schu

**Comment by 2opremio** [comment]
@alban has suggested offline:

> if it is reproducible, I would add logs to print the cpu number for both events..
>
> I would try to reproduce an issue with the tcptracer-bpf test program (without scope) in the dev environment with your kernel, using a script like https://github.com/weaveworks/scope/pull/2507#issuecomment-300735719 with different cpu# in different terminals
