### ISSUE TITLE
scope URLs do not restore context when copy-pasted

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2337]
I am quite sure this used to work...

1. fire up a local scope
2. find something interesting to look at, e.g. do a search in the table mode of the process topology
3. fire up an anonymous browser session
4. in that session, find something else to look at, eg. a do a different search, in the graph mode of the container view
5. copy-paste the URL from the first session over the 2nd session and hit return

Nothing happens.

By contrast, if you copy-paste the URL right after step 3, then the proper context is restored.

Perhaps the state stored in the cookie / elsewhere somehow takes precedence over the URL state?

The same problem occurs in Weave Cloud dev/prod.

**Comment by jpellizzari** [comment]
Most likely related to this commit: https://github.com/weaveworks/scope/commit/d77502079466624caff88fa1c60431f4e7bfcdcc#diff-7dc7875cc44ad2eec50c55c6932e6ec2
