### ISSUE TITLE
Warning/log messages about Weave Net not being found still need to be less alarming

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#2343]
Users remain confused by log messages in Scope about Weave Net not being found. e.g.

    WARN: 2016/12/19 15:38:33.465245 Cannot resolve 'scope.weave.local.': dial tcp 172.17.0.1:53: getsockopt: connection refused

Maybe it could be:

    Cannot resolve 'scope.weave.local.'; (the Scope web-app registers automatically in DNS if Weave Net is found).

Or something else that makes it less alarming for users.

**Comment by rade** [comment]
dup of #1726
