### ISSUE TITLE
Duplicated data returned in Scope /topology request

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/scope#2347]
To reproduce

1. Navigate to https://frontend.dev.weave.works/api/app/nameless-night-79/api/topology
2. Check out the JSON payload

Expected:
It shouldn't have so many topology options

Actual:
It has lots of duplicated `subtopology` options

Responses are ~40KB, which seems way high

**Comment by jpellizzari** [comment]
Link to an example response: https://files.slack.com/files-pri/T0928HEN4-F4LPWKFRD/download/scope.json

**Comment by jpellizzari** [comment]
Screenshot from response preview:
![screen shot 2017-03-17 at 11 37 58 am](https://cloud.githubusercontent.com/assets/2802257/24057878/3c68172c-0b06-11e7-84e6-cd0dc15b3de1.png)

**Comment by jpellizzari** [comment]
Possibly related to this (complete guess): https://github.com/weaveworks/scope/commit/76ddc75fb8180011202ab1494e722758b43d2a86

**Comment by rade** [comment]
The change got reverted in #2348. I've re-opened the associated issue #1504.
