### ISSUE TITLE
Specify nodeSelector as query param on Kubernetes installer

### ISSUE THREAD

**Issue by markmandel** [weaveworks/scope#2349]
On both weave cloud and standalone mode, when you run `kubectl apply -f 'https://cloud.weave.works/launch/k8s/weavescope.yaml'` there is no way to specify the nodeSelector via a query parameter - much like you can with version and Kubernetes service type.

This means that when you install weave scope on a cluster with more than one node pool, the Deployment could end in any of them (unless you manually download the file and edit it), which potentially could be bad - depending on what you are doing in your node pools.

My suggestion would be to have an optional query param of nodeSelector that you could pass a key value pair, separated by a `:` character. This would then add the `nodeSelector` section to the appropriate place in the nodePool.  To send multiple key values, separate by a comma `,`

For example:
`kubectl apply -f 'https://cloud.weave.works/launch/k8s/weavescope.yaml?nodeSelector=role:apps`

Or multiple:
`kubectl apply -f 'https://cloud.weave.works/launch/k8s/weavescope.yaml?nodeSelector=role:apps,version:1.0`

Not wedded to the implementation - but just wanted to provide an example to get started.

**Comment by 2opremio** [comment]
CC @errordeveloper

**Comment by 2opremio** [comment]
This issue was moved to weaveworks/launch-generator#77
