### ISSUE TITLE
two overlapping nodes, drawn at the same location

### ISSUE THREAD

**Issue by alban** [weaveworks/scope#2356]
In the screenshot above, the "googleapis" cloud and the "chrome" process overlap: they are drawn at the same location.

![image](https://cloud.githubusercontent.com/assets/27575/24103896/010b859c-0d81-11e7-9cbd-2bfe43a6d9d1.png)

I don't know how to reproduce. I was looking at the UI while processes appear and disappear. This gets fixed when clicking on the "force re-layout" button.

**Comment by rade** [comment]
Seems vaguely similar to #1450.

**Comment by fbarl** [comment]
> Seems vaguely similar to #1450.

Now the problem seems to occur only with added external connection nodes - probably a duplicate of #2261.
