### ISSUE TITLE
Re-implement contrast mode

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/scope#2363]
Currently, Scope relies on loading a second stylesheet with overridden Sass variables to show a high-contrast mode. This works well for stand-alone, but it difficult to deal with when running as a component. 

Instead of a second stylesheet, we should create a wrapper CSS class with the necessary style overrides. Then, to enable contrast mode, we switch the class that is applied to the Scope root DOM element. This is generally how 'theme-ing' is implemented. 

Benefits:
* Less `webpack` shenanigans
* Theme switches immediately (no network call needed)

**Comment by fbarl** [comment]
This was resolved in #3580.
