### ISSUE TITLE
Static assets failed to load

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/scope#2367]
Vendors chunk failed to load with a 403:
`https://s3.amazonaws.com/static.weave.works/scope-ui/vendors-347ca389e66f1d4b7ba7.js?881b7f6d9790e78d185e `

**Comment by awh** [comment]
Offending build: master-2a61656 https://circleci.com/gh/weaveworks/scope/6830

For some reason the uploaded vendors.js doesn't match:

```
upload: client/build-external/vendors-1e4f85cd2fcebb5a6473.js to s3://static.weave.works/scope-ui/vendors-1e4f85cd2fcebb5a6473.js
```

**Comment by jpellizzari** [comment]
My theory is that Circle used the assets from cache instead of building them.

**Comment by jpellizzari** [comment]
It looks like the root cause is the `build-external` directory getting pushed, when assets were built in the `build` directory.

**Comment by jpellizzari** [comment]
We have an open issue to move to a different package manager that should give us deterministic builds:

https://github.com/weaveworks/scope/issues/2090

The main difference is that `yarn` uses a lockfile checked into version control to ensure that whatever versions are used to build locally are used to build in CI.
