### ISSUE TITLE
Integration test 311 shows failures in eBPF tracker initialization

### ISSUE THREAD

**Issue by alban** [weaveworks/scope#2379]
The integration test `integration/311_container_to_container_edge_with_ebpf_test.sh` sometimes fails.

Example: https://circleci.com/gh/weaveworks/scope/6881

The ebpf offset guessing work fails at different steps. Examples:

> <probe> WARN: 2017/03/23 07:37:09.109943 Error setting up the eBPF tracker, falling back to proc scanning: failed to init perf map for IPv4 events: error guessing offsets: in valid guessing state while guessing source port, got checking expected checked, status.offset_saddr: 4

> <probe> WARN: 2017/03/23 08:33:39.356490 Error setting up the eBPF tracker, falling back to proc scanning: failed to init perf map for IPv4 events: error guessing offsets: in valid guessing state while guessing destination address IPv6, got checking expected checked, status.offset_saddr: 4

So far, only reproducible on CircleCI by repetitively run the tests.

Some more details in https://github.com/weaveworks/tcptracer-bpf/pull/30

**Comment by iaguis** [comment]
This is fixed by #2411. We can close it now.
