### ISSUE TITLE
Implement a graphical, (slightly) animated version of Kubernetes Network Policy

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2381]
_From @abuehrle on March 7, 2017 23:8_

It would be very useful if you could graphically see your network policy live without having to manually do so: 

1. Create a test mode that can be launched and reads your .yaml file and graphically shows you where your policy has been implemented so that you can see if it works as expected. 
2. A 'standard' mode that shows which containers can talk to what and which nodes, microservices are blocked.
3. Ability to set up network policy from the UI, instead of having to edit the very fiddly .yaml. file in which to do so.  

_Copied from original issue: weaveworks/service-ui#319_

**Comment by 2opremio** [comment]
_From @jpellizzari on March 11, 2017 0:20_

@abuehrle Is the info to support this UI already available from one of our existing services? Wouldn't this be a feature of Scope's Kubernetes integration?

**Comment by 2opremio** [comment]
_From @abuehrle on March 11, 2017 3:24_

This is a good point @jpellizzari and I put it in here because this is a private repo.  Please move the issue as you see what's best  @pidster @lukemarsden @rade

**Comment by 2opremio** [comment]
_From @rade on March 23, 2017 11:29_

@2opremio please move this to weaveworks/scope

**Comment by rade** [comment]
dup of #1778.
