### ISSUE TITLE
View mode selector not responding well to resize

### ISSUE THREAD

**Issue by fbarl** [weaveworks/scope#2396]
<img width="1160" alt="screen shot 2017-03-25 at 10 43 06 am" src="https://cloud.githubusercontent.com/assets/1216874/24322275/4c908ffc-1160-11e7-8212-a6b527ffdae8.png">

**Comment by 2opremio** [comment]
I still see this in Weave Cloud

**Comment by 2opremio** [comment]
<img width="920" alt="screen shot 2017-04-25 at 18 48 01" src="https://cloud.githubusercontent.com/assets/2362916/25397266/06844620-29e8-11e7-91ca-d4a63de91ef4.png">

**Comment by fbarl** [comment]
Yeah, so the issue has been fixed on master, but since nobody updated the Scope UI version `package.json` of *service-ui* for a several weeks now, the changes haven't been propagated to Weave Cloud yet.

I created https://github.com/weaveworks/service-ui/pull/481 just for that, but I wonder what our general issue closing policy should be now that the two things are separate (and can happen with a significant time diff)?
