### ISSUE TITLE
Pods number doesn't update on scale up or scale down

### ISSUE THREAD

**Issue by bboreham** [weaveworks/scope#2401]
When I press the + or - (scale up or scale down) buttons, the number in the topology doesn't update until I press refresh.

See picture below: on the right it says "# PODS: 2" while on the left it says "3 pods".

![image](https://cloud.githubusercontent.com/assets/8125524/24363085/9ccfcba2-1306-11e7-9363-a2ed5ebbf822.png)

**Comment by 2opremio** [comment]
Must be a UI state problem

**Comment by rade** [comment]
@bboreham reports that the number on the main canvas remains wrong even after closing the detail panel.

@rndstr has reproduced the problem.

As @2opremio says, this most certainly is a UI issue. To check, retrieve the controller topology with something like
```
curl -s http://localhost:4040/api/topology/kube-controllers | jq -S '.' > controllers.json
```
and look at the counts contained in that.
