### ISSUE TITLE
Download report as JSON button does not work

### ISSUE THREAD

**Issue by ekimekim** [weaveworks/scope#2402]
Steps to reproduce:

* Go to a scope instance on cloud.weave.works
* Press the bug icon in the lower right
* Press `Save raw data as JSON`

Expected:

The report JSON is downloaded as file `report.json`

Actual:

The cloud.weave.works index.html file is downloaded as `report.html`

Tested on Chromium 57.0.2987.110

Details:

The link given by the button (as seen with 'copy link address') is `https://cloud.weave.works/app/api/report`, which is not a valid endpoint for cloud.weave.works - it should contain an instance name. The backend is serving index.html as this is its default response (related: we should really serve proper 404s at some point).

**Comment by jpellizzari** [comment]
Closed by #2403
