### ISSUE TITLE
Running vs Stopped Containers not filtering properly in Container DNS View

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2427]
Flipping between stopped and running in Containers by DNS Name is not filtering correctly. 

See: 

http://recordit.co/abC1ErxpSi

**Comment by fbarl** [comment]
I wonder if it's part of the same filtering logic I touched in https://github.com/weaveworks/scope/pull/2244.

**Comment by 2opremio** [comment]
Yep, I was going to say that. I didn't start looking at it yet, so feel free.

**Comment by rade** [comment]
dup of #2603 (filed later but has more info).
