### ISSUE TITLE
Audit test files for proper packages

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#244]
In general, foo_test.go should be in package pkg_test, with an exception when you're testing package/component internals of an especially complex package. This ticket is to audit all _test.go files for compliance, and make fixes as appropriate.

**Comment by tomwilkie** [comment]
We could add something to the linter to enforce this rule...

**Comment by peterbourgon** [comment]
Interesting idea. We still want to allow exceptions, so maybe the easiest implementation would be based on filename, i.e.

- `*_internal_test.go` must be `package foo`
- Remaining `*_test.go` must be `package foo_test`

**Comment by tomwilkie** [comment]
Sounds like a plan.

**Comment by tomwilkie** [comment]
We should discuss the policy of tests having to live in foo_test packages.  It means you have to expose in the public API of a package all the mocking stubs, for instance.

**Comment by peterbourgon** [comment]
Yes, when that's easy I think we should do it, when it's exposing too many internals I think it's fine to do a foo_internal_test.go in package foo. Just a judgment call, with a preference for the former.

**Comment by peterbourgon** [comment]
Closed by #292
