### ISSUE TITLE
enable ebpf connection tracking by default

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2441]
Currently the ebpf connection tracking from #2135 needs to be enabled explicitly with `--probe.ebpf.connections=true`. Once we have gained some confidence in the correctness and stability of this feature, we should enable it by default.

**Comment by 2opremio** [comment]
We should probably fix this https://github.com/weaveworks/tcptracer-bpf/issues/10 first though

**Comment by alban** [comment]
https://github.com/weaveworks/tcptracer-bpf/issues/10 is fixed now

**Comment by 2opremio** [comment]
Then I think we can finally go ahead enable it by default.

It won't be released until 1.5.0 though. I am cutting the 1.4.0 release soon (in 1 or 2 days) and I find it premature without further testing (i.e. having it enabled in master for a while).

We need to be careful about the integration tests when enabling eBPF by default. They should verify the fall back and old behaviour (`/proc` connection walking). So, we may need to incorporate a couple of integration tests and/or explicitly disable eBPF in a few in the existing ones
