### ISSUE TITLE
[Kubernetes 1.6] Container network traffic visualisations don't display

### ISSUE THREAD

**Issue by markmandel** [weaveworks/scope#2446]
When running weave scope on Kubernetes 1.6, the network traffic visualisations on the containers view are no longer working.

From the logs off the `weave-scope-app` I see:

```
<app> INFO: 2017/04/15 16:43:26.635507 app starting, version 1.3.0, ID 564c01605bb11971
<app> INFO: 2017/04/15 16:43:26.635745 command line args: --logtostderr=true --mode=app --no-probe=true
<app> INFO: 2017/04/15 16:43:26.671230 listening on :4040
<app> WARN: 2017/04/15 16:43:26.683007 Error updating weaveDNS, backing off 20s: Error running weave ps: exit status 1: "Link not found\n"
<app> WARN: 2017/04/15 16:43:46.703942 Error updating weaveDNS, backing off 40s: Error running weave ps: exit status 1: "Link not found\n"
<app> WARN: 2017/04/15 16:44:26.723912 Error updating weaveDNS, backing off 1m0s: Error running weave ps: exit status 1: "Link not found\n"
```

Grabbing the logs from an agent I see:

```
time="2017-04-15T16:42:45Z" level=info msg="publishing to: 10.19.249.77:80"
<probe> INFO: 2017/04/15 16:42:45.690501 command line args: --logtostderr=true --mode=probe --no-app=true --probe.docker=true --probe.docker.bridge=docker0 --probe.kubernetes=true 10.19.249.77:80
<probe> INFO: 2017/04/15 16:42:45.690543 probe starting, version 1.3.0, ID 4500079cdd033e05
<probe> INFO: 2017/04/15 16:42:45.702513 kubernetes: targeting api server https://10.19.240.1:443
<probe> ERRO: 2017/04/15 16:42:45.735635 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
<probe> ERRO: 2017/04/15 16:42:45.743370 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
<probe> WARN: 2017/04/15 16:42:45.766036 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> WARN: 2017/04/15 16:42:45.781844 Cannot resolve 'scope.weave.local.': dial tcp 169.254.123.1:53: getsockopt: connection refused
<probe> INFO: 2017/04/15 16:42:45.782096 Success collecting weave proxy status
<probe> INFO: 2017/04/15 16:42:45.782525 Success collecting weave plugin status
<probe> WARN: 2017/04/15 16:42:45.808085 Error collecting weave ps, backing off 20s: exit status 1: "Link not found\n"
<probe> INFO: 2017/04/15 16:42:46.696665 Control connection to 10.19.249.77 starting
<probe> INFO: 2017/04/15 16:42:48.783218 Publish loop for 10.19.249.77 starting
<probe> WARN: 2017/04/15 16:42:55.766755 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> WARN: 2017/04/15 16:43:05.842870 Error collecting weave ps, backing off 40s: exit status 1: "Link not found\n"
<probe> WARN: 2017/04/15 16:43:15.767369 Error collecting weave status, backing off 40s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> ERRO: 2017/04/15 16:43:25.986164 Error doing controls for 10.19.249.77, backing off 1s: dial tcp 10.19.249.77:80: getsockopt: connection refused
<probe> INFO: 2017/04/15 16:43:31.706384 Control connection to 10.19.249.77 starting
<probe> INFO: 2017/04/15 16:43:31.706775 Publish loop for 10.19.249.77 exiting
<probe> INFO: 2017/04/15 16:43:31.707659 Control connection to 10.19.249.77 exiting
<probe> INFO: 2017/04/15 16:43:33.790490 Publish loop for 10.19.249.77 starting
<probe> WARN: 2017/04/15 16:43:45.877888 Error collecting weave ps, backing off 1m0s: exit status 1: "Link not found\n"
<probe> WARN: 2017/04/15 16:43:55.768032 Error collecting weave status, backing off 1m0s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
```

**Comment by markmandel** [comment]
So the title of this bug is misleading, since I just tested on 1.5.6, and the SAME errors display in the logs, however, it DOES display the visualisation of network traffic between pods - so I changed it. Looks like the errors messages in the logs may be a red herring. Not sure.

I have yet to check on 1.6.1 (Only 1.6.0).

(Image for reference - it's the gray lines that don't show when running a 1.6 cluster)
![screenshot from 2017-04-15 15 17 27](https://cloud.githubusercontent.com/assets/298370/25067113/ab5edb30-21ee-11e7-8509-5c4d19038678.png)

**Comment by 2opremio** [comment]
The Weave Net warnings are harmless unless you are using Weave Net for networking (in fact you are encouraged to run scope with `--weave=false` if you are no using Weave Net).

Regarding the lack of edges, could you export a JSON report? (Bug icon on the bottom right of the screen -> `</>` button). Bear in mind this report contains command line arguments and env variables so please elide any secrets before sharing (or share the report privately).

Regarding the lack of edges:
1. Do edges show in the process or container views?
2. Do edges show for any processes/containers/pods?
3. Did you confirm there is an actual TCP connection between the pods? (It would help if you could share the relevant line from the output of exec'ing `netstat -tn` on any two connected pods missing an edge).

**Comment by 2opremio** [comment]
Lastly, it may be worth trying to run the scope agents (probes) with `--probe.ebpf.connections=true`

**Comment by bboreham** [comment]
I suspect it's because the probe is not running in the host pid space, because of https://github.com/kubernetes/kubernetes/issues/44041

Fixed in Kubernetes 1.6.2

**Comment by rade** [comment]
> Fixed in Kubernetes 1.6.2

which isn't out yet :(

**Comment by 2opremio** [comment]
`--probe.ebpf.connections=true` _may_ be able to work around it since the PIDs are extracted directly from the kernel.

**Comment by 2opremio** [comment]
(for the connections that is, other things like the CPU/memory consumption of processes won't​ work)

**Comment by 2opremio** [comment]
@markmandel Could you please try with [kubernetes 1.6.2](https://github.com/kubernetes/kubernetes/releases/tag/v1.6.2) ?

**Comment by markmandel** [comment]
Will do once it hits GKE, and I have access to it.

**Comment by markmandel** [comment]
Just tested in 1.6.2 - all back to working again!

Closing the ticket.
