### ISSUE TITLE
Capture connections that traverse Docker port mapping

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#245]
Follow on from #227, the work here is to capture the fact that a process in a container can listen to e.g. port 80, but be accessible to other processes as e.g. port 23456.

**Comment by tomwilkie** [comment]
We have the port remapping info in the docker tagger.  We could have the docker tagger mutate the endpoints graph to remove the port remapping, but that makes me shiver.

How else might we solve this?

**Comment by peterbourgon** [comment]
The docker "tagger" could add endpoints to the endpoint topology, rather than mutate existing endpoints.

**Comment by tomwilkie** [comment]
Here is a report that exhibits the problem:

https://gist.github.com/tomwilkie/694df9bcc650b38141b1

(The weaver process are being port remapped)

**Comment by tomwilkie** [comment]
Lets setup some terminology:
- weaver1 is pid 19499 on host twilkie-test-1
- weaver2 is pid 31401 on host twilkie-test-2
- weaver1 has ip 172.17.0.12 on the docker bridge
- weaver2 has ip 172.17.0.1 on the docker bridge
- weaver2 is connected to weaver1

```
">;172.17.0.12;6783" -> ";10.240.240.51;58906"
">;172.17.0.1;58906" -> ";10.240.81.226;6783"
```

The real adjacency should be:
```
">;172.17.0.1;58906" -> ";172.17.0.12;6783"
```

Also note ips on the docker bridge can be the same on different hosts, so will need scoping (#265)

**Comment by tomwilkie** [comment]
so what we're seeing is:
```
weaver1:6783 -> twilkie-test-2:58906
weaver2:58906 -> twilkie-test-1:6783
```
My worry is that neither probe has enough information to resolve this, as they don't know about port mappings on other hosts.  Each host could emit port mapping as part of the topology:
```
twilkie-test-1:6783 -> weaver1:6783
twilkie-test-2:6783 -> weaver1:6783
```
Which would give you the connection in one direction at least:
```
weaver1:6783 -> twilkie-test-2:58906
weaver2:58906 -> twilkie-test-1:6783 -> weaver1:6783
```
I wonder if its coincidence that the client ports for weave2 and twilkie-test-2 are the same.  If that how NAT works?

**Comment by tomwilkie** [comment]
Given that the probes don't have enough information to rewrite the reports they emit, we could emit a remapping table with the reports, and have a remapping step in the app.  The remapping table would basically be the contents of the NAT table.

**Comment by tomwilkie** [comment]
We can get the contents of the NAT table for destination ports:
```
vagrant@twilkie-test-2:~$ sudo iptables -t nat -L DOCKER
Chain DOCKER (2 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             anywhere             tcp dpt:6783 to:172.17.0.1:6783
DNAT       udp  --  anywhere             anywhere             udp dpt:6783 to:172.17.0.1:6783
DNAT       udp  --  anywhere             172.17.42.1          udp dpt:domain to:172.17.0.2:53
```

How do we get it for client ports?

**Comment by tomwilkie** [comment]
this does it:
```
vagrant@twilkie-test-2:~$ sudo conntrack -L
tcp      6 111 TIME_WAIT src=10.240.240.51 dst=91.189.92.200 sport=54642 dport=80 src=91.189.92.200 dst=10.240.240.51 sport=80 dport=54642 [ASSURED] mark=0 use=1
tcp      6 431970 ESTABLISHED src=10.240.240.51 dst=169.254.169.254 sport=57933 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57933 [ASSURED] mark=0 use=1
udp      17 5 src=10.160.0.0 dst=224.0.0.251 sport=54442 dport=5353 [UNREPLIED] src=224.0.0.251 dst=10.160.0.0 sport=5353 dport=54442 mark=0 use=1
tcp      6 85 TIME_WAIT src=10.240.240.51 dst=169.254.169.254 sport=57921 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57921 [ASSURED] mark=0 use=1
tcp      6 30 TIME_WAIT src=10.240.240.51 dst=169.254.169.254 sport=57923 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57923 [ASSURED] mark=0 use=1
tcp      6 432000 ESTABLISHED src=37.157.33.76 dst=10.240.240.51 sport=23341 dport=22 src=10.240.240.51 dst=37.157.33.76 sport=22 dport=23341 [ASSURED] mark=0 use=1
udp      17 2 src=172.17.42.1 dst=172.17.42.1 sport=37991 dport=53 src=172.17.0.2 dst=172.17.42.1 sport=53 dport=37991 mark=0 use=1
udp      17 179 src=10.240.240.51 dst=169.254.169.254 sport=57239 dport=53 src=169.254.169.254 dst=10.240.240.51 sport=53 dport=57239 [ASSURED] mark=0 use=1
tcp      6 90 TIME_WAIT src=10.240.240.51 dst=169.254.169.254 sport=57932 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57932 [ASSURED] mark=0 use=1
tcp      6 90 TIME_WAIT src=10.240.240.51 dst=169.254.169.254 sport=57931 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57931 [ASSURED] mark=0 use=1
udp      17 161 src=10.240.240.51 dst=169.254.169.254 sport=48107 dport=53 src=169.254.169.254 dst=10.240.240.51 sport=53 dport=48107 [ASSURED] mark=0 use=1
tcp      6 431970 ESTABLISHED src=10.240.240.51 dst=169.254.169.254 sport=57928 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57928 [ASSURED] mark=0 use=1
udp      17 2 src=10.160.0.0 dst=224.0.0.251 sport=59799 dport=5353 [UNREPLIED] src=224.0.0.251 dst=10.160.0.0 sport=5353 dport=59799 mark=0 use=1
tcp      6 431989 ESTABLISHED src=172.17.0.1 dst=10.240.81.226 sport=58906 dport=6783 src=10.240.81.226 dst=10.240.240.51 sport=6783 dport=58906 [ASSURED] mark=0 use=1
tcp      6 431999 ESTABLISHED src=127.0.0.1 dst=127.0.0.1 sport=59539 dport=4030 src=127.0.0.1 dst=127.0.0.1 sport=4030 dport=59539 [ASSURED] mark=0 use=1
udp      17 2 src=172.17.42.1 dst=172.17.42.1 sport=54938 dport=53 src=172.17.0.2 dst=172.17.42.1 sport=53 dport=54938 mark=0 use=1
tcp      6 34 CLOSE_WAIT src=10.240.240.51 dst=10.240.240.51 sport=44974 dport=4030 src=10.240.240.51 dst=10.240.240.51 sport=4030 dport=44974 [ASSURED] mark=0 use=1
tcp      6 20 TIME_WAIT src=10.240.240.51 dst=169.254.169.254 sport=57914 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57914 [ASSURED] mark=0 use=1
tcp      6 90 TIME_WAIT src=10.240.240.51 dst=169.254.169.254 sport=57930 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57930 [ASSURED] mark=0 use=1
tcp      6 30 TIME_WAIT src=10.240.240.51 dst=169.254.169.254 sport=57919 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57919 [ASSURED] mark=0 use=2
udp      17 20 src=10.240.240.51 dst=169.254.169.254 sport=58085 dport=53 src=169.254.169.254 dst=10.240.240.51 sport=53 dport=58085 mark=0 use=1
tcp      6 30 TIME_WAIT src=10.240.240.51 dst=169.254.169.254 sport=57924 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57924 [ASSURED] mark=0 use=1
udp      17 2 src=172.17.42.1 dst=172.17.42.1 sport=49129 dport=53 src=172.17.0.2 dst=172.17.42.1 sport=53 dport=49129 mark=0 use=1
tcp      6 30 TIME_WAIT src=10.240.240.51 dst=169.254.169.254 sport=57925 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57925 [ASSURED] mark=0 use=1
udp      17 2 src=10.128.0.1 dst=224.0.0.251 sport=34499 dport=5353 [UNREPLIED] src=224.0.0.251 dst=10.128.0.1 sport=5353 dport=34499 mark=0 use=1
tcp      6 431999 ESTABLISHED src=10.240.81.226 dst=10.240.240.51 sport=37596 dport=4030 src=10.240.240.51 dst=10.240.81.226 sport=4030 dport=37596 [ASSURED] mark=0 use=1
tcp      6 431999 ESTABLISHED src=10.240.240.51 dst=10.240.81.226 sport=60276 dport=4030 src=10.240.81.226 dst=10.240.240.51 sport=4030 dport=60276 [ASSURED] mark=0 use=1
udp      17 169 src=10.240.240.51 dst=169.254.169.254 sport=50182 dport=53 src=169.254.169.254 dst=10.240.240.51 sport=53 dport=50182 [ASSURED] mark=0 use=1
udp      17 115 src=10.240.240.51 dst=169.254.169.254 sport=48463 dport=53 src=169.254.169.254 dst=10.240.240.51 sport=53 dport=48463 [ASSURED] mark=0 use=1
udp      17 178 src=172.17.0.1 dst=10.240.81.226 sport=6783 dport=6783 src=10.240.81.226 dst=10.240.240.51 sport=6783 dport=6783 [ASSURED] mark=0 use=1
udp      17 5 src=10.128.0.1 dst=224.0.0.251 sport=56106 dport=5353 [UNREPLIED] src=224.0.0.251 dst=10.128.0.1 sport=5353 dport=56106 mark=0 use=1
tcp      6 90 TIME_WAIT src=10.240.240.51 dst=169.254.169.254 sport=57926 dport=80 src=169.254.169.254 dst=10.240.240.51 sport=80 dport=57926 [ASSURED] mark=0 use=1
conntrack v1.4.2 (conntrack-tools): 32 flow entries have been shown.
```

**Comment by tomwilkie** [comment]
Having slept on it, I think the we should
- add a Remapping field of type map[string]string to the Topology struct
- this field should contain a mapping from Node ID -> Node ID
- have the spy code emit this remapping when it builds the endpoint topology, by using conntrack data
- in the app, when the lifo produces a report,

**Comment by tomwilkie** [comment]
This does the filtering for us:
```
vagrant@twilkie-test-1:~$ sudo conntrack -L --dst-nat
udp      17 10 src=172.17.42.1 dst=172.17.42.1 sport=56524 dport=53 src=172.17.0.13 dst=172.17.42.1 sport=53 dport=56524 mark=0 use=1
udp      17 10 src=172.17.42.1 dst=172.17.42.1 sport=56518 dport=53 src=172.17.0.13 dst=172.17.42.1 sport=53 dport=56518 mark=0 use=1
udp      17 10 src=172.17.42.1 dst=172.17.42.1 sport=46441 dport=53 src=172.17.0.13 dst=172.17.42.1 sport=53 dport=46441 mark=0 use=1
udp      17 174 src=10.240.240.51 dst=10.240.81.226 sport=6783 dport=6783 src=172.17.0.12 dst=10.240.240.51 sport=6783 dport=6783 [ASSURED] mark=0 use=1
tcp      6 431994 ESTABLISHED src=10.240.240.51 dst=10.240.81.226 sport=58906 dport=6783 src=172.17.0.12 dst=10.240.240.51 sport=6783 dport=58906 [ASSURED] mark=0 use=1
conntrack v1.4.2 (conntrack-tools): 5 flow entries have been shown.
```
I wonder if we can have https://github.com/typetypetype/conntrack do that too?

**Comment by peterbourgon** [comment]
AFAIK, conntrack is a kernel module, not reliably present. Do you have some numbers about its availability?

**Comment by tomwilkie** [comment]
I don't I'm afraid. I'll see if I can find some. We could always fall back
to iptables / docker port mapping so, but unfortunately that will only
solve one half of the problem (the server port remapping, not the client
port). That will be enough to make the connection appear in the ui, in one
direction.

Other than that, general approach sound sane? Can you think of other ways
of doing it?

**Comment by peterbourgon** [comment]
Watching conntrack is like looking at the effect of the mapping. The other way, I guess, is looking at the source — querying the Docker daemon for its active port mappings. Then you can annotate existing endpoint node metadata with mapped port(s).

**Comment by tomwilkie** [comment]
The challenge there is that docker doesn't know about the client port
remapping - that's just at Linux nat at work.

But more generally, assuming we have a source for the mapping info, are you
happy with the approach of including this in the topology (as a remapping
field) and having the app do the remapping?

**Comment by peterbourgon** [comment]
I'm very hesitant to +1 a change to the topology struct. It means the topology is not actually correct/usable until remap is invoked, which is going to have lots of consequences, many of them subtle. I don't (yet) understand why you can't "flatten" the remapping within the probe, before emitting the report. Can you explain why you prefer your solution?

**Comment by tomwilkie** [comment]
The problem is, from the probes POV, it's the remote end of the connection
that needs remapping, and he doesn't have enough information to do that.
Hence he can emit he remapping info for other connections to be remapped,
but it has to be the guys who seems the combination of the two that can do
the remapping.

Does that make sense? I don't prefer this solution, I just can't think of
any other way.

**Comment by peterbourgon** [comment]
Here's my understanding. Please correct mis-statements.

Given

```
+------------------host1-+     +-host2------------------+
|+-container1-+          |     |          +-container2-+|
||     :1234--|--:23456--|-----|--:34567--|--:80       ||
|+------------+          |     |          +------------+|
|    +-scope1-+          |     |          +-scope2-+    |
|    |        |          |     |          |        |    |
|    +--------+          |     |          +--------+    |
+------------------------+     +------------------------+
```

scopes see TCP 4-tuples (host1_ip 23456 host2_ip 34567) and (host2_ip 34567 host1_ip 23456) and create nodes (host1_ip 23456) and (host2_ip 34567).

You're proposing to amend the topology with something like 

```
scope1: (host1_ip 23456) -> (container1_ip 1234)
scope2: (host2_ip 34567) -> (container2_ip 80)
```

I'm suggesting we can do the same thing without modifying data structures by instead creating new, effectively duplicate, endpoint nodes

```
scope1: (container1_ip 1234): {metadata copied from (host1_ip 23456)}
scope2: (container2_ip 80):   {metadata copied from (host2_ip 34567)}
```

Correlation can then occur normally.

If we want to declare that 2 (or more) concrete nodes actually represent the same logical node — which I'm not sure we actually need to do — we could link them together through a foreign (more like local) key in their node metadatas. 

- Will this work?
- Will this work, but you prefer the other way?
- Will this not work at all?

**Comment by tomwilkie** [comment]
Yes thats sounds like it will work; I think copying the node metadata is more than enough (as the render logic will merge them as they get rolled up).

I think we should use conntrack data as the docker port remapping doesn't have client-port info, and it would also make the solution non-docker specific.

**Comment by automaticgiant** [comment]
@tomwilkie what else needs to happen to support non-dockerized workloads?
