### ISSUE TITLE
Tasks in ECS are not communicating with Scope

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2481]
To reproduce: install using the AWS cloudformation template

Tasks & Services appear, but when you click on a Task, the details panel says it's not communicating (did this work before?)

<img width="1207" alt="screen shot 2017-04-27 at 9 02 52 am" src="https://cloud.githubusercontent.com/assets/13420383/25487115/e9589a8c-2b28-11e7-9fcd-a2b3f6e957b1.png">

**Comment by 2opremio** [comment]
> did this work before?

Yes, does it happen with all the tasks? It could be that that particular task died or was removed.

**Comment by abuehrle** [comment]
All four tasks in my view had the same result.

**Comment by 2opremio** [comment]
@abuehrle Can you send me the report?

**Comment by 2opremio** [comment]
Also, does it happen with Scope 1.3.0 or just in master?

**Comment by 2opremio** [comment]
Duplicate of https://github.com/weaveworks/scope/issues/2484 ?

**Comment by abuehrle** [comment]
Was that created after I logged this one?  It looks like.

**Comment by 2opremio** [comment]
That one is more complete though.

@abuehrle Can you try to reproduce with `:latest` and see if the problem is gone?

**Comment by abuehrle** [comment]
Not seeing this issue in this release.
