### ISSUE TITLE
Pseudo nodes are unclickable

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#249]
Is this intentional?

**Comment by davkal** [comment]
> we don't have any NodeMetadata for them, so nothing to render in the side panel

This was also my reasoning. Nothing to see there.
Under which circumstances is there any meta data?

**Comment by tomwilkie** [comment]
Pseudo nodes in the containers view have a ton of metadata.

**Comment by peterbourgon** [comment]
By definition pseudonodes are nodes we have to invent because we have them as a destination in an edge, but don't have any other data (metadata) for them. If a node has metadata, by definition it is not a pseudonode.

**Comment by tomwilkie** [comment]
Are you suggesting uncontained should not be a pseudo node?

Note that even under you definition, we still have useful info we should
show the user - for instance, the Internet pseudo node has a mass be list
of ip addresses we could show, and other pseudo nodes has port numbers we
could show.

**Comment by peterbourgon** [comment]
Agh, uncontained. Right. For the record, we're abusing the pseudo flag for that one.

But, point taken. There's always going to be *some* information we can display, actually.

**Comment by davkal** [comment]
Which nodes in which topologies do not have any data?

I'm asking because we could show an actionable message like *install a probe* in the details panel in that case.

**Comment by tomwilkie** [comment]
Not much in the process topology to show.  And "the internet" never has any info.  Really its only the uncontained node that has meaningful info I think.  OTOH paul's recent connections stuff might work for all pseudo nodes...
