### ISSUE TITLE
Scope Agent not showing up on Master and Pod View not appearing

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2500]
Ubuntu: 10.04
Version: 

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:22:08Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

I set up a kubernetes cluster on DO and launched the agents with this command (which is in the UI presently): 

```
kubectl apply -n kube-system -f \
  "https://cloud.weave.works/k8s.yaml?t=XXX-version=$(kubectl version | base64 | tr -d '
')"
```
More information after running that command: 

```
kubectl apply -n kube-system -f \
>    https://cloud.weave.works/k8s/scope?service-token=XXXX-version=$(kubectl version | base64 | tr -d '\n')
[1] 6422
serviceaccount "weave-scope" created
daemonset "weave-scope-agent" created
k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI2IiwgR2l0VmVyc2lvbjoidjEuNi4yIiwgR2l0Q29tbWl0OiI0NzdlZmMzY2JlNmE3ZWZmY2EwNmJkMTQ1MmZhMzU2ZTIyMDFlMWVlIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0wNC0xOVQyMDozMzoxMVoiLCBHb1ZlcnNpb246ImdvMS43LjUiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjYiLCBHaXRWZXJzaW9uOiJ2MS42LjIiLCBHaXRDb21taXQ6IjQ3N2VmYzNjYmU2YTdlZmZjYTA2YmQxNDUyZmEzNTZlMjIwMWUxZWUiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE3LTA0LTE5VDIwOjIyOjA4WiIsIEdvVmVyc2lvbjoiZ28xLjcuNSIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJsaW51eC9hbWQ2NCJ9Cg==: command not found
[1]+  Done                    kubectl apply -n kube-system -f https://cloud.weave.works/k8s/scope?service-token=XXXXX
```

And only two scope agents showed up: 
```
kubectl get pods --all-namespaces
NAMESPACE     NAME                                READY     STATUS    RESTARTS   AGE
kube-system   etcd-master-01                      1/1       Running   0          9h
kube-system   kube-apiserver-master-01            1/1       Running   0          9h
kube-system   kube-controller-manager-master-01   1/1       Running   0          9h
kube-system   kube-dns-3913472980-cxd12           3/3       Running   0          9h
kube-system   kube-proxy-4hjp3                    1/1       Running   0          9h
kube-system   kube-proxy-76jr4                    1/1       Running   0          9h
kube-system   kube-proxy-wgfqx                    1/1       Running   0          9h
kube-system   kube-scheduler-master-01            1/1       Running   0          9h
kube-system   weave-net-6k4bc                     2/2       Running   1          9h
kube-system   weave-net-fqh32                     2/2       Running   1          9h
kube-system   weave-net-rkbgk                     2/2       Running   0          9h
kube-system   weave-scope-agent-5x4xk             1/1       Running   0          9h
kube-system   weave-scope-agent-cng7r             1/1       Running   0          9h
```

**Comment by 2opremio** [comment]
@abuehrle Can you get us the logs of the agent pods? e.g.:

```
kubectl logs --namespace=kube-system weave-scope-agent-5x4xk 
```

**Comment by 2opremio** [comment]
@abuehrle Are any other k8s views showing up?

**Comment by 2opremio** [comment]
Oh, it seems that something went wrong when you passed the k8s version to the launch generator:

```
k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI2IiwgR2l0VmVyc2lvbjoidjEuNi4yIiwgR2l0Q29tbWl0OiI0NzdlZmMzY2JlNmE3ZWZmY2EwNmJkMTQ1MmZhMzU2ZTIyMDFlMWVlIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0wNC0xOVQyMDozMzoxMVoiLCBHb1ZlcnNpb246ImdvMS43LjUiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjYiLCBHaXRWZXJzaW9uOiJ2MS42LjIiLCBHaXRDb21taXQ6IjQ3N2VmYzNjYmU2YTdlZmZjYTA2YmQxNDUyZmEzNTZlMjIwMWUxZWUiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE3LTA0LTE5VDIwOjIyOjA4WiIsIEdvVmVyc2lvbjoiZ28xLjcuNSIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJsaW51eC9hbWQ2NCJ9Cg==: command not found
```

**Comment by 2opremio** [comment]
Please try again, while quoting correctly the url, that is `"https://cloud.weave.works/k8s/scope?service-token=XXXX-version=$(kubectl version | base64 | tr -d '\n')"`

**Comment by rade** [comment]
Note that the instructions on Weave Cloud were missing the quotes for a week. (And still are; fix is on dev but not prod yet)

**Comment by abuehrle** [comment]
This was using the copy function on the GUI. I'll test that again.

**Comment by rade** [comment]
As I said, the text in the GUI is wrong; it's missing the quotes.

**Comment by abuehrle** [comment]
@rade I missed your comment. This is what I've run and I'm still not seeing the views. 
```
 kubectl apply -n kube-system -f   "https://cloud.weave.works/k8s.yaml?t=gniyhtrgkijybxstosig7o135qxnaide&k8s-version=$(kubectl version | base64 | tr -d '
')"
```

The only thing that's connected is Flux. 

https://cloud.weave.works/org/cold-hill-34

**Comment by abuehrle** [comment]
When I run this from dev (which is what's running now in my instance): 

```
kubectl apply -n kube-system -f \
   "https://cloud.weave.works/k8s/scope?service-token=XXXX-version=$(kubectl version | base64 | tr -d '\n')"
```
I get the same result as this bug, i.e no scope on the master and also no Flux and no Cortex

```
NAMESPACE     NAME                                READY     STATUS    RESTARTS   AGE
kube-system   etcd-master-01                      1/1       Running   0          19h
kube-system   kube-apiserver-master-01            1/1       Running   0          19h
kube-system   kube-controller-manager-master-01   1/1       Running   0          19h
kube-system   kube-dns-3913472980-cxd12           3/3       Running   0          19h
kube-system   kube-proxy-4hjp3                    1/1       Running   0          19h
kube-system   kube-proxy-76jr4                    1/1       Running   0          19h
kube-system   kube-proxy-wgfqx                    1/1       Running   0          19h
kube-system   kube-scheduler-master-01            1/1       Running   0          19h
kube-system   weave-net-6k4bc                     2/2       Running   1          19h
kube-system   weave-net-fqh32                     2/2       Running   1          19h
kube-system   weave-net-rkbgk                     2/2       Running   0          19h
kube-system   weave-scope-agent-634tx             1/1       Running   0          25s
kube-system   weave-scope-agent-j41p6             1/1       Running   0          25s
```

**Comment by rade** [comment]
I am rather suspicious of the `\n` having disappeared from the command you posted.

**Comment by abuehrle** [comment]
That's what you get if you just select it and don't use the copy function. (Part of the command, as you said is chopped off.)  

But as I mentioned, you get the same result when you run the "correct command" from dev. i.e. no scope on master and no flux and cortex agents. 
Let me know how I can help.

**Comment by abuehrle** [comment]
Logs from one of the agents: 

```
<probe> ERRO: 2017/05/05 13:06:51.594290 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:165: Failed to list *api.Service: the server does not allow access to the requested resource (get services)
<probe> ERRO: 2017/05/05 13:06:51.594989 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:165: Failed to list *api.Pod: the server does not allow access to the requested resource (get pods)
<probe> ERRO: 2017/05/05 13:06:51.601273 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:165: Failed to list *api.Node: the server does not allow access to the requested resource (get nodes)
<probe> ERRO: 2017/05/05 13:06:51.602296 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:165: Failed to list *api.ReplicationController: the server does not allow access to the requested resource (get replicationcontrollers)
<probe> ERRO: 2017/05/05 13:06:53.227721 Dropping report to cloud.weave.works
```

**Comment by errordeveloper** [comment]
>  ...also no Flux and no Cortex

Yes, because you've used `/k8s/scope`, it only gives you Scope.

> ...no scope on the master

Because you effectively installed 1.5 version of manifests, so tolerations aren't set correctly.

And `the server does not allow access to the requested resource (get services)` errors are also due to this being a 1.5 version, i.e. no RBAC objects.

It's best to uninstall and start re-install using command with quotes.

I am aware of this fact that these recent changes created a bunch of room for users to make errors, and I'd like to fix it, but to me it seems like we should rethink the approach.

**Comment by abuehrle** [comment]
@errordeveloper Yes that is confusing.  

>And the server does not allow access to the requested resource (get services) errors are also due to this being a 1.5 version, i.e. no RBAC objects.

That was a straight download of the new binaries using the KubeAdm instructions.  Are you saying that it has downloaded a mix of versions?  Should we log a bug over there?

**Comment by errordeveloper** [comment]
> Are you saying that it has downloaded a mix of versions?

No, I'm saying that due to a syntax error in the command you've effectively had Weave Cloud manifests for Kubernetes 1.5 installed on your Kubernetes 1.6 cluster.

I believe we've resolved this issue per-se, but there is still a UX issue with launch generator – the command is too long and thereby has too much room for user errors.

@rade @2opremio please close if you agree.

**Comment by 2opremio** [comment]
I do.
