### ISSUE TITLE
Info Tab for Services conflicts with what's returned on the command line

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2529]
The Info for 'front-end' service in Scope doesn't match the information returned on the command line. For example, `kubectl get pods --all-namespaces` says that the age of the pod is 8d yet Scope says 9d. 

<img width="305" alt="screen shot 2017-05-18 at 8 31 43 am" src="https://cloud.githubusercontent.com/assets/13420383/26204474/7cc2de50-3ba4-11e7-98b6-e7fa21ac8e26.png">

<img width="880" alt="screen shot 2017-05-18 at 8 33 48 am" src="https://cloud.githubusercontent.com/assets/13420383/26204580/c694b486-3ba4-11e7-9d24-f46790df78c2.png">

**Comment by rndstr** [comment]
I looked up the rounding mechanisms

**kubectl**
Does a simple truncate (`8.7d --> 8d`)
https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/common.go#L24-L41 (thanks @bboreham)

**scope frontend**
Uses momentjs which uses a humanized version with some [fancier rounding](https://momentjs.com/docs/#/displaying/fromnow/) (`8.7d --> 9d`)

I would keep the frontend as is (which is the better version IMHO)
