### ISSUE TITLE
Scope possibly misses connections on GKE in container but not pod view?

### ISSUE THREAD

**Issue by lukemarsden** [weaveworks/scope#2532]
scope on GKE seems to miss some connections in “containers” view, but not in “pods” view. odd.

<img width="691" alt="screen shot 2017-05-19 at 20 15 13" src="https://cloud.githubusercontent.com/assets/264658/26308038/541b8d48-3eac-11e7-9fcb-ad5368183e71.png">

<img width="618" alt="screen shot 2017-05-19 at 20 15 32" src="https://cloud.githubusercontent.com/assets/264658/26308049/603341de-3eac-11e7-9a4b-79929fe65758.png">

note productpage pod is definitely actively talking to reviews, details etc. but the same container ain’t doing nothing.

screenshots taken within half a second of eachother.

you should be able to reproduce the problem if you have time by following the guide I wrote here: https://deploy-preview-144--weaveworks-website-next.netlify.com/docs/tutorials/istio/istio/

**Comment by rade** [comment]
@lukemarsden could you grab a report, please? ('bug' icon in bottom right corner -> "Save raw data as JSON")

**Comment by lukemarsden** [comment]
Sorry for the delay @rade,

I've taken a look my GKE cluster in Scope (in Weave Cloud) and it doesn't seem to exhibit this behaviour:

<img width="540" alt="screen shot 2017-07-13 at 13 36 57" src="https://user-images.githubusercontent.com/264658/28166609-75d525fa-67d0-11e7-84a6-d432bffd0594.png">

Albeit this is without Istio in the mix. FWIW, these two containers are on different VMs.

So I would close this ticket and I'll reopen it if I ever see the issue again.

**Comment by lukemarsden** [comment]
hrm

**Comment by lukemarsden** [comment]
this came up again

**Comment by lukemarsden** [comment]
<img width="1792" alt="screen shot 2017-07-25 at 14 43 13" src="https://user-images.githubusercontent.com/264658/28575031-a5e9b618-7147-11e7-9c91-a4387e068bff.png">

**Comment by lukemarsden** [comment]
<img width="1792" alt="screen shot 2017-07-25 at 14 43 18" src="https://user-images.githubusercontent.com/264658/28575044-ad99b1ec-7147-11e7-90b2-3bc58bd3afea.png">

**Comment by lukemarsden** [comment]
this time it's a rancher cluster

**Comment by lukemarsden** [comment]
[report.json.zip](https://github.com/weaveworks/scope/files/1173321/report.json.zip)

**Comment by lukemarsden** [comment]
```
luke@starry:~/Projects/Weave/rancher-demo$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:34:20Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.6-rancher1", GitCommit:"973d2fa162b887a6f696f4574b85e949d480a071", GitTreeState:"clean", BuildDate:"2017-06-17T03:54:44Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lukemarsden** [comment]
it’s almost like containers on the pod network can’t be correlated with their pods
