### ISSUE TITLE
Probes don't exit cleanly when ebpf is enabled

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#2536]
See integration test failure at https://circleci.com/gh/weaveworks/scope/7232#tests/containers/1

**Comment by 2opremio** [comment]
This may be transient (or at least not systematic) since it didn't fail again after rebuilding.

**Comment by alban** [comment]
Not sure if it is related, but gobpf recently gained support for stopping properly: https://github.com/iovisor/gobpf/pull/51

tcptracer-bpf & Scope should probably make use of it.

**Comment by 2opremio** [comment]
> tcptracer-bpf & Scope should probably make use of it

Thanks
