### ISSUE TITLE
Clicking on a node in graph view doesn't open details on windows

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/scope#2540]
Reported during an on-site training in SF. User was on chrome on windows with a thinkpad. There was not stack trace when the node was clicked, and using the table view seemed to work. 

I have a sneaking suspicion that the click was registering as a drag for some reason.

**Comment by crw** [comment]
Speaking with @jpellizzari this is related to using a touchpad or magic mouse. I attempted to reproduce in Win10 1703 / Chrome 63.0.3239.84 with a touchpad, could not reproduce. Please reopen if this is still an issue.
