### ISSUE TITLE
Scope help text is incorrect (or very confusing)

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#2543]
When running `scope help` the output includes:

    -app-only
      Only run the probe.

and

    -probe-only
      Only run the app.

Which seem to be the wrong way round, to me.

**Comment by rade** [comment]
I fixed that a couple of weeks ago in bf02eb0cc.

**Comment by rade** [comment]
That change is in the 1.4.0 release too. @pidster were you running an ancient version?

**Comment by pidster** [comment]
Hmm. Maybe the script wasn't up to date.
