### ISSUE TITLE
Environment variable not picking up in terminal of scope 

### ISSUE THREAD

**Issue by thatsk** [weaveworks/scope#2550]
Environment variable is not picking up in scope terminal. Even it showing in Path variable.

![error](https://cloud.githubusercontent.com/assets/15324013/26621240/b921b1c8-4603-11e7-8345-dabe27e6023c.png)

**Comment by thatsk** [comment]
# @ @

**Comment by 2opremio** [comment]
What behavior did you expect?

The container terminals are simply the equivalent of running the following:

```
docker run -ti <containerid> /bin/sh  -l, -c 'TERM=xterm exec $( (type getent > /dev/null 2>&1  && getent passwd root | cut -d: -f7 2>/dev/null) || echo /bin/sh)'
```

See https://github.com/weaveworks/scope/blob/253657887cb5de0f23914f4b566965496f4e6280/probe/docker/controls.go#L115

**Comment by 2opremio** [comment]
The PATH may be lost due to spawning a login shell, which we do to make some users happy: https://github.com/weaveworks/scope/issues/1698

**Comment by thatsk** [comment]
But As you check at bottom i Have already set an environment . So i need jmeter command directly fire without using absolute path. But when i check the environment variable its not showing .And i am using alpine container so its basic shell is /bin/ash.
But When i try to terminal of server its perfectly running.

**Comment by thatsk** [comment]
/var/lib/apache-jmeter-3.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Also at the bottom corner you see PATH variable . But when i login to terminal its not picking up first one. why

**Comment by 2opremio** [comment]
I can confirm that `docker exec` respects the PATH env variable:

```
ubuntu@ubuntu-yakkety:~/scope$ docker run -e FOO=BAR -d --name nginx nginx
6b2ab9089c07992552538984e24a5640e9debbd19ee7c81ff645f5d6f045220b
ubuntu@ubuntu-yakkety:~/scope$ docker exec -ti nginx sh -c 'echo $FOO'
BAR
```

**Comment by 2opremio** [comment]
@errordeveloper You requested the login-shell functionality, but I agree with @thatsk on this one, so I am considering to stop using a login shell. Thoughts?

**Comment by thatsk** [comment]
Thanks . Use default behaviour. Of docker run not to add anything they can
manage in their dockerfile

**Comment by rade** [comment]
How about using login shells for *host* terminals only? That is in fact all that what was asked for in #1698.
