### ISSUE TITLE
no container connections when `probe.proc.spy=false`

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2551]
When setting `probe.proc.spy=false`, no container connections are displayed.

My test setup consist of two machines:

1. my desktop, running the scope app & probe
2. a VM, running the scope probe

I tried three variations:

### scope connections
Just checking whether the connection between the probes and app are showing. They don't. @2opremio says that in the absence of proc info scope tries to identify containers with an IP address, which won't work here because scope runs in the host netns and hence doesn't have  an IP of its own

### plain containers
on the desktop run: `docker run --rm -p 1122:1122 -ti alpine nc -lkp 1122`
on the VM run: `docker run --rm -ti alpine nc <desktop-ip> 1122`

The connection gets established and anything I type gets echoed across, but the connection does not show up in scope.

### containers on weave net
on the desktop run
```
$ weave launch
$ eval $(weave env)
$ docker run --rm --name=foo -ti alpine nc -lkp 1122
```
on the VM run
```
$ weave launch <desktop-ip>
$ eval $(weave env)
$ docker run --rm -ti alpine nc foo 1122
```
The connection gets established and anything I type gets echoed across, but the connection does not show up in scope.

**Comment by rade** [comment]
when repeating the experiment with containers running on the same host, with the nc client connecting to the server's docker IP, the connection does show up. It does *not* show up when going via the port published on the host IP.

**Comment by rade** [comment]
> with containers running on the same host, with the nc client connecting to the server's docker IP, the connection does show up.

That's true even when running with `probe.proc.spy=true`!

**Comment by rade** [comment]
> That's true even when running with `probe.proc.spy=true`!

I have raised #2558 for that.

**Comment by rade** [comment]
I've figured out what's going on here...

The `ContainerRenderer` produces nodes in three different ways:

1. projection from the process renderer, mapping processes to containers
2. projection from the endpoint topology, mapping IPs to containers
3. selection of everything in the "container" topology

Crucially, the 2nd projection *ignores endpoints with `procspied=true`*, under the assumption that such endpoints will be mapped via the 1st projection. That assumption is false...

For the process topology to map an endpoint to a process, that endpoint needs to have a PID. But it is `probe.proc.spy=true` (help text: "associate endpoints with processes") that does that. Whereas `procspied` gets set even when an endpoint was created from a simple scan of `/proc/net/tcp`, which does not produce PIDs. That's exactly what happens when `probe.proc.spy=false`.

It seems to me that the author of the `ContainerRenderer` code conflated `procspied` with "endpoint was detected with probe.proc.spy=true". Which is an easy mistake to make given the confusing terminology! Or perhaps in the past `procspied` was indeed only set on endpoints that had been obtained from a proper, pid-producing /proc walk.

The obvious fix is to set `procspied` only for "genuinely" procspied endpoints. IMO a cleaner fix would be to not to look at `procspied` at all, and instead simply check whether the endpoint has an associated PID. That would also take care of another bug which I've spotted: eBPF connection tracking produces endpoints with pids and sets `eBPF=true` but not `procspied`. (NB: the process renderer *did* get updated to check both, but not the container renderer).

**Comment by rade** [comment]
This PR has resulted in an unexpected and significant performance improvement in producing the host and k8s topologies.

Steps to reproduce:
1. grab a recent ["prod on dev"](https://frontend.dev.weave.works/app/nameless-night-79) report via the 'Save raw data as JSON' item in the 'bug' menu
2. feed this as a static report to scope by running the executable rather than the container
```
 prog/scope --mode=app --weave=false --app.collector=file:/home/matthias/tmp/prod-on-dev-report.json 
```
3. `time curl -so /dev/null localhost:4040/api/topology/hosts`

Results (times in seconds):

|            |  before | after |
| ---------- | --- | --- |
| processes  | 0.3 | 0.3 |
| containers | 1.8 | 1.8 |
| pods       | 2.5 | 1.5 |
| services   | 2.4 | 1.4 |
| hosts      | 2.6 | 1.6 |

This happens because previously the `ConnectionJoin`s from the k8s and container topologies had distinct `mapEndpoint2IP` mappers, whereas now they are shared via a global variable. Consequently memoization can eliminate the multiple executions of these mappers which results from the embedding of the container renderers in the k8s and host topology renderers.

**Comment by 2opremio** [comment]
Awesome. A test failed after merging to master though :S

**Comment by rade** [comment]
> A test failed after merging to master though :S

I fixed that.
