### ISSUE TITLE
connections between local containers via host IP not shown

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2558]
Scope fails to show connections between local containers when these connections go via the host IP.

e.g. launch scope and then two containers as follows
1. `docker run --rm -p 1122:1122 -ti alpine nc -lkp 1122`
2. `docker run --rm -ti alpine nc <host-ip> 1122`

and then look at the container topology in scope, which shows two containers with no connection between them.

By contrast, when the 2nd container is run on a different machine, with a scope probe running on that too, then the connection *does* show up.

**Comment by 2opremio** [comment]
Maybe related to https://github.com/weaveworks/scope/issues/1733 ?

**Comment by rade** [comment]
Now that eBPF-tracking is the default, this does actually work. But not when eBPF-tracking is disabled with `--probe.ebpf.connections=false`.

**Comment by rade** [comment]
The following patch makes the connection show up:
```diff
diff --git a/render/container.go b/render/container.go
index 81d34832..f2e5a6cb 100644
--- a/render/container.go
+++ b/render/container.go
@@ -44,10 +44,7 @@ var ContainerRenderer = MakeFilter(
 
 var mapEndpoint2IP = MakeMap(
        endpoint2IP,
-       // We drop endpoint nodes which were procspied, as they will be
-       // joined to containers through the process topology, and we don't
-       // want to double count edges.
-       MakeFilter(Complement(procspied), SelectEndpoint),
+       SelectEndpoint,
 )
 
 const originalNodeID = "original_node_id"
```

This suggests that the endpoints in question do not have a pid and hence aren't propagated to containers via the process topology.

**Comment by rade** [comment]
Here's a condensed report:
```javascript
{
  "Container": {
      "74dcf877a0fb807b25473485966df5463b1a8fcfc7e4a177911b3fee85411e72;<container>": { // client
          "docker_container_ips": ["172.17.0.3"],
          "docker_container_ips_with_scopes": ["xps;172.17.0.3"],
      },
      "fc2d0a43a340cf699d517bc9f59603f6e6a8f4bd4d7b227feab3ea7ea6c1511f;<container>": { // server
          "docker_container_ips": ["172.17.0.2"],
          "docker_container_ips_with_scopes": ["xps;172.17.0.2"],
          "docker_container_ports": ["192.168.3.22:1122->1122/tcp"]
      },
  },
  "Endpoint": {
      "xps;172.17.0.3;42293": {
          "adjacency": [";192.168.3.22;1122"],
          "edges": {";192.168.3.22;1122": {}},
          "conntracked": "true",
          "procspied": "true",
          "pid": "18162"
      }
      "xps;172.17.0.2;1122": {
          "adjacency": null,
          "edges": null,
          "conntracked": "true",
          "procspied": "true",
          "pid": "17571"
      },
      ";192.168.3.22;1122": {
          "adjacency": null,
          "edges": null,
          "conntracked": "true",
          "procspied": "true",
          "pid": "17549"
      },
      "xps;172.17.0.1;55670": {
          "adjacency": ["xps;172.17.0.2;1122"],
          "edges": {"xps;172.17.0.2;1122": {}},
          "conntracked": "true",
          "procspied": "true",
          "pid": "17549"
      },
  },
  "Process": {
      "xps;18162": {
          "cmdline": "nc 192.168.3.22 1122 ",
          "docker_container_id": "74dcf877a0fb807b25473485966df5463b1a8fcfc7e4a177911b3fee85411e72"
      },
      "xps;17571": {
          "cmdline": "nc -lkp 1122 ",
          "docker_container_id": "fc2d0a43a340cf699d517bc9f59603f6e6a8f4bd4d7b227feab3ea7ea6c1511f"
      },
      "xps;17549": {
          "cmdline": "/usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 1122 -container-ip 172.17.0.2 -container-port 1122 ",

      },
  }
}
```

So here's what's going on...

`ConnectionJoin` is the only place which knows how to deal with container port mapping. In particular it will transform the `;192.168.3.22;1122` endpoint into the `fc2d0a43a` container. That is crucial because while `xps;172.17.0.3;42293` and `xps;172.17.0.2;1122` can be mapped to containers by `MapProcessToContainer`, `;192.168.3.22;1122`cannot, since its associated process is a docker-proxy.

However, the current code excludes procspied endpoints from `ConnectionJoin`, under the assumption that they will be mapped to processes and then containers by `MapProcessToContainer`.

Hence `;192.168.3.22;1122` does not get mapped to a container, and thus the edge to `;192.168.3.22;1122` which `74dcf877a` got via the mapping of the `xps;172.17.0.3;42293` endpoint, does not go anywhere.

**Comment by rade** [comment]
I am rather tempted to use my patch from above to fix this. What could go wrong?

1. performance might suffer, since we'd be feeding more endpoints to `ConnectionJoin`
2. we might end up with some stray pseudo nodes, for the same reason
3. counts may be off, because of the stark warnings in the code about the need to we need to include edges only once

(1) I can check/measure. For (2), I am not really sure what to look for. For (3), I have yet to find exactly where and how things go wrong. @2opremio any pointers for (2) and (3)?

Note that we are *already* looking at the same endpoints multiple times, because process rendering looks for "procspied or ebpf-tracked" whereas `ConnectionJoin` looks for "not procspied". (for a reason, as it turns out - see 6eaffb4). Alas "endpoint" != "edge"... the comments in the code liberally conflate the two, which doesn't help.

**Comment by 2opremio** [comment]
> Hence `;192.168.3.22;1122` does not get mapped to a container

But `;192.168.3.22;1122` has a PID, why doesn't it end up as a process connection and in turn a container through `MapProcessToContainer` ? 

I've read your explanation above a few times and it still isn't clear to me why that doesn't happen (I see it as a bug).


> I am rather tempted to use my patch from above to fix this

Can we clarify the point above first?

**Comment by rade** [comment]
> But `;192.168.3.22;1122` has a PID

That PID is the docker-proxy.

> why doesn't it end up as a process connection and in turn a container through `MapProcessToContainer` ?

Because the docker-proxy is not a container. Besides, we don't really want to show the connection as going via the docker-proxy; that is an implementation detail. The right way to resolve the adjacency is via the container port mapping. Which is one of the things `ConnectionJoin` is doing.

**Comment by rade** [comment]
I compared the topologies produced from a recent production report with a) the current code, and b) no endpoint filtering on `ConnectionJoin`.  The hosts, processes and container topologies are unchanged. But the service topology produced by the current code is missing 4 connections between services and external services, e.g. `fluxy-db-exporter` and `service-prod-fluxy-`vpc-database.cqqzyyx2xnct.us-east-1.rds.amazonaws.com`, as well as 4 connections from `prometheus` to the likes of the `control` and `demo`. And the pod topology is missing 39 connections; in addition to the aforementioned service connections, it is also missing a bunch of connections from `authfe` pods to `collection` pods, as well as many others.

So there's a real accuracy issue here.

I've also run some performance tests, using the methodology from https://github.com/weaveworks/scope/pull/2559#issuecomment-306142823

|            | old | new |
| ----------- | ----- | ----- |
| processes  | 0.3 | 0.3 |
| containers | 1.7 | 2.0 |
| pods       | 1.3 | 1.5 |
| services   | 1.2 | 1.4 |
| hosts      | 1.3 | 1.5 |

So removing the endpoint filtering from `mapEndpoint2IP` does incur a noticeable performance penalty. I'll see whether I can find a better way to get the accurate results, but in the end accuracy trumps performance.

**Comment by 2opremio** [comment]
> Besides, we don't really want to show the connection as going via the docker-proxy; that is an implementation detail. 

Yep, agreed. I think this is corner case though. Would it make sense to elide docker-proxy explicitly? It would allow us to include the connections without losing performance.

**Comment by rade** [comment]
> Would it make sense to elide the docker-proxy explicitly?

It's not so much about eliding it - it's being elided already - but somehow making sure the associated endpoints get mapped to containers. That would require `MapProcess2Container` to access the ip->container map currently produced by `ConnectionJoin`. It's doable of course but will require a major re-working of the code.

Also as I noted above in my topology comparison above, there are other problems with the current endpoint filtering that have nothing to do with the docker-proxy.

And I would still like to know what the deal is with counts. See point 3 and the last paragraph in https://github.com/weaveworks/scope/issues/2558#issuecomment-306209780.

**Comment by 2opremio** [comment]
> That would require `MapProcess2Container` to access the ip->container map currently produced by `ConnectionJoin`

That's what I meant.

> That would require `MapProcess2Container` to access the ip->container map currently produced by `ConnectionJoin`

If we mark docker-proxy endpoints specially, can't we do it in the second part of `ipToNode()` ?

> I would still like to know what the deal is with counts

I thought that the connection counts could be affected. Due to the merging of duplicates I thought that the adjacency list would get duplicates or that the connections counters would get screwed up due to the extra increment of node counters.

But
1. Adjacency lists are really sets
2. Node counters are not really used by the connection counter (`render/detailed/connections.go`)

However, node counters are used for the Container Image Node Summary, so duplicates may break that. But .. I guess we can avoid duplicate increments by looking at the original topology of the nodes.

> I compared the topologies produced from a recent production report with a) the current code, and b) no endpoint filtering on `ConnectionJoin`.  
> [...]
> the service topology produced by the current code is missing 4 connections between services and external services, 
> [...]
> as well as 4 connections from `prometheus` to the likes of the `control` and `demo`. And the pod topology is missing 39 connections

Uhm, could the duplicates could be affecting the `IP` counter?  causing it to be unexpectedly higher than 1 in some cases and thus discarding connections?

**Comment by rade** [comment]
> If we mark docker-proxy endpoints specially, can't we do it in the second part of `ipToNode()` ?

Are suggesting that we mark the proxy endpoints in the probe? And then amend the endpoint filter in `mapEndpoint2IP` to include these endpoints?

> Uhm, could the duplicates could be affecting the IP counter? causing it to be unexpectedly higher than 1 in some cases and thus discarding connections?

My comparison was between a) the current code, and b) no endpoint filtering on ConnectionJoin. If anything, the latter would produce higher IP counts than the former, so cannot explain why *more* connections are included that way.

**Comment by 2opremio** [comment]
> Are suggesting that we mark the proxy endpoints in the probe? And then amend the endpoint filter in `mapEndpoint2IP` to include these endpoints?

Not in the probe, but as a extra pass in the renderer.

> My comparison was between a) the current code, and b) no endpoint filtering on ConnectionJoin. If anything, the latter would produce higher IP counts than the former, so cannot explain why *more* connections are included that way.

I misread, you are totally right about that.

Do the probes generating that report have eBPF enabled? If so I am a bit lost, since the current code doesn't filter out endpoints generated by eBPF.

**Comment by rade** [comment]
> Do the probes generating that report have eBPF enabled?

The report was from Weave Cloud production. So no.
