### ISSUE TITLE
Pods subnavigation occupies lots of vertical space

### ISSUE THREAD

**Issue by rndstr** [weaveworks/scope#2566]
This is especially an issue on monitors whose vertical resolution is on the lower end.

When I'm trying to move the graph down by drag & drop I clicked a few times on a Pod subnav instead of starting the movement.
![pod-subnavigation-weave-cloud](https://cloud.githubusercontent.com/assets/32963/26833293/f3303004-4ac9-11e7-8e8f-107515c55c22.png)

I think this is especially prevalent on Weave Cloud where the whole navigation is more to the left (since the weaveworks logo is not there) thus leading to that heavier Pod navigation being in the dead center.

One idea would be to only display 2 subnav items (recently used? most used?) and reveal the others only when hovering over the navigation

Edit: realized there is a similar issue (#2565) just before mine, feel free to close/merge

**Comment by rade** [comment]
We are shrinking that sub-menu as part of the "hybrid view" in #552 /  #2552 work.

**Comment by rndstr** [comment]
The combined view improved this, closing this.
