### ISSUE TITLE
Nothing to show watermark displaying when it shouldn't

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2592]
Version: weaveworks/scope:release-1.5-1667984
Docker for Mac
Sockshop
Standalone Scope

In the Container view when you switch between the DNS and Image filters nothing to show message still appears. 

<img width="760" alt="screen shot 2017-06-13 at 7 05 38 am" src="https://user-images.githubusercontent.com/13420383/27079714-c430ac56-5006-11e7-925b-1c5afc832b31.png">

**Comment by abuehrle** [comment]
This seems to occur when you first launch scope in standalone and click around. One you switch between Memory and CPU filters, and then go back between topologies it seems to disappear.

**Comment by rade** [comment]
Fixed by #2597, right, @fbarl?

**Comment by fbarl** [comment]
> Fixed by #2597...

Yup, forgot to close it after I bumped the Scope UI version.
