### ISSUE TITLE
Container View by DNS and apply Stopped containers shows nothing

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2594]
Version: weaveworks/scope:release-1.5-1667984
Docker for Mac
Sockshop
Standalone Scope

I have a lot of stopped containers on my local mac, but filtering when in container --> DNS view these don't appear. 

Filtering by Stopped containers shows me nothing when all of the containers are stopped.

**Comment by abuehrle** [comment]
Amended this - running containers do display, but so do the stopped ones when filtering by 'Running' containers. Essentially 'both' and 'running containers' show the same thing, and 'stopped' shows nothing.

**Comment by 2opremio** [comment]
Can you add a video/screenshot?

**Comment by abuehrle** [comment]
Image and Container filter properly, but DNS does not: 

<img width="1190" alt="screen shot 2017-06-13 at 12 55 37 pm" src="https://user-images.githubusercontent.com/13420383/27094330-c3c4e878-5037-11e7-9bb5-b1fb86f6ff1e.png">

<img width="1174" alt="screen shot 2017-06-13 at 12 56 01 pm" src="https://user-images.githubusercontent.com/13420383/27094353-cd7c3e7a-5037-11e7-838d-0d3d6ba23d9b.png">

**Comment by abuehrle** [comment]
I'm going to open a new issue. There are some problems with the filters.
