### ISSUE TITLE
Contrast Mode control not appearing in Weave Cloud

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2598]
Version: weaveworks/scope:release-1.5-1667984
Docker for Mac
Sockshop
Standalone Scope

Not sure if this was always there to begin with, but the release candidate version does not show the high contrast mode control. 

<img width="615" alt="screen shot 2017-06-13 at 10 21 54 am" src="https://user-images.githubusercontent.com/13420383/27087150-2f7ac382-5022-11e7-9dbd-74d327c5704f.png">

I will invite you to my instance, if you need to check this.

**Comment by fbarl** [comment]
The contrast mode button has been missing from the Cloud env for quite some time already: https://github.com/weaveworks/service-ui/issues/350

**Comment by abuehrle** [comment]
I will log WC issues over there.
