### ISSUE TITLE
Method for deduping reports

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#26]
With #13, the possibility of an app connecting to a probe multiple times has been introduced.  This will allow an app to receive the same report more than once, and potentially double count.  We need to disallow this.

Options:
- Make report merge fully idempotent ie r1.merge(r1) == r1 and so on
- Make probes only accept one connection per app
- Include a random unique id in each report, and dedupe on the app

I like (1), as it has nice properties for the future; but it is also the hardest.

**Comment by tomwilkie** [comment]
Short-term we'll only accept one connection per app, based on source ip.

**Comment by peterbourgon** [comment]
Closed by #56
