### ISSUE TITLE
We have 3 test Report "fixtures".  Consider having just one.

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#260]
they are:
- app/mock_reporter_test.go
- render/topologies_test.go
- report/report_fixture_test.go

**Comment by peterbourgon** [comment]
Can easily collapse to e.g. test/fixture.go.

**Comment by tomwilkie** [comment]
Yes thats what I was thinking.  Not a big fan of having a 'test' module, but can't think of a better solution.

**Comment by peterbourgon** [comment]
Fine for now, IMO.
