### ISSUE TITLE
Scope is not appearing in Containers View

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2601]
Version: weaveworks/scope:release-1.5-1667984
Docker for Mac
Sockshop

Searching for Scope doesn't appear in Containers view, but does in Processes. 

Please see the video (the right one this time!):

http://recordit.co/LKidN6iQ3t

**Comment by pidster** [comment]
It's a system container and is filtered out. Not sure whether the highlighting feature is supposed to identify that, or not.

**Comment by 2opremio** [comment]
@abuehrle It's filtered out as a system container. I am pretty sure you were not displaying the system containers, can you confirm?

**Comment by abuehrle** [comment]
Yes, I was filtered on application containers. 
 
Might be good to highlight the system filter to indicate to the user that it's in there - like you do for all of the other views.

**Comment by 2opremio** [comment]
Please create a separate ticket with a screenshot
