### ISSUE TITLE
Time Travel: make use of /api endpoint report persistence capability flag

### ISSUE THREAD

**Issue by fbarl** [weaveworks/scope#2607]
Since #2575, we are able to tell in the UI whether Scope reports are stored persistently. Instead of treating *Time Travel* as a Cloud-only feature, we should be showing it whenever historical reports are available. Apart from Weave Cloud, that would enable the use of time travel in Scope standalone whenever the reports are stored persistently.

**Note:** This should only be addressed after the feature-flag for *Time Travel* has been removed.

**Comment by rade** [comment]
@filip @fons We should consider adding very limited time travel capability to standalone scope, simply by getting the app to hold on for a bit more than 15s of reports, probably configurable via some flag.

That would give OSS users a sneak peek of the feature, with some limited, but nevertheless useful, functionality ("What just happened? Let me skip back a minute.").

Looks like the capability to enable the timetravel UI is called `report_persistence`, which is a bit unfortunate given that (limited) time travel is possible w/o persistence. I reckon we should rename the capability. `historic_reports`?

**Comment by rade** [comment]
@fbarl a related question: how well do the timetravel controls work for short periods, say 2 minutes?

**Comment by 2opremio** [comment]
> We should consider adding very limited time travel capability to standalone scope.

I am not sure it's worth the effort by itself. It will end up being a glorified _instant replay_ which I don't think is very useful. It may be worth of there's value in having it as a demo or a way to drive more people to Weave Cloud. @Futurile ?

> I reckon we should rename the capability. `historic_reports`?

Fine by me. If we are going to enable it by default then we don't need any capabilities.

**Comment by rade** [comment]
>  It may be worth of there's value in having it as a demo or a way to drive more people to Weave Cloud.

That's the idea. Though I wouldn't want to enable the feature just as a demo. It actually has to be of some (limited) use. That's why I postulated a "What just happened? Let me skip back a minute." use case, though thinking about it now, that may not work particularly well when reports get expired underneath.

**Comment by fbarl** [comment]
@rade,

> We should consider adding very limited time travel capability to standalone scope, simply by getting the app to hold on for a bit more than 15s of reports, probably configurable via some flag.

I don't know how much work it would be and whether it's worth the effort - I'd suggest we wait until we get some more info how people are using the time control.

> I reckon we should rename the capability. `historic_reports`?

I think `historic_reports` is a more clear - maybe I could rename it in #2616.

> How well do the timetravel controls work for short periods, say 2 minutes?

We are rounding everything to seconds on the frontend, but I think the backend supports full granularity down to milliseconds, so I'd say exploring 2 minutes intervals should be pretty accurate (as far as I remember, backend is always taking a 15s window ending at the requested timestamp).

**Comment by rade** [comment]
@fbarl
> I think historic_reports is a more clear - maybe I could rename it in #2616.

Go for it. And change the PR title too, since it talks about persistence :)

**Comment by rade** [comment]
> I think `historic_reports` is a more clear - maybe I could rename it in #2616.

I've done this in #2774.

**Comment by Futurile** [comment]
I think the most useful case is actually going to be the last couple of "minutes": because it's a more obvious way to do troubleshooting. But, lets see how people actually use it first ...
