### ISSUE TITLE
WeaveDB filters on Application Containers

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2610]
Version: (VERSION 0869d26e)
Product: Net and Scope
Orchestrator: AWS - ECS

The WeaveDB is filtering on application containers and it should be in system containers. 

<img width="1033" alt="screen shot 2017-06-16 at 10 29 55 am" src="https://user-images.githubusercontent.com/13420383/27230985-0c8f2570-527f-11e7-835a-ff74f510c55f.png">

**Comment by rade** [comment]
This was a problem in weave net. It's fixed there so the issue will go away with the next release.
