### ISSUE TITLE
The K8S + weavescope is deployed on the cloud host, and the node can not be fully tracked

### ISSUE THREAD

**Issue by ylf881011** [weaveworks/scope#2612]
Cloud host 3 sets
10.10.14.63
10.10.19.230
10.10.7.49

SELinux has been disabled
3 nodes are fully started, but weavescope can always view only one node information

![image](https://user-images.githubusercontent.com/16286574/27241119-01a6ff58-530a-11e7-8d41-9593a1c25a03.png)

At first I thought it was network segment conflict, try to modify the service-cidr network segment for 192.168.0.0/16, but still the same

Then I checked the weave-scope-app log and found these errors

[root@qa3 ~]# docker logs a9ef32ac87a7 
time="2017-06-16T18:23:50Z" level=info msg="publishing to: 192.168.166.137:80" 
<probe> INFO: 2017/06/16 18:23:50.327720 command line args: --logtostderr=true --mode=probe --no-app=true --probe.docker=true --probe.docker.bridge=docker0 --probe.kubernetes=true 192.168.166.137:80
<probe> INFO: 2017/06/16 18:23:50.327790 probe starting, version 1.4.0, ID 3e825ea65245a301
<probe> INFO: 2017/06/16 18:23:50.364735 kubernetes: targeting api server https://192.168.0.1:443
<probe> ERRO: 2017/06/16 18:23:50.396293 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
<probe> ERRO: 2017/06/16 18:23:50.411436 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
<probe> WARN: 2017/06/16 18:23:50.438687 Cannot resolve 'scope.weave.local.': dial tcp 172.17.0.1:53: getsockopt: connection refused
<probe> WARN: 2017/06/16 18:23:50.438935 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> INFO: 2017/06/16 18:23:50.440725 Success collecting weave plugin status
<probe> INFO: 2017/06/16 18:23:50.440793 Success collecting weave proxy status
<probe> WARN: 2017/06/16 18:23:50.595000 Error collecting weave ps, backing off 20s: exit status 1: "Link not found\n"
<probe> ERRO: 2017/06/16 18:23:51.329505 Error fetching app details: Get http://192.168.166.137:80/api: dial tcp 192.168.166.137:80: getsockopt: connection refused
<probe> INFO: 2017/06/16 18:23:52.344284 Control connection to 192.168.166.137 starting
<probe> INFO: 2017/06/16 18:23:53.456497 Publish loop for 192.168.166.137 starting
<probe> WARN: 2017/06/16 18:24:00.439598 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> ERRO: 2017/06/16 18:24:05.416227 Error checking version: Get https://checkpoint-api.weave.works/v1/check/scope-probe?arch=amd64&flag_kernel-version=3.10.0-229.el7.x86_64&flag_kubernetes_enabled=true&flag_os=linux&os=linux&signature=9z4E%2BngjQgX38DUmNlFsl1XwuFpmPBbYZ7YmmIsSaGg%3D&version=1.4.0: dial tcp 172.217.24.19:443: i/o timeout
<probe> WARN: 2017/06/16 18:24:10.636120 Error collecting weave ps, backing off 40s: exit status 1: "Link not found\n"
<probe> WARN: 2017/06/16 18:24:20.442020 Error collecting weave status, backing off 40s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> WARN: 2017/06/16 18:24:50.676328 Error collecting weave ps, backing off 1m0s: exit status 1: "Link not found\n"
<probe> INFO: 2017/06/16 18:24:51.900445 Pipe pipe-3463107226906191821 connection to 192.168.166.137 starting
<probe> INFO: 2017/06/16 18:24:58.555668 Pipe pipe-3463107226906191821 connection to 192.168.166.137 exiting
<probe> WARN: 2017/06/16 18:25:00.442666 Error collecting weave status, backing off 1m0s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
<probe> WARN: 2017/06/16 18:25:07.440548 K8s reporter took longer than 1s
<probe> WARN: 2017/06/16 18:25:11.450492 K8s reporter took 5.010120637s (longer than 1s)
<probe> WARN: 2017/06/16 18:25:12.458963 K8s reporter took longer than 1s

**Comment by 2opremio** [comment]
The problem resides here:

```
ERRO: 2017/06/16 18:23:51.329505 Error fetching app details: Get http://192.168.166.137:80/api: dial tcp 192.168.166.137:80: getsockopt: connection refused
```

For some reason the probe whose logs you provided cannot reach the Scope app. 

I would start by running `curl http://192.168.166.137:80/api` (or whatever IP the Scope service has at that moment), from the Kubernetes nodes. That should work, so try to figure out why that is.

According to your screenshot, the Scope App must be getting reached by at least a probe, otherwise the UI would be empty, so my guess is that only the probe co-located in the same node as the app can reach it.

We have seen problems like this before, and the cause was a misconfiguration of the Kubernetescluster (missing iptables rule or misconfigured kube-proxy), preventing processes in the host networking namespace (like the Scope probes) from accessing the Service IPs. For instance, see https://github.com/weaveworks/scope/issues/2544

The other warnings are harmless:

1. The `weave ps`, `weave status` and `Cannot resolve 'scope.weave.local'`warnings expected when Weave Net is nor running (and it doesn't need to in order for Scope to work). You can run the probes with `--weave=false` to silence them.
2. The `Error checking version` only means that the probe doesn't have access to the internet.
3. `NOTICE: Netlink socket buffer size has been set to 425984 bytes.` is harmless.

**Comment by ylf881011** [comment]
Today found that other weave-scope-agent nodes have been given
But I entered the container to visit http://192.168.69.152:80 is responsive
![image](https://user-images.githubusercontent.com/16286574/27253463-a038e706-53a7-11e7-9454-5d51c5e99c2a.png)
![image](https://user-images.githubusercontent.com/16286574/27253470-b547225c-53a7-11e7-9e4e-5b4513fa6226.png)

**Comment by ylf881011** [comment]
C node can display normally.
Just tried the next. I entered the A, B node of the agent container curl http://192.168.69.152/api/report is blocked
C node inside the agent container, curl http://192.168.69.152/api/report immediately get a lot of information

Do not know for what reason, led to the A and B node blocking.
And no matter how many times I rebuild the cluster, always the last node can be displayed

**Comment by 2opremio** [comment]
The report-dropping errors in your screenshot above are most likely due to the CPU not being powerful enough (the Scope agents are pretty CPU-hungry). Where are you running this?

> I Do not know for what reason, led to the A and B node blocking.

You should double check your networking configuration. It's probably a missing iptables rule or something in those lines.

**Comment by ylf881011** [comment]
This should not be related to iptables
Because A, B node access curl http://192.168.69.152/api is available information
But visit curl http://192.168.69.152/api/report blocked

**Comment by ylf881011** [comment]
This is a problem in the cloud environment that is normal in my own virtual machine (VMWARE) environment.
In addition to provide the environmental parameters
UCLOUD cloud: three nodes 10.10.14.63,10.10.19.230,10.10.7.49
    K8S: kubeadm init --pod-network-cidr = 172.70.0.0 / 16 --service-cidr = 192.168.0.0 / 16
    Calico: 172.70.0.0/16
   
My VMWARE: three nodes 192.168.180.110, 192.168.180.111, 192.168.180.112
    K8S: kubeadm init --pod-network-cidr = 172.50.0.0 / 16
    Calico: 172.50.0.0/16

**Comment by 2opremio** [comment]
> curl http://192.168.69.152/api/report blocked
This is a POST request, curl uses GET by default

**Comment by ylf881011** [comment]
是的。我今天意识到了这点，换成了POST请求，可以立马获得响应。
 但我不知道这个接口完整的参数，只是试探了下，有http响应。可以证明是通畅的，跟iptables无关。
 但是为什么在云环境上报这个错我不明白
 Error doing publish for 192.168.201.144, backing off 1m0s: Post http://192.168.201.144:80/api/report: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
<probe> ERRO: 2017/06/18 16:00:36.056840 Dropping report to 192.168.201.144

**Comment by 2opremio** [comment]
Unfortunately I can't help you with Ucloud or your Kubernetes installation.

**Comment by ylf881011** [comment]
I heard that Ucloud cloud host can not support multicast technology. Did weavescope use this technology?

**Comment by 2opremio** [comment]
No

**Comment by 2opremio** [comment]
Did you figure out what was wrong?
