### ISSUE TITLE
Text in Kubernetes views overlaps data in table mode

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2614]
Need more space for 'Services' topology when viewing Kubernetes pods: 

<img width="1231" alt="screen shot 2017-06-18 at 7 43 29 pm" src="https://user-images.githubusercontent.com/13420383/27265176-a3209d58-545e-11e7-970e-9f34126f635f.png">

**Comment by rndstr** [comment]
duplicate #2565

**Comment by abuehrle** [comment]
sorry @rndstr should have looked first!
