### ISSUE TITLE
Filters in Kubernetes Views not functioning - shows all namespaces only

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2619]
WC Version: 0869d26e
Cloud: Digital Ocean
OS: Unbuntu: 16.04.2  4.4.0-79-generic
Kubernetes: ```Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.5", GitCommit:"490c6f13df1cb6612e0993c4c14f2ff90f8cdbf3", GitTreeState:"clean", BuildDate:"2017-06-14T20:15:53Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}```

Can't filter my app (sockshop) by its namespace in the Kubernetes views. 

See: 

http://recordit.co/iikhgXmadE

**Comment by rade** [comment]
it's hard to tell from the video what is going on. Are you clicking on the "sock-shop" namespace selector but it's not activating?

**Comment by abuehrle** [comment]
I'm not seeing this behaviour now. If I see it again. I will reopen this.
