### ISSUE TITLE
`nodeSummaryGroupSpec` looks wrong

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2630]
The [`nodeSummaryGroupSpec`](https://github.com/weaveworks/scope/blob/v1.5.0/render/detailed/node.go#L130) looks wrong. AFAICT the data is (only) used to display children in the details panel. But several of the included items cannot be children of anything: Hosts, K8S Services, ECS Services.

For a moment I thought that perhaps it's a "list of all the things", but Deployments and DaemonSets aren't in it.

@2opremio @ekimekim Am I misunderstanding the purpose of this list?

**Comment by ekimekim** [comment]
I concur. We should either ensure everything is in the list, or delete anything that isn't needed and is unlikely to ever be needed. My preference is the latter, especially since there's fallback code that presents a sane default if one is missing.
