### ISSUE TITLE
max zoom level varies by window height

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2642]
The maximum zoom level depends on the window height, i.e. one can zoom further when the window is taller.

max zoom in short window:
![screenshot from 2017-06-25 10-16-23](https://user-images.githubusercontent.com/109109/27514922-c72557b2-598f-11e7-9047-cffeaf830807.png)

max zoom in tall window:
![screenshot from 2017-06-25 10-17-29](https://user-images.githubusercontent.com/109109/27514923-cb4ffd92-598f-11e7-9299-5635ae361cc5.png)

**Comment by fbarl** [comment]
This was also done by design:

```
// Max scale limit will always be such that a node covers 1/5 of the viewport.
const maxScaleSelector = createSelector(
  [
    canvasWidthSelector,
    canvasHeightSelector,
  ],
  (width, height) => Math.min(width, height) / NODE_BASE_SIZE / 5
);
```

I have no good argument behind this decision so we could make max-zoom constant if that would be preferable, but that could make the diff in sizes between normal and radial view (#2643) even more extreme on small screens, so the question is if it's worth it. @rade thoughts?

**Comment by rade** [comment]
The problem with the current approach is that the font-size, especially of the sub-labels, is just too small at max zoom level when the window is small.

**Comment by rade** [comment]
I also reckon the user experience of having different zoom scales based on window size is weird. Doesn't happen in google maps ;)

**Comment by rade** [comment]
it's also totally bizarre that it's based on the height only.

**Comment by fbarl** [comment]
> it's also totally bizarre that it's based on the height only

It's actually proportional to the min of both dimensions (see above: `Math.min(width, height)`).

Alright, I'll try to find a good value and make it constant then!

**Comment by rade** [comment]
> It's actually proportional to the min of both dimensions

Ah, that kinda makes sense. Just doesn't work well in practice.
