### ISSUE TITLE
zoom level in radial view is lower than in normal view

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2643]
The zoom level of nodes/text in the radial view displayed when showing the details panel is lower than in the normal graph view.

Notice the difference in size between the foreground and background nodes in
![screenshot from 2017-06-25 10-22-21](https://user-images.githubusercontent.com/109109/27514945-70c59be2-5990-11e7-983f-ad5810d11821.png)

**Comment by fbarl** [comment]
This has been the case for months now and I didn't see it as a bug. It does look a bit weird from the screenshot though, but the only simple solution that comes to mind is decreasing the max-zoom level in the normal view. @rade do you think that would be ok?

**Comment by rade** [comment]
Oh, is the issue here simply that we need enough space to draw a complete circle?

If so, then fair enough, it's not a bug, it's a feature :)

**Comment by rade** [comment]
> Oh, is the issue here simply that we need enough space to draw a complete circle?

Yeah, looks like it. Here's an extreme example
![screenshot from 2017-06-26 14-47-06](https://user-images.githubusercontent.com/109109/27542186-66c145a8-5a7e-11e7-86bc-3e68b968e360.png)

Given that there is no way to control zoom or pan when the details panel is open, that is the only vaguely sane solution. -> closing
