### ISSUE TITLE
Resuming from pause is slower than it needs to be

### ISSUE THREAD

**Issue by ekimekim** [weaveworks/scope#2653]
After being paused for a while, resuming made it seem to apply all subsequent changes one-by-one, and this was very slow. By changing timeline to in the past, then back to the present, I forced it to refresh and instantly 'catch up' to up-to-date reports.
Ideally I shouldn't have to trick the UI into performing this operation - I'd suggest it happen automatically if the number of pending changes exceeds some (very small) threshold - or even just have it happen on unpause no matter what.

**Comment by fbarl** [comment]
> ...or even just have it happen on unpause no matter what

I feel the same - recently we had a discussion about it here in Berlin and @bia also didn't quite understand why we're still doing buffering. I don't think we have a good reason for keeping it, especially now that we'll be able to use Time Travel to go through the recent states. Would gladly get rid of it altogether once time travelling is there!
