### ISSUE TITLE
Error when retrieving logs from k8s pod with >1 container

### ISSUE THREAD

**Issue by awh** [weaveworks/scope#2656]
When you attempt to use `kubectl logs <pod>` with a pod that has >1 container, you are forced to supply a container name in addition to the pod name. This error appears in the UI:

![screenshot from 2017-06-28 10-57-28](https://user-images.githubusercontent.com/1504438/27631654-1907e9d8-5bf1-11e7-9af3-17a1ca4a0242.png)

It would be useful if we could show the interleaved logs for all containers, with individual lines prefixed by container name, rather than just requiring the selection of a particular container (although that might be useful also)

**Comment by rade** [comment]
dup of #1493.

**Comment by awh** [comment]
Argh, sorry, I thought this was new functionality for some reason and so didn't check for an existing bug.
