### ISSUE TITLE
static.go uses excessive memory when compiling

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#267]
Uses > 512MB for me.

**Comment by peterbourgon** [comment]
This is a known issue with the compiler. We might look into changing the tool we use to build the static assets. The author of https://github.com/tv42/becky claims it's been benchmarked as the most efficient mechanism.

**Comment by paulbellamy** [comment]
There's also several alternative tools which zip the static files, then append that to the exe post-compilation, which removes them from the go source altogether.

**Comment by peterbourgon** [comment]
Have a link? I find that methodology a little dubious on first pass but I probably need to research more.

**Comment by paulbellamy** [comment]
There's several, but the one I was thinking of is: https://bitbucket.org/tebeka/nrsc

**Comment by tomwilkie** [comment]
wontfix: this isn't causing us any issues, and its not worth the investment.
