### ISSUE TITLE
Time Travel: Make slider into timeline

### ISSUE THREAD

**Issue by fbarl** [weaveworks/scope#2677]
In order to display different historic metadata in the *Time Travel* component (which would give better clues as to where we want to navigate), current slider will be made into a timeline which would be holding the metadata. The idea is to make that timeline both *zoomable* and *pannable*.

**Comment by fbarl** [comment]
@bia is currently working on the sketches for it - the very initial ones start from [here](https://www.dropbox.com/sh/45hq01047u7zfir/AABQugkx5FjhOOpIGilBB0pBa?dl=0&preview=170628timelineSketch9.png).

**Comment by rade** [comment]
zoom and pan are important features in their own right, and quite independent of representing historic meta data on the timeline. So let's tackle that *first*. I've raised #2686 for that.

This issue is therefore only about representing events on the timeline.

**Comment by fbarl** [comment]
Some comments @foot made in #2651 (and still need to be considered):

> * I got stressed by the "busy" cursor that appeared as soon as I started dragging. Maybe show that onMouseUp when stuff starts happening.
> * Not a biggie but I'd prefer a "Go!" button next to the textfield, if I'm using it I'm probably making a couple of changes and it feels a bit hectic things changing around as you're trying to enter a value.
timestamp is truncated a tiny bit for me :).
> * Not sure about "live", but can't think of anything else right now.
> * Show the date next to the mouse pointer when dragging? Bit of eye flicking there.

**Comment by fbarl** [comment]
Addressed by #2703.
