### ISSUE TITLE
Time Travel: zoom and pan for easy navigation in time

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2686]
Zooming and panning are well understood control operations for exploring/navigating a space, e.g. on online maps. The same controls work for exploring/navigating in the time dimension.

So imagine a timeline spanning the width of the screen. The mid-point represents the point in time for which scope shows data. The user can
- click-and-drag the timeline to move backward and forward
- hover over any point and use the scroll wheel to expand/contract the window represented by the timeline, with the zoom operation centered around the point under the mouse
- alternatively, use a slider to control zoom around the center point - important for mouse-less operation
- (maybe) click to re-center the timeline of the point under the mouse

**Comment by fbarl** [comment]
This is pretty much the direction where we are already going with the [mockups](https://www.dropbox.com/sh/45hq01047u7zfir/AABQugkx5FjhOOpIGilBB0pBa?dl=0&preview=170705timelineSketch11.png) @bia is working on.

Actually, all the points you mentioned above will be addressed with the new design except maybe the 3rd one (slider for zoom control). The timeline would be zoomable when scrolling over it but ideally we'd want to have an additional way to control the zoom which doesn't look like another control. I'd say this is the main point we'd have to figure for the new design, how to make zooming obvious without ruining the simplicity of the *Time Travel* component.

**Comment by rade** [comment]
> The timeline would be zoomable when scrolling over it but ideally we'd want to have an additional way to control the zoom which doesn't look like another control. 

Exactly. Because we know from experience with the Scope main zoom that a good proportion of users do not realise that the scroll wheel zooms. Which is why we added the little slider.
