### ISSUE TITLE
Deploy details say "Image up to date" when it isn't

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/scope#2697]
_From @abuehrle on May 18, 2017 13:2_

One of my services was recently deployed, and when you click on the recently deployed service, it says, "Image up to date".  This should instead display the image tag or something more useful.

Actually my image isn't up to date, it is 5 versions behind latest. 

<img width="377" alt="screen shot 2017-05-18 at 7 57 08 am" src="https://cloud.githubusercontent.com/assets/13420383/26203289/4c0b60ba-3ba0-11e7-9407-8263903c3302.png">
 

_Copied from original issue: weaveworks/service-ui#557_

**Comment by jpellizzari** [comment]
> One of my services was recently deployed, and when you click on the recently deployed service, it says, "Image up to date". This should instead display the image tag or something more useful.

@abuehrle This is working as intended. The intent was to show the user that an update is available. We already display the container image tag in the details panel for containers.

> Actually my image isn't up to date, it is 5 versions behind latest.

Can you invite me to the instance where this is occurring?

**Comment by abuehrle** [comment]
@jpellizzari I'll have to re-create this scenario, but will invite you.

**Comment by abuehrle** [comment]
You can run through this tutorial here to create it: 

https://www.weave.works/docs/tutorials/core/part-2-deploy-continuous-delivery/

Make more than one commit and then check the tags in Scope. 

I think then this is a feature that will soon fixed?

**Comment by rade** [comment]
Let's wait for flux 1.0.0 to get out there and then re-test this.

**Comment by rade** [comment]
I am seeing this in the sock shop cluster. For example, `kube-system:daemonset/weave-cortex-node-exporter` in the Deploy view shows that the deployed image is `4 version(s) behind latest`, but in the Explore view the corresponding controller details panel says `Image up to date`.

Perhaps that's because automation isn't enabled for that service in Deploy? It should still show the availability of newer images in that case; after all, Deploy does the same. Related: #2932

**Comment by jpellizzari** [comment]
> Perhaps that's because automation isn't enabled for that service in Deploy

Or because someone was sloppy and called `.length` on a something other than an array (it was me).
