### ISSUE TITLE
Popped out terminal hides beneath browser after clicking on main screen

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2706]
Browser: Chrome

When you pop out a terminal and then click somewhere on the main interface, it is hidden beneath the browser.  It makes it look like the window closes when it fact it's just hidden beneath the browser. 

http://recordit.co/5P5LMCUk2v

**Comment by abuehrle** [comment]
>That is totally expected behaviour. You've popped out the window; it's now behaves like any other window on your system.
@rade 
I don't recall the window going directly beneath my browser though. I think this is a z-depth (css) issue.

**Comment by rade** [comment]
A popped out window is a window on your desktop. It behaves like any other window. When you click on the main browser window, it raises that to the foreground, hiding the popped out window behind it. This is totally standard desktop window behaviour.
