### ISSUE TITLE
obscure error when container terminal cannot be opened due to lack of shell

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2707]
Browser: Chrome
AWS ECS in with Weave Cloud

Opening a terminal on the ECS agent in Cloud returns this intermittent error and then closes the connection to the agent: 

```
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec
failed: container_linux.go:247: starting container process caused \"exec: \\\"/b
in/sh\\\": stat /bin/sh: no such file or directory\"\n"
```
I managed to capture an instance of it here: 

http://recordit.co/O1PoNnmOQx

**Comment by rade** [comment]
Does this *ever* work for an ECS agent container?

**Comment by abuehrle** [comment]
Not sure, but maybe remove the ability to do this if it's not possible?

**Comment by rade** [comment]
This is actually a dup of  #1384.

@abuehrle how did you manage to see the error? It's not shown in the recording.

**Comment by abuehrle** [comment]
@rade this error is intermittent, in that case I had to open the terminal twice. It shows it near the end of the video.
