### ISSUE TITLE
Error on opening Pod Logs

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2721]
Katacoda: [keynote demo](https://katacoda.com/courses/weave/keynote-demo)

I'm not sure if this is a Katacoda issue or a Scope problem. But with the Sockshop launched in katacoda, I am getting a `no such node` error in trying to retrieve container logs from the Cart pod. 

http://recordit.co/0Tteg7dEfd

**Comment by rade** [comment]
I very much doubt this is a scope bug; looks like a problem with the katacoda environment / the k8s setup on it.

Alas, I cannot get that tutorial to work at all; I get stuck at step 3 - Weave Cloud doesn't think there are any agents connected.

**Comment by abuehrle** [comment]
You have to paste in the kubectl apply + token command from Weave Cloud in step 2 and then configure Flux. 

I will post this issue over in the katacodas issue. I suspected as much since maybe all the nodes are actually running on the same virtual machine?

**Comment by rade** [comment]
> You have to paste in the kubectl apply + token command from Weave Cloud in step 2 and then configure Flux.

Ah yes, am just doing that now...

**Comment by rade** [comment]
I am getting the same error in the katacoda shell:
```
root@master:~# kubectl -n sock-shop logs cart-2013512370-v9xxq
Error from server: Get https://node01:10250/containerLogs/sock-shop/cart-2013512370-v9xxq/cart:
dial tcp: lookup node01 on 62.210.16.6:53: no such host
```
Looks like name resolution is broken in this katacoda setup.

**Comment by abuehrle** [comment]
Ok thx I will log this one in the katacoda issues.
