### ISSUE TITLE
Controller minor labels don't display properly when controller has no pods

### ISSUE THREAD

**Issue by ekimekim** [weaveworks/scope#2722]
In this example, `configs-db` has 1 pod whereas `configs-db-exporter` has 0. This results in the Pods counter not being present at all, and the string formatting breaking.

Related, the '# Pods' metadata item also doesn't display in the metadata tab, but this is more arguable.

We can fix the minor label issue by changing the minor label formatting code directly, or we can fix the root cause by making all Counter lookups default to 0 for items that aren't there.

**Comment by 2opremio** [comment]
Can you add a screenshot?

**Comment by ekimekim** [comment]
![screenshot](https://user-images.githubusercontent.com/570052/28336621-8caa664c-6bb7-11e7-855e-4504f03306c5.png)
