### ISSUE TITLE
CPU sudden increase

### ISSUE THREAD

**Issue by funkydorian** [weaveworks/scope#2727]
Platform: OpenShift

We also installed sch_netem kernel module for additional latency monitoring.

We are experiencing sudden CPU increase when we install  and CPU went down after we uninstalled.

May it be possible to decrease the frequency?

**Comment by 2opremio** [comment]
Hi @funkydorian . Thanks for reporting this, can you give us more details on:

1. Where are you running Scope? Machine sizes, type of load, containers per machine ...
2. How much CPU is Scope causing. Are the probes (agents) or the app which is causing the high CPU?
3. Ideally could you get us a CPU profile of Scope? See
See https://www.weave.works/docs/scope/latest/building/#profiling

**Comment by rade** [comment]
Could this be a dup of #1544?

**Comment by rade** [comment]
closing as a dup of #1544, at least until more information comes to light.
