### ISSUE TITLE
Stuck at "Locating topologies" after launching on CentOS

### ISSUE THREAD

**Issue by calvintam236** [weaveworks/scope#2737]
OS: CentOS 7 (lastest)
Arch: x86_64

**Comment by rade** [comment]
@calvintam236 any more info on this?

**Comment by calvintam236** [comment]
seems to be Debian comes with older Linux kerne (3.x) that scope cannot run.

**Comment by rade** [comment]
> seems to be Debian comes with older Linux kernel (3.x) that scope cannot run.

Scope should run just fine on kernels >=3.10. Though, I would certainly recommend moving to 4.4 or higher.

**Comment by calvintam236** [comment]
I have already switched back to Ubuntu when scope doesn't launch.
You should able to reproduce the error on the latest version of CentOS even in the virtual machine.
I might attach logs if I have time to install Debian as virtual machine once I have time.. (kinda busy recently)

**Comment by 2opremio** [comment]
I have just run CentOS through Vagrant ( https://app.vagrantup.com/centos/boxes/7 ) and works just fine:

<img width="2048" alt="screen shot 2017-08-08 at 16 04 37" src="https://user-images.githubusercontent.com/2362916/29075780-bd78e9f4-7c53-11e7-8750-bf50480e53ac.png">

Just put the following content in a file called `Vagranfile`:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # on fedora-like, you must use the downloadable package of vagrant
  # available on hashi corp website.
  # The per distrib provided package wont provide winrm support..
  # see https://www.vagrantup.com/downloads.html

  config.vm.define :win2016 do |win|
    win.vm.box = "centos/7"
    win.vm.network "private_network", ip: "172.17.0.6"
  end

end
```

And run the following commands:

```
$ vagrant up
$ vagrant ssh
[vagrant@ip-10-0-2-15 ~]$ sudo yum install docker
[vagrant@ip-10-0-2-15 ~]$ sudo systemctl start docker
[vagrant@ip-10-0-2-15 ~]$ sudo curl -L git.io/scope -o /usr/local/bin/scope
[vagrant@ip-10-0-2-15 ~]$ sudo chmod a+x /usr/local/bin/scope
[vagrant@ip-10-0-2-15 ~]$ sudo /usr/local/bin/scope launch
```
