### ISSUE TITLE
"Local Networks" is confusing

### ISSUE THREAD

**Issue by bboreham** [weaveworks/scope#2748]
I don't really know what it is supposed to be, but maybe strip out the `/32` entries because they are not "networks"?

![image](https://user-images.githubusercontent.com/8125524/28571719-20d64f82-713c-11e7-8121-2e9f65389c06.png)

**Comment by rade** [comment]
The /32 are there because of an evil hack to do with k8s services.

**Comment by 2opremio** [comment]
These are the K8s services. There wasn't a clean way to add them cleanly bec ause k8s doesn't expose the service network CIDR. https://github.com/kubernetes/kubernetes/issues/25533

**Comment by bboreham** [comment]
But why are you showing them to the user on that screen?  What is she supposed to do with them?

**Comment by rade** [comment]
Why are we showing "Local Networks" *at all*?

Currently this contains
- the networks of host interfaces
- the IPAM ranges of docker networks
- the Weave Net IPAM default subnet
- all k8s service IPs
