### ISSUE TITLE
Controllers view, deployment detail panel, desired replica error

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#2751]
In the new Scope view for Kubernetes Controllers, the detail panel of a Deployment shows an unexpected value for the "Desired Replicas" property.

<img width="1054" alt="controllers-detail-panel" src="https://user-images.githubusercontent.com/303151/28572778-4ad13d66-7140-11e7-93ce-2114bbef0d6e.png">

**Comment by ekimekim** [comment]
This was fixed in 38814d54a615683894a6fb1e90c383982f681677 (part of #2724), update your probe.
At a guess, it was introduced by #2659. Do we need to do a fix release?

**Comment by rade** [comment]
> Do we need to do a fix release?

Nah.
