### ISSUE TITLE
Search for "type:Daemon Set" is impossible

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#2752]
As a user of the new Kubernetes Controllers view I want to search by type of controller.

I can search using the filter "type:Deployment", but as "Daemon Set" contains a space, I can't search for it.

**Comment by ekimekim** [comment]
I could change the name to `Daemonset`, but that doesn't really fix the issue. We need either some frontend work to remove the limitation of the search syntax, or add back in the type filter option group.

**Comment by rade** [comment]
> I could change the name to `Daemonset`, but that doesn't really fix the issue.

It would fix the issue in practice for now though, would it not?

> add back in the type filter option group.

No way. I am enjoying the reduced clutter.

**Comment by pidster** [comment]
I note: the [Kubernetes docs refer to the object](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/) using a single word 'DaemonSet'.
