### ISSUE TITLE
Time Travel takes up too much vertical space

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2770]
Time Travel takes up a lot of vertical space, for no apparent reason. E.g. look at
![screenshot from 2017-07-29 15-49-58](https://user-images.githubusercontent.com/109109/28745813-11bf798a-7478-11e7-9e1c-c1da2a82ad04.png)
There's an entire blank "row" at the top, above the year. And the timestamp below takes up a whole row too - surely we can find a better place for that.

Vertical space matters for the likes of the details panel, so we don't want to lose it for no good reason.

**Comment by fbarl** [comment]
My suggestion would be to wait with this story a bit to see how repositioning of the top controls would affect the vertical space (e.g. see [these mockups](https://www.dropbox.com/sh/45hq01047u7zfir/AABQugkx5FjhOOpIGilBB0pBa?dl=0&preview=170710timelineSketch2.png)).

> ... the timestamp below takes up a whole row too - surely we can find a better place for that.

This has already been addressed by the mockups above and was planned to be implemented in #2702, but that was put on hold for a bit until we figure the new layout completely (with repositioned controls).

> There's an entire blank "row" at the top, above the year.

That's only true when you're not zoomed into hours/minutes, and I assume users would very often be zoomed in to that level. Also, a lot of that unused vertical space will start to be used soon by the metadata and I'd rather see where that takes us and then take away some vertical space if we can than taking it away now and then reverting it back when we put in the metadata.

One idea that I think @bboreham suggested would be to always keep at most 3 rows of time tags, i.e. fade out the years when we'd enter hours/minutes precision. I think that might be one way to go, but I'd rather try to fill in the timeline with some metadata and get some user metrics before we make a final judgement.

**Comment by rade** [comment]
> My suggestion would be to wait with this story a bit to see how repositioning of the top controls would affect the vertical space

Fair enough, though that design will need some more iterations.

> One idea that I think @bboreham suggested would be to always keep at most 3 rows of time tags,

Or even just two. Though for now I suggest we simply drop the year. After all the year is easy to tell from the timestamp, and we don't envisage providing time travel for more than 13 months, so there will never be more than two different years to display.

> but I'd rather try to fill in the timeline with some metadata and get some user metrics before we make a final judgement.

That may not happen for a while. Let's see whether we can make some quick improvements before then.

**Comment by fbarl** [comment]
> Though for now I suggest we simply drop the year. After all the year is easy to tell from the timestamp, and we don't envisage providing time travel for more than 13 months, so there will never be more than two different years to display.

Alright, I'll make the years fade out with zooming, keeping at most 3 rows of time tags visible at a time.

> [adding metadata] That may not happen for a while.

Actually, I'd be curious to try adding deployments metadata tomorrow (like the current Cortex blue dot annotations). If it'd look like more than 1 day of work, I'd drop it for now, otherwise I'd just go with it.
