### ISSUE TITLE
update ECS AMI to latest version

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2773]
The [ECS AMI](https://www.weave.works/docs/scope/latest/ami/) is currently [shipping Scope 1.3.0 and Net 1.9.4](https://www.weave.works/docs/scope/latest/ami/#whats-in-ecs-ami). We should update to the latest Scope and Net releases (1.6.1 and 2.0.1, at this point).

**Comment by bboreham** [comment]
This was done in https://github.com/weaveworks/integrations/pull/133
