### ISSUE TITLE
scope container growing memory usage

### ISSUE THREAD

**Issue by calvintam236** [weaveworks/scope#2780]
Version: v1.6.1

After running a day of v1.6.1, the RAM usage increased to ~450MB from ~150MB in one day. I had to restart the container manually. Maybe there is a memory leak? (The scope page is open for the whole time)

**Comment by 2opremio** [comment]
Is this the app or the probe? Could you get us a memory profile following https://www.weave.works/docs/scope/latest/building/#profiling

**Comment by calvintam236** [comment]
It seems the extra ram usage are not by those two processes. Attached the profiling below.


![screen shot 2017-07-31 at 9 57 10 pm](https://user-images.githubusercontent.com/6436149/28809926-6a004d12-763b-11e7-9856-11f4d9a425f3.png)
![screen shot 2017-07-31 at 10 05 07 pm](https://user-images.githubusercontent.com/6436149/28810052-62af3a86-763c-11e7-9fe0-b80db33fd703.png)


[pprof.scope.localhost-4040.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz](https://github.com/weaveworks/scope/files/1189533/pprof.scope.localhost-4040.alloc_objects.alloc_space.inuse_objects.inuse_space.001.pb.gz)

**Comment by 2opremio** [comment]
Can you show me the memory consumption of the other two processes running in the container (hidden under `+2`).

Your profile shows that the scope app is only consuming 34MB (resident memory). Note that the Go runtime allocates large memory regions for goroutines which stay in virtual memory until used (i.e. they are accounted for but don't really correspond to consumed memory), see https://github.com/weaveworks/scope/issues/266#issuecomment-174004355 , specifically:

> But checking `/proc/$(pgrep -f scope-app)/status` shows that there are large regions (the heap/stack of goroutines?) which effectively account to to virtual memory but which are not mapped to physical memory (yet).

Also, related https://github.com/weaveworks/scope/issues/1133

**Comment by calvintam236** [comment]
![screen shot 2017-08-03 at 11 57 55 am](https://user-images.githubusercontent.com/6436149/28938475-08c767ec-7843-11e7-95fd-e184f497de18.png)
No permission for root running `/proc/$(pgrep -f scope-app)/status`


![screen shot 2017-08-03 at 11 55 34 am](https://user-images.githubusercontent.com/6436149/28938357-b45af412-7842-11e7-9990-10d965129424.png)

Reproduce:
- attach the host in scope
- run `PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin apt dist-upgrade`
before start 290mb, after execution 1.3gb

**Comment by 2opremio** [comment]
> No permission for root running /proc/$(pgrep -f scope-app)/status

That's not an executable file

> before start 290mb, after execution 1.3gb

Where can I see that 1.3 GB figure?

**Comment by calvintam236** [comment]
![screen shot 2017-08-12 at 1 32 28 am](https://user-images.githubusercontent.com/6436149/29239238-b9b1aee8-7efe-11e7-8f5d-22c747b57d13.png)
![screen shot 2017-08-12 at 1 32 43 am](https://user-images.githubusercontent.com/6436149/29239237-b9b00ba6-7efe-11e7-9e31-1391f504519b.png)

**Comment by rade** [comment]
When you are launching a host terminal in scope, all processes in it are associated with the scope container. Hence, as you can see from your 2nd screenshot, your 'apt' process is part of the scope container, and hence its memory usage is counted towards the scope container. The memory usage of scope itself hasn't changed, as you can see from the reported usage of the `scope-app` and `scope-probe` processes.

**Comment by calvintam236** [comment]
So is it correct to have more memory used in a container than the real memory usage here. What is the UVM in the processes?

![screen shot 2017-09-15 at 2 15 22 pm](https://user-images.githubusercontent.com/6436149/30503848-a43f885e-9a20-11e7-9cf1-83a0a9032d5b.png)
![screen shot 2017-09-15 at 2 17 09 pm](https://user-images.githubusercontent.com/6436149/30503849-a44c93c8-9a20-11e7-9beb-2f9108a24611.png)

**Comment by rade** [comment]
>  What is the UVM in the processes?

I have no idea. Probably some OS process.

In the absence of compelling evidence that there really is a leak, I am closing this. Happy to re-open when there is more data.

**Comment by AmazingTurtle** [comment]
My nodes are becoming unresponsive because weavescope leaks memory. I may got SSH running (close to timeout) and managed to run `$ ps -o pid,user,%mem,command ax | sort -b -k3 -r` which gave me:

```
  PID USER     %MEM COMMAND
17784 root     60.5 /home/weave/scope --mode=app
```

free -m shows:
```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1955        1702          65           1         187          48
Swap:             0           0           0
```
