### ISSUE TITLE
Time Travel: timeline labels are cut off at bottom on Chrome

### ISSUE THREAD

**Issue by rndstr** [weaveworks/scope#2789]
![time-travel-line-height-chromium](https://user-images.githubusercontent.com/32963/28917329-90542f54-7845-11e7-9476-4ba9ee5be250.png)

I played around with `line-height` which would fix the issue for Chrome (but possibly break it for FF) 

OS | Linux
Chromium | 59.0.3071.115 (Developer Build) (64-bit)
&&
Google Chrome | 60.0.3112.66 (Official Build) beta (64-bit)

(Looks fine in FF)

**Comment by rade** [comment]
This looks totally fine for me in dev, in both chrome 60.0.3112.78 and FF 54.0 on Ubuntu.

![screenshot from 2017-08-03 11-44-32](https://user-images.githubusercontent.com/109109/28918473-465568c2-7841-11e7-9ba4-5e235d7dafe1.png)
![screenshot from 2017-08-03 11-45-23](https://user-images.githubusercontent.com/109109/28918491-557230a6-7841-11e7-9e05-0c767d53c742.png)

**Comment by rndstr** [comment]
`foreignObject { line-height: 150% }` fixes it for me on Chrome while keeps it as is on FF (where it already computes the correct value `19.5px`)

`19.5px` stems from 13px (font-size of <a>) * 150% (inherited line-height) 

Not sure where or why Chrome miscalculates this and ends up as `39px`. The parent element has the correct `19.5px` line-height.
