### ISSUE TITLE
clusterroles.rbac.authorization.k8s.io "weave-scope" is forbidden: attempt to grant extra privileges

### ISSUE THREAD

**Issue by rzhang2403** [weaveworks/scope#2797]
Used:  k8s 1.7.0
Tried to install the weave-scope agent, flux agent on the k8s cluster, and got the following errors:

~/.kube$ kubectl apply -n kube-system -f    "https://cloud.weave.works/k8s.yaml?t=_service_token_&k8s-version=$(kubectl version | base64 | tr -d '\n')"
serviceaccount "weave-flux" configured
clusterrolebinding "weave-flux" configured
deployment "weave-flux-agent" configured
serviceaccount "weave-scope" configured
clusterrolebinding "weave-scope" configured
serviceaccount "weave-cortex" configured
clusterrolebinding "weave-cortex" configured
deployment "weave-cortex-agent" configured
service "weave-cortex-agent" configured
configmap "weave-cortex-agent-config" configured
Error from server (Forbidden): clusterroles.rbac.authorization.k8s.io "weave-flux" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["*"], APIGroups:["*"], Verbs:["*"]} PolicyRule{NonResourceURLs:["*"], Verbs:["*"]}] user=&{admin admin [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
Error from server (Forbidden): clusterroles.rbac.authorization.k8s.io "weave-scope" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["*"], APIGroups:["*"], Verbs:["*"]} PolicyRule{NonResourceURLs:["*"], Verbs:["*"]}] user=&{admin admin [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
Error from server (Invalid): DaemonSet.extensions "weave-scope-agent" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
Error from server (Forbidden): clusterroles.rbac.authorization.k8s.io "weave-cortex" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["*"], APIGroups:["*"], Verbs:["*"]} PolicyRule{NonResourceURLs:["*"], Verbs:["*"]}] user=&{admin admin [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
Error from server (Invalid): DaemonSet.extensions "weave-cortex-node-exporter" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy

Any idea?  Thanks.

**Comment by rade** [comment]
@errordeveloper any idea?

**Comment by errordeveloper** [comment]
@rzhang2403 you will need to tweak some RBAC settings, but before I  can
tell you more, I will need more info on  how was this cluster created, did
you use a in-house installer or perhaps it is a hosted version of
Kubernetes of some sort?

**Comment by rzhang2403** [comment]
We used the Canonical Distribution for Kubernetes on the AWS.  It creates the planned k8s nodes for the applications.  The k8s is the 1.7.0, not latest.   Before this, when I used the weave scope on my local vmware environment with k8s 1.6.x, it was working fine.   I understood that either the 1.7 requires the RBAC configuration, or the Canonical doesn't set this properly.  Thanks for the helps.

**Comment by errordeveloper** [comment]
@rzhang2403 as far as I'm aware, the Canonical distribution doesn't enable RBAC, unless you've explicitly enabled it yourself.

Could you please try this and let me know if it works  for you:
```
curl -s \
  https://gist.githubusercontent.com/errordeveloper/1e5cd249669b158da4b70e43b21d37d7/raw/e5bdc67fb5ff7e45e2a2cecaf0d850ef53369af7/weave-cloud-kube-1.7-without-rbac.yaml \
  | sed 's/_service_token_/_your_service_token_/' \
  | kubectl apply -n kube-system -f -
```

**Comment by rzhang2403** [comment]
I tried the above suggestion, and got the following error:

serviceaccount "weave-flux" configured
deployment "weave-flux-agent" configured
serviceaccount "weave-scope" configured
serviceaccount "weave-cortex" configured
deployment "weave-cortex-agent" configured
service "weave-cortex-agent" configured
configmap "weave-cortex-agent-config" configured
Error from server (Invalid): DaemonSet.extensions "weave-scope-agent" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy
Error from server (Invalid): DaemonSet.extensions "weave-cortex-node-exporter" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy

**Comment by errordeveloper** [comment]
To fix this you will need to run
```shell
juju config kubernetes-master allow-privileged=true
juju config kubernetes-worker allow-privileged=true
```shell
And then re-run
```
curl -s \
  https://gist.githubusercontent.com/errordeveloper/1e5cd249669b158da4b70e43b21d37d7/raw/e5bdc67fb5ff7e45e2a2cecaf0d850ef53369af7/weave-cloud-kube-1.7-without-rbac.yaml \
  | sed 's/_service_token_/_your_service_token_/' \
  | kubectl apply -n kube-system -f -
```

**Comment by rzhang2403** [comment]
It works now.  Thanks!

**Comment by kedare** [comment]
Any idea of how to fix it without Juju (On GKE in our case) ?

```
namespace "weave" created
serviceaccount "weave-scope" created
clusterrolebinding "weave-scope" created
deployment "weave-scope-app" created
service "weave-scope-app" created
daemonset "weave-scope-agent" created
Error from server (Forbidden): clusterroles.rbac.authorization.k8s.io "weave-scope" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["*"], APIGroups:["*"], Verbs:["*"]} PolicyRule{NonResourceURLs:["*"], Verbs:["*"]}] user=&{mathieu@lodgify.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]} PolicyRule{NonResourceURLs:["/swagger-2.0.0.pb-v1"], Verbs:["get"]} PolicyRule{NonResourceURLs:["/swagger.json"], Verbs:["get"]}] ruleResolutionErrors=[]
```

**Comment by rade** [comment]
@kedare a GKE install should just work. We are doing these all the time; I ran through one only a couple of days ago. Did you run the extra command that is in GKE install instructions in Weave Cloud?
```
kubectl create clusterrolebinding "cluster-admin-$(whoami)" --clusterrole=cluster-admin --user="$(gcloud config get-value core/account)"
```

**Comment by allanlei** [comment]
I am also getting the same error as @kedare on GKE 1.8.7 in a testing cluster.

Following instructions at https://www.weave.works/docs/scope/latest/installing/#k8s-standalone and don't see a reference to `kubectl create clusterrolebinding "cluster-admin-$(whoami)" --clusterrole=cluster-admin --user="$(gcloud config get-value core/account)"`

```
amespace "weave" created
serviceaccount "weave-scope" created
clusterrolebinding "weave-scope" created
deployment "weave-scope-app" created
service "weave-scope-app" created
daemonset "weave-scope-agent" created
Error from server (Forbidden): clusterroles.rbac.authorization.k8s.io "weave-scope" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["*"], APIGroups:["*"], Verbs:["*"]} PolicyRule{NonResourceURLs:["*"], Verbs:["*"]}] user=&{allan@17.media  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]} PolicyRule{NonResourceURLs:["/swagger-2.0.0.pb-v1"], Verbs:["get"]} PolicyRule{NonResourceURLs:["/swagger.json"], Verbs:["get"]}] ruleResolutionErrors=[]
```

@rade Can you provide the link? I might be missing it

**Comment by rade** [comment]
The instructions are embedded in Weave Cloud. I have filed #3051to get the docs updated.
