### ISSUE TITLE
Time Travel: namespace selection does not respect time

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2802]
This is a picture of Weave Cloud dev from about a year ago...
![screenshot from 2017-08-08 23-44-20](https://user-images.githubusercontent.com/109109/29097802-b5a8347e-7c93-11e7-9c01-e2623aa56ae3.png)
Notice that I've selected the 'cortex' namespace. But at that time no cortex namespace existed, so it shouldn't really be shown. And even if it was shown, selecting it certainly shouldn't display any nodes. The graph that is displayed actually shows *all* nodes.

**Comment by fbarl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Time Travel - namespace selection does not respect time](https://trello.com/c/0LnsuaMR/31-time-travel-namespace-selection-does-not-respect-time)
