### ISSUE TITLE
Details on process-by-name grouping aren't showing both processes

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#281]

**Comment by tomwilkie** [comment]
This was causes by newline (\n) making it into rendered node ids.  I've trimmed the newline off the process name to prevent this.

I believe that was another UI issue @davkal; looks like the UI doesn't escape newlines in generate URLs correctly.  Will leave this ticket open to discuss that.

**Comment by davkal** [comment]
Why are there newlines in the first place?

**Comment by tomwilkie** [comment]
Oh the file we were reading to get the process name had a newline at its end.  Thats fixed now.  But I think it unearthed a bug in the UI, so probably worth you investigating.
