### ISSUE TITLE
Communication between Weave CNI in Kubernetes & Datacenter network.

### ISSUE THREAD

**Issue by prasenforu** [weaveworks/scope#2813]
Communication between Weave CNI in Kubernetes & Datacenter network with firewall.

I came out some used case where this discussion fall.

Let me explain little briefly.

We running multiple pod inside kubernetes platform. Take examples APP-1, APP-2 APP-3.

Now my multiple databases (DB-1, DB-2, DB-3) running outside kubernetes cluser. In front of all database there was firewall.

Now App-1only can connect DB-1 no other container should connect DB-1 similarly App-2 only connect DB-2 Not others for App-3 also same way.

As kubernetes uses flat networking so each container can talk other even outside side of kubernetes cluster.

Can you please explain how networks policy will be in this given scenario & what changes (rule or policy) we have to do in external firewall.

**Comment by rade** [comment]
This issue appears to have nothing to do with Weave Scope, but concerns Weave Net and CNI. I suggest you follow the [Weave Net Getting Help](https://github.com/weaveworks/weave#getting-help) instructions.
