### ISSUE TITLE
Show name of the host you're connected to in the UI

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#282]

**Comment by tomwilkie** [comment]
Would also be useful to show name of probes which the host you are connected to is connected to.

**Comment by davkal** [comment]
* How can I be connected to hosts (multiple that is)?
* What is the motivation behind this?

**Comment by tomwilkie** [comment]
This was mainly to help me debug situations where I'm seeing inconsistencies between hosts.  If its useful for me, it might be useful in the field for a user.

**Comment by davkal** [comment]
Is this still wanted? If so, I propose putting this info in the response to `/api`

**Comment by tomwilkie** [comment]
Yeah I think this would be useful.  Will stick it in /api

**Comment by tomwilkie** [comment]
Ah I forgot this was waiting on me!
