### ISSUE TITLE
Switching from one instance to another retains search data it shouldn't

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2831]
In one instance: kubernetes cluster set up with the sock shop running.   Search for Flux, and let it highlight where it finds the term: 

![screen shot 2017-08-21 at 2 20 00 pm](https://user-images.githubusercontent.com/13420383/29538898-91a67822-867c-11e7-910e-a7ac7375ca20.png)

Now switch to an empty instance. Notice the search term 'flux' is carried over to the empty instance and it is disabled and can't be deleted. 

![disabled-search-term](https://user-images.githubusercontent.com/13420383/29538944-cd7f97e8-867c-11e7-96e2-597a334b2cd9.png)

**Comment by rade** [comment]
The retention of the search data is intentional.

The reason you cannot change it is because there is no data available at all for that instance.

**Comment by abuehrle** [comment]
This is also carried over if you have say the properties panel open on a container that doesn't exist in the instance you are switching to and it look like an error.

**Comment by rade** [comment]
I am not seeing that.

When I switch instances with a detail panel open, and the new instance doesn't have the corresponding object, then I just get shown the underlying topology, with no detail panel.
