### ISSUE TITLE
Does Scope can show historical metrics?

### ISSUE THREAD

**Issue by WangHouLing** [weaveworks/scope#2832]
Hi,

Scope default display within 15 seconds of data, this can not see the overall long-term performance trends. It may be possible to change the time limit by modifying the configuration file, or to use the timeline to select the time.I do not know if it is feasible, please help me find more information.

I will be grateful for any help you can provide.

**Comment by rade** [comment]
Scope isn't really designed as a general metrics gathering platform, or for retaining historic data (it has no storage). Such features *are* available in [Weave Cloud](https://www.weave.works/product/cloud/), which a) retains historic scope data, including metrics, and has a "time travel" feature to inspect the past state of the system, b) gathers and stores a plethora of metrics via Prometheus, and c) links Scope entities to associated Prometheus metrics.

**Comment by WangHouLing** [comment]
@rade Thank you!
