### ISSUE TITLE
How to run "weave status" command when weave net deployed in container 

### ISSUE THREAD

**Issue by panxia6679** [weaveworks/scope#2845]
Is there anyone to tell me how I can run "weave status" command  (just like ones in https://www.weave.works/docs/net/latest/troubleshooting/) when weave net was deployed in container.  

When I tried to run the "weave status" from container directly, I got the following errors.

Thanks.

~~~
/home/weave # ./weave status
./weave: line 250: docker: not found
ERROR: Unable to parse docker version
/home/weave # ./weave report
./weave: line 250: docker: not found
ERROR: Unable to parse docker version
/home/weave # ./weave version
weave script 2.0.1
./weave: line 250: docker: not found
ERROR: Unable to parse docker version
~~~

#weave is deployed in kubernate in the following way.
wget https://git.io/weave-kube
kubectl create -f weave-kube

**Comment by bboreham** [comment]
@panxia6679 Please see https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#troubleshooting for information specific to this situation.

Brief summary: you need to add `--local`

**Comment by panxia6679** [comment]
thanks @bboreham.

**Comment by hemantaltair** [comment]
Still it's not working

**Comment by StephanX** [comment]
the syntax is `weave --local status`
