### ISSUE TITLE
Scope stays in reticulating or fetching pods when switching contexts

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2847]
Cloud/OS: Digital Ocean/ Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-79-generic x86_64)
Kubernetes: ```Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}```

Sockshop running

When switching contexts say from the Deploy config page back to Explore, results in the screen spending a long time redrawing.  

Pressing pause on the timeline sometimes breaks it out of churning and restores the live state, but not always, and once it does load again, the same occurs when you switch contexts again.

Please see:  

http://recordit.co/oFfjA94ZeV

I have my instance running if you need to see it.

**Comment by rade** [comment]
I think that was just a case of Weave Cloud being overloaded at the time. If it happens again, try waiting for longer - if the topology hasn't drawn after 10s then something else might be amiss.
