### ISSUE TITLE
Time-travel does not clear the display on error

### ISSUE THREAD

**Issue by bboreham** [weaveworks/scope#2849]
First I time-travel to one date:

![image](https://user-images.githubusercontent.com/8125524/30247958-146597ee-9617-11e7-8a62-8190f8724cd4.png)

Then I time-travel to an earlier date and get an error message, but it hasn't cleared the old display:

![image](https://user-images.githubusercontent.com/8125524/30247984-541c8dca-9617-11e7-9ce5-33ca29a2ef1c.png)

If I mouse over the main view then it redraws.

Using Chrome on Windows.

**Comment by rade** [comment]
I cannot reproduce this. Running FF on Linux. @bboreham is this still happening for you?

**Comment by bboreham** [comment]
Seems to be fixed for me using Chrome on Mac
