### ISSUE TITLE
Graph view edges sometimes disappear

### ISSUE THREAD

**Issue by fbarl** [weaveworks/scope#2850]
@rade noticed in #2848 that _occasionally all the edges disappear_, but probably the issue has been there for a while.

![edges-missing](https://user-images.githubusercontent.com/1216874/30277043-f132500a-9706-11e7-8159-612b3e767781.png)

**Comment by rade** [comment]
I've seen this before, very occasionally, but now it happens *a lot*

**Comment by rade** [comment]
@fbarl is this issue present in the most recent Scope OSS release?

**Comment by fbarl** [comment]
> is this issue present in the most recent Scope OSS release?

@rade I tested it on the branch `release-1.6` and I'm afraid the answer is yes :( Do you think the bug is serious enough to get a patch release? cc @2opremio

**Comment by rade** [comment]
> Do you think the bug is serious enough to get a patch release

I am seeing this *a lot* in Weave Cloud; if the problem occurs anywhere near that often for OSS Scope then yes, we should do a release.

**Comment by 2opremio** [comment]
I will take care of making a new release next week

**Comment by fbarl** [comment]
> I will take care of making a new release next week

Thanks @2opremio!
