### ISSUE TITLE
Uptime should be shown in days

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/scope#2875]
At the moment, uptime seems to only be in hours, even after many hours. The uptime should be shown in days at some point, say after 24, 48 or 72 hours.
![uptime-in-days](https://user-images.githubusercontent.com/7986/31084408-3ddd2da4-a78c-11e7-9e8b-572bac0f8a88.png)

(Also we could add spaces between days/hours/minutes):

```
629h49m54s
```
vs
```
26 days
```

**Comment by dlespiau** [comment]
Also, we probably don't care about the seconds if the node has been up for 62 days. I'd suggest we un-clutter a bit the display at that point and only show days/hours. A tooltip on hover could show the full details (maybe).

**Comment by fbarl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scope uptime should be shown in days](https://trello.com/c/YHhIkroa/171-scope-uptime-should-be-shown-in-days)
