### ISSUE TITLE
Is scope compatible with Project Photon on Fusion?

### ISSUE THREAD

**Issue by MichelDiz** [weaveworks/scope#2876]
See https://github.com/vmware/photon/wiki/Running-Project-Photon-on-Fusion

Cheers

**Comment by dlespiau** [comment]
Hi,

From what I understand of the project, it's a Linux distribution where you can install the docker daemon. It looks like scope would have no problem running on it: scope runs as a privileged docker container and (can) use the docker daemon APIs to report information about container & control your containers.

HTH,
