### ISSUE TITLE
probe/host is completely broken and doesn't compile on Darwin

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#288]
- Uname is only defined for Linux, so we need to mock it out at a higher level, i.e. getKernelVersion
- Darwin doesn't have /proc, so same deal for /proc/{uptime,loadavg}
- Perhaps more as I discover them...

**Comment by tomwilkie** [comment]
Can we add a GOOS=darwin step to circle to prevent this happening again?

**Comment by peterbourgon** [comment]
Yeah, let's do it! I'll fold it into the PR I'm making.

**Comment by peterbourgon** [comment]
Closed by #289
