### ISSUE TITLE
Pinch to zoom doesn't work under Linux

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#2884]
Reported by @rade.

- Chrome / FF not responding to pinch to zoom gesture under Linux. It should zoom in / out on the node canvas.
- Works under OSX but the sensitivity is very low.

**Comment by rade** [comment]
Interestingly this does work with my track pad, but not my touch screen. And Google Maps is similarly affected. I suspect this is a driver issue, and not in fact a Scope bug.
