### ISSUE TITLE
Time Travel: adjust control to available time range

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2887]
I've seen a number of users run into difficulty with the time travel controls because they were panning too far in the past. This is most prominent when users have only just installed scope etc since then they will only have a few seconds worth of data.

We should be able to determine the datetime of the first data point, and hence adjust the controls accordingly. Some suggestions:

- visual indicator of "no data beyond here", e.g. similar to the way the future is coloured differently
- prevent panning beyond the first data point, similar to how one is prevented from panning into the future
- adjust the initial zoom level to be further zoomed in when the first data point is very recent, so that panning works meaningfully out of the box in these situations.

cc @bia @fbarl

**Comment by fbarl** [comment]
If we want to go with a simple and accurate approach that doesn't require any work on the backend, I think saying things began at `firstSeenConnectedAt` would tie nicely with the new onboarding flow.

The downside is that not all users would have access to that field:
* People using Scope standalone with their own report storage other than Weave Cloud for which Time Travel would be available - possible in theory, but not sure there are such people yet.
* People who are able to use Scope in Weave Cloud, but somehow don't have `firstSeenConnectedAt` field set - also not sure how big that group is.

I think using `firstSeenConnectedAt` would still work for a big majority of our users, so maybe it's a good place to start?

cc @aaron7

**Comment by rade** [comment]
Relying on `firstSeenConnectedAt` seems reasonable to me, but I would like to hear whether @aaron7 can think of any gotchas or better option.

**Comment by fbarl** [comment]
@dlespiau @leth - since @aaron7 is on holiday, maybe you could share your thoughts here.

If there are no blockers, I'd like to pick up this issue after lunch :)

**Comment by leth** [comment]
Sounds good to me!

> People who are able to use Scope in Weave Cloud, but somehow don't have firstSeenConnectedAt field set - also not sure how big that group is.

Our intent is that this should be zero people; (i.e. everyone should have a firstSeenConnectedAt). I don't have hard data on that though.

**Comment by leth** [comment]
Oh, actually, if `firstSeenConnectedAt` is for some reason not set, they'll be prevented from viewing scope until it is. So it's a safe thing to assume.

**Comment by fbarl** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use `firstSeenConnectedAt` as beginning of time in Time Travel](https://trello.com/c/NaWMs59W/166-use-firstseenconnectedat-as-beginning-of-time-in-time-travel)
