### ISSUE TITLE
Is `render.Row.ValueMinor` still needed?

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#290]
It is only ever set to `""`, so should be removed. Unless it has some other purpose?

**Comment by peterbourgon** [comment]
We can remove it for now, but it's designed to hold units. For example, when we report bandwidth, KB/s, or MB/s, or etc.

**Comment by peterbourgon** [comment]
Probably this can be addressed with #301.

**Comment by peterbourgon** [comment]
Closing in deference to #301
