### ISSUE TITLE
K8S(1.8) cluster not showing Scope UI using NodePort option

### ISSUE THREAD

**Issue by thatsk** [weaveworks/scope#2904]
I am using Kubernetes 1.8 cluster 
i have deployed 4 node cluster using kubeadm and also deployed kubernetes dashboard .I am trying to deploy weavescope but not getting UI showing on browser.
I have deployed Weave Scope UI as per your DOC:-
https://www.weave.works/docs/scope/latest/installing/#k8s

So what i run commands on kubernetes master as follows:-
```code
kubectl apply --namespace kube-system -f "https://cloud.weave.works/k8s/scope.yaml?k8s-version=$(kubectl version | base64 | tr -d '\n')?k8s-service-type=NodePort"
````
```
kubectl port-forward -n kube-system "$(kubectl get -n kube-system pod --selector=weave-scope-component=app -o jsonpath='{.items..metadata.name}')" 4040
```
When i Run above command i am getting following Output:-
```
Forwarding from 127.0.0.1:4040 -> 4040
```
Tried Following URL in browser But Not showing Scope UI:-
```
http://node-name:4040 OR https://node-name:4040
```

**Comment by thatsk** [comment]
When i checking the logs i get some error they are as follows:-
```
 kubectl logs -n kube-system weave-scope-app-567cfdb6d5-k5nbw
```
Output:-
```
<app> INFO: 2017/10/20 19:24:24.939146 app starting, version 1.6.5, ID 7f05df408cec211c
<app> INFO: 2017/10/20 19:24:24.939440 command line args: --mode=app --no-probe=true
<app> INFO: 2017/10/20 19:24:24.955916 listening on :4040
<app> WARN: 2017/10/20 19:24:25.011041 Error updating weaveDNS, backing off 20s: Error running weave ps: exit status 1: "Link not found\n"
<app> WARN: 2017/10/20 19:24:45.052765 Error updating weaveDNS, backing off 40s: Error running weave ps: exit status 1: "Link not found\n"
```

**Comment by rade** [comment]
>  i get some error

These are `WARN`ings. You can ignore them.

> Tried Following URL in browser But Not showing Scope UI: `http://node-name:4040 OR https://node-name:4040`

The instructions make scope accessible on the host on which the `kubectl` command is run. It looks like you are running `kubectl` on the master and then try to access scope from a different machine - that won't work.

**Comment by thatsk** [comment]
@rade  When i check the 
{code}
kubectl -n kube-system edit svc weave-scope-app
{code}
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.weave.works/launcher-info: |-
      {
        "server-version": "master-1677a73",
        "original-request": {
          "url": "/k8s/v1.7/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI4IiwgR2l0VmVyc2lvbjoidjEuOC4xIiwgR2l0Q29tbWl0OiJmMzhlNDNiMjIxZDA4ODUwMTcyYTlhNGVhNzg1YTg2YTNmZmEzYjNhIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0xMC0xMVQyMzoyNzozNVoiLCBHb1ZlcnNpb246ImdvMS44LjMiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjgiLCBHaXRWZXJzaW9uOiJ2MS44LjEiLCBHaXRDb21taXQ6ImYzOGU0M2IyMjFkMDg4NTAxNzJhOWE0ZWE3ODVhODZhM2ZmYTNiM2EiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE3LTEwLTExVDIzOjE2OjQxWiIsIEdvVmVyc2lvbjoiZ28xLjguMyIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJsaW51eC9hbWQ2NCJ9Cg==?k8s-service-type=NodePort",
          "date": "Fri Oct 20 2017 19:24:23 GMT+0000 (UTC)"
        },
        "email-address": "support@weave.works"
      }
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"cloud.weave.works/launcher-info":"{\n  \"server-version\": \"master-1677a73\",\n  \"original-request\": {\n    \"url\": \"/k8s/v1.7/scope.yaml?k8s-version=Q2xpZW50IFZlcnNpb246IHZlcnNpb24uSW5mb3tNYWpvcjoiMSIsIE1pbm9yOiI4IiwgR2l0VmVyc2lvbjoidjEuOC4xIiwgR2l0Q29tbWl0OiJmMzhlNDNiMjIxZDA4ODUwMTcyYTlhNGVhNzg1YTg2YTNmZmEzYjNhIiwgR2l0VHJlZVN0YXRlOiJjbGVhbiIsIEJ1aWxkRGF0ZToiMjAxNy0xMC0xMVQyMzoyNzozNVoiLCBHb1ZlcnNpb246ImdvMS44LjMiLCBDb21waWxlcjoiZ2MiLCBQbGF0Zm9ybToibGludXgvYW1kNjQifQpTZXJ2ZXIgVmVyc2lvbjogdmVyc2lvbi5JbmZve01ham9yOiIxIiwgTWlub3I6IjgiLCBHaXRWZXJzaW9uOiJ2MS44LjEiLCBHaXRDb21taXQ6ImYzOGU0M2IyMjFkMDg4NTAxNzJhOWE0ZWE3ODVhODZhM2ZmYTNiM2EiLCBHaXRUcmVlU3RhdGU6ImNsZWFuIiwgQnVpbGREYXRlOiIyMDE3LTEwLTExVDIzOjE2OjQxWiIsIEdvVmVyc2lvbjoiZ28xLjguMyIsIENvbXBpbGVyOiJnYyIsIFBsYXRmb3JtOiJsaW51eC9hbWQ2NCJ9Cg==?k8s-service-type=NodePort\",\n    \"date\": \"Fri Oct 20 2017 19:24:23 GMT+0000 (UTC)\"\n  },\n  \"email-address\": \"support@weave.works\"\n}"},"labels":{"app":"weave-scope","name":"weave-scope-app","weave-cloud-component":"scope","weave-scope-component":"app"},"name":"weave-scope-app","namespace":"kube-system"},"spec":{"ports":[{"name":"app","port":80,"protocol":"TCP","targetPort":4040}],"selector":{"app":"weave-scope","name":"weave-scope-app","weave-cloud-component":"scope","weave-scope-component":"app"}}}
  creationTimestamp: 2017-10-20T19:24:25Z
  labels:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
  name: weave-scope-app
  namespace: kube-system
  resourceVersion: "1547183"
  selfLink: /api/v1/namespaces/kube-system/services/weave-scope-app
  uid: 487d3909-b5cc-11e7-8adc-441ea16045ac
spec:
  clusterIP: 10.101.180.206
  externalTrafficPolicy: Cluster
  ports:
  - name: app
    nodePort: 30733
    port: 80
    protocol: TCP
    targetPort: 4040
  selector:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

**Comment by dlespiau** [comment]
The copy/paste of your `kubectl edit` isn't very clear as it's being formatted as markdown. Could you indicated what you've edited in the configuration?

Thanks.
