### ISSUE TITLE
Containers-by-image groups by image id, doesn't group images of different version together

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#291]
Whilst this is strictly correct (two different versions of with the same image name are different images), I don't think this distinction is useful.  We should probably just group by image name - this grouping is intended to reduce the cardinality, and currently sometimes doesn't.

**Comment by peterbourgon** [comment]
Is it as simple as splitting on the `:` and discarding the suffix?

**Comment by tomwilkie** [comment]
I think so.
