### ISSUE TITLE
eliminate unused memoisation

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2923]
Rendering makes use of memoisation, by wrapping  filters, maps, reducers and conditionalRenderers in `render.Memoise` structs. The objective here is to
- evaluate common sub-expressions of a rendering function only once
- evaluate the top-level rendering functions only once when they are invoked multiple times on the same report (e.g. when the browser requests the same rendering for the same timespan and no new reports have been received for that timespan)

The memoisation is accomplished in the renderer constructors, i.e. `MakeFilter`, `MakeFilterPseudo`, `MakeMap`, `MakeReduce`, `ConditionalRenderer`, by wrapping with a `render.Memoise` struct.

That actually leads to a lot of unnecessary memoisation, since many of these constructors are in places that are neither common sub-expressions nor the top-level.

We should remove the memoisation from the constructors and instead insert it at the call sites that are in these places.

**Comment by bboreham** [comment]
Are there good examples when memoisation is expected to help common subexpressions?

**Comment by rade** [comment]
It definitely happens - a while ago I instrumented the memoisation code and it showed plenty of cache hits even in a single render of a report.

**Comment by bboreham** [comment]
Here's one:

`HostRenderer` (called by the `hosts` api) calls `ColorConnectedProcessRenderer`, and calls `ContainerRenderer` which also calls `ColorConnectedProcessRenderer`.

Ironically `ColorConnectedProcessRenderer` is not memoised.

**Comment by rade** [comment]
I fixed that in the #2924 :)
