### ISSUE TITLE
cronjobs not detected on k8s 1.8

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#3032]
I've noticed the following the probe logs in a GKE 1.8.6 cluster:
```
<probe> INFO: 2018/01/18 18:20:05.103074 CronJobs are not supported by this Kubernetes version: the server could not find the requested resource
```
I suspect the reason is the same as kubernetes/kube-state-metrics#295 - scope is looking for cronjobs under `batch/v2alpha1` when they actually are under `batch/v1beta1`.

According to the [API docs](https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#cronjob-v1beta1-batch) the latter is indeed the correct version for k8s 1.8.

**Comment by rbruggem** [comment]
`batch/v1beta` was introduced by k8s.io/client-go v5.0.0.
Currently scope is pinned to k8s.io/client-go on 99c19923,  branch release-3.0 and does not support `batch/v1beta`  .

 k8s.io/client-go needs to be upgraded before proceeding.
Upgrading may break compatibility as explained in https://github.com/kubernetes/client-go/blob/master/CHANGELOG.md

**Comment by rade** [comment]
Oh joy. Anything jumping out from the breaking changes list that might affect us?

**Comment by rbruggem** [comment]
From a first inspection it seems that breaking changes that affect Scope would break at compile time.
