### ISSUE TITLE
Scope fails to launch on Docker for Mac

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#3064]
Using Docker for Mac: Version 18.02.0-ce-mac52 (22582)

On running `scope launch` the result is the following:

```Status: Downloaded newer image for weaveworks/scope:1.7.3
docker: Error response from daemon: Mounts denied: 
The path /var/run/scope/plugins
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
ERRO[0007] error waiting for container: context canceled```

**Comment by dglaubman** [comment]
I think the check for mac in the `scope` script may be incorrect.  This check protects a call to `create_plugins_dir` which appears to address the problem docker complains about.

```check_docker_for_mac() {
    [ "$(uname)" = "Darwin" ] \
        && [ -S /var/run/docker.sock ] \
        && [ ! "${DOCKER_HOST+x}" = x ] \
        && [ "${HOME+x}" = x ] \
        && [ -d "${HOME}/Library/Containers/com.docker.docker/Data/database" ]
}```

On my machine, `$HOME` is set and `"${HOME}/Library/Containers/com.docker.docker/Data/database" ` does not exist.

**Comment by dglaubman** [comment]
by the way, to get thru the tutorial, I took the Docker command that `scope launch` creates and edited it to point the Mac plugins directory to one inside `/Users`.  This worked.

**Comment by dholbach** [comment]
It looks like the actual path was `${HOME}/Library/Containers/com.docker.docker/Data` for @dglaubman.

The path is referred to from [recent release notes](https://docs.docker.com/docker-for-mac/release-notes/#docker-community-edition-18030-ce-mac59-2018-03-26) of Docker for Mac as well.

**Comment by rade** [comment]
> It looks like the actual path was `${HOME}/Library/Containers/com.docker.docker/Data` for @dglaubman.

What makes you say that?

**Comment by foot** [comment]
It worked for me doing with d4m ce:
> Version 18.03.0-ce-mac60 (23751)
> Channel: stable
> 6ddfc0f1d3

El Capitan:
> 10.11.6 (15G18013)

Downloaded and launched with
```sh
curl --silent --location https://git.io/scope --output /usr/local/bin/scope
sudo chmod +x /usr/local/bin/scope
scope launch --service-token=<cloud-token>
```

Maybe something was fixed in the very latest d4m? =/

**Comment by dholbach** [comment]
>>  It looks like the actual path was ${HOME}/Library/Containers/com.docker.docker/Data for @dglaubman.
> >
> What makes you say that?

@dglaubman brought this up in an email conversation.

**Comment by rade** [comment]
@foot how exactly did you obtain&install d4m?

I am curious why @glaubman's docker version makes no mention of `-macXX`.

**Comment by foot** [comment]
ahh, the about screen is a bit confused, there are opportunities to grab versions from diff places.

![screen shot 2018-04-12 at 16 03 16](https://user-images.githubusercontent.com/22008/38682358-2c09015e-3e6b-11e8-96cf-2b892dc64ab2.png)

**Comment by rade** [comment]
@foot is it possible that you had the `${HOME}/Library/Containers/com.docker.docker/Data/database` left over from a previous DfM installation?

**Comment by foot** [comment]
Possibly, will wipe it out re-install and test.

**Comment by foot** [comment]
Repro! Yes, wiping, re-installing, and reseting to factory defaults. My database was missing.

Changing line 127 to remove `/database` fixed it 👌. ⭐️ @rade .

**Comment by dholbach** [comment]
@errordeveloper https://pastebin.com/6v5y297A would be the minimal fix for this. Do we need something more sophisticated to cater for older Docker for Mac installs?

**Comment by errordeveloper** [comment]
> Do we need something more sophisticated to cater to older Docker for Mac installs?

No.
