### ISSUE TITLE
Image Names not displaying when downloaded

### ISSUE THREAD

**Issue by shiveshabhishek** [weaveworks/scope#3067]
When I hit on "Save canvas as SVG (does not include search highlighting)" it downloads a image(.svg) but shows only the topology, not the name of image/continer. From my view, without the names, topology is not of any worth

![image](https://user-images.githubusercontent.com/29581152/36254081-b6a5e1ec-126f-11e8-94e0-b887b0955f0f.png)

**Comment by rade** [comment]
Dup of #1718
