### ISSUE TITLE
Duplicate namespace buttons

### ISSUE THREAD

**Issue by bboreham** [weaveworks/scope#3079]
After I had a view of a Kubernetes cluster open for a while, the namespace buttons at the bottom grew really long, and I could see some of the names were repeated.

Refreshing the screen made the problem go away.

**Comment by fbarl** [comment]
@bboreham were you able to reproduce it again recently?

**Comment by bboreham** [comment]
@fbarl no, I left a window open for a while and do not see it happening now; I'll close this issue.

**Comment by bboreham** [comment]
I'm pretty sure the trigger for this is the back-end restarting.  We auto-deploy all master builds to Weave Cloud staging environment, so when I leave a view open there it will tend to hit some restarts over time.

**Comment by bboreham** [comment]
I have just seen the buttons duplicate right in front of me, when I restarted the _probe_.
Can reproduce on demand now.
