### ISSUE TITLE
In Host details, pods in status "Failed" are listed first

### ISSUE THREAD

**Issue by dholbach** [weaveworks/scope#3083]
In the Explore →Hosts view of socks-shop in WC, upon clicking on a particular host, I can see a truncated list of pods on the host in the host details dialog. All of the ones shown in the collapsed list are status: "Failed".

While this might be useful debugging information to see which ones failed in the past, it might be more reassuring to see the ones which are currently running. Expanding the list, I can see the expected list of running pods just fine.

![screenshot-failed-pods](https://user-images.githubusercontent.com/1346979/36541896-b2991a90-17df-11e8-9240-85c4efc7ab4d.png)

**Comment by rade** [comment]
Perhaps we shouldn't show Failed pods at all; in general Scope only shows what's running.

**Comment by dholbach** [comment]
Nice one!
