### ISSUE TITLE
Enhanced support Metadata template data types [hyperlinks]

### ISSUE THREAD

**Issue by todkap** [weaveworks/scope#3099]
In the Metadata template data types, the following is documented

https://www.weave.works/docs/scope/latest/plugins/#report-data-structures
**Metadata Templates section**
> dataType specifies the type of data, and determines how the value is displayed. Possible values for this attribute are: “number”, “ip”, “datetime” and “” for strings.

It would be great if there was support for URLs that support direct linking to resources.   The use case is that we have a Node that represents a Deployment of some service.   This service exposes a set of links for administration, logging, etc.   

**Food for thought**
If there was a more pluggable extension model, templates could define their own data types backed by the plugin to support other data types as well.

**Comment by bboreham** [comment]
Hi, thanks for the suggestion!

How do you envisage this would look, both in the code and on the screen?

**Comment by RcrsvSquid** [comment]
Hello,

I work with Todd.

We've implemented the feature by first running a plugin that posts metadata or mulit-column data including the `dataType: link` field. The frontend then conditionally renders either a link or the original component.

Our implementation is here: https://github.com/weaveworks/scope/pull/3105

**Comment by rade** [comment]
Resolved by #3105.
