### ISSUE TITLE
Upgrade moment.js dependency due to security vulnerability

### ISSUE THREAD

**Issue by fbarl** [weaveworks/scope#3101]
Github reports:

![image](https://user-images.githubusercontent.com/1216874/37055428-02770c4c-2182-11e8-981d-8c6b24bdc0ef.png)

p.s. Should also bump `ui-components` version to make sure no old `moment.js` versions are persisted.

**Comment by bboreham** [comment]
It would be useful to have the CVE linked here so we know which vulnerability.

**Comment by fbarl** [comment]
> It would be useful to have the CVE linked here so we know which vulnerability.

I think this was it: https://github.com/moment/moment/issues/4163
