### ISSUE TITLE
CRI support for the scope probe

### ISSUE THREAD

**Issue by crw** [weaveworks/scope#3106]
Scope talks to the Docker API directly for a variety of stats collection; this is an issue when using other container runtimes (CRI-O being the current example). 

Capturing feedback from @dlespiau:
> CRI has now a stats API since k8s 1.8, we could teach scope to use that API instead of using directly docker
> (just to be more precise, it's not just about stats collection, but everything we do with the docker API like opening a shell in the container or getting container logs)

**Comment by rade** [comment]
What actually goes wrong right now? Is the only issue that non-docker containers are missing CPU/Memory graphs?

**Comment by dlespiau** [comment]
Not just for stats, controls/actions on containers end up calling the docker API: https://github.com/weaveworks/scope/blob/master/probe/docker/controls.go#L14 and those would need to be CRI instead. I mentioned stats because they were missing in the first version of CRI.

**Comment by LiliC** [comment]
Started looking into this to add support for CRI to scope probe.

>  scope to use that API instead of using directly docker

I would not replace but instead add CRI support as an additional option, for Kubernetes from 1.8 onwards we can always use CRI, but fallback to docker in other cases. My initial thinking was a flag to switch, but am open to suggestions?

**Comment by dlespiau** [comment]
A flag would be perfect, we'' be able to ship a manifest with the CRI option for k8s 1.8+ then.

**Comment by rade** [comment]
Why do we need a flag? Why can't scope detect the presence of / _try_ to talk to CRI, and fall back to Docker if that fails?

**Comment by jml** [comment]
What's the status on this?

**Comment by LiliC** [comment]
@rade Was not sure if I should close this, as network support is not implemented yet?

> ? Did that turn out to be infeasible?

Nope, it didn't. I tried creating a more sophisticated detection tool, but the CRI API does not expose the actual endpoint which we would need to mount. Also it's a chicken egg problem https://github.com/weaveworks/scope/pull/3305#issuecomment-411356077 So we decided to go with https://github.com/weaveworks/launcher/pull/252 in weave.cloud which works in most cases and user can override it, and we generate the manifest files based on that endpoint. 
As for scope, the user needs to mount the volume for docker anyways, when using the docker probe, so it's similiar for any CRI runtime.

**Comment by rade** [comment]
Sounds like there is nothing left to do here - all remaining work is covered by separate issues. I suggest we close this.

**Comment by huapox** [comment]
How's it going

**Comment by bboreham** [comment]
Still work to do:
https://github.com/weaveworks/scope/issues?q=is%3Aissue+is%3Aopen+cri

**Comment by draconiun** [comment]
@bboreham 
did it work for you in kubernetes?
