### ISSUE TITLE
Scope not showing datas in OpenShift Enterprise

### ISSUE THREAD

**Issue by coolpalani** [weaveworks/scope#3111]
I had following this below instructions for installing weave scope in OSE [url](https://www.weave.works/docs/scope/latest/installing/#ose)

when I look dashboard none of datas fetch from node or container. It showing as empty. but weave pods are running.

`[root@master` ~]# oc get pods
NAME                               READY     STATUS    RESTARTS   AGE
weave-scope-agent-2ql7z            1/1       Running   0          13m
weave-scope-agent-6687g            1/1       Running   0          13m
weave-scope-agent-jrdsj            1/1       Running   0          13m
weave-scope-agent-nm9z6            1/1       Running   0          12m
weave-scope-agent-vhd94            1/1       Running   0          13m
weave-scope-app-2206400545-td446   1/1       Running   0          22m

Could someone assist me to fix this problem.
Thanks in advance.

**Comment by rade** [comment]
check the agent logs

**Comment by coolpalani** [comment]
weave-scope-agent logs showing as below

`<probe> WARN: 2018/03/17 11:36:33.111456 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused`
`<probe> ERRO: 2018/03/17 11:36:33.952225 Error fetching app details: Get http://172.30.111.4:80/api: dial tcp 172.30.111.4:80: getsockopt: connection refused`
`<probe> WARN: 2018/03/17 11:36:34.069862 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused`
`<probe> WARN: 2018/03/17 11:36:35.059538 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused`

**Comment by rade** [comment]
See #3104, in particular the suggestion to set `KUBERNETES_NODENAME` or setting `--probe.kubernetes.kubelet-port=10250`.

**Comment by rade** [comment]
Also, what version of weave scope are you running? (Check the top of the logs)

Version 1.8.0, released a week ago, should automatically set `KUBERNETES_NODENAME` and hence not run into the above problem.

**Comment by coolpalani** [comment]
I had deployed version 1.8.0
when I add --probe.kubernetes.kubelet-port=10250 , I am getting the following error message in agent logs

        spec:
          containers:
            - name: scope-agent
              args:
                - '--no-app'
                - '--probe.docker.bridge=docker0'
                - '--probe.docker=true'
                - '--probe.kubernetes=true'
                - '--probe.kubernetes.kubelet-port=10250'
                - 'weave-scope-app.weave.svc.cluster.local:80'

Agent logs:

`<probe> WARN: 2018/03/19 14:07:35.168633 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10250/pods/: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"`
`<probe> WARN: 2018/03/19 14:07:36.230388 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10250/pods/: net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x15\x03\x01\x00\x02\x02"`

**Comment by rade** [comment]
> I had deployed version 1.8.0

Do you have the up-to-date yaml? The error message you are seeing should not appear at all if the KUBERNETES_NODENAME env var is supplied, which is done in the yamls we released last week.

**Comment by coolpalani** [comment]
yaml is update. I followed the instructions which is mentions here 

oc new-project weave-scope
oc adm policy add-cluster-role-to-user cluster-admin -z weave-scope
oc adm policy add-scc-to-user privileged -z weave-scope
oc adm policy add-scc-to-user anyuid -z default

wget https://cloud.weave.works/k8s/scope.yaml

changed the namespace into weave-cope instead of weave.

I had applied --probe.kubernetes.kubelet-port=10250 also. but still no luck.

`time="2018-03-20T18:10:35Z" level=info msg="publishing to: weave-scope-app.weave.svc.cluster.local:80"`
`<probe> INFO: 2018/03/20 18:10:35.913921 command line args: --mode=probe --no-app=true --probe.docker=true --probe.docker.bridge=docker0 --probe.kubernetes=true `
`--probe.kubernetes.kubelet-port=10250 --weave=false weave-scope-app.weave.svc.cluster.local:80`
`<probe> INFO: 2018/03/20 18:10:35.913994 probe starting, version 1.8.0, ID 5438d4baa1c807b9`
`<probe> WARN: 2018/03/20 18:10:35.931861 Error setting up the eBPF tracker, falling back to proc scanning: kernel not supported: got kernel 3.10.0-693.11.6.el7.x86_64 but need kernel >=4.4`
`<probe> INFO: 2018/03/20 18:10:35.932269 kubernetes: targeting api server https://172.30.0.1:443`
`<probe> WARN: 2018/03/20 18:10:35.948931 Cannot resolve 'weave-scope-app.weave.svc.cluster.local': `lookup weave-scope-app.weave.svc.cluster.local on 10.53.44.99:53: no such host`
`<probe> ERRO: 2018/03/20 18:10:36.230590 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 8388608 bytes.`
`<probe> ERRO: 2018/03/20 18:10:36.232028 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 8388608 bytes.`

Base Operating System: RHEL 7.4
Kernel: 3.10.0-693.11.6.el7.x86_64
Seems log refers to upgrade the kernel.

**Comment by coolpalani** [comment]
I suspect issue in the DNS now. As per weave-scope-agent logs, I added --weave=false in the container specs argument field

Error logs:
`time="2018-03-21T21:28:19Z" level=info msg="publishing to: weave-scope-app.weave.svc.cluster.local:80"`
`<probe> INFO: 2018/03/21 21:28:19.754199 command line args: --mode=probe --no-app=true --probe.docker=true --probe.docker.bridge=docker0 --probe.kubernetes=true --weave=false weave-scope-app.weave.svc.cluster.local:80`
`<probe> INFO: 2018/03/21 21:28:19.757829 probe starting, version 1.8.0, ID ef420e27c0fba52`
`<probe> WARN: 2018/03/21 21:28:19.800795 Cannot resolve 'weave-scope-app.weave.svc.cluster.local': lookup weave-scope-app.weave.svc.cluster.local on 10.53.44.100:53: no such host`
`<probe> WARN: 2018/03/21 21:28:19.812536 Error setting up the eBPF tracker, falling back to proc scanning: kernel not supported: got kernel 3.10.0-693.11.6.el7.x86_64 but need kernel >=4.4`
`<probe> ERRO: 2018/03/21 21:46:41.597776 DNSSnooper: error decoding packet: No decoder for layer type DHCPv4`

I was tried to access this url weave-scope-app.weave.svc.cluster.local from weave-scope-agent to weave-scope-app but name resolution not resolving.

**Comment by chilcano** [comment]
Hi Coolpalani,

Clean your installation and install Scope again from the URL.
Please, don't change the Namespace, it should be weave.

Regards

**Comment by rade** [comment]
@coolpalani did you get this to work in the end? As @chilcano says, don't change the namespace, at least not until you've got everything working w/o such a change.

**Comment by coolpalani** [comment]
Thanks for supporting everyone.
I have followed this instructions and fixed this problem now
https://github.com/weaveworks/scope/issues/2485
