### ISSUE TITLE
Shortcut property is not copied by report.Report.Copy method

### ISSUE THREAD

**Issue by gglogowski** [weaveworks/scope#3113]
Shortcut property is not copied by report.Report.Copy method

Method Copy ignores Shortcut property: https://github.com/weaveworks/scope/blob/3de06b5a0963549308bd28a296063ec5c5e963d7/report/report.go#L258

As a result, report is published with Shortcut property always set to false for docker.reporter
It happens because probe.drainAndPublish function makes report copy calling rpt.BackwardCompatible()
https://github.com/weaveworks/scope/blob/7b0f0cb158d3f8e468913ee5658ddbfae933b8b7/probe/probe.go#L203

**Comment by rade** [comment]
This does look like a bug indeed. Could you submit a PR with a fix?
