### ISSUE TITLE
Docker Compose - Killed 9 

### ISSUE THREAD

**Issue by LedgerBlocks** [weaveworks/scope#3114]
I have installed docker compose. When I try to run a docker-compose command from the Mac terminal I get Killed: 9

When I try to reinstall with brew I get told its installed and I can link to in by 'brew-link --overwrite --dry-run -docker-compose' but when I do this it returns 'Would remove:
/usr/local/bin/docker-compose -> /Users/johnr/Library/Group Containers/group.com.docker/bin/docker-compose' and the problem remains - 

Any ideas?

for completeness the command I'm trying to run is '/strato-run.sh'

Anyone any idea? Thanks

**Comment by rade** [comment]
What does this have to do with Weave Scope?

**Comment by LedgerBlocks** [comment]
Good point nothing! Wrong group
