### ISSUE TITLE
label list truncation breaks a bunch of stuff

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#3127]
Probes limit the number of docker container labels, docker env vars, docker image labels, and kubernetes labels to [20](https://github.com/weaveworks/scope/blob/v1.8.0/report/table.go#L16) each. For most labels such truncation is only a problem for users when they are interested in that specific label. However, some labels are actually accessed by the scope app. For example, the namespace filter in the container topology is keyed on the `io.kubernetes.pod.namespace` container label, and therefore when that label is filtered out by truncation, we show the associated container as not belonging to any namespace. I observed this for the `carts` container in the sock-shop.

**Comment by rade** [comment]
A related issue is that the truncation is non-deterministic, since the insertion is [iterating over a map](https://github.com/weaveworks/scope/blob/v1.8.0/report/table.go#L54). This, a) makes truncation less effective than it should be since the app is aggregating multiple reports, and b) ought to result in view instability - i.e. the labels shown for a container changing over time. However, I have not observed this, which is odd.

**Comment by rade** [comment]
One way of fixing this would be to introduce a list of "precious" labels which truncation won't remove. That does introduce an undesirable coupling of the probes (label producers) and apps (label consumers), but short of getting rid of truncation altogether, that is inevitable.

@bboreham thoughts?

**Comment by rade** [comment]
I cannot find any kubernetes labels that are accessed in the app.

The only docker env var accessed is [`MARATHON_APP_ID`](https://github.com/weaveworks/scope/blob/v1.8.0/render/detailed/summary.go#L442).

The only image label accessed is [`works.weave.role`](https://github.com/weaveworks/scope/blob/v1.8.0/render/filters.go#L236).

The _probe_ accesses some docker labels:
- `com.docker.swarm.service.id`
- `com.docker.swarm.service.name`
- `com.docker.stack.namespace`
- `com.amazonaws.ecs.task-arn`
- `com.amazonaws.ecs.cluster`
- `com.amazonaws.ecs.task-definition-family`
- `io.kubernetes.pod.uid`

(That last one is needed to add pod parents to containers)

The app accesses the following docker labels:
- `com.amazonaws.ecs.container-name`
- `com.docker.stack.namespace`
- `io.kubernetes.pod.namespace`
- `io.kubernetes.pod.name`
- `io.kubernetes.container.name`
- `works.weave.role`

**Comment by bboreham** [comment]
Do we have any stats on how many labels are being truncated?  Strikes me that 20 is already hard to work with.  So I would try to establish that we very rarely see much more than 20, and then remove truncation.

**Comment by rade** [comment]
In the sock-shop we have 108 container nodes, 5 of which exceed the 20 label limit by 5,2,5,2,5 labels, respectively. env entries get exceeded on 50 containers, with two "clusters" of excess around 32 and 93 entries. pod labels are never exceeded.

Based on that it would seem safe to lift the label limit, but keep the env limit in place. (Though frankly I don't see the value of the truncated list.)

**Comment by rade** [comment]
@bboreham and I decided that we should ditch the limiting, and invert the default of the `probe.omit.env-vars` flag to `true`.
