### ISSUE TITLE
Add controls

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#315]
Want to have the ability for the UI to send actions all the way back to the probe.  Example is the "quarantine" action.

Heres a rough design / plan:

In the report data types, do the follow:
- [x] <s>Change NodeMetadata to a struct, existing metadata will live in ndm.metadata field.</s> (Done in #318)
- [x] Add "controls" field to this struct; plan for just a []string of control identifiers
- [x] Add a "controls" field to top-level Topology struct, containing the i18n & parameter info

In the App / Client:
- [x] Render all this out into the detailed node struct, using the i18n data from the topologies
- [x] Have the UI stick this in the details panel (any maybe a right click menu?)
- [x] Add new POST `/api/topology/{topology}/{id}` handler, which will use the origin host node metadata info to route the action back to the right probe
- [x] Add a new websocket handler at `/api/controls`, which the probe will connect a websocket to, to allow the app to send and receive async messages to/from the probe

In the Probe:
- [x] Connect to the app, handle control requests and responses
- [x] In probe, have a map of control id -> function, have various modules register in this map, and when we get a action just lookup and run said function
- <s>Have actions travel the other way down the app<->probe connection; reuse existing connection.</s>  (now that we post the reports to the app, this makes little sense)

Future
- <s>Have WeaveTagger add quarantine control to the Container topology</s> (this will have to be in some eventual weave run integration)
- [x] Have Docker Reporter add stop / restart controls to the Container topology

Open questions:
- Do we want to support actions on nodes that are merges from multiple probes (eg container images?)  I think no, for now
- Do we want actions to have responses? yes.
- Do we want actions to have parameters? yes

**Comment by peterbourgon** [comment]
> Add new /api/topology/{topology}/{id}/{action}

The semantics of this are interesting to me... it would need to be a POST, and support parameters, but I'm not sure the best way to do that — JSON body? Arbitrary URL params? Also, I think it needs to be synchronous, waiting for a response from the probe, which has interesting consequences on package xfer...

> Do we want to support actions on nodes that are merges from multiple probes (eg container images?) I think no, for now

I don't see the problem, you just need to select which origin host you want the action to apply to, in the detail pane. Maybe that's not UI we care to build out in a first cut.

> Do we want actions to have responses? I think yes.

Agree.

> Do we want actions to have parameters? I think no for now.

I don't think we can do anything useful without parameters. What did you have in mind?

**Comment by tomwilkie** [comment]
> Add new /api/topology/{topology}/{id}/{action}
>
> The semantics of this are interesting to me... it would need to be a POST,
> and support parameters, but I'm not sure the best way to do that — JSON
> body? Arbitrary URL params? Also, I think it needs to be synchronous,
> waiting for a response from the probe, which has interesting consequences
> on package xfer...
>
Yes it needs to be post. I'm not sure about parameters right now - the
first few actions / capabilities will all be void Afaict - quarantine,
maybe pause, kill, stop etc.

Also that handler overlaps with the edge metadata handler, so we'll need to
pick something else.

It would be significantly easier if it were fire and forget, but I agree, I
think it really needs to be synchronous. It's not too hard to implement in
xfer.

 Do we want to support actions on nodes that are merges from multiple
> probes (eg container images?) I think no, for now
>
> I don't see the problem, you just need to select which origin host you
> want the action to apply to, in the detail pane. Maybe that's not UI we
> care to build out in a first cut.
>
Indeed that was my motivation. I say we just implement actions on nodes
from a single host for now. We can extend it later.

>  Do we want actions to have responses? I think yes.
>
> Agree.
>
good, I guess. xfer will need to hold a list of outstanding actions, and a
action id to pair actions and responses, and implement timeouts etc.
can  you think of a simpler way? Anything we can reuse?

>  Do we want actions to have parameters? I think no for now.
>
> I don't think we can do anything useful without parameters. What did you
> have in mind?
>

I guess I'm making there be an explicit first parameter of the node id. But
other than that, what parameter for what actions do you have in mind?
Everything I can imagine is a void (as above), plus I don't want to build
the ui for specifying parameters.

Of course we shouldn't do anything to rule this out in the future.

**Comment by peterbourgon** [comment]
> Also that handler overlaps with the edge metadata handler, so we'll need to pick something else.

I like the idea that a POST to a node or edge endpoint invokes the capability handler, with the capability being a URL or body parameter. Fits nicely with HTTP semantics.

- GET /api/topology/containers/{id} — return the node
- POST /api/topology/containers/{id}?action=stop — invoke a capability

**Comment by tomwilkie** [comment]
Yeah that works nicely.

Now, should we pass the action & parameters in the query parameters or
body?  Passing everything in the query params is horrifc, but putting
everything in the body might be too opaque.  And a mix (action in query
parameter, parameters in body) just seems wrong.  Thoughts?

**Comment by peterbourgon** [comment]
I'd like to know more about the initial set of capabilities. What do we intend to include, and what will they do, concretely?

**Comment by tomwilkie** [comment]
So I only plan on adding one right now - Quarantine.  It will be added to containers by the weave tagger.  When run, it will temporarily (for 1 hour, say) remove said container from weave dns.  A PR for this functionality should be opened in weave today.

But fair enough, it would be good for the user to say how long to drain something for, so looks like we need parameters.

We should probably also add un-quarantine (release?).  @monadic are we sticking with the verb quarantine?  What should the opposite be?  I do prefer drain and undrain, they are shorter.

**Comment by peterbourgon** [comment]
If the thing you're acting upon is a container, i.e. in the application/user domain, quarantine/release makes sense. If the thing you're acting upon is a router, i.e. in the network/operator domain, drain/undrain makes sense. (We should make sure to have consistent verbiage across Scope and Weave, of course.)

So — the capability will send a signal to the Weave DNS container, presumably. Whether or not a container is quarantined is not obvious by simple inspection. That information authoritatively lives in Weave DNS, so if we want it reflected in the UI (which, I think, we do) we'll have to write a new tagger or something.

On reflection, I prefer URL parameters over rich request bodies. It puts pressure on us to keep the capability API simple, which is virtuous. Proposal: 

- App will pass all provided URL parameters as k/v pairs, opaquely, down to the probe
- Probe's capability handler will parse all parameters, take action, return result
- It should reject any request with extra, missing, or invalid params, i.e. it should be strict

How does that sound?

**Comment by tomwilkie** [comment]
The quarantine is being implemented as part of the new weavedns, embedded
in the router.  I'll extend the weave tagger to keep a list of the current
quarantines and the weave tagger can put a "quarantined" bit in the
metadata for the node.  I'll also do the same for the hosts topology.

Putting everything on in the query string will do for now, I guess.
