### ISSUE TITLE
k8s

### ISSUE THREAD

**Issue by zhangll1990** [weaveworks/scope#3154]

**Comment by Deepak1100** [comment]
Hi,
I am getting the same error in all the nodes. and all other pods are working I tried pulling some new image those are also working. i think its some problem with weave-scope image

**Comment by dholbach** [comment]
The issue seen by @deepak1100 is #3585.

(Does https://github.com/moby/moby/issues/35747 have anything to do with this?)

**Comment by Deepak1100** [comment]
Hi @dholbach 
i am pretty sure my issue is not #3587
but it is similart to  moby/moby#35747.
even after build new image with scope binary in it. i am getting this issue in all the new nodes. and after this issue come all other new images also start giving this error.
But it work on existing node where i update the image from weavework to mine. i don't know whats the problelm with the new nodes.
may be weave is not yet started over the new image before it scope is starting and causing lots of issue.

**Comment by Deepak1100** [comment]
And if I try manually pulling image on the server where I am not running scope daemonset it's not giving any error in the image.
So the error probably start may be after starting weave scop as it have docker socket mounted. OR
it is the way kubernetes pulls the image.
Or it can be ubuntu 16.04 bug as i seen some one have same problem and using same os

**Comment by dholbach** [comment]
Please ignore the scope issue I pointed to, that was obviously a mistake.

**Comment by bboreham** [comment]
Can we get some more information, e.g. the `kubelet` logs?
Also the output of `uname -a` on the node please.
