### ISSUE TITLE
Clusters with many namespaces don't fit on the UI

### ISSUE THREAD

**Issue by Stono** [weaveworks/scope#3176]
Hey

A picture says 1000 words:

<img width="1079" alt="screen shot 2018-05-17 at 09 54 53" src="https://user-images.githubusercontent.com/1486729/40167142-28043926-59b8-11e8-920d-277cd129f89a.png">

Might be worth having a UI which responsively switches to a multi-select drop down instead when over the width of the page?

**Comment by rade** [comment]
dup of #3096
