### ISSUE TITLE
Terminal window width wrong

### ISSUE THREAD

**Issue by bboreham** [weaveworks/scope#3178]
The character window is about half the width of the UI window, and a little less tall.

Maybe because it's a Retina display?  But why wouldn't it be the same wrong in both dimensions?

![image](https://user-images.githubusercontent.com/8125524/40172924-1ba9dd30-599e-11e8-9d48-1db4ced15fb0.png)

**Comment by LiliC** [comment]
Could this be because of the bumping the version of xterm @fbarl? https://github.com/weaveworks/scope/pull/3172

**Comment by fbarl** [comment]
> Could this be because of the bumping the version of xterm?

Yeah, that's probably the reason, although I don't know why exactly. Simple adjusting the estimated character size fixed the issue though.
