### ISSUE TITLE
Pod view is showing two containers per pod on Kubernetes 1.10 

### ISSUE THREAD

**Issue by stefanprodan** [weaveworks/scope#3182]
On GKE 1.10 the Pod view is wrongly displaying `POD` containers:

<img width="1142" alt="screen shot 2018-05-19 at 12 11 26" src="https://user-images.githubusercontent.com/3797675/40266993-df89a3f0-5b5d-11e8-81eb-7032c8838f0d.png">

Same on the Containers view:

<img width="724" alt="screen shot 2018-05-19 at 12 11 38" src="https://user-images.githubusercontent.com/3797675/40266987-dcfd70f8-5b5d-11e8-9821-4347dc7bec63.png">

**Comment by rade** [comment]
Are you sure you haven't got the filter (bottom left) set to 'All' instead of 'Application Containers'?

If it _is_ set correctly, try toggling it back and forth.

**Comment by rade** [comment]
Hmm, given that the POD containers also show up in the Pod view, I wonder whether something has changed in k8s 1.10 that breaks our detection of these special containers. Scope [looks for containers with an image of `google_containers/pause`](https://github.com/weaveworks/scope/blob/v1.9.0/probe/kubernetes/reporter.go#L186). @stefanprodan please check that. PRs welcome.

**Comment by stefanprodan** [comment]
The image name changed to `k8s.gcr.io/pause-amd64`
