### ISSUE TITLE
"Process by name" view is broken

### ISSUE THREAD

**Issue by shyam-dev** [weaveworks/scope#3205]
Hello;

The "process by name" view seems to be broken since 1.7.0.

This is the view with 1.6.7

![process-by-name-1 6 7](https://user-images.githubusercontent.com/1436408/40797687-b80518a0-6526-11e8-9f15-ea2761919a0d.png)

This is the view with 1.9.0

![process-by-name-1 9 0](https://user-images.githubusercontent.com/1436408/40797717-cc4a99a2-6526-11e8-9bc1-a4eb759e2d92.png)

Has this been removed on purpose ??

**Comment by rade** [comment]
Looks like a bug.

**Comment by rade** [comment]
The bug is in the connectedness marking. If one selects 'Show Unconnected' in the bottom left then the nodes do show up, including connected nodes (so the fault isn't in edge propagation).
