### ISSUE TITLE
Weave Scope not working on Kubernetes 1.10

### ISSUE THREAD

**Issue by abalasu1** [weaveworks/scope#3218]
I have weave scope installed on IBM Cloud Private (2.1.0.3) and it is not showing any data on the ui, whereas on 2.1.0.2 it works perfectly.

-----
$ kubectl get nodes
NAME             STATUS    ROLES     AGE       VERSION
172.16.202.206   Ready     <none>    1h        v1.10.0+icp-ee
172.16.202.94    Ready     <none>    1h        v1.10.0+icp-ee
172.16.203.56    Ready     <none>    1h        v1.10.0+icp-ee
-----
$ kubectl get ds -n weave
NAME                DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
weave-scope-agent   3         3         3         3            3           <none>          52m
-----
$ kubectl get pods -n weave
NAME                              READY     STATUS    RESTARTS   AGE
weave-scope-agent-2mssf           1/1       Running   0          53m
weave-scope-agent-mx8fx           1/1       Running   0          53m
weave-scope-agent-wxhf9           1/1       Running   0          53m
weave-scope-app-dbd44d984-msf8h   1/1       Running   0          53m
-----
$ kubectl logs weave-scope-agent-mx8fx -n weave
time="2018-06-07T11:32:02Z" level=info msg="publishing to: weave-scope-app.weave.svc.cluster.local:80" 
<probe> INFO: 2018/06/07 11:32:02.920899 command line args: --mode=probe --probe-only=true --probe.docker=true --probe.docker.bridge=docker0 --probe.kubernetes=true weave-scope-app.weave.svc.cluster.local:80
<probe> INFO: 2018/06/07 11:32:02.920954 probe starting, version 1.9.0, ID 38358b4aff5c9985
<probe> WARN: 2018/06/07 11:32:02.931237 Cannot resolve 'weave-scope-app.weave.svc.cluster.local': lookup weave-scope-app.weave.svc.cluster.local on 10.0.0.10:53: no such host
<probe> WARN: 2018/06/07 11:32:02.941744 Error setting up the eBPF tracker, falling back to proc scanning: kernel not supported: got kernel 3.10.0-693.17.1.el7.x86_64 but need kernel >=4.4
<probe> INFO: 2018/06/07 11:32:02.942257 kubernetes: targeting api server https://10.0.0.1:443
<probe> WARN: 2018/06/07 11:32:02.949733 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> WARN: 2018/06/07 11:32:02.952782 Cannot resolve 'scope.weave.local.': dial tcp 172.17.0.1:53: getsockopt: connection refused
<probe> ERRO: 2018/06/07 11:32:02.957117 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 8388608 bytes.
<probe> ERRO: 2018/06/07 11:32:02.957735 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 8388608 bytes.
<probe> WARN: 2018/06/07 11:32:02.995789 Error collecting weave ps, backing off 20s: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> WARN: 2018/06/07 11:32:03.981202 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:04.964337 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:05.962192 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:06.966057 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:07.969127 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:08.980839 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:09.968225 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:10.962689 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:11.961720 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:12.950257 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> WARN: 2018/06/07 11:32:12.961865 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:13.963265 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:14.966740 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:15.961279 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:16.964460 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:17.963753 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:18.967469 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:19.962970 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:20.965638 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:21.961753 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:22.971041 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
<probe> WARN: 2018/06/07 11:32:23.024842 Error collecting weave ps, backing off 40s: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> WARN: 2018/06/07 11:32:23.966786 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: getsockopt: connection refused
...
-----
$ kubectl logs weave-scope-app-dbd44d984-msf8h -n weave
<app> INFO: 2018/06/07 11:31:58.642220 app starting, version 1.9.0, ID 1bcb6dbaa58e0a90
<app> INFO: 2018/06/07 11:31:58.643486 command line args: --mode=app
<app> INFO: 2018/06/07 11:31:58.646507 listening on :4040
<app> WARN: 2018/06/07 11:31:58.687482 Error updating weaveDNS, backing off 20s: Error running weave ps: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<app> WARN: 2018/06/07 11:32:18.711700 Error updating weaveDNS, backing off 40s: Error running weave ps: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.

**Comment by abalasu1** [comment]
Found the issue:
Cannot resolve 'weave-scope-app.weave.svc.cluster.local': lookup weave-scope-app.weave.svc.cluster.local on 10.0.0.10:53: no such host

While installing the cluster i had changed the cluster domain, so my weave scope service is weave-scope-app.weave.svc.app-us.local. Corrected the args in scope.yaml to point to the right service and that resolved the issues.

**Comment by 2opremio** [comment]
Awesome!
