### ISSUE TITLE
Namespace list not visible

### ISSUE THREAD

**Issue by Nalum** [weaveworks/scope#3237]
I currently have 45 namespaces (many of which are created as part of the product being run) on my GKE cluster and is expected to grow beyond this and when running scope the list of namespaces along the bottom of the page is not fully visible.

Would this be better as a multi-select dropdown?

![ns](https://user-images.githubusercontent.com/384180/41771427-9df0b80e-7604-11e8-97b7-614f51302fc1.png)

**Comment by bboreham** [comment]
Hi @Nalum, thanks for your interest.  I believe this is a duplicate of #3096

**Comment by Nalum** [comment]
@bboreham thanks for that, I didn't find it when I was looking :+1:
