### ISSUE TITLE
lines overlapping in terminals

### ISSUE THREAD

**Issue by satyamz** [weaveworks/scope#3245]
Lines in the log output of pod shown in the weave scope terminal are overlapping. 

Environment Details:
Kubernetes Version: 1.9.6-gke

![screenshot from 2018-06-29 15-49-51](https://user-images.githubusercontent.com/5508956/42090102-a3b380e6-7bbd-11e8-8864-c9b3955f4914.png)

**Comment by rade** [comment]
This happens for _all_ terminals - host, container attach, container exec, and pod logs.

**Comment by satyamz** [comment]
Hi @rade  I can confirm that this issue is not there in weave scope 1.9.0
![screenshot from 2018-06-29 20-23-17](https://user-images.githubusercontent.com/5508956/42099283-a8281962-7bda-11e8-84aa-763cf91c9c0f.png)

**Comment by foot** [comment]
It looks like this: https://github.com/xtermjs/xterm.js/issues/1170

Which indicates it might be a chrome only issue, does this match your experience or happening under firefox too?

**Comment by rade** [comment]
I am seeing this in FF.

**Comment by satyamz** [comment]
@foot Thanks for fixing this.
