### ISSUE TITLE
Pop-out is not showing any Pod log data in weave scope Pod terminal

### ISSUE THREAD

**Issue by satyamz** [weaveworks/scope#3246]
When I try to pop-out terminal, log data isn't appearing on the terminal even after waiting for 5 minutes.

Environment Details:
Kubernetes Version: 1.9.6-gke

![image](https://user-images.githubusercontent.com/5508956/42090474-3a943e14-7bbf-11e8-8e79-dc1a1b33dca2.png)

**Comment by rade** [comment]
This does work fine for me, in the context of Weave Cloud at least.

**Comment by satyamz** [comment]
This did not work for me even for `weave scope v1.9.0`

![screenshot from 2018-06-29 20-27-57](https://user-images.githubusercontent.com/5508956/42099466-1cde041a-7bdb-11e8-9196-9d5a454f81bd.png)

**Comment by satyamz** [comment]
Hi again, I think issues has been resolved in `v1.10.2`. I see that terminal takes some time to load data. 

![Screenshot from 2019-04-11 15-11-34](https://user-images.githubusercontent.com/5508956/55947483-25170600-5c6c-11e9-86a6-4479d1ae185e.png)

Thanks
