### ISSUE TITLE
Support pluggable NodeHealthItem renderers and clean up default Scope ones

### ISSUE THREAD

**Issue by fbarl** [weaveworks/scope#3247]
In Scope standalone, these are not clickable:

![image](https://user-images.githubusercontent.com/1216874/42100183-cdfdafe6-7bbf-11e8-8d61-a7dab8e86cc3.png)

However, if we're in Weave Cloud, these link to dashboards with more info. We should strip the Scope code from those links and instead support optional _render_ func params which override/extend the default behaviour (e.g. see https://github.com/weaveworks/scope/pull/3244 for other Node Details stuff).

Part of https://github.com/weaveworks/service-ui/issues/2759 - getting rid of Weave Cloud UI code in Scope.

**Comment by bboreham** [comment]
I'm not entirely sure what you are referring to - I don't recognize the term "NodeHealthItem" nor the idea of linking to _dashboards_.

I thought we had created the metrics stuff so it would work for any Prometheus-compatible system where a URL would take you to a page which runs a query.  In Weave Cloud we use a Notebook page.

**Comment by fbarl** [comment]
@bboreham Point taken. My understand of that logic was wrong - what we really need to support here is passing custom link wrappers to the Scope UI component instead of having Weave Cloud specific `CloudLink` wrappers in Scope code.

Opened #3278 in favor of this issue.
