### ISSUE TITLE
Prometheus agent sending huge bursts of samples

### ISSUE THREAD

**Issue by masterley** [weaveworks/scope#3264]
Currently in conversation with support regarding this issue.
Running a kubernetes cluster of 6 nodes, 20vCPU and 120GB mem. Running in the region of 130 pods. The cluster is never resource constrained. 

Logs attached.
[weave-prometheus-logs.tar.gz](https://github.com/weaveworks/scope/files/2184845/weave-prometheus-logs.tar.gz)

**Comment by bboreham** [comment]
I'm going to close this because it isn't really a Scope issue - we will continue from the support ticket.
