### ISSUE TITLE
Move to Circle 2.0

### ISSUE THREAD

**Issue by fbarl** [weaveworks/scope#3288]
From any of our jobs in Circle CI:

![image](https://user-images.githubusercontent.com/1216874/43327674-4d2a32be-91bc-11e8-8877-859a87974c3e.png)

We only have about one more month to go!

Could potentially help with #2271.

**Comment by fbarl** [comment]
A hint from @bboreham in https://github.com/weaveworks/scope/pull/3295#issuecomment-409531361:

> I've tended to use pre-build build images for speed. E.g. https://github.com/weaveworks/weave/pull/3270/files , https://github.com/weaveworks/service-conf/blob/master/.circleci/config.yml

**Comment by fbarl** [comment]
Anyone else feels like having a stab at it? @bboreham @leth @guyfedwards

**Comment by guyfedwards** [comment]
Happy to pick it up 👍

**Comment by guyfedwards** [comment]
I don't think I am going to have much time this week to look at this, anyone else has some time, @bboreham @leth ?

**Comment by bboreham** [comment]
Duplicate of #3217
