### ISSUE TITLE
make getting the docker run command easier

### ISSUE THREAD

**Issue by progrium** [weaveworks/scope#329]
The launcher is nice, but it won't work for how we deploy stuff. And I imagine many others. I had to pick through the script to see how the container is actually run. It would be nice to see the docker run command as an alternative way to run it in the readme, and/or a subcommand that will return the docker run command (that could be passed into a subshell or just copy and pasted from the command line). 

I can submit a PR for the former if that sounds ok.

**Comment by tomwilkie** [comment]
Hi Jeff; a contribution like that would be welcome.

The scope script is also used to register scope with weave DNS, which is
done so scopes can find each other and automatically cluster.

Thanks

Tom

**Comment by progrium** [comment]
It's a privileged container so you could register from inside the
container, right?

On Tuesday, July 21, 2015, Tom Wilkie <notifications@github.com> wrote:

> Hi Jeff; a contribution like that would be welcome.
>
> The scope script is also used to register scope with weave DNS, which is
> done so scopes can find each other and automatically cluster.
>
> Thanks
>
> Tom
>
> On Monday, 20 July 2015, Jeff Lindsay <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > The launcher is nice, but it won't work for how we deploy stuff. I had to
> > pick through the script to see how the container is actually run. It
> would
> > be nice to see the docker run command as an alternative way to run it in
> > the readme, and/or a subcommand that will return the docker run command
> > (that could be passed into a subshell or just copy and pasted from the
> > command line).
> >
> > I can submit a PR for the former if that sounds ok.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/weaveworks/scope/issues/329>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/weaveworks/scope/issues/329#issuecomment-123218616>.
>


-- 
Jeff Lindsay
http://progrium.com

**Comment by tomwilkie** [comment]
Yes thats a good point; we should do that.
