### ISSUE TITLE
Single nodes should not use stacked node icon

### ISSUE THREAD

**Issue by bia** [weaveworks/scope#3296]
kube-dns... and weave-flux... have the correct icon, however since nodes like the orange 1701fc... comprise only 1 container, their icon should not be stacked.
cc @bboreham 

<img width="567" alt="screen shot 2018-08-01 at 15 16 22" src="https://user-images.githubusercontent.com/92439/43523901-110f84c4-959e-11e8-9ec1-ca5a8823d539.png">

Related to plans for developing #2667.

**Comment by rade** [comment]
I am not convinced. I've always read the stack as "_may_ contain more than one thing". A pod with a single container is different from _just_ a container, and while right now we never show both in the same graph, that may change (see e.g. #522), and hence they should be represented by different icons.

**Comment by bia** [comment]
Ok, makes sense.
