### ISSUE TITLE
Error doing controls for 127.0.0.1, backing off 1s: dial tcp 127.0.0.1:4040: connect: connection refused

### ISSUE THREAD

**Issue by gggitpl** [weaveworks/scope#3299]
$ scope version
Weave Scope version 1.9.1

$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:11:02 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:09:05 2018
  OS/Arch:          linux/amd64
  Experimental:     false

$ uname -a
Linux instance-l5h7edlz 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

## Logs:
```
$ docker logs weavescope
```
<app> INFO: 2018/08/06 03:36:33.559901 app starting, version 1.9.1, ID 27bec0b8031eda8e
<app> INFO: 2018/08/06 03:36:33.560034 command line args: --mode=app --probe.docker=true
time="2018-08-06T03:36:33Z" level=info msg="publishing to: 127.0.0.1:4040"
<probe> INFO: 2018/08/06 03:36:33.640257 command line args: --mode=probe --probe.docker=true
<probe> INFO: 2018/08/06 03:36:33.640304 probe starting, version 1.9.1, ID 4dffa2fea96c799f
<app> INFO: 2018/08/06 03:36:33.655053 listening on :4040
<app> WARN: 2018/08/06 03:36:33.742633 Error updating weaveDNS, backing off 20s: Error running weave ps: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> WARN: 2018/08/06 03:36:33.849285 Cannot resolve 'scope.weave.local.': dial tcp 172.17.0.1:53: connect: connection refused
<probe> INFO: 2018/08/06 03:36:33.965025 Control connection to 127.0.0.1 starting
<probe> WARN: 2018/08/06 03:36:34.505717 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: connect: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> ERRO: 2018/08/06 03:36:34.544275 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 8388608 bytes.
<probe> INFO: 2018/08/06 03:36:34.566801 Publish loop for 127.0.0.1 starting
<probe> WARN: 2018/08/06 03:36:44.506687 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: connect: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<app> ERRO: 2018/08/06 03:36:49.482713 Error checking version: Get https://checkpoint-api.weave.works/v1/check/scope-app?arch=amd64&flag_kernel-version=4.13.0-36-generic&flag_os=linux&os=linux&signature=j7sFoRNmCp9V8x%2FiiU%2F1jjOIH8eRSj5jPiVrwBP%2BxBg%3D&version=1.9.1: dial tcp 172.217.160.115:443: i/o timeout
<app> WARN: 2018/08/06 03:36:53.760693 Error updating weaveDNS, backing off 40s: Error running weave ps: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> WARN: 2018/08/06 03:37:04.507657 Error collecting weave status, backing off 40s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: connect: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
INFO: 2018/08/06 03:46:52.487945 === received SIGINT/SIGTERM ===
*** exiting
<app> INFO: 2018/08/06 03:46:52.488395 app exiting
ok: down: app: 0s, normally up
<probe> ERRO: 2018/08/06 03:46:52.504782 Error doing publish for 127.0.0.1, backing off 1s: Post http://127.0.0.1:4040/api/report: EOF
INFO: 2018/08/06 03:46:52.505793 === received SIGINT/SIGTERM ===
*** exiting
<probe> ERRO: 2018/08/06 03:46:52.512862 Error doing controls for 127.0.0.1, backing off 1s: dial tcp 127.0.0.1:4040: connect: connection refused
<probe> INFO: 2018/08/06 03:46:52.513036 Control connection to 127.0.0.1 exiting
<probe> INFO: 2018/08/06 03:46:52.515857 Publish loop for 127.0.0.1 exiting
<probe> INFO: 2018/08/06 03:46:52.515986 probe exiting
ok: down: probe: 0s, normally up
reaped child process 22926 (0)
/sbin/sv stop probe: waitid: no child processes

**Comment by bboreham** [comment]
Can you clarify what happened just before this error message?
Looks like you asked Scope to shut down?

**Comment by gggitpl** [comment]
Just did these
##### Getting started
sudo curl -L git.io/scope -o /usr/local/bin/scope
sudo chmod a+x /usr/local/bin/scope
scope launch

**Comment by bboreham** [comment]
Well it thinks it got a signal about ten minutes after you started it.  Is this symptom repeatable?

**Comment by gggitpl** [comment]
@bboreham 
Sorry, I don’t understand very well. I am Chinese.
Can you say a little more, or give some advice? Thank you very much.

**Comment by bboreham** [comment]
I think this is just a bit of noise in the logs when you ask Scope to shut down - there are two parts, and one of them tried to talk to the other just as it had shut down.
