### ISSUE TITLE
Migrate to CircleCI 2.0 before August 31st

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#3303]
CircleCI 1.0 will be decommissioned on August 31st so we should make sure to migrate the configuration to 2.0 before that happens.

**Comment by 2opremio** [comment]
More dtails: https://circleci.com/blog/sunsetting-1-0/

**Comment by bboreham** [comment]
Duplicate of #3288

**Comment by 2opremio** [comment]
ops, my bad
