### ISSUE TITLE
CRI: improve error msg when probe fails

### ISSUE THREAD

**Issue by LiliC** [weaveworks/scope#3306]
We should format the error msg in a better way to know where it originates. e.g. include CRI probe in the msg.
Currently this is how the error msg looks like:
```
 probe> ERRO: 2018/08/08 09:50:46.146900 error generating report: rpc error: code = Unavailable desc = grpc: the connection is unavailable
```

**Comment by bboreham** [comment]
Do you know where in the code the error originates?

**Comment by princerachit** [comment]
May I work on this issue? @LiliC
