### ISSUE TITLE
URL mentioned in repository description shows Page not found

### ISSUE THREAD

**Issue by rachari** [weaveworks/scope#3313]
The URL mentioned in the repository description shows Page not found.

Broken URL - https://www.weave.works/product/weave-scope/

Assuming that this is the correct URL - https://www.weave.works/oss/scope/

Can the repository description be updated so that it points to the correct URL ?

![weaveworks_scope_broken_url](https://user-images.githubusercontent.com/7726582/43960106-7df7d54c-9ca0-11e8-93fd-2b58f41e600e.png)

**Comment by dholbach** [comment]
Thanks a lot for reporting this. Fixed!
