### ISSUE TITLE
weave-scope-agent  pod status Blocked

### ISSUE THREAD

**Issue by zhenfdfs** [weaveworks/scope#3319]
I excute command as follow
kubectl apply -f "https://cloud.weave.works/k8s/scope.yaml?k8s-version=$(kubectl version | base64 | tr -d '\n')"
after this, I excute kubectl get pods -n weave, the output show  weave-scope-agent-xxx  pod status Blocked, what's meaning for this status?

**Comment by SaifRehman** [comment]
same issue
