### ISSUE TITLE
Weave scope in Kubernetes cluster not showing any containers in UI

### ISSUE THREAD

**Issue by aditivghag** [weaveworks/scope#3327]
Hi! I have installed Weave scope in a Kubernetes cluster. When I connect to the UI, not a single container is displayed. 

Scope version: 1.9.1
Kubernetes version: 1.10

kubectl get pods -n weave
NAME                               READY     STATUS    RESTARTS   AGE
weave-scope-agent-9vsqn            1/1       Running   0          15h
weave-scope-agent-ww4kz            1/1       Running   0          15h
weave-scope-agent-xpsjt            1/1       Running   0          15h
weave-scope-app-75f7f59dc5-9845h   1/1       Running   0          15h

 kubectl get service -n weave
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
weave-scope-app   ClusterIP   10.100.88.161   <none>        80/TCP    15h

 kubectl describe service weave-scope-app -n weave
Name:         weave-scope-app
Namespace:    weave
Labels:       app=weave-scope
              name=weave-scope-app
              weave-cloud-component=scope
              weave-scope-component=app
Annotations:  cloud.weave.works/launcher-info={
  "original-request": {
    "url": "/k8s/v1.8/scope.yaml",
    "date": "Wed Aug 22 2018 22:10:20 GMT+0000 (UTC)"
  },
  "email-address": "support@weave.works"
}
Selector:          app=weave-scope,name=weave-scope-app,weave-cloud-component=scope,weave-scope-component=app
Type:              ClusterIP
IP:                10.100.88.161
Port:              app  80/TCP
TargetPort:        4041/TCP
Endpoints:         172.25.0.2:4041
Session Affinity:  None
Events:            <none>

curl http://172.25.0.2:4040/api
{"capabilities":{"historic_reports":false},"hostname":"weave-scope-app-75f7f59dc5-9845h","id":"39c96d8bee9d647b","plugins":[],"version":"1.9.1"}

Weave containers (weave-scope-agent and weave-app don't have any error messages)

What could I be missing? How do I go about troubleshooting this?

Thanks for your help!
<img width="1349" alt="screen shot 2018-08-23 at 10 56 07 am" src="https://user-images.githubusercontent.com/7741174/44543008-3bfbee80-a6c3-11e8-98d6-9962819bb12e.png">

**Comment by aditivghag** [comment]
There was an issue with agents not being able to connect to the app service. With that fixed, I'm able to see all the deployed containers in my cluster. Closing this issue.

**Comment by khaniqshahid** [comment]
I have same issue, and there is no error or connection issue it shows. May I ask help here?
