### ISSUE TITLE
package.json content in weave-scope.tgz not always up to date

### ISSUE THREAD

**Issue by fbarl** [weaveworks/scope#3351]
For example, commit https://github.com/weaveworks/scope/commit/3f66348ad78dba8f000ec5a9cb5c314f66d63417 bumps the `weaveworks-ui-components` version to `0.12.2`, but looking into the corresponding package build https://s3.amazonaws.com/weaveworks-js-modules/weave-scope/3f66348a/weave-scope.tgz, there the `package.json` file still says `"weaveworks-ui-components": "0.11.14"`.

Looks like a caching issue with the UI part of our build pipeline, possibly related to #3333.

cc @bboreham @guyfedwards @foot

**Comment by bboreham** [comment]
Yes, the changes in #3333 require you to push a new build image and change `.circleci/config.yml` to point to it every time the contents of that image change.

**Comment by leth** [comment]
A couple of other alternatives: 
1. remove the baked-in-ui-build-image and add yarn cache to the circleCI cache instead
2. Overwrite the `package.json` with the up-to-date one

I think 1 would be best as 2 is actually more complex than it sounds once you try and work out how to ensure the package published has the right versions etc.

**Comment by guyfedwards** [comment]
Yea I wondered about 1, and then was reminded about my previous experiences trying to get node_modules caching to work properly in CI. That would be a good solution though as yarn is lightning when from cache.

Thinking about it, its a little early days yet but the yarn Plug-n-Play proposal could be helpful in the future https://github.com/yarnpkg/rfcs/pull/101
