### ISSUE TITLE
Support Kubernetes Job workload

### ISSUE THREAD

**Issue by bboreham** [weaveworks/scope#3362]
The Scope probe reports CronJobs; it should also report plain Jobs.

And the GUI should display them.

**Comment by rade** [comment]
Display them where? Jobs don't have a controller, so they don't naturally belong in the Controller topology.

**Comment by bboreham** [comment]
Job looks enough like Deployment for me to say put them in the same place.

**Comment by rade** [comment]
> Jobs don't have a controller

Actually, reading the docs again, it looks like they do.

**Comment by bboreham** [comment]
This is what CronJobs look like: 
![image](https://user-images.githubusercontent.com/8125524/46683763-eb940e00-cbe8-11e8-9af4-f9e8d987b1a8.png)
