### ISSUE TITLE
Label scope container (and weave container) as 'system', filter them from view.

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#337]

**Comment by tomwilkie** [comment]
I'm going to use the PR in weave as a canary; we'll use the same label in scope that they do.

**Comment by squaremo** [comment]
If you want this to be a general mechanism for hiding containers from display in Scope, I think using labels is a poor choice. Firstly, it's indirect -- you're asking the user to go and change how a container is labelled (which involves *recreating* the container!), just to hide it in their display. Secondly, the user may not even have control over how containers are created -- that might be done by kubernetes, or marathon, or whatever.
