### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by 1032231418** [weaveworks/scope#3394]
Does the project provide interface connection? For example, Python

**Comment by bboreham** [comment]
@1032231418 the components of Scope talk to each other via http, sending data that is either JSON or MSGPACK-encoded. So yes, it would be possible to do something in Python.

Note there is no documentation for the interfaces outside of the source code.

**Comment by 1032231418** [comment]
If you have an interface document, it is a good thing to look forward to adding it.
