### ISSUE TITLE
Error building /app

### ISSUE THREAD

**Issue by tayzlor** [weaveworks/scope#34]
Not sure if you wan't bug reports or not yet... but when running make build I had an issue. Drilling down a bit the error occurs when building in /app

```
scope/app# go build -v
github.com/gorilla/context
github.com/gorilla/mux
github.com/gorilla/websocket
github.com/weaveworks/scope/report
github.com/weaveworks/scope/xfer
_/root/scope/app
go build _/root/scope/app: /usr/local/go/pkg/tool/linux_amd64/6g: signal: killed
```

I'm running on ubuntu 14.04 using ```go version go1.4.2 linux/amd64```

**Comment by tomwilkie** [comment]
Hi!  Is your $GOPATH setup properly?  Where have you checkout out scope?

**Comment by tayzlor** [comment]
as root on a digitalocean instance - 

```
echo $GOPATH
/root/go
```
scope is checked out to 
```
/root/scope/app
```

**Comment by tomwilkie** [comment]
You need to checkout scope into the appropriate place; move it to /root/go/src/github.com/weaveworks/scope then give it a go.

**Comment by tayzlor** [comment]
Looks like I already have a ```go/src/github.com/weaveworks/scope/``` and a ```go/src/github.com/weaveworks/procspy``` dirs there. Might have been retrieved via go get ?

**Comment by tomwilkie** [comment]
Could have; I'd delete /root/scope and run with the ones in go/src/...

If you do a make in there, does it work?

**Comment by tayzlor** [comment]
See above - doesn't work form ~/go/src/github.com/weaveworks/scope either

**Comment by tomwilkie** [comment]
Hmmm I'm at a bit of a loss; could be something to do with building as root?  I doubt it.  Can you build other go projects?

Do you get the same error when running make in the root of the repo?

**Comment by tomwilkie** [comment]
According to this it might be a memory problem: https://github.com/beego/wetalk/issues/32

How much memory does the VM have?

**Comment by tayzlor** [comment]
its just a small DO instance - so it has 512 MB

**Comment by tomwilkie** [comment]
Ah thats probably it.  I think you might need more memory to build I'm afraid.

**Comment by tayzlor** [comment]
Cool - i'll try bumping it and see

**Comment by tayzlor** [comment]
Confirming build works if I bump to 1GB memory, Closing.
