### ISSUE TITLE
LICENSE info missing from README.md

### ISSUE THREAD

**Issue by akshatnitd** [weaveworks/scope#3404]
## What you expected to happen?
LICENSE info should be present in the README.md

## What happened?
LICENSE info missing from README.md

## How to reproduce it?
NA

## Anything else we need to know?
NA

## Versions:

```
$ scope version
$ docker version
$ uname -a
$ kubectl version
```

## Logs:
```
$ docker logs weavescope
```
or, if using Kubernetes:
```
$ kubectl logs <weave-scope-pod> -n <namespace> 
```

**Comment by bboreham** [comment]
Please provide some justification for this issue.

There is a file https://github.com/weaveworks/scope/blob/master/LICENSE, which is a very common pattern; GitHub puts a nice icon to link to it on the home page.
