### ISSUE TITLE
Favicon icon is missing in UI dev mode

### ISSUE THREAD

**Issue by satyamz** [weaveworks/scope#3434]
## What you expected to happen?
Weaveworks logo should appear as a favicon. 
## What happened?

favicon icon is missing from the scope.
## How to reproduce it?

I am trying to build & test latest changes on the master branch as release is close.

`cd client`
`yarn install && yarn start`

## Anything else we need to know?

@fbarl was able to reproduce this issue too.
## Versions:

```
```
![image](https://user-images.githubusercontent.com/5508956/48838732-42c3fb80-edaf-11e8-8c75-f7de20129767.png)

**Comment by bboreham** [comment]
If I do a full `make` then `scope launch` I do get the favicon.

So maybe this is just a problem with the development workflow of `yarn start` ?

**Comment by satyamz** [comment]
Yes!

**Comment by satyamz** [comment]
Tried this now, its working for me.

**Comment by fbarl** [comment]
Experiencing this again in dev mode...
