### ISSUE TITLE
authentication for weavescope web UI

### ISSUE THREAD

**Issue by devops083** [weaveworks/scope#3453]
how to enable authentication for weavescope web UI ?

**Comment by 2opremio** [comment]
We support HTTP basic auth. Set the following environment variables for both the Scope app and the Scope probe:

`ENABLE_BASIC_AUTH`: set to `true` 
`BASIC_AUTH_USERNAME`: set to the desired user (defaults to `admin`)
`BASIC_AUTH_PASSWORD`: set to the desired password (defaults to `admin`)

**Comment by rade** [comment]
Shouldn't this be documented somewhere?

**Comment by 2opremio** [comment]
Yep, it definitely should. I had to figure it out from the sourcecode.

**Comment by devops083** [comment]
I have configured weavescope in k8s

kubectl apply -f "https://cloud.weave.works/k8s/scope.yaml?k8s-version=$(kubectl version | base64 | tr -d '\n')"

where shoud I enable authentication in above scrip?

**Comment by devops083** [comment]
done its working thnx

**Comment by dholbach** [comment]
It's very briefly documented here: https://github.com/weaveworks/scope/blob/master/site/faq.md#rbac-and-weave-scope-oss

**Comment by fbarl** [comment]
@devops083 I've opened #3531 to clarify that in our FAQ section.

I'll close this issue as it seems your questions have been answered by @2opremio, but feel free to reopen it if you have more follow-up questions.

**Comment by 2opremio** [comment]
> It's very briefly documented here

I think we should at least add documentation for the env variables.

**Comment by M0nsieurChat** [comment]
Hello there,
We love using Scope and we would like to make our project managers use it.

However, we would be comfortable for them to use their own bearer token so that we can restrict the namespaces and objects they can see instead of the whole cluster for everyone.

Is there something I could do to achieve this goal ?

Cheers,

**Comment by fbarl** [comment]
Hi @M0nsieurChat,

Thanks for showing interest in Scope!

> However, we would be comfortable for them to use their own bearer token so that we can restrict the namespaces and objects they can see instead of the whole cluster for everyone.

Unfortunately, there is nothing of that sort in place right now. As mentioned above, Scope doesn't even have a concept of a user role (yet!), so limiting access to e.g. namespaces per user is not possible. However, here are a few options you might consider:

1. You can check out https://github.com/weaveworks/scope/blob/master/examples/k8s/cluster-role.yaml as an example on how to set up global Scope permissions in the Kubernetes setting
2. Check out the updated docs on how to disable write access: https://github.com/weaveworks/scope/blob/e373b04ff469c65cc53aca07dd45b25c46c52455/site/faq.md#disabling-scope-write-access
3. While Weave Scope OS doesn't have a concept of user roles, Weave Cloud service (that includes Weave Scope and a lot more) has a basic implementation of RBAC, so you might be interested in checking that option - https://www.weave.works/product/cloud/

Finally, if none of the suggestions above works for you, we always accept new PRs and this one would be quite a feature! :)
