### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by devops083** [weaveworks/scope#3454]
## Versions:

```
$ scope version
$ docker version
$ uname -a
$ kubectl version
```

## Logs:
```
$ docker logs weavescope
```
or, if using Kubernetes:
```
$ kubectl logs <weave-scope-pod> -n <namespace> 
```

**Comment by 2opremio** [comment]
@devops083 we need a lot more information than this for this ticket being valid. Can you please edit the description and add a few phrases indicating what's the problem or what feature you want?
