### ISSUE TITLE
Can't find docker's relationship by Weave Scope

### ISSUE THREAD

**Issue by xrgy** [weaveworks/scope#3538]
**What happened**
Weave Scope can't find docker's relationship.There are some cases:
For example, Prometheus and Alertmanger, there is flow by tcpdump. But Weave Scope can't find it.
And this case, AlertManager push alerts to an webhook endpoint. Weave Scope can't find their relationship.

**Version**
Kubernetes: 1.5
Prometheus:2.2
AlertManager:0.15

**Comment by bboreham** [comment]
What I wanted to know was: is Prometheus opening a connection to alertmanager by service address (“cluster ip”), or by pod ip, or some other way?

**Comment by xrgy** [comment]
cluster ip, service address

**Comment by xrgy** [comment]
Endpoint is using conntrack. Container 's topology is from pod. Pod's topology is from  container. Why containers'relationship can't be found. But their pods'relationship can be found. Why? Its confused me!!!

**Comment by bboreham** [comment]
I tried to recreate this issue by making a Kubernetes cluster using `kubeadm` and installing the [Prometheus Operator](https://github.com/coreos/prometheus-operator/tree/master/contrib/kube-prometheus)

I see connections between Prometheus and Alertmanager in Pods:

![image](https://user-images.githubusercontent.com/8125524/50653917-0b866400-0f83-11e9-8fd9-d14c8ba9cdea.png)

and in Containers:

![image](https://user-images.githubusercontent.com/8125524/50653955-248f1500-0f83-11e9-97c7-a7518e35fedf.png)

So I still do not know what is going wrong in your case.

Please give more detail how you set up Prometheus and Alertmanager.

**Comment by xrgy** [comment]
Is it with ebpf?
The relationship about Prometheus with Alertmanager in my case is just using conntrack. My kernel doesn’t support ebpf.
What about yours? With ebpf?

发自我的 iPhone

**Comment by bboreham** [comment]
Never did find out what this issue was about.
