### ISSUE TITLE
weave-scope-agent and app cause DNS flooding upstream in k8s standalone

### ISSUE THREAD

**Issue by VileBrigandier** [weaveworks/scope#3544]
## Expected Behavior
Installing Weave Scope in a standalone Kubernetes deployment should work without incorrect DNS lookups being sent upstream.

### Problem 1:
After installing Weave Scope in my home lab, I began getting a lot of DNS lookups on my upstream DNS for `weave-scope-app.weave.svc.cluster.local.mydomain.com`. After enabling coredns logging, I saw failed lookups for the same but also `weave-scope-app.weave.svc.cluster.local.weave.svc.cluster.local`, `weave-scope-app.weave.svc.cluster.local.svc.cluster.local`, and `weave-scope-app.weave.svc.cluster.local.cluster.local.`.

### Problem 2:
Later I noticed a load of lookups for `localhost.mydomain.com` and `localhost` in my upstream DNS as well. In the coredns logs, I also see the same for the Kubernetes search domains similar to above.

### Problem 1:
This appears to affect all weave scope installs done with the example config. Here's the link to the problem line: https://github.com/weaveworks/scope/blob/master/examples/k8s/ds.yaml#L32 - the argument `- 'weave-scope-app.weave.svc.cluster.local:80'` doesn't have enough dots to satisfy the usual `ndots:5` requirement in resolv.conf, causing the agents to attempt to find the above at all search domains in resolve.conf. Once all of those fail it attempts a direct resolve and gets the proper address.

### Problem 2:
Update: The `localhost` lookups upstream are for a completely different reason than above. There is no `/etc/nsswitch.conf` file in the agent/app containers, so it doesn't attempt to do DNS resolution via file before attempting DNS lookup. See https://github.com/gliderlabs/docker-alpine/issues/367

### Problem 1:
I found two fixes for the weave-scope-app lookup issue:

1. Add an additional dot to the end of the address, which isn't good for portability it seems; or,
2. trim this down to `weave-scope-app:80` and let search domains work properly. The first search domain in resolv.conf handles this nicely.

### Problem 2:
The fix for the `localhost` lookups upstream was to add `/etc/nsswitch.conf` to all the containers. I accomplished this by adding a configmap with default `nsswitch.conf` contents, and using a volumeMount in the deployment/daemonset to mount this into `/etc/nsswitch.conf` on the containers.

![image](https://user-images.githubusercontent.com/8582658/50703205-ff4ce600-1018-11e9-80de-5b3577ae6af3.png)
This graph shows clearly where queries ramped up when Weave Scope was installed and fell off after using the solutions above.

## Versions:
This isn't version related, but DaemonSet configuration related, and affects the yaml used in your current Kubernetes install URL in the Installation docs as well.

Thanks!

**Comment by bboreham** [comment]
Thanks for the report, @VileBrigandier .  This multiple DNS lookups is very typical with Kubernetes.

I don't understand "isn't good for portability" - I have often recommended adding a dot, elsewhere.  Can you explain what you meant?

**Comment by VileBrigandier** [comment]
@bboreham I just mean if someone decides to use a different namespace name, they'll have to go update the URL as well from `weave-scope-app.weave.svc.cluster.local.` to `weave-scope-app.somethingElse.svc.cluster.local`. By keeping it very short, it'll use whatever namespace is in resolv.conf on the first search domain and should work nicely.

But, I am still fairly new to Kubernetes, I have been wrong before. :)

**Comment by icebal** [comment]
going by the kubernetes reasoning below, the correct way is to do just service name, and leave the rest to internal dns:

https://github.com/kubernetes/kubernetes/issues/33554#issuecomment-266251056

**Comment by VileBrigandier** [comment]
I have updated the original bug report, as these containers are also spamming upstream DNS with `localhost.mydomain.com` and `localhost` lookups. This is due to neither the app or agent containers having an `/etc/nsswitch.conf` file that specifies to attempt host lookups by file before dns. Adding a default `nsswitch.conf` fixes this issue and the containers begin resolving localhost via `/etc/hosts` as expected.

**Comment by bboreham** [comment]
We're not going to add `nsswitch.conf`.  What is looking up `localhost` ?  I cannot find any mention of that name in the Scope source code.
Maybe open a separate issue for that?

**Comment by VileBrigandier** [comment]
I don't know on the code level what is looking up localhost, only that the app container and all agent containers are attempting to do so via DNS server instead of checking `/etc/hosts` first. When adding `nsswitch.conf` and giving the container instruction to check file for resolution before DNS (like most Linux systems) they all quit doing it.

I've adjusted my manifest on both fronts and I am satisfied now, this was to let you guys know the behaviors are there and clear it up for anyone else experiencing the same.

**Comment by bboreham** [comment]
Don't we still want to fix https://github.com/weaveworks/scope/blob/master/examples/k8s/ds.yaml#L32 ?

**Comment by bboreham** [comment]
Looking at https://github.com/golang/go/issues/22846, maybe we should add `nsswitch.conf`. 
Still, it's a separate issue.

**Comment by 2opremio** [comment]
I added nsswitch for flux in case we want to reuse that for scope https://github.com/weaveworks/flux/pull/1630

**Comment by bboreham** [comment]
Thanks. Personally I would avoid a lookup on `localhost` as I've been bitten enough times from that resolving to some random address, and `127.0.0.1` is easy enough to type.  Still that would be a separate issue.
