### ISSUE TITLE
Consider gently converging NodeMetadata struct and RenderableNode

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#357]
- move adjacency information in a topology into the NMDs
- have probes make psuedo nodes

**Comment by inercia** [comment]
How are these _pseudo-nodes_ going to be generated? I assume that this will break the _"Internet"_ node in some other _pseudo-nodes_, but we probably do not want to generate a _pseudo-node_ for each remote end of a connection, so is there any rule we will follow for generating these nodes?

**Comment by tomwilkie** [comment]
Currently the probes only create nodes for stuff (endpoints, processes) it actually has locally - but it creates edges to things that might (or might not exist).  This means the graph is incomplete.  In the rendering stage, we introduce these pseudo nodes if they don't exist.

The idea here would be to have the probes create nodes for both ends of every edge in a way that merges nicely if both ends of the connection are seen by two different probes.

**Comment by inercia** [comment]
Cool, but wouldn't this mean that probes would be sending lots of data for nodes that would never be rendered?

**Comment by tomwilkie** [comment]
> Cool, but wouldn't this mean that probes would be sending lots of data 

Not "lots" - a constant factor more than we already send.  And we have compression.

> for nodes that would never be rendered?

Pseudo nodes are rendered.

**Comment by tomwilkie** [comment]
Part of this is addressed in #411

Suggested next steps:
* Move EdgeMetadatas into NodeMetadata.EdgeMetadatas, define appropriate merge and collapse semantics.  Merge is as-is, collapse would merge together all the edgemetadatas for a single node into the edgemetadata in RenderableNode.  Could also solve the edge double-counting issue.
* Rename NodeMetadata (and associated types & functions) to Node
* Topology just has a single field map[string]Node - don't want to collapse, as we'll be adding capability descriptors there in the future.

Then options for converging RenderableNode and Node.  We shouldn't change the API to the UI, so we still need to serve RenderableNodes (or things that look like RenderableNodes):
* Embed Node struct in RenderableNode, provide a function to generate a basic RenderableNode from a Node, perhaps with heuristics for filling out Names.  Leave the current rendering pipeline in tact.
* Extend Node to have LabelMajor, LableMinor, Rank, etc etc fields.  Have the probe attempt to fill them in appropriately.  Define some merge semantics for how these fields are merged...

Other ideas?

**Comment by tomwilkie** [comment]
Independently, we can now merge LeafMap and Map in the rendering pipeline, which I'll do next.

@peterbourgon thoughts on above?

**Comment by tomwilkie** [comment]
We should also be able to merge report/id.go and render/id.go

**Comment by tomwilkie** [comment]
Also, we could consider removing Adjacency altogether, and just going off EdgeMetadata (with empty structs where appropriate)

**Comment by peterbourgon** [comment]
> Move EdgeMetadatas into NodeMetadata.EdgeMetadatas,

I guess this can be just `NodeMetadata.Edge` (or Edges)

> define appropriate merge and collapse semantics. Merge is as-is, collapse would merge together all the edgemetadatas for a single node into the edgemetadata in RenderableNode. 

Sure. Collapse is spelled "Flatten".

> Rename NodeMetadata (and associated types & functions) to Node

I'd have to see how it feels on the page, but sure.

> Topology just has a single field map[string]Node - don't want to collapse, as we'll be adding capability descriptors there in the future.

Yep.

> Then options for converging RenderableNode and Node. We shouldn't change the API to the UI, so we still need to serve RenderableNodes (or things that look like RenderableNodes):
>
> - Embed Node struct in RenderableNode, provide a function to generate a basic RenderableNode from a Node, perhaps with heuristics for filling out Names. Leave the current rendering pipeline in tact.

This makes sense...

> - Extend Node to have LabelMajor, LableMinor, Rank, etc etc fields. Have the probe attempt to fill them in appropriately. Define some merge semantics for how these fields are merged...

...this doesn't. A node generated at the probe level will effectively always go through transformations (merges) before it gets in front of a user. The concept of labels only make sense at the end of that pipeline, and it kind of has to be defined as part of the topology definition.

Good stuff overall. The expression engine will benefit massively from these changes. I'd like to bump it as high as we can in the priority queue.

**Comment by tomwilkie** [comment]
All agreed; I'll finish out this ticket before working on tracer.

**Comment by tomwilkie** [comment]
I think this little bout of refactoring is done now.
