### ISSUE TITLE
can not zoom in in latest chrome

### ISSUE THREAD

**Issue by leavest** [weaveworks/scope#3592]
## What you expected to happen?
It can zoom out and zoom in in chrome.
## What happened?

It can zoom out but can't zoom in after I've updated chrome to 73.0.3683.103(the latest version) 
and web  console:
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>

## How to reproduce it?

scope launch and use chrome version 73.0.3683.103(the latest version) to  open http://127.0.0.1:4040 and rolling.

## Anything else we need to know?

It works in firefox and older versions of the chrome
(I didn't go back to the older versions of the chrome, but it was fine a few days ago).
It can't zoom out and zoom in in safari.

## Versions:

```
$ scope version
Weave Scope version 1.10.2
$ docker version
$ uname -a
Darwin zuilideMacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Wed Feb 27 00:43:23 PST 2019; root:xnu-4570.71.35~1/RELEASE_X86_64 x86_64
$ kubectl version
```

**Comment by leavest** [comment]
resolved

**Comment by fbarl** [comment]
Thanks for opening the issue @leavest!

> resolved

We don't usually close issues until the PR that resolves them has been merged with master, so I will reopen this one.
