### ISSUE TITLE
Consider differentiating internet node between clients and servers

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#360]
With the directionality change, the internet node commonly appears at the top (for incoming connections) and bottom (for outgoing connections).  It might help users to duplicate the node, with a minor label for incoming/outgoing.

**Comment by peterbourgon** [comment]
This feels like it's counter to how pretty much everyone would visualize their infrastructure... we're not building a data/connection flow model, but rather a component graph. In a perfect world, we'd fix the internet at the top, then lay out the border components below that, then the application layer, and the data layer at the bottom. Edges that jumped between those layers would (and should!) stand out.

**Comment by peterbourgon** [comment]
I'd be really interested to see if we can fix the internet node at e.g. top-center, and then perform the rest of the layout top-to-bottom...

**Comment by paulbellamy** [comment]
The decision between a connection-flow diagram vs a component diagram is, "Which question are we trying to help the user ask/answer?"

For a component diagram, internet-at-the-top is also what I would expect, but maybe not necessarily as a single entity. e.g. I'm thinking of a webservice handling requests, sending emails via some service, and pushing out webhooks. *Ideally* there would be 3 internet nodes: Incoming requests, Email service, and Webhook targets.

**Comment by peterbourgon** [comment]
So partitioning the internet based on the (type of) node on the other side of the edge? That would be odd, I think. In any network diagram I've ever seen, the internet is a single node. That's what I care about as an operator or application designer: the stuff in my boundary of control, and then everything else...
