### ISSUE TITLE
Customize UI, 0 containers issue, and tracing db connection.

### ISSUE THREAD

**Issue by shindanim** [weaveworks/scope#3601]
## What you wanna do?
1. I'd like to modify some UI display. 
2. debug for "0 containers"
3. Is there any way to tracing connection to db ?

## Anything else we need to know?

My weave scope had been deployed with stable helm chart. 
![Screenshot from 2019-05-13 18-03-44](https://user-images.githubusercontent.com/15517737/57610473-d7aff080-75ab-11e9-93ce-d3b3fa2b6dea.png)

## Versions:

```
$ scope version 1.10.1
$ docker version 18.09.2
$ uname -a Linux dayoungshin 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version
Client Version: v1.13.0
Server Version: v1.11.8-eks-7c34c0
```

## Logs:
```
$ kubectl logs <weave-scope-pod> -n <namespace> 
<probe> WARN: 2019/05/13 05:03:01.829712 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: connect: connection refused
<probe> WARN: 2019/05/13 05:03:02.800212 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: connect: connection refused
<probe> WARN: 2019/05/13 05:03:03.822055 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: connect: connection refused
<probe> WARN: 2019/05/13 05:03:04.814679 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: connect: connection refused
<probe> WARN: 2019/05/13 05:03:05.801323 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: connect: connection refused
<probe> WARN: 2019/05/13 05:03:06.803980 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: connect: connection refused
```

**Comment by dholbach** [comment]
It looks like this issue is about three separate things. Can you please file three separate issues in Github please?

- Regarding 1: What are you trying to do? Are you trying to rebrand Scope? Or why do you want to remove the information?
- Regarding 2: This looks odd. And the logs you pasted below look like they're related. Were there some connection issues?
- Regarding 3: connections to the db should be listed in Scope. Are they not?

**Comment by shindanim** [comment]
[Issue 1](https://github.com/weaveworks/scope/issues/3602), [2,](https://github.com/weaveworks/scope/issues/3604) and [3](https://github.com/weaveworks/scope/issues/3604) has been separated to individual issue.
