### ISSUE TITLE
Customize web ui of scope

### ISSUE THREAD

**Issue by shindanim** [weaveworks/scope#3602]
## What you expected to happen?
Hello, weave team. 
Now I'm trying to customize web ui of scope for better usage. It's not regarding re-branding thing. 
* I'd like to remove version info of right bottom, 
because if there increases namespaces, the version info ui hide some of namespaces.
Please refer number 1 of following pic.
![Screenshot from 2019-05-13 18-03-44](https://user-images.githubusercontent.com/15517737/57743671-f7a4f880-7700-11e9-8ee9-c2811e38f019.png)

## Anything else we need to know?

My project is on AWS. k8s, helm controls my configuration. 
Also, stable helm chart is used for deploying scope. 

## Versions:

```
$ scope version 1.10.1
$ docker version 18.09.2
$ uname -a 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version
Client Version: v1.13.0
Server Version: v1.11.8-eks-7c34c0
```

**Comment by qiell** [comment]
This is already fixed in scope version `1.10.2`.

**Comment by satyamz** [comment]
Hi @shindanim, As pointed by @qiell, this has been fixed in the previous release i.e. `1.10.2`. Hence, I am closing this issue.

**Comment by shindanim** [comment]
Thanks for the information Weave team
, but don't you have any general guide for modifying Web UI? 
Because I'd like to size down the font on `node-details-header-label` of <h2> tag.

**Comment by satyamz** [comment]
You are welcome! 
I think @fbarl  can help you with UI modifications.
