### ISSUE TITLE
Cannot tracing db connection in scope

### ISSUE THREAD

**Issue by shindanim** [weaveworks/scope#3603]
## What you expected to happen?
Hello Weave team, 

For this moment, my team is using the weave scope for real-time connections. The connection to the aws resource or external auth server can be traced within scope, but the db connection does not seem to be traced.

Please see number 3 of following picture.
![Screenshot from 2019-05-13 18-03-44](https://user-images.githubusercontent.com/15517737/57743888-e7d9e400-7701-11e9-808d-47220d86f60c.png)

The rds of my system is aurora db of AWS.

## What happened?

Cannot tracing Aurora db connection from a backend service. 

## Anything else we need to know?

Server is on AWS(EKS), kubernetes and helm configures my cluster.  
Stable helm is used for deploying Weave Scope.

## Versions:

```
$ scope version 1.10.1
$ docker version 18.09.2
$ uname -a  4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ kubectl version v1.13.0
$ kubectl version v1.11.8-eks-7c34c0
```

**Comment by satyamz** [comment]
Hi @shindanim , How are you deploying Aurora DB? Is it a part of the EKS Kubernetes cluster?
If its not, then it will not be visible in the Scope.

**Comment by shindanim** [comment]
@satyamz Hello, thanks for your kind reply :)
My Aurora DB exists outside of my cluster. Is it the normal behaviour for the Weave Scope?
If then, I have another question. 
Sometimes, I found external connections like auth server connection which is not a part of my eks cluster, (which is not checked wich a `kubectl` command) become part of the topology while it is connected.
How can Weave detect connections outside the cluster?

**Comment by satyamz** [comment]
> Sometimes, I found external connections like auth server connection which is not a part of my eks cluster, (which is not checked wich a kubectl command) become part of the topology while it is connected.
How can Weave detect connections outside the cluster?

In Scope, only network connections are shown in case of the services running outside the cluster. Those are shown as a `The Internet` node on the UI.

**Comment by shindanim** [comment]
>> Sometimes, I found external connections like auth server connection which is not a part of my eks cluster, (which is not checked wich a kubectl command) become part of the topology while it is connected.
How can Weave detect connections outside the cluster?

> In Scope, only network connections are shown in case of the services running outside the cluster. Those are shown as a The Internet node on the UI.

Thanks @satyamz , 
1. Do you mean that the DB connection is not the network connection? 
2. I found that AWS secrets manager connection made though it is not the part of cluster.
How Scope can say the connection is for secrets manager like following topology? 
![question_secret_connection](https://user-images.githubusercontent.com/15517737/58148296-212dc900-7c99-11e9-9a85-4d464b7d8d5c.png)

**Comment by satyamz** [comment]
Hi @shindanim 
> Do you mean that the DB connection is not the network connection?

No. Your application and DB connection is certainly a network connection. 
In Kubernetes, we have a resource known as [PersistentVolume](https://kubernetes.io/docs/concepts/storage/persistent-volumes/), which is used to deploy DBs in the Kubernetes cluster. If you are not creating any PVC or PV to deploy the DBs in the Kubernetes cluster then that will not be visible in the Scope in the form of the (graph) nodes. If PVC and  PV are present then those will be shown in the cylinder form in Scope, which is visible when you use the storage filter in the `Pods` topology.

This is how it is shown:
 
![Screenshot from 2019-05-22 12-23-04](https://user-images.githubusercontent.com/5508956/58153734-71069300-7c8d-11e9-9d8a-f98e992d2c40.png)


In your case, DB is outside of the cluster. Hence, it will not be shown in the Scope as above. 


> I found that AWS secrets manager connection made though it is not the part of cluster.

They are outside hence shown as a `Cloud` nodes i.e. `The Internet` and `secretsmanager`. 

> How Scope can say the connection is for secrets manager like following topology?

Scope tracks all the network connections to and from the application. Here, your application must be communicating with AWS secret manager. Hence, it's showing connection to the outside node i.e. `Cloud` node, we call such node as `Pseudo Node`.

**Comment by shindanim** [comment]
> Scope tracks all the network connections to and from the application. 
Is this mean that Scope sniffs all the packets for all connections ?

**Comment by satyamz** [comment]
@shindanim 
> Is this mean that Scope sniffs all the packets for all connections ?

Yes!

**Comment by rade** [comment]
No, it doesn't. It traces the kernel's CONNECT, ACCEPT and CLOSE events on network file descriptors.

**Comment by satyamz** [comment]
Sorry, I got that wrong. Information for me to know  :sweat_smile:

**Comment by shindanim** [comment]
Thanks @satyamz @rade for solving my question :) !
