### ISSUE TITLE
Remove references to quay.io

### ISSUE THREAD

**Issue by fbarl** [weaveworks/scope#3614]
We've moved away from publishing Scope images in quay.io, but there are still places in the code referring to it, e.g.

* `.circleci/config.yml`
* `bin/release` script

We should remove all the code that tries to push to quay.io as we're unlikely to get back to it any time soon.

**Comment by dholbach** [comment]
Publishing to two different places makes sense. It's what Flux does as well AFAIR - Dockerhub and GCR? Maybe @2opremio or @hiddeco can comment?

**Comment by hiddeco** [comment]
Flux is currently only published to DockerHub, we have been talking about publishing it to multiple registry vendors but did not make a decision (yet).

**Comment by bboreham** [comment]
`.circleci/quay.io` only uses quay.io if a variable is set; `bin/release` fixed by #3657
