### ISSUE TITLE
today,I find a Mining procedure on my computer, the path show the /scope

### ISSUE THREAD

**Issue by youyouvi** [weaveworks/scope#3624]
## Versions:

```
$ scope version
$ docker version
$ uname -a
$ kubectl version
```

## Logs:
```
$ docker logs weavescope
```
or, if using Kubernetes:
```
$ kubectl logs <weave-scope-pod> -n <namespace> 
```

**Comment by bboreham** [comment]
Can you give more detail?  That’s not really enough information to do anything with. 

Those bits at the end, like `version` and `logs`, you are supposed to run the command and paste the output here. 

Use the address security@weave.works if it is confidential or you are reporting a vulnerability.

**Comment by youyouvi** [comment]
This morning, I found the mining program on the server I managed, disguised as a MySQL user.
So I used the "ls/proc/pid/cwd" instruction and found that the path pointed to / scope.
So I executed rm-rf/usr/local/bin/scope and rm-rf/run/scope.
Weave is installed according to the instructions on GitHub。
Sorry，my english is poor





------------------ 原始邮件 ------------------
发件人: "Bryan Boreham"<notifications@github.com>;
发送时间: 2019年5月27日(星期一) 下午3:29
收件人: "weaveworks/scope"<scope@noreply.github.com>;
抄送: "yo.vi"<yo.vi@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [weaveworks/scope] today,I find a Mining procedure on mycomputer, the path show the /scope (#3624)




Can you give more detail?  That’s not really enough information to do anything with.
 
Those bits at the end, like version and logs, you are supposed to run the command and paste the output here.
 
Use the address security@weave.works if it is confidential or you are reporting a vulnerability.

**Comment by bboreham** [comment]
Is your server open to the Internet?  In the installation instructions we warn " the Scope app endpoint (port 4040) should not be made accessible on the Internet"

**Comment by youyouvi** [comment]
Yes,  my server open to the Internet 


 
---Original---

**Comment by bboreham** [comment]
OK, suggest you use a firewall to block port 4040 from public access (indeed, block all ports you don't explicitly need to open).
We do try to warn about this [in the installation instructions](https://github.com/weaveworks/scope/blob/master/site/installing.md#installing-on-docker) - I've created #3650 to cover another place where users might arrive first.
