### ISSUE TITLE
Enable .JWT authentication or another solution

### ISSUE THREAD

**Issue by gibati** [weaveworks/scope#3640]
## Situation:

I Dear,

I would like to know if is possible enable .JWT authentication on weavescope, it's because we need to enable authetication by ldap, and I must to use multiple users for security restrictions.

I've read: https://www.weave.works/docs/scope/latest/faq/ ,
but I can't find the solution or I can't undertand as I need.

If exist other solution, please let'me know
thanks in advance

**Comment by bboreham** [comment]
JWT isn't built in.  You may find it easier to put a reverse-proxy in front of Scope which implements the restrictions you need - that's what we do in implementing https://cloud.weave.works

**Comment by gibati** [comment]
Thank you very much for the brief reply.
