### ISSUE TITLE
Can I get container association result information from weave scope？

### ISSUE THREAD

**Issue by AnyuanLuo** [weaveworks/scope#3656]
I want to get the associated data between the containers instead of visualizing them in the browser. Is there have a weave scope API, for example, the API will output  containers which associated the container1?

**Comment by fbarl** [comment]
Hi @AnyuanLuo,

There is a short API endpoints listing in Scope FAQ section - https://github.com/weaveworks/scope/blob/master/site/faq.md#api-endpoints.

Specifically, you can probe `/api/topology/containers` to get the info on all containers and `/api/topology/containers/[NODE_ID]` to get the info on a specific container, provided its internal ID.

I hope this answers your question.

**Comment by AnyuanLuo** [comment]
Thank you! That's Exactly what I need!

**Comment by fbarl** [comment]
> Thank you! That's Exactly what I need!

You're welcome! In that case, I'm closing down the issue :)
