### ISSUE TITLE
How to use API to obtain monitoring information of containers for a period of time?

### ISSUE THREAD

**Issue by AnyuanLuo** [weaveworks/scope#3663]
For example, I want get the cpu metric of one contianer between 7:00 am and 8:am,  how can I use the API like http://localhost:80/......   ?

**Comment by bboreham** [comment]
Technically this is possible - you'd need to configure storage such as S3 - but in practice the data structure is not designed for it so you'd be much happier using something like Prometheus.

**Comment by fbarl** [comment]
> you'd need to configure storage such as S3

I've opened #3651 to document this better, but the current state of things is that you _have_ to set up S3 to get out of the box experience of historical reports, everything else probably requires some tweaking of the code.

As for the API part, none of our [endpoints](https://github.com/weaveworks/scope/blob/master/site/faq.md#api-endpoints) currently supports querying for metrics specifically (so you'd need to parse a bigger JSON for a specific container) and more importantly, we don't really support querying a time range, only specific timestamps.

So Prometheus might indeed be a better way to go for your use case :)

**Comment by AnyuanLuo** [comment]
Thanks for your answer, I'll try to  use prometeus

**Comment by fbarl** [comment]
> Thanks for your answer

You are welcome! I'll close the issue then as it's unlikely that we're going to turn it into something actionable that is not already covered by other open issues.
