### ISSUE TITLE
Plugin control error in controller view

### ISSUE THREAD

**Issue by shadra35** [weaveworks/scope#3667]
Hi all,

I found an issue about plugins. Custom plugins with controls are not working very well on controller/service view of weavescope. When we fire the custom control, it fails. Response from backend is error 400 with body:

"Control \"blabla\" not recognised"

After slack discussion. It seems that the standard kubernetes weave scope deployment miss the plugin mount volume for the cluster agent.

Adding the mount of plugins in the cluster agent solves my issue.

BR,
Thierry

**Comment by bboreham** [comment]
Specifically [the cluster agent manifest](https://github.com/weaveworks/scope/blob/445b4065f220e22c366ac04f26867c1b411791e0/examples/k8s/probe-deploy.yaml) is missing [this mount](https://github.com/weaveworks/scope/blob/445b4065f220e22c366ac04f26867c1b411791e0/examples/k8s/ds.yaml#L45)

**Comment by chandankumar4** [comment]
Hi @bboreham I would like to solve this issue

**Comment by bboreham** [comment]
Sure!
