### ISSUE TITLE
Weave scope running in eks throws error messages

### ISSUE THREAD

**Issue by runningman84** [weaveworks/scope#3669]
## What you expected to happen?
I have installed scope using helm into an eks cluster. Everything seems to work fine but my logs get spammed with error messages from weave scope agent.

## What happened?
```
weave/weave-scope-agent-weave-scope-xkxx4[weave-scope-agent]: <probe> WARN: 2019/08/30 12:20:16.948717 No node name and cannot obtain local pods, reporting all (which may impact performance): Get http://127.0.0.1:10255/pods/: dial tcp 127.0.0.1:10255: connect: connection refused
```

## How to reproduce it?
Install weave scope using the helm chart with default values.

## Anything else we need to know?
aws eks cluster

## Versions:
weave-scope helm version: 1.1.2
weave-scope image version: tag: master-c99a5e6d
kubectl version 1.13

**Comment by bboreham** [comment]
This is caused by the config. Can you take it up with the maintainer of the helm chart?
Ideally they would make changes in line with #3569

**Comment by bboreham** [comment]
Looks like you've made a PR for the helm chart - thanks!

**Comment by runningman84** [comment]
I was quite happy about the quick response from you so I thought it might be a good idea to help you out here.

**Comment by fbarl** [comment]
My understanding is that this issue has been addressed fully by https://github.com/helm/charts/pull/16796.

@runningman84 feel free to reopen if that is not true. And thanks for your contribution! :)
