### ISSUE TITLE
Reconsider use of sass-lint

### ISSUE THREAD

**Issue by dholbach** [weaveworks/scope#3694]
sass-lint hasn't seen updates upstream for quite a while and it pulls in quite a few old js dependencies. On Github its status is declared as unmaintained:

https://github.com/sasstools/sass-lint#this-project-is-currently-unmaintained---last-developmentstable-release-october-2017

**Comment by fbarl** [comment]
We should drop `sass-lint` completely in favor of `stylelint` - https://github.com/weaveworks/scope/issues/3577.

I remember the problem there was that we keep our styles both in SASS files and in styled components and `stylelint` could only be used for linting _one_ of those at the time so we made it lint styled components and used `sass-lint` for the SASS files.

A simple solution to proceed might be to wrap all our SASS styles with a `createGlobalStyle` and thus get rid of the SASS files.

**Comment by fbarl** [comment]
Closing in favor of #3577.
