### ISSUE TITLE
Properly Dockerize Scope

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#37]
This work is mostly porting @tomwilkie's prerelease commits. End result is a working Docker container for Scope, plus coherent reproducible build instructions in the README.

**Comment by tomwilkie** [comment]
We're going to mimic weave's user install journey:
- a scope script people curl, that has launch and stop commands
- a published container in the docker hub.

This script will also do all the weave-dns foo.

We can later merge the script
