### ISSUE TITLE
Scope probe should set the user-agent string

### ISSUE THREAD

**Issue by bboreham** [weaveworks/scope#3715]
Right now it shows up in access logs as "Go-http-client/1.1", which is very dull.

We could copy Prometheus, which sets it to something like "Prometheus/2.12.0".

**Comment by harshshekhar15** [comment]
Hi @bboreham I would like to try this. Can you guide me how to get started.

**Comment by bboreham** [comment]
You are welcome, @harshshekhar15 !

There is a brief outline how to build and run in the file [CONTRIBUTING](https://github.com/weaveworks/scope/blob/master/CONTRIBUTING.md#how-to-build-and-run-the-project).

You should research how to set the user-agent in Go, and see where that could fit into the [probe](https://github.com/weaveworks/scope/tree/master/probe/appclient) code.

Ideally also write a test, though I won't insist on it for this particular change.

**Comment by harshshekhar15** [comment]
Thanks for the heads-up @bboreham.

**Comment by DarthSett** [comment]
Hi @bboreham, 
I would like to try this as well. This will also be my first PR if all goes well. Can you guide me on how to get started?

**Comment by bboreham** [comment]
There's no point both of you doing the same task.
But maybe @harshshekhar15 gave up?

How far did you get in the instructions I already gave?

**Comment by DarthSett** [comment]
I just wanted to clarify certain things. I have to first fork this repo, then after making the change, I am supposed to make a pr, which is basically me telling you that "I have made this change. Please review and add to master". And then you add it. Right?

**Comment by harshshekhar15** [comment]
Hi @bboreham and @DarthSett. @bboreham no I didn't gave up, actually was caught up with some work and didn't got time to look into the issue. By the way @DarthSett are you ready with the changes, if yes then please go ahead and raise a PR, else I will try to raise a PR once I'm done.

**Comment by DarthSett** [comment]
@bboreham What do you want the header value to be? I can set it to something like "Scope/1.11.6" for now.

**Comment by DarthSett** [comment]
@bboreham @harshshekhar15 
I have listed a PR for this issue.

**Comment by bboreham** [comment]
Thanks!  There is already a version string set at build time [here](https://github.com/weaveworks/scope/blob/4bb2a435aea9a9f0a3103493c6868af2a7b27488/Makefile#L28) via the `-X` flag.

**Comment by monadic** [comment]
Thank you all
