### ISSUE TITLE
More intuitive detail pane

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#372]
* Include Docker labels
* Fix bugs (origin container, etc.)
* More intelligent data structure, better rendering; backend produce HTML

**Comment by peterbourgon** [comment]
Other tickets related to the detail pane...

- [On groupings which traverse hosts . . . you can't tell which hosts the details come from](https://github.com/weaveworks/scope/issues/296)
- [Connections and Connection Details seem redundant](https://github.com/weaveworks/scope/issues/322)
- [Table type should be more flexible](https://github.com/weaveworks/scope/issues/301)
- [Empty fields in details pane look broken](https://github.com/weaveworks/scope/issues/370)

**Comment by 2opremio** [comment]
Closing this ticket since the only remaining one is #301 which we are tracking separately

**Comment by 2opremio** [comment]
Actually ... reopening since there's no ticket for including docker labels.
