### ISSUE TITLE
is weave k8s cluster agent probe support 1.16.x upstream version?

### ISSUE THREAD

**Issue by pakhomov-passteam** [weaveworks/scope#3722]
I am using conf below
bare metal cluster 3 master + 5 nodes, CRI-O runtime

kubectl version
`Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", 
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", 

crictl
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.16.0-rc2
RuntimeApiVersion:  v1alpha1

kubectl -n weave logs weave-scope-cluster-agent-79d4cd6568-qtj6n
time="2019-10-30T17:01:45Z" level=info msg="publishing to: weave-scope-app.weave:80"
<probe> INFO: 2019/10/30 17:01:45.553094 Basic authentication disabled
<probe> INFO: 2019/10/30 17:01:45.563634 command line args: --mode=probe --probe-only=true --probe.kubernetes.role=cluster --weave=false weave-scope-app.weave:80
<probe> INFO: 2019/10/30 17:01:45.563695 probe starting, version 1.11.6, ID 1a9fdb075edf0135
<probe> INFO: 2019/10/30 17:01:45.566150 kubernetes: targeting api server https://10.96.0.1:443
<probe> INFO: 2019/10/30 17:01:45.576758 Control connection to weave-scope-app.weave starting
<probe> INFO: 2019/10/30 17:01:45.578435 volumesnapshotdatas are not supported by this Kubernetes version
<probe> INFO: 2019/10/30 17:01:45.590706 deployments are not supported by this Kubernetes version
<probe> INFO: 2019/10/30 17:01:45.590814 daemonsets are not supported by this Kubernetes version
<probe> INFO: 2019/10/30 17:01:45.592053 volumesnapshots are not supported by this Kubernetes version
<probe> INFO: 2019/10/30 17:01:45.592149 statefulsets are not supported by this Kubernetes version
<probe> INFO: 2019/10/30 17:01:45.602677 Publish loop for weave-scope-app.weave starting

Pod --> Controllers section of the UI is empty
Enabling "Show unmanaged" filter shows nodes in the UNMANAGED STATE.

What i am doing wrong?
Maybe recent k8s beta APIs deprecation may result such probe behavior?
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by qiell** [comment]
You need to update the Scope image to `1.12.0` which is released recently and having the support of K8s 1.16. For more information, you can have a look at Release Notes https://github.com/weaveworks/scope/releases/v1.12.0.

Thank You. :)
