### ISSUE TITLE
Scope behind apache2 proxy has nothing to show

### ISSUE THREAD

**Issue by engiwip** [weaveworks/scope#3725]
Hello Team
.

## What you expected to happen?
I want to access to weave scope page behind apache2 proxy 
-> it's okay by the direct way  ( without proxy) after opening the port 4040  ( ufw allow)
I m able to access to weave scope page 

-> it s  not okay by the proxy way : ( and after  disable ufw 4040 rule  )

scope install method :
  sudo curl -L git.io/scope -o /usr/local/bin/scope
  sudo chmod a+x /usr/local/bin/scope
  scope launch

check install and port 
 netstat -ntulp | grep 4040

tcp6       0      0 :::4040                 :::*                    LISTEN    

 curl -I http://localhost:4040
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-Length: 836

proxy : apache
apache2 -v
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2019-09-16T12:58:48

vim  /etc/apache2/mods-enabled/proxy.conf 
ProxyPass "/scope" "http://localhost:4040"
ProxyPassReverse "/scope" "http://localhost:4040"

vim /etc/apache2/sites-enabled/mysite.conf
<IfModule mod_ssl.c>
<VirtualHost *:443>
        ServerName mysite.fr
         ErrorLog /var/log/apache2/error.mysite.fr.log
        CustomLog /var/log/apache2/access.mysite.log combined
RewriteEngine on
SSLCertificateFile /etc/letsencrypt/live/mysite/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/mysitefr/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>

sudo a2enmod proxy proxy_http proxy_wstunnel
sudo systemctl reload apache2
sudo systemctl restart apache2

## What happened?
**blank page  
http://my.site.com/scope --> blank page -> no outputs show in html page**

but curl test is ok with a 200 http status :
curl -I http://localhost/scope->ok
curl -I http://my.site.com/scope-->ok
HTTP/1.1 200 OK
Date: Mon, 11 Nov 2019 11:58:06 GMT
Server: Apache/2.4.29 (Ubuntu)
Accept-Ranges: bytes

but endpoint api show output in html page like 
http://my.site.com/scope/admin/summary--> ok

Nov 11 11:35:33.112: ;<host>: endpoint:34, process:254, container:8, container_image:8, host:1, overlay:2
Nov 11 11:35:39.106: ;<host>: endpoint:3, process:253, container:5, host:1
Nov 11 11:35:42.126: ;<host>: endpoint:33, process:254, container:8, container_image:8, host:1, overlay:2
Nov 11 11:35:45.109: ;<host>: endpoint:2, process:253, container:5, host:1
Nov 11 11:35:48.106: ;<host>: endpoint:10, process:254, container:5, host:1
http://my.site.com/scope/admin/summary--> ok

http://my.site.com/scope/api --> ok 
{"capabilities":{"historic_reports":false},"hostname":"xxxx","id":"13c3ccb75d054430","plugins":[],"version":"1.11.6"}

## How to reproduce it?
install apache 2.4 and configure reverse proxy

## Anything else we need to know?
no cloud provider : scope install by the direct way

## Versions:
Weave Scope version 1.11.6
$ docker version 19.03
$ uname -a   Linux ns377122 4.15.0-50-generic #54-Ubuntu 
$ kubectl version --> no k8s install
```

## Logs:
```
$ docker logs weavescope

 [127.0.0.1:4040 --> 127.0.0.1:57514], pid=17232, netNS=4026531993)
<probe> DEBU: 2019/11/11 11:22:25.611206 handleConnection(close, [10.32.0.2:4040 --> 10.32.0.2:38344], pid=17232, netNS=4026531993)
<probe> DEBU: 2019/11/11 11:22:25.611232 handleConnection(close, [91.121.xx.xx:4040 --> 91.121.xx.xx:39360], pid=17232, netNS=4026531993)
<probe> DEBU: 2019/11/11 11:22:26.088013 plugins: scanning...
<app> DEBU: 2019/11/11 11:22:27.102803 Received report sizes: compressed 9536 bytes, uncompressed 157919 bytes (6.04%)
<app> DEBU: 2019/11/11 11:22:30.124212 Received report sizes: compressed 24047 bytes, uncompressed 282601 bytes (8.51%)
<probe> DEBU: 2019/11/11 11:22:31.087975 plugins: scanning...

$ journalctl -u docker.service --no-pager
nothing
-->

Many thanks

**Comment by bboreham** [comment]
The main view in a browser needs websockets to be working, whereas the other ones like `/summary` are plain http.

I see you mentioned `proxy_wstunnel` - maybe it didn't get configured correctly?  I suggest you focus in that area.

**Comment by studiokingyo** [comment]
<VirtualHost *:443>
 	ServerName weavescope.<your domain>.jp


	SSLEngine on
	ServerAdmin webmaster@localhost
	SSLCertificateFile /etc/letsencrypt/live/<your domain>/cert.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/<your domain>/privkey.pem
	SSLCertificateChainFile /etc/letsencrypt/live/<your domain>/chain.pem


	ProxyRequests Off
	ProxyPreserveHost On

	RewriteEngine On
	RewriteCond %{HTTP:Connection} Upgrade [NC]
	RewriteCond %{HTTP:Upgrade} websocket [NC]
	RewriteRule /(.*) ws://localhost:4040/$1 [P,L]

	RequestHeader set X-Forwarded-Proto "https"
	RequestHeader set X-Forwarded-Port "443"


	ProxyPass / http://localhost:4040/
	ProxyPassReverse / http://localhost:4040/
	ProxyPass / ws://localhost:4040/
	ProxyPassReverse / ws://localhost:4040/

</VirtualHost>

**Comment by engiwip** [comment]
great response from d.Kingyo

**Comment by JialuZhang** [comment]
In your configuration,
```
<VirtualHost *:443>
ServerName mysite.fr
ErrorLog /var/log/apache2/error.mysite.fr.log
CustomLog /var/log/apache2/access.mysite.log combined
RewriteEngine on
SSLCertificateFile /etc/letsencrypt/live/mysite/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/mysitefr/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
```
the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
