### ISSUE TITLE
Weave scope "Nothing to show" about Kubernetes cluster

### ISSUE THREAD

**Issue by vutuong** [weaveworks/scope#3771]
## What happened?

 I run a K8s cluster with Calico addon. I install WeaveScope follow this guidline: https://www.weave.works/docs/scope/latest/installing/#k8s.
But I got nothing in the web UI ("Nothing to show"). Can anyone help to solve my problem?
## Versions:

```
root@master:~# scope version
Weave Scope version 1.12.0

root@master:~# docker version
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:19:38 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       2d0083d
  Built:            Thu Aug 15 15:12:41 2019
  OS/Arch:          linux/amd64
  Experimental:     true

root@master:~# uname -a
Linux master 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

root@master:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

## Logs:

```
root@master:~#  kubectl logs -n weave weave-scope-app-597f846bbd-lvkkz
<app> INFO: 2020/03/24 15:02:24.978265 app starting, version 1.13.0, ID 3e5404e2c7e7ecd5
<app> INFO: 2020/03/24 15:02:24.979096 command line args: --mode=app
<app> INFO: 2020/03/24 15:02:24.983998 Basic authentication disabled
<app> INFO: 2020/03/24 15:02:25.185407 listening on :4040
<app> WARN: 2020/03/24 15:02:25.535112 Error updating weaveDNS, backing off 20s: Error running weave ps: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<app> WARN: 2020/03/24 15:02:45.558408 Error updating weaveDNS, backing off 40s: Error running weave ps: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<app> ERRO: 2020/03/24 15:02:56.306816 Error checking version: Get https://checkpoint-api.weave.works/v1/check/scope-app?arch=amd64&flag_kernel-version=4.10.0-28-generic&flag_os=linux&os=linux&signature=RA7FJglD1DFl9rcrJ7ylyh4OYYUTnBzeIeMpBzLFwp4%3D&version=1.13.0: dial tcp: i/o timeout
 
```

**Comment by bboreham** [comment]
Can you show one or two logs from the probes (the daemonset)?

**Comment by vutuong** [comment]
@bboreham I got this logs:
'''
root@master:~# kubectl logs -n weave weave-scope-cluster-agent-5fd97b4cdb-xsx6c
time="2020-03-24T15:01:45Z" level=info msg="publishing to: weave-scope-app.weave.svc.cluster.local:80"
<probe> INFO: 2020/03/24 15:01:45.081330 Basic authentication disabled
<probe> INFO: 2020/03/24 15:02:25.099727 command line args: --mode=probe --probe-only=true --probe.http.listen=:4041 --probe.kubernetes.role=cluster --probe.publish.interval=4.5s --probe.spy.interval=2s weave-scope-app.weave.svc.cluster.local:80
<probe> INFO: 2020/03/24 15:02:25.099986 probe starting, version 1.13.0, ID 3789e2a898e6c147
<probe> ERRO: 2020/03/24 15:02:25.100286 Error getting docker bridge ip: route ip+net: no such network interface
<probe> INFO: 2020/03/24 15:02:25.101162 kubernetes: targeting api server https://10.96.0.1:443
<probe> ERRO: 2020/03/24 15:02:25.102599 plugins: problem loading: no such file or directory
<probe> INFO: 2020/03/24 15:02:25.139079 Profiling data being exported to :4041
<probe> INFO: 2020/03/24 15:02:25.139292 go tool pprof http://:4041/debug/pprof/{profile,heap,block}
<probe> WARN: 2020/03/24 15:02:25.223451 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: connect: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> INFO: 2020/03/24 15:02:25.368911 volumesnapshotdatas are not supported by this Kubernetes version
<probe> INFO: 2020/03/24 15:02:25.381479 volumesnapshots are not supported by this Kubernetes version
<probe> WARN: 2020/03/24 15:02:35.226376 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: connect: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> WARN: 2020/03/24 15:02:55.235099 Error collecting weave status, backing off 40s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: connect: connection refused. If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> ERRO: 2020/03/24 15:02:55.686900 Error checking version: Get https://checkpoint-api.weave.works/v1/check/scope-probe?arch=amd64&flag_kernel-version=4.10.0-28-generic&flag_kubernetes_enabled=true&flag_os=linux&os=linux&signature=RA7FJglD1DFl9rcrJ7ylyh4OYYUTnBzeIeMpBzLFwp4%3D&version=1.13.0: dial tcp: i/o timeout
<probe> WARN: 2020/03/24 15:03:05.156144 Cannot resolve 'weave-scope-app.weave.svc.cluster.local': lookup weave-scope-app.weave.svc.cluster.local on 10.96.0.10:53: read udp 10.244.235.133:52296->10.96.0.10:53: i/o timeout
<probe> ERRO: 2020/03/24 15:03:26.713668 Error checking version: Get https://checkpoint-api.weave.works/v1/check/scope-probe?arch=amd64&flag_kernel-version=4.10.0-28-generic&flag_kubernetes_enabled=true&flag_os=linux&os=linux&signature=RA7FJglD1DFl9rcrJ7ylyh4OYYUTnBzeIeMpBzLFwp4%3D&version=1.13.0: dial tcp: i/o timeout
<probe> ERRO: 2020/03/24 22:19:53.293321 Error checking version: Get https://checkpoint-api.weave.works/v1/check/scope-probe?arch=amd64&flag_kernel-version=4.10.0-28-generic&flag_kubernetes_enabled=true&flag_os=linux&os=linux&signature=RA7FJglD1DFl9rcrJ7ylyh4OYYUTnBzeIeMpBzLFwp4%3D&version=1.13.0: dial tcp: i/o timeout
'''

**Comment by vutuong** [comment]
I have problem with Kubenertes CNI when my setting server has multiple physical interface. After checking, downing all unnecessary interface and installing again, the problem is solved.
