### ISSUE TITLE
Wrong number of TCP connections reported in the details pane

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#378]
The details pane of the scope container reads *TCP connections 1*:

<img width="990" alt="screen shot 2015-08-19 at 6 29 00 pm" src="https://cloud.githubusercontent.com/assets/2362916/9363762/326e47b8-46a0-11e5-8e7a-5e2133128395.png">

But the number of connections is clearly higher than 1:

<img width="1006" alt="screen shot 2015-08-19 at 6 30 52 pm" src="https://cloud.githubusercontent.com/assets/2362916/9363814/786a0efa-46a0-11e5-8126-bff821145e00.png">

**Comment by peterbourgon** [comment]
Is this still happening?

**Comment by peterbourgon** [comment]
@2opremio ^^

**Comment by 2opremio** [comment]
@peterbourgon I need to check but I won't have time to do this today. Can it wait until Monday?

**Comment by peterbourgon** [comment]
No rush, was just doing some issue cleanup.

**Comment by 2opremio** [comment]
Yes, this is still broken. In the case below I think it breaks because of the reverse DNS lookup (leading to the same `dataproducer.weave.local` name from different IPs): 
<img width="1627" alt="screen shot 2015-09-21 at 13 06 33" src="https://cloud.githubusercontent.com/assets/2362916/9991442/f312286a-6061-11e5-91cc-208abe2e26ef.png">

Here's the output of `/api/report/`: https://gist.github.com/2opremio/4aa41b303862270dad6e

I suspect it still breaks when no DNS records are involved. I will try to reproduce that too.

**Comment by 2opremio** [comment]
Here is another example with different DNS records:

<img width="1642" alt="screen shot 2015-09-21 at 13 22 50" src="https://cloud.githubusercontent.com/assets/2362916/9992038/07ea4e20-6067-11e5-86f4-8082a8b38f32.png">

Report: https://gist.github.com/2opremio/d6f78a62b84a7b4f8259

As I understand it, the count should be 4, and not 2.

Also, this example partly shows the problem with reverse DNS records pointed out at https://github.com/weaveworks/scope/issues/504 (the view shows `scope.weave.local` names mixed up with `ip-172-31-*` names)

**Comment by 2opremio** [comment]
Here's another example:

<img width="1112" alt="screen shot 2015-10-01 at 2 05 41 pm" src="https://cloud.githubusercontent.com/assets/2362916/10221335/ad84d6b2-6845-11e5-9e99-2bd2cb047954.png">


report: https://gist.github.com/2opremio/65d1858fa30a1bf0ec91

**Comment by paulbellamy** [comment]
We don't show this anymore, so won't be an issue until #680 is done.
