### ISSUE TITLE
regarding helm chart

### ISSUE THREAD

**Issue by Hokwang** [weaveworks/scope#3792]
Hi,

I have a question about helm chart.
There's stable/weave-scope helm chart,
is that managed from your team?

If yes,
please add nodeSelector, tolerations, and env options for pod.

If no,
helm/charts repo will be deprecated, do you have a plan for chart?
I mean it is the best your team manage helm chart officially 
and in this case, this is feature request.

Thanks,

**Comment by dholbach** [comment]
The kured team is having a similar discussion right now: https://github.com/weaveworks/kured/issues/140

**Comment by bboreham** [comment]
I see my name is in the OWNERS file despite I have never written a helm chart in my life, nor used one intentionally.

I've marked this feature request as "help wanted".

**Comment by dholbach** [comment]
> I see my name is in the OWNERS file despite I have never written a helm chart in my life, nor used one intentionally.

I think I pinged all of you maintainers when we got questions around the Helm chart and couldn't easily update the version in there. This allowed us to get people on new versions of Scope more easily.
