### ISSUE TITLE
Expandable detail-pane tables in UI

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#382]
UX part of #322 

The UI will know what rows to expand based on a new optional row key: `expandable`

Sample table:

```json
{
    "title": "Connections",
    "numeric": false,
    "rows": [
        {
            "key": "TCP connections",
            "value_major": "2"
        },
        {
            "key": "Client",
            "value_major": "Server",
            "expandable": true
        },
        {
            "key": "127.0.0.1:3445",
            "value_major": "127.0.0.1:80",
            "expandable": true
        },
        {
            "key": "127.0.0.1:5647",
            "value_major": "127.0.0.1:560",
            "expandable": true
        }
    ]
}
```

**Comment by miztiik** [comment]
Can we make the details pane moveable instead of fixing it to the default right hand side?

**Comment by peterbourgon** [comment]
@miztiik any specific reason other than aesthetics?

**Comment by miztiik** [comment]
I found the details pane sometimes blocking the view of the underlying container, I intuitively was looking to move it to see the underlying container connections information and also the details pane.

**Comment by davkal** [comment]
@miztiik you can drag the container view. But thanks for pointing out your intuitive use. The blocking of the view is certainly a shortcoming.
