### ISSUE TITLE
Will Weaveworks scope support containerd for fetching container logs, k8s > 1.23

### ISSUE THREAD

**Issue by PradeepShetty14** [weaveworks/scope#3895]

**Comment by kingdonb** [comment]
No, it requires Docker (doesn’t work with containerd).

Scope also requires the `privileged` security context.

**Comment by PradeepShetty14** [comment]
@kingdonb  -- So how can we display the container level logs in weavescope with latest Kubernetes installed? Can you please provide these details? 
Is there a new release we can expect that provides the container logs as well.

**Comment by kingdonb** [comment]
Scope is not in active development, and is officially a community project by Weaveworks. It's provided as (gratis) Open Source Software under the Apache license without any formal support or guarantees, unless you have a support agreement.

The latest Kubernetes release still works with Docker Shim (1.23) but the next release will not, according to my information (1.24) [News Link](https://kubernetes.io/blog/2022/01/07/kubernetes-is-moving-on-from-dockershim/). This will present an obstacle to anyone that depends on Docker, and that includes Scope users.

Scope will not work with the Containerd CRI or any other than Docker at present. It also has difficult scaling problems which made it difficult to pursue further development. As nodes scale to hundreds of pods, the amount of resources consumed by Scope increases too, and it increases for each node that Scope runs on. This is a serious design impediment to scaling.

I'm sorry that I cannot be more helpful, but I am nearly certain we will not see a resurgence in Scope development. (Watch this space, perhaps there will be something new to replace Scope in the future!)

**Comment by PradeepShetty14** [comment]
@kingdonb -- Thanks a lot for the information.
