### ISSUE TITLE
Get per-link bandwidth info

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#39]
An option would be to make the weave router track this for (src, dst mac addr pairs) and provide an api to support it.

**Comment by tomwilkie** [comment]
To be clear, the info from ifconfig is not enough, as its per device, not per 'connection'.

And mac pairs wouldn't allow us to differentiate between connections between the same peer on different ports.

**Comment by davkal** [comment]
That would allow for some nice visual cues.

**Comment by tomwilkie** [comment]
@peterbourgon can this be closed now?

**Comment by peterbourgon** [comment]
Sure.
