### ISSUE TITLE
Release of scope-backend-build docker image

### ISSUE THREAD

**Issue by srajmane** [weaveworks/scope#3900]
Hi,
When could we expect the release of scope-backend-build docker image?
It would be great if you release scope-backend-build docker image with an updated backend dockerfile.
Thanks :slightly_smiling_face:

**Comment by srajmane** [comment]
@qiell @fbarl @satyamz @bboreham
Any updates on this issue? Thanks :)

**Comment by bboreham** [comment]
The image has jumped from about 1GB to about 2.3GB since last updated in CI; I will see if I can fix that.

**Comment by srajmane** [comment]
@bboreham Gentle ping, any updates for this issue? Thanks :)

**Comment by srajmane** [comment]
@bboreham Could you please have a look? Thanks :)

**Comment by bboreham** [comment]
Sorry, can you remind me which specific change(s) you need?

From #3902 we had an image `weaveworks/scope-backend-build:go-1-17-8-bcdf2caa` in April; I have just merged that PR which means `master` is using it.

That image is 1.15GB, so at least the problem I noted on 7th March is fixed.

**Comment by srajmane** [comment]
@bboreham 
Thank you for the update. I was awaiting updates on weaveworks/scope-backend-build:go-1-17-8-bcdf2caa image. And since master now uses the updated image we can close this issue.
