### ISSUE TITLE
Doesn't work if it can't get to the internet

### ISSUE THREAD

**Issue by Telmo** [weaveworks/scope#395]
This seems to be a chronic issue with all docker base projects, but... `scope` tries to download containers from the registry, which is an issue when trying to start it up on a hosts in a restricted network

```
[root@docker-as-4p tmp]# ./scope launch
Unable to find image 'gliderlabs/alpine:latest' locally
Pulling repository docker.io/gliderlabs/alpine
Network timed out while trying to connect to https://index.docker.io/v1/repositories/gliderlabs/alpine/images. You may want to check your internet connection or if you are behind a proxy.
Unable to find image 'weaveworks/scope:0.6.0' locally
Pulling repository docker.io/weaveworks/scope
Network timed out while trying to connect to https://index.docker.io/v1/repositories/weaveworks/scope/images. You may want to check your internet connection or if you are behind a proxy.
[root@docker-as-4p tmp]#
```

**Comment by peterbourgon** [comment]
The scope script you're running, like the [weave script](https://github.com/weaveworks/weave/blob/master/weave) it was roughly based on, is a bootstrapping shim that eventually just calls out to a Docker daemon. As you've noticed, if a Docker daemon doesn't have the requisite container images locally, it will attempt to download them.

You can use Docker on an internet-connected host to fetch the images, and then move them to your restricted network however you see fit. Then, Docker (via the scope script) won't need to reach out to the internet.

On the internet-connected host,

```
$ docker pull weaveworks/scope:0.6.0
$ docker save -o scope-0.6.0.tar weaveworks/scope:0.6.0
```

Copy the file to the restricted host using your provisioning system, and then

```
$ docker load -i scope-0.6.0.tar
$ ./scope launch
```

Please let me know if that solves your problem!

**Comment by Telmo** [comment]
As I did with weave I went the long way around, pulled the images to our internal registry and then modified the scope script to point to the internal images. I still feel that this is an issue affecting most of docker base projects. Having to hack scripts of move images around is a blocker for a wider adoption of the projects.

**Comment by peterbourgon** [comment]
The scope script is meant as a bootstrapping tool, and isn't intended to cover all use cases, especially in infrastructures with constraints like restricted network access. I'm glad you were able to get it working. If you have suggestions for how we might better package and distribute our software, we'd be happy to hear them!
