### ISSUE TITLE
Consider also tracking unix domain socket connections

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#405]
Then we'd also show scope_probe -> docker links.

**Comment by tomwilkie** [comment]
and also ecsagent -> weaveproxy -> docker links (see #489)

**Comment by inercia** [comment]
[It seems](http://serverfault.com/questions/252723/how-to-find-other-end-of-unix-socket-connection) it is not possible to get the information about the other side of the unix socket on Linux...

**Comment by tomwilkie** [comment]
Yup.  Oh well.
