### ISSUE TITLE
Trim long container names in UI

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#413]
Here's an example of how the UI looks like with long container names (mangled by ECS):

<img width="1193" alt="screen shot 2015-08-28 at 6 29 35 pm" src="https://cloud.githubusercontent.com/assets/2362916/9553850/b6c5f964-4db9-11e5-806e-7348bef97e8b.png">

**Comment by tomwilkie** [comment]
We should definitely trim the names.

Also perhaps a feature for th DSL would be to allow users to apply regexs
to the names, like we do in the proxy for weave DNS? @peterbourgon?

**Comment by peterbourgon** [comment]
@tomwilkie Easily done. +1 to the idea.

**Comment by tomwilkie** [comment]
Moving the regex discussion to another ticket
