### ISSUE TITLE
Add NodeMetadata.Sets

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#417]
Some values in nmd.Metadata are actually sets encoded as string separated lists, with set-merge semantics.

Like NodeMetadata.Counters, we should put these in NodeMetada.Sets (of type map[string]IDList) and define appropriate merge semantics.

Examples would be container IP addresses + hostnames, host networks.  Others?

**Comment by peterbourgon** [comment]
Not map[string]IDList but map[string]StringSet, otherwise :+1:

**Comment by tomwilkie** [comment]
IDList is a stringset; can we just typedef it?

**Comment by peterbourgon** [comment]
Sure, just want to make it distinct.
