### ISSUE TITLE
Trim Columns keys and Table titles in details pane

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#418]
<img width="405" alt="screen shot 2015-09-01 at 1 51 23 pm" src="https://cloud.githubusercontent.com/assets/2362916/9604654/d4cbc0c0-50b0-11e5-9cc0-2e30d070de13.png">

Also, both for the keys and values, provide a way to view the full value when trimmed (i.e. hover-on) so that the user can view the full text.

**Comment by tomwilkie** [comment]
Can confirm row labels are truncated as expected.

However, table headers are still wrapping:

![screen shot 2015-09-02 at 17 04 24](https://cloud.githubusercontent.com/assets/444037/9636700/bec95d16-5194-11e5-920c-2057b5fc35d0.png)
