### ISSUE TITLE
"Dancing" nodes

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#419]
I recall someone addressed this one before   ( @tomwilkie ? ) but we are still suffering from it. The whole layout changes when a new container is spawned.

The following gif was recorded from the Scope-variant of the ECS guide I am working on ( You can reproduce it by following https://github.com/weaveworks/guides/tree/aws-ecs-scope/aws-ecs ).

![Dancing containers](http://g.recordit.co/hXSMIHPSVe.gif)

Context: A new container is being spawned every 2 seconds due to  `weave status` being called repeatedly in from an Upstart script (to see whether Weave died and re-launch it). For the time being I will workaround the problem by checking Weave's status differently but we should still fix this.

**Comment by peterbourgon** [comment]
Another end-run around this problem is using the "hide system containers" option we're working on in #420.

**Comment by davkal** [comment]
We're currently using the dagre library which gives ok results for layered graphs. It's perfect for single runs, but sub-optimal for changing graphs, e.g. adding a single node may change your edge cross count [which might lead to a different layer matrix being chosen](https://github.com/cpettitt/dagre/blob/master/lib/order/index.js#L43). There are no options to configure this.

Apart from writing our own library or finding a different one that suits us better, an approach with dagre (which is no longer maintained) could be to only do single runs per topology, and then implement our own transitions for adding/removing nodes.

**Comment by davkal** [comment]
A previous attempt was made in #379 by reusing chart engine instances, but that wont help if a change in the topology causes a heuristic to choose a different layout.

**Comment by 2opremio** [comment]
@davkal Sorry if this question is naive, but have you looked at the other graph libraries? This github project seems to provide a pretty good summary of what's out there: https://github.com/anvaka/graph-drawing-libraries

**Comment by 2opremio** [comment]
It actually happens even when no new containers are seemingly added. This is also a gif from the ECS demo, once I modified it to avoid creating new containers:

![More dancing containers](http://g.recordit.co/S35ssg13LQ.gif)

**Comment by 2opremio** [comment]
And it also happens periodically in the hosts view, as @rade pointed out:

![hosts cha cha cha](http://g.recordit.co/LZI6qpu3T2.gif)

**Comment by paulbellamy** [comment]
It's particularly bad on a redis cluster. They ping each other every few seconds, which sometimes short-lived connections catch, and sometimes not.

**Comment by paulbellamy** [comment]
I don't believe it's strictly an issue of nodes moving. It is hard to predict when and *why* the nodes are moving around (hence people referring to it as "dancing"). Possibly a simpler layout algorithm (that people could predict), would feel subjectively better. We could also look at deterministically positioning nodes based on some immutable criteria. Which, while probably less optimal for connections, may be easier for people to "track".

As a user, I almost don't care about the connection lines being short. When drawing an architecture diagram, people tend to start with the nodes, then add connections between them (disregarding if the connections are slightly longer).

**Comment by tomwilkie** [comment]
@davkal can we close this now?  Is there more work to do?

**Comment by davkal** [comment]
The dancing has been reduced. Other tickets deal with different layout issues.

Fixed by #593
