### ISSUE TITLE
TestResolver is flaky

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#427]
```
--- FAIL: TestResolver-4 (0.00s)
	resolver_test.go:89: didn't Stop in time
FAIL
```

Seen 2-3 times recently, including: https://circleci.com/gh/weaveworks/scope/1100

**Comment by inercia** [comment]
@tomwilkie you mean `probe/resolver_test.go`, don't you?

**Comment by tomwilkie** [comment]
Yes.

**Comment by tomwilkie** [comment]
And again: https://circleci.com/gh/weaveworks/scope/1110
