### ISSUE TITLE
Allow users to apply a transform to container names

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#432]
See #413

**Comment by 2opremio** [comment]
As discussed with @peterbourgon the idea (for now) is to render names based on the container's context. For instance, in the case of ECS, [container names are mangled](https://github.com/weaveworks/guides/tree/5a70632985c5f1c64dcb807e35cb33cab6a7745e/aws-ecs#whats-happening-in-the-hosts) but ECS provides the original container name in a Docker container label: `com.amazonaws.ecs.container-name`

The probes will obtain the container's cloud context and include a Container report metadata entry, say `"provider"="ECS"` which the renderer can use to adapt the container name to display (from the `com.amazonaws.ecs.container-name`) and tweak other presentation details.

**Comment by 2opremio** [comment]
@paulbellamy I would be interested to know if this would work well for kubernetis too.

**Comment by paulbellamy** [comment]
A transform would work ok. There's not really a container-specific label that would work well in the container's view. There's just the pod name label, which will be shared between multiple containers.

**Comment by tomwilkie** [comment]
Sounds fine.

> The probes will obtain the container's cloud context and include a Container report metadata entry, say "provider"="ECS"

How will it know this?  Is it enough to 'just' use com.amazonaws.ecs.container-name as the name if its present?

**Comment by 2opremio** [comment]
I actually agree with @tomwilkie we should just use the label if present for now. We can use a `provider` metadata entry when/if the cloud-provider-specific rendering gets more sophisticated.

**Comment by tomwilkie** [comment]
@fons do you think we can close this?  I don't think we need anything more general, do we?

**Comment by 2opremio** [comment]
Not for now, I'll close it
