### ISSUE TITLE
Allow one-to-many mappings in the renderer

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#438]
The current rendering pipeline supports many-to-one mappings (including one-to-one) ie endpoint to process, process to container, container to image.

The pipeline doesn't allow us to go in the opposite direction, for instance enrich processes with container info, or containers with image info.  We hack this up with custom renderers (see #437 ContainerWithImageNameRenderer and ProcessWithContainerNameRenderer) which do two render passes and then do custom lookups.

I propose we generalise this by allowing mappers to emit intermediate keys, not merging RenderableNodes with the same intermediate keys, and allowing mappers to accept multiple RenderableNodes with the same intermediate key.  The MapFunc prototype would become:

```
func (key string, RenderableNodes) []struct{key string, RenderableNode}
```

Current behaviour would be provided by a special 'Reduce' Mapper, which would merge together all the RenderableNodes with the same intermediate key.

Then, to implement ProcessWithContainerNameRenderer, the ProcessRenderer would emit the Container ID as the intermediate key, and the next Mapper would receive all the Process for a given container _and_ the container, where it could then do the arbitrary enriching and emit a set of nodes for the processes.  It would look something like:

```
ProcessRenderer   -> {containerid: [n]processes} -
                                                  |->  ProcessContainerRenderer -> {processid: [1]process}
ContainerRenderer -> {containerid: [1]container} -
```

This would bring out existing Map/Reduce rendering pipeline much closer to real Map/Reduce.  As part of this, we should rename the ReduceRendered to be a MergeRenderer, to prevent (more) confusion.

**Comment by bboreham** [comment]
This was done in e4970f9214d4245104a2eb84ed7fc584c5b49547
