### ISSUE TITLE
Reports of rendering issues in safari 8

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#439]
https://twitter.com/mategabri/status/639751165530517504?cn=cmVwbHk%3D&refsrc=email

**Comment by peterbourgon** [comment]
Another report from @pidster

![image](https://cloud.githubusercontent.com/assets/114509/10040842/b9d52bd6-61df-11e5-86c7-4a324bb49c89.png)

**Comment by davkal** [comment]
I'm on Safari 9.0.1 and dont see the font render issue.
But there seems to be a box render issue instead:

![screen shot 2015-11-18 at 09 22 35](https://cloud.githubusercontent.com/assets/859729/11235953/17687d30-8dd6-11e5-9028-3b2e12341b37.png)
