### ISSUE TITLE
Missing edges between the ECS-demo containers

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#446]
Steps to reproduce.

1. Launch the scope variant of the ECS demo (which uses `scope:latest`)

    ```
git clone -b aws-ecs-scope git@github.com:weaveworks/guides.git
cd guides/aws-ecs
./setup
```

   Which should output three urls let's call them `u1`, `u2`, `u3`.

2. Make sure that the Http Servers are communicating with the Data Producers:

  ```bash
  while true; do 
    for I in u1 u2 u3; do 
      curl $I
    done
  done
  ```

3. Open Scope in any of the three instances (e.g. `u1:4040`)
    
    The HttpServer and DataProducers ( the `ecs-weave-ecs...` containers) should be connected since they are communicating with each other. However they are not.
<img width="1134" alt="screen shot 2015-09-04 at 4 11 28 pm" src="https://cloud.githubusercontent.com/assets/2362916/9687147/b02d4b78-531f-11e5-8a12-5d260cebcf11.png">

**Comment by 2opremio** [comment]
In fact, I also expect an edge between all the weavescope containers since every probe is reporting to all the apps.

**Comment by tomwilkie** [comment]
@2opremio attaching the contents of /api/report and /api/topology/containers to bugs like this will massively help narrow it down.

**Comment by 2opremio** [comment]
There you go https://gist.github.com/2opremio/9494a1f48b340a620526

**Comment by tomwilkie** [comment]
I've figured this out.

My bad.

**Comment by 2opremio** [comment]
Great that you figured it out. Out of curiosity, can you elaborate on what's causing it?

**Comment by tomwilkie** [comment]
I thought I had it but I didn't. Sorry.  Still working on it.

**Comment by peterbourgon** [comment]
Any update here? This is the only remaining release-blocker.

**Comment by tomwilkie** [comment]
The attached or fixes some issues but doesn't fix it 100%.

I've got two test cases: cross host communication over the weave network,
and cross host communication via docker port mapping.  (1) works now, (2)
doesn't.

I don't know why it doesn't work yet.

Feel free to review the pr, I see no reason why it can't go in.

**Comment by tomwilkie** [comment]
This is mostly fixes - pseudo nodes are working again, and short lived connections from containers to the internet are working.

But the short lived connection code doesn't deal with connections coming from the internet, as they go to the hosts IP, not the containers.  We know the port mapping for containers, so we should be able to fix this.  See #493
