### ISSUE TITLE
UI needs to pass option params to API calls

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#454]
1. Select Containers view
2. Select Show system containers
3. Click on any system container

Expected behavior: call to `/api/topology/containers/a0b1c2e3d4?system=show` is made (note URL param)

Actual behavior: call without URL param is made, resulting in 404

/cc @tomwilkie this explains the regression

**Comment by tomwilkie** [comment]
Nb this is a release blocker.
