### ISSUE TITLE
Frequently getting disconnected lines in scope UI

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#460]
If you leave it running on a changing topology, this happens pretty easily:

<img width="1524" alt="screen shot 2015-09-07 at 22 03 54" src="https://cloud.githubusercontent.com/assets/444037/9722829/704e062a-55ac-11e5-9188-d06ef7eb818c.png">

**Comment by davkal** [comment]
I've seen this today for the first time, too.

**Comment by tomwilkie** [comment]
Its the tcp report publisher.  I've got a fix on the PR.

**Comment by tomwilkie** [comment]
ignore me.

**Comment by davkal** [comment]
How can this be a backend thing?

**Comment by tomwilkie** [comment]
it was late.  i was wrong.

**Comment by davkal** [comment]
Not seeing this in the #445 PR branch.

**Comment by davkal** [comment]
Cant reproduce in master with example, either :( doing lots zooming  and panning.
Please reopen with steps to reproduce.

**Comment by davkal** [comment]
Just saw it happening, but cant reproduce :(
