### ISSUE TITLE
gopacket seems to statically initialise a lot of memory...

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#466]
![heap](https://cloud.githubusercontent.com/assets/444037/9741797/52c9d6f8-5654-11e5-8213-6c1a1a2c02c3.png)

**Comment by peterbourgon** [comment]
Is this an actual problem?

**Comment by tomwilkie** [comment]
Makes debugging the heap usage a little tougher, and seems like a shame
considering its not turned on by default.

**Comment by peterbourgon** [comment]
Well, I guess the subtext to that question was "is there anything we can do about it" save forking and cleaning up gopacket?

**Comment by tomwilkie** [comment]
An alternative would be to move the packet inspection code into a separate binary and only launch it when we enable that feature.

I think we probably want to do this for the tracer anyway (as its performance critical), so perhaps the same reasoning applies here?

**Comment by peterbourgon** [comment]
I'm fine with ripping packet capture out of Scope. Failed experiment.

**Comment by tomwilkie** [comment]
I wouldn't go that far just yet; its still a candidate for getting better metrics.  Maybe move it to experimental?  That will prevent some of the bit rot.
