### ISSUE TITLE
Manual scope setup (ie without weave) not working

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#471]
report from @bboreham

**Comment by bboreham** [comment]
I have 3 vms, set up using the weave Net test vagrant file.  Recently rebooted, etcd and skydns running but not weave.

On 192.168.48.11 I did:

    wget https://raw.githubusercontent.com/weaveworks/scope/master/scope
    chmod a+x ./scope
    ./scope launch

On 193.168.48.12 and 13 I did:

    wget https://raw.githubusercontent.com/weaveworks/scope/master/scope
    chmod a+x ./scope
    ./scope launch 192.168.48.11

When I point my browser at http://192.168.48.11:4040/ I get some entries, from that host only.

When I point my browser at http://192.168.48.12:4040/ I get a blank screen, with "Trying to reconnect.." in top-right.

**Comment by peterbourgon** [comment]
@bboreham Can you paste the output of `docker logs weavescope` from both hosts?

**Comment by tomwilkie** [comment]
I suspect this is to do with the buffer sharing, fixed in #484

**Comment by 2opremio** [comment]
@tomwilkie I also think this is related to #484 since it's very similar to what I was experiencing yesterday in ECS.

**Comment by tomwilkie** [comment]
Yes I can confirm it is; I just spun up a test with and without #484.

**Comment by 2opremio** [comment]
Let's close this in favor of #484
