### ISSUE TITLE
Cancel outstanding http posts in probe when it exists

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#472]
See https://github.com/weaveworks/scope/pull/459

**Comment by peterbourgon** [comment]
Will this actually have any positive effect?

**Comment by tomwilkie** [comment]
s/exists/exits/

It might help with ctrl-c'ing scope.

**Comment by peterbourgon** [comment]
I don't see how it could. To the best of my knowledge, outstanding HTTP requests have no way to preempt termination. Let's close this until we get some evidence.

**Comment by peterbourgon** [comment]
In testing for #503, I never experienced a problem with outstanding HTTP requests. Accordingly, I'll close this.
