### ISSUE TITLE
Missing edges from the Internet node

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#489]
Related to #446

After the fixes in #465, I get edges between the `httpserver`s and `dataproducer`s in the [ECS demo](http://weave.works/guides/service-discovery-with-weave-aws-ecs.html) but I am missing edges between the Internet node and the `httpserver`s

<img width="1146" alt="screen shot 2015-09-15 at 11 47 08 am" src="https://cloud.githubusercontent.com/assets/2362916/9874696/e3e4e2b8-5b9f-11e5-9b79-ffda76a3acef.png">

Here's the report: https://gist.github.com/2opremio/0a80f1a86138c6828468

**Comment by 2opremio** [comment]
As @tomwilkie mentioned offline, there should also be edges from each `ecs-agent`s to a `weaveproxy` but we they are not displayed because we are not tracking unix sockets (the `ecs-agent` talks to `weaveproxy` through `/var/run/weave.sock`)

**Comment by tomwilkie** [comment]
Unix domain sockets: #405
