### ISSUE TITLE
Show hint about empty topology

### ISSUE THREAD

**Issue by davkal** [weaveworks/scope#499]
Similar to #474 we could use a hint to show that there are no nodes in the topology and the reasons, e.g. no probes connected.

@peterbourgon what reasons do exist for an empty topology?

**Comment by tomwilkie** [comment]
We could show the number of filtered nodes; the main reason for an empty view is either being filter as they are disconnected (processes) or system (containers)

**Comment by davkal** [comment]
What about no connected probes?

**Comment by peterbourgon** [comment]
1. We haven't received any reports from probes recently. Are the probes properly configured?
1. There are nodes, but they're currently hidden. Check the hidden settings in the bottom-left.
1. Empty containers view only: you're not running Docker, or you don't have any containers.

To rule out (1), each /api/topology/xxx response could include a timestamp of the most recent received report. Or maybe something simpler, a bool indicating there have been recent reports. If the timestamp is too old, or the bool is false, then (1) would be the most likely cause. Is that worth doing?

**Comment by tomwilkie** [comment]
Fixed by #505
