### ISSUE TITLE
Update bin/release script

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#500]
The `bin/release` script from Weave contains improvements which haven't yet made it into Scope.

Ideally we should put the script in the [tools repository](https://github.com/weaveworks/tools) so that both Scope and Weave could share it.

**Comment by awh** [comment]
It's probably a good idea for someone more involved in Scope to review the new process for the updated script https://github.com/weaveworks/weave/blob/master/docs/release-process.md to make sure it doesn't break your workflow...

**Comment by tomwilkie** [comment]
@peterbourgon this is fixed now?

**Comment by peterbourgon** [comment]
This is resolved with the merge of the 0.8.0 release branch. I've also updated [the wiki release process](https://github.com/weaveworks/scope/wiki/Release-Process) accordingly.
