### ISSUE TITLE
Unstable reverse DNS lookups in UI

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#504]
When viewing the connections of a container talking to servers with multiple A-records, the view switches the displayed server names frequently making it confusing.

I tried to record the example but I wasn't fast enough since the names displayed ended up stabilizing. Will add it later if I see it again.

**Comment by 2opremio** [comment]
@inercia Are we sorting the DNS records consistently across requests after making a reverse lookup? If we don't, that would explain it.

**Comment by tomwilkie** [comment]
Hmm I didn't realise it would be possible to return multiple domain names for a given IP; we should make this a list (and make the cache store multiple entries) etc

**Comment by inercia** [comment]
So what should we do? When doing a reverse resolution, should we sort all the names we get for the IP and then return the first one? Should we make it a lista and return all of them? :confused:

**Comment by tomwilkie** [comment]
the later - list and return them all.

**Comment by inercia** [comment]
Ok, I'll fix it.

**Comment by tomwilkie** [comment]
@inercia the Node.Sets PR (#522) is pretty much ready to go, so you could base a full solution to this on that.

**Comment by inercia** [comment]
@tomwilkie ok, I'll take a look
