### ISSUE TITLE
Edges showing where they shouldn't

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#520]
See screen shot:

<img width="1792" alt="screen shot 2015-09-25 at 12 59 44" src="https://cloud.githubusercontent.com/assets/444037/10093474/671898cc-6385-11e5-9b26-6f9be8a5745c.png">

Edge between scope & app should not be there.  Its hard to reproduce and only happens occasionally

**Comment by squaremo** [comment]
I see this in my example app. This may help reproduce it (assumes you are using the weave API proxy, and Scope):

```bash
git clone https://github.com/squaremo/micro-wiki
cd micro-wiki
make -C pages
make -C conf
make -C preso
./microwikictl up
# will probably download a lot of things
./microwikictl load
# now go watch Scope
```

NB it's all quite rickety but feel free to ask for help :)

**Comment by tomwilkie** [comment]
@squaremo I get an error:
```
vagrant@ubuntu-14:~/src/github.com/squaremo/micro-wiki$ make -C pages
make: Entering directory `/home/vagrant/src/github.com/squaremo/micro-wiki/pages'
npm install
npm WARN package.json micro-wiki-pages-service@0.0.3 No README data
npm ERR! git clone git@github.com:file:../us Cloning into bare repository '/home/vagrant/.npm/_git-remotes/git-github-com-file-us-d1dcada0'...
npm ERR! git clone git@github.com:file:../us fatal: remote error: 
npm ERR! git clone git@github.com:file:../us    is not a valid repository name
npm ERR! git clone git@github.com:file:../us   Email support@github.com for help
npm ERR! notarget No compatible version found: us@'file:../us'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.0.1","1.0.2","1.0.3","1.1.0","1.1.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/vagrant/src/github.com/squaremo/micro-wiki/pages
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/vagrant/src/github.com/squaremo/micro-wiki/pages/npm-debug.log
npm ERR! not ok code 0
make: *** [pages.uptodate] Error 1
```

**Comment by squaremo** [comment]
npm v 1.4.28 is ancient, especially by node.js standards -- possibly it doesn't support file: modules as dependencies. Would you try upgrading it (easiest way might be to upgrade node.js)

**Comment by tomwilkie** [comment]
Can I haz a build container?

**Comment by squaremo** [comment]
> Can I haz a build container?

Not at this time

**Comment by tomwilkie** [comment]
Update: this is being caused by the short lived connection logic & our use of conntrack.  We can see from this report (https://gist.github.com/squaremo/06a699d7b7078e4de98d) that the erroneous connection from pages1 -> pages2 did in fact come from conntrack. 

When looking on the machine in the host net namespace, conntrack is reporting this connection.  From within the container lsof does not (it instead reports a valid connection to redis).

For not, we're going to add a flag to disable conntrack, but leave it on by default.

**Comment by squaremo** [comment]
I've put the output of conntrack on the host and lsof in the container in the gist, for reference.

**Comment by 2opremio** [comment]
Last week, while demoing the ECS guide at a talk I noticed a connection between an http server and a data producer which shouldn't be there. However the connection details on the http server's side indicated it was connected to scope.weave.local ...

**Comment by awh** [comment]
Whilst attempting to repro #1577 to prove the fix worked, I observed two spurious TCP connections in scope - one allegedly originating from the nginx container and looping back to itself on port 4040, and one from the nginx container to the client on port 4040.

**Comment by tomwilkie** [comment]
I think we need to get on top of this for v1.

Given it looks like from within a network namespace conntrack behaves itself, we could run a conntrack -E per namespace?  I don't think the performance overhead would be too high - these things seems to use little cpu and 600Kb of memory.

@paul what do you think to trying this?

**Comment by rade** [comment]
I haven't seen incorrect connections for a long time. If anybody does, please re-open.
