### ISSUE TITLE
Weave integration has false negatives

### ISSUE THREAD

**Issue by squaremo** [weaveworks/scope#523]
The `scope` script checks that the weave script is in the user's path (via `command_exists`). But this won't be the case in general; and in particular, if weave is being run remotely.

The result is that scope doesn't associate weave IPs with containers, and thereby doesn't detect short-lived connections over the weave network.

**Comment by tomwilkie** [comment]
We should move the logic for enabling the weave integration into the entrypoint script (or even into the go code)
