### ISSUE TITLE
Expose Kubernetes namespaces and labels

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#528]
Namespaces and labels can be presented with some kind coloured tag boxes. Namespace have resources associated with them also (#527).

**Comment by 2opremio** [comment]
A user was requesting this on twitter https://twitter.com/manojlds/status/711800881734361088 and @janwillies is interested too

**Comment by janwillies** [comment]
We are leveraging namespaces pretty heavily in kubernetes and it's starting to become a pain to find the right pod in scope

**Comment by tomwilkie** [comment]
@janwillies Sounds like what you really want is to filter in/out certain namespaces?

**Comment by janwillies** [comment]
exactly

2016-03-23 16:45 GMT+01:00 Tom Wilkie <notifications@github.com>:
