### ISSUE TITLE
Take new screenshot that includes window chrome for readme

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#53]
I think it might look nicer with some sort of border; perhaps the browser window will be enough?

Also, centre align it pls.

**Comment by davkal** [comment]
The current one is pulled from the official website. I added a version with window to the new website, waiting for it to be launched.

**Comment by tomwilkie** [comment]
This was fixed in https://github.com/weaveworks/scope/commit/bd245384ef0db14141c79986027b0e80020eb00c
