### ISSUE TITLE
Move entirely to Go 1.5, remove netgo cruft from Makefile

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#530]
- Check for Go 1.5 during builds
- Remove all netgo cruft from Makefile and other scripts

**Comment by tomwilkie** [comment]
Alternatively, how about we move to a completely container-based build process (we almost have it), have that container use go1.5?

Also, its not clear we can remove the netgo cruft, given what we discovered when deploying the service.

**Comment by peterbourgon** [comment]
+1 to both points. Please amend the original post?
