### ISSUE TITLE
Expose Kubernetes service connections

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#538]
Kubernetes service connections go through kube-proxy, which shows up as an "Uncontained" node. This makes following those connections difficult for users. We should split up those connections by service (virtual IP), and render a pseudo-node for each.

The kube-proxy is either a userspace hop, or a bunch of iptables rules, depending on configuration.

Created from #441

**Comment by tomwilkie** [comment]
With k8s 1.2, connections are remapped using iptables.  And we deal with them correctly.
