### ISSUE TITLE
i can't launch scope

### ISSUE THREAD

**Issue by josselinchevalay** [weaveworks/scope#548]
hi, 

i try launch this project but i catch an error. the message is 

flag provided but not defined: --pid

my docker version is Docker version 1.0.1, build 990021a

thx in advance.

**Comment by tomwilkie** [comment]
Hi Chevalay; I'm afraid Scope needs a fairly recent version of Docker.  We generally all use the latest (1.8), although it should work with 1.6.  ```--pid``` was introduced in 1.5, so that is a bare minimum.

We should add a warning on docker version to the scope script though.

**Comment by josselinchevalay** [comment]
thx a lot i upgraded my docker client.
