### ISSUE TITLE
RFC: Probe plugins

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#554]
Aim: allow people to add nodes & metadata to the scope object model. 

Example would be embedding links and iframes from cadvisor in the UI, or adding custom metadata for filtering in the DSL.

Proposal:
- bind mount /etc/weave/scope-probe-plugins into the scope containers
- for each executable script in there, run it every probe tick and parse stdout as a json report.  Eg:
```
#!/usr/bin/python
import json

if __name__ == "__main__":
  print json.dumps({
    "Container": {
      "Nodes": {
        "<hostname>;<containerid>": {
          "metadata": {
            "some-third-party-key": "hello world"
          }
        }
      }
    }
  })
```
- add a field to the node struct called 'Links', with type []link, in such a way that plugins can add links to it, and the UI renders them in the details panel:
```
type link struct {
  label string
  url strgin
}
```
- add a field to the node struct calleds 'Embeds', with type []embed, in such a way that plugins can add links to it, and the UI renders them as iframes in the details panel:
```
type link struct {
  title string
  url string
  height, width int
}
```
- implement an example that embeds cadvisor links and iframe of graphs in the UI.
- implement an example that annotates container with something from ECS, and allows user to filter them.

**Comment by paulbellamy** [comment]
Might also be worth looking at https://github.com/hashicorp/go-plugin

**Comment by paulbellamy** [comment]
Seems like it wouldn't really fit for control, pipe, or UI plugins.

**Comment by alepuccetti** [comment]
Should this PR fix https://github.com/weaveworks/scope/issues/1022?
