### ISSUE TITLE
SVG export for large topologies?

### ISSUE THREAD

**Issue by faddat** [weaveworks/scope#555]
Common displays aren't large enough to display all of the detail that scope can expose.  Most computers aren't powerful enough to render this detail smoothly, so:

 * .svg exports
 * a way for users to select how much they'd like their PC to be abused by scope (slider?)

**Comment by peterbourgon** [comment]
.svg export is an interesting idea. @davkal, is it technically feasible?

The way Scope chooses to make more or less information visible is via topologies of different levels of abstraction. Further, I don't see an immediately obvious, user-friendly way to scale detail up and down based on any parameter, manual or automatic. That said, we're definitely looking in to all kinds of ways to increase the information density for large infrastructures. Thanks for the ideas, we'll put them in the pot!

**Comment by davkal** [comment]
SVG exports are technically possible since it's just a DOM subtree, but we need a way to inline the relevant CSS. Without CSS the graph looks quite poor.

**Comment by davkal** [comment]
In case you mean export SVG to PNG, we could try html2canvas.

**Comment by faddat** [comment]
It's that button!  I'd forgotten!   :D!!!!!!!!
