### ISSUE TITLE
Probe posting should follow redirects

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#559]

**Comment by tomwilkie** [comment]
Comment on https://golang.org/pkg/net/http/#Client CheckRedirect would imply golangs http client is supposed to follow redirects.

Perhaps the problem is not having certificates?

**Comment by paulbellamy** [comment]
[Here](https://golang.org/src/net/http/client.go?s=897:2420#L252) It shows it follows POST redirects for 302, and 303, but not 301 (which is right-ish, by the spec). So I guess the answer is to use a 302, instead of a 301.

**Comment by paulbellamy** [comment]
Ah, but [here](https://golang.org/src/net/http/client.go?s=897:2420#L353), if you are following a redirect it will change `POST` to `GET`, regardless of the semantics of the redirect code (i.e. disrespecting code `308 Permanent Redirect`.
