### ISSUE TITLE
Scope binaries are getting a bit big

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#569]
```
-rwxr-xr-x 1 vagrant vagrant  22M Oct 17 12:36 scope-app
-rwxr-xr-x 1 vagrant vagrant  21M Oct 17 12:36 scope-probe
```

Making them one binary would probably save most of this, as I bet its mostly shared libraries.

**Comment by peterbourgon** [comment]
I don't see how this is a problem.

**Comment by tomwilkie** [comment]
It hit me when testing over the weekend; the total image is something like
70MB, and copying it to test VMs on GCE was taking a while.
