### ISSUE TITLE
Vendor using GO15VENDOREXPERIMENT

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#573]
- [Design doc](https://docs.google.com/document/d/1Bz5-UB7g2uPBdOx-rw5t9MxJwkfpx90cqG9AFL0JAYo/edit)
- [Blog post, perhaps easier to digest](https://medium.com/@freeformz/go-1-5-s-vendor-experiment-fd3e830f52c3)

**Comment by tomwilkie** [comment]
Dupe of #535?

**Comment by peterbourgon** [comment]
...yup
