### ISSUE TITLE
Considered resolving connections through the docker-proxy

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#606]
![scope screenshot from 2015-10-29 16_30_07](https://cloud.githubusercontent.com/assets/444037/10825371/a3783cae-7e5c-11e5-9f26-b75a9fd7a9e2.png)

Theory is the connection from skydns -> etd is going through the docker-proxy.

**Comment by tomwilkie** [comment]
Probably not worth doing, as it looks like docker-proxy is going away:

https://github.com/docker/docker/pull/14973

**Comment by tomwilkie** [comment]
Or not: https://github.com/docker/docker/pull/16347

**Comment by bboreham** [comment]
/api/report result: https://gist.github.com/bboreham/7946c6fab7096aadd976

**Comment by bboreham** [comment]
Note if skydns connects to etcd on host2 (as opposed to host1 in the picture) then a direct link between them is shown.

**Comment by bboreham** [comment]
It would perhaps be a benefit to mark the node as 'docker-proxy'; as @rade commented it is unnecessary to go via the published port when connecting on the same machine.

**Comment by tomwilkie** [comment]
Yes, hiding proxies has the downside.   Having a hybrid view like that suggested in #552 would help; I think we might want both, with some visual distinction for edges we've 'shortcutted', and an option to not shortcut them.

**Comment by 2opremio** [comment]
@tomwilkie Can we close this?
