### ISSUE TITLE
When weave is running, scope doesn't run

### ISSUE THREAD

**Issue by faddat** [weaveworks/scope#609]
Okay, so here's my history:

   86  weave reset
   87  eval $(weave env --restore)
   88  docker ps
   89  weave launch 104.199.133.238
   90  docker ps
   91  scope launch 104.199.133.238
   92  docker ps
   93  scope stop
   94  weave reset
   95  docker ps
   96  weave launch 104.199.133.238
   97  weave status
   98  eval $(weave env)
   99  scope launch 104.199.133.238
  100  weave reset
  101  eval $(weave env --restore)
  102  scope launch 104.199.133.238
  103  docker ps
  104  scope
  105  weave launch 104.199.133.238
  106  eval $(weave env)
  107  scope launch 104.199.133.238
  108  docker ps

One thing I know for sure is that my machine was filling up with sigproxy containers.  I got them cleared out using weave reset and 

eval $(weave env --restore)

if I launch a scope container without weave running, I can get to the scope GUI, but of course that's worthless.  If I then start weave, nothing updates in the scope GUI to reflect that.  If, after I've started weave, I scope stop and then scope launch <peer> I get:

![image](https://cloud.githubusercontent.com/assets/7142025/10871204/fa56314e-8112-11e5-9ac8-6d5db118d62c.png)

Everybody's pal 404.

Thoughts?

**Comment by faddat** [comment]
A development!

When I kill one of the sigproxies, suddenly I can access scope again instead of a 404, thus:

https://gist.github.com/faddat/006797a9a4d6639681aa

When I then try to hit weave I get a:

![image](https://cloud.githubusercontent.com/assets/7142025/10871332/a01ddfb6-8116-11e5-941a-0c211e61c7d6.png)

**Comment by tomwilkie** [comment]
Hi Jacob; could you please send the output of `docker -v`, `weave version` and `docker images | grep scope`

Also could you please put the result of `docker logs weavescope` in a gist?

**Comment by tomwilkie** [comment]
Hi Jacob; any chance reproducing this?  I think this is the same cause as #608 (weave not achieving quorum), so I'm going to close as dupe.
