### ISSUE TITLE
Nodes count is 0 while showing nodes in containers by host

### ISSUE THREAD

**Issue by davkal** [weaveworks/scope#621]
![screen shot 2015-11-05 at 10 32 30](https://cloud.githubusercontent.com/assets/859729/10964671/d409bf36-83a8-11e5-8d4a-71f6fea51846.png)

[/api/topology](https://gist.github.com/davkal/b0108a029d4c106887df)
[/api/report](https://gist.github.com/davkal/7fdad7cf112d8fdf451d)

Same for containers by image.

**Comment by tomwilkie** [comment]
From the version number in the bottom right, looks like this was on the controls PR?

**Comment by tomwilkie** [comment]
Can confirm have seen on master.
