### ISSUE TITLE
k8s: Show pod status

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#634]
Right now pending pods show up just as if they were already running.

**Comment by tomwilkie** [comment]
Could do this as part of #659

**Comment by errordeveloper** [comment]
May be, but it would look more obvious if the non-ready pods show up grey or kind of translucent.

**Comment by tomwilkie** [comment]
We already use grey-translucent to indicate pseudo nodes, so doing that might be confusing.  Would be easy to hack up through.

**Comment by tomwilkie** [comment]
Marking all k8s related issues as post-1.0
