### ISSUE TITLE
Update for Docker 1.10

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#647]
Things to do:
- [x] update test VM
- [x] update client
- [x] Multiple networks - tag containers, filter by network?
- [x] are there new docker bridge names?
- [ ] new stats (#636)

**Comment by paulbellamy** [comment]
re: docker bridge names, afaict this hasn't changed.

**Comment by rade** [comment]
Closing this since it's just a tracking issue and there is only one thing left to do.
