### ISSUE TITLE
CPU usage sparklines are very flat when multiple cores are available

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#662]
The sparklines are only 16px tall, but scaled to the min/max cpu usage (e.g. for 4-cores 0-400%). Therefore, 1px = 25% cpu usage. This makes the graphs stay very flat.

**Comment by tomwilkie** [comment]
If we rendere sparklines like [cubism](https://square.github.io/cubism/), ie wrapping and getting darker, we could pin to 100% and it would be a little more obvious.

**Comment by rade** [comment]
NB: we changed the scale to be 100%-based in #1830, but that doesn't change the substance of the issue - a single-threaded process operating at max capacity will only take up 25% overall CPU on 4 coures, which is only 4px tall in the graph.

Is that really that much of an issue though? @paulbellamy were you perhaps encountering #1664, which resulted in host CPU usage being under-reported by a factor of num_cores (i.e. maxing out a single core on a four-core machine would actually show up as only 1/16th utilisation, i.e. 1px tall)?

**Comment by paulbellamy** [comment]
Possibly, yes.
