### ISSUE TITLE
Consider hiding containers that are created by the weave & scope scripts from Scope

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#664]
Using the works.weave.role=system hack.

**Comment by paulbellamy** [comment]
We do this for the containers in weave, but not scope.

**Comment by tomwilkie** [comment]
I don't think we do it in weave: https://github.com/weaveworks/weave/blob/master/weave#L101

**Comment by tomwilkie** [comment]
Also we missed one: https://github.com/weaveworks/scope/blob/master/scope#L112

**Comment by tomwilkie** [comment]
Ah but for weave the container image should be labeled...

**Comment by paulbellamy** [comment]
https://github.com/weaveworks/weave/blob/master/prog/weaveexec/Dockerfile#L4
and
https://github.com/weaveworks/scope/blob/master/docker/Dockerfile#L3

**Comment by tomwilkie** [comment]
Okay so it turns out the labels in the Dockerfiles don't translate to labels on the container, but on the images.

**Comment by paulbellamy** [comment]
Then how do the weave and scope containers ever get hidden?

**Comment by tomwilkie** [comment]
we also filter on container name (see https://github.com/weaveworks/scope/blob/master/render/filters.go#L174)
