### ISSUE TITLE
Internet should not count as a stopped container

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#665]
![](http://g.recordit.co/AfVA5mwKZt.gif)

report.json: https://gist.github.com/paulbellamy/3728756331b3e781f6ef

**Comment by tomwilkie** [comment]
The bigger question is why is there an unconnected internet node?  It looks like that node exists due to an old connection to an old container.  Its similar to the unconnected uncontained node, see in #511.

**Comment by tomwilkie** [comment]
There is a baked in assumption that pseudo nodes cannot exist unless they are connected to something.  The filter code assumes this, so assumes any unconnected pseudo nodes are newly unconnected by the filtering process, and removes them.  I think this is still correct.

The fix therefore is to ensure unconnected pseudo nodes don't make it into the topology to begin with.  This can happen a bunch of ways, in particular is a container does short lived connections to the internet from the host net ns - the short lived connection code cannot attribute them, as they share an IP.

Anyway, fix is to filter out unconnected nodes from the short-lived-connection logic before merging with the final view.
