### ISSUE TITLE
Nodes that reappear sometimes overlap

### ISSUE THREAD

**Issue by davkal** [weaveworks/scope#671]
![screen shot 2015-11-13 at 11 14 05](https://cloud.githubusercontent.com/assets/859729/11147124/1fef02fa-8a14-11e5-9806-ead3ea9c84c1.png)

This is how it happens: node A and B have a connection, node B disappears, node C appears having a connection to A, node C will be rendered in a similar location as B, then node B reappears overlapping with C. This is due to the node location cache that is used to mitigate the need for re-layouts.

**Comment by rade** [comment]
@davkal is this still happening? Do you have steps to reproduce this?

**Comment by davkal** [comment]
I have not seen it in the wild, ( @2opremio or @pidster ?) but given the above description, you can `nc` your way into this. Also, I can construct a test case.

**Comment by 2opremio** [comment]
I haven't see it in a while either. @errordeveloper , have you? (you reported a similar issue https://github.com/weaveworks/scope/issues/1450 )

**Comment by rade** [comment]
> you can `nc` your way into this

I've tried and failed.
