### ISSUE TITLE
Consider deduping connections by client port numbers in the details panel

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#680]
In lots of cases (esp. since the short lived connection stuff went in) we see LOTS of connections lists in the details panel.  We tend to be less interested in the client port number, so perhaps all lines that share a client port, connecting to a unique dst ip, dst port, could be deduped, and show as a range?

**Comment by tomwilkie** [comment]
This was also suggested (or something similar) as part of the details panel redesign.

**Comment by tomwilkie** [comment]
Just did hangout with @peterbourgon @davkal and @paulbellamy.

Grouping incoming connections by local port makes little sense, and the cardinality of that is likely to be very low (1-2) in most situations.  Similarly grouping outgoing connections by remote port makes little sense.

It was observed that the current connections tables lists every tcp 4 tuple for the selected node: this is likely to be too much information.  It was suggested that the connections table should instead group by the granularity of whatever topology you are currently viewing, eg when viewing the container topoloy, we  would have the following ables:

```
Incoming Connections
+------------------+
+------------------------------------------------+
|Container         |Local Port     |Count        |
+------------------------------------------------+
|Foo               |80             |12           |
|Foo               |443            |13           |
|Bar               |80             |2            |
|Baz               |80             |4            |
|Baz               |443            |8            |
+------------------------------------------------+

Show more...

Outgoing Connections
+------------------+
+------------------------------------------------+
|Container         |Remote Port    |Count        |
+------------------------------------------------+
|Foo               |80             |12           |
|Foo               |443            |13           |
|Bar               |80             |2            |
|Baz               |80             |4            |
|Baz               |443            |8            |
+------------------------------------------------+

Show more...
```

Ordering of the columns is TBD.  Port and Count columns should be sortable.

**Comment by peterbourgon** [comment]
What if a container has a connection to something that isn't represented as a container? Will it fall back to the TCP 4 tuple? Hopefully the answer is yes. In which case the header of the leftmost column shouldn't be Container, but rather Remote or Other or something.

```
Incoming connections
+------------------+------------+-------+
| Remote           | Local port | Count |
|------------------|------------|-------|
| _Foo_            |       1337 |     3 |
| 8.8.4.2          |         80 |     1 |
+------------------+------------+-------+
```

**Comment by tomwilkie** [comment]
Yes +1, if its a pseudo node then we display what ever that is.  Agree re: title

**Comment by paulbellamy** [comment]
I was under the impression that pseudonodes were to be displayed the same as other nodes:

```
Incoming connections
+------------------+------------+-------+
| Remote           | Local port | Count |
|------------------|------------|-------|
| Foo              |       1337 |     3 |
| The Internet     |         80 |     2 |
+------------------+------------+-------+
```

**Comment by tomwilkie** [comment]
@paulbellamy yup, I think peter was saying the "Containers" column title wasn't appropriate if the column also container pseudo nodes.

**Comment by peterbourgon** [comment]
Sure, if it's the internet. I'm more interested in things that are in the local network but not containerized.
