### ISSUE TITLE
HTML-GL

### ISSUE THREAD

**Issue by faddat** [weaveworks/scope#683]
I would have made this a pull request, but I'm honestly not so great with HTML and I could figure out quite how to get this in the right place in scope.  

https://github.com/PixelsCommander/HTML-GL

I think this will enable larger uses of Scope.  Long term, my scope use-case is sales related:  a 60" 4k TV on our office wall showing our network in real time.  The more sexified we can make it, the more effective a tool it will be.

**Comment by davkal** [comment]
Thanks for the suggestions, we're continuously investigating other drawing techniques in the browser.
https://github.com/flipboard/react-canvas looks quite promising too. We'll have a look at HTML-GL as well.

For this to be a real issue, I'd like to reproduce your topologies to see the lag. If it's not sensitive, could you please send a report of your network by pointing your browser URL to `/api/report` of your scope instance, copy the response, put it in a secret gist and send the link to davidk@weave.works?

**Comment by faddat** [comment]
I don't mind at all.

http://142.0.199.20:4040/api/report

(Not sensitive, planning to slather it all over klouds.org at some point
soon)

**Comment by davkal** [comment]
Thank you! It's definitely a big report. Good that we filter system nodes by default :smile: 
It will help us a lot to optimise the UI for bigger topologies, which seems to be your use case.

PS. Could we invite to our public scope channel on slack to get some more feedback?

**Comment by faddat** [comment]
for sure!



Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421
