### ISSUE TITLE
Empty details panel after stopping container

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#693]
Either the details panel should be implicitly hidden after stopping a container or we should show a friendlier message such as, "container stopped"

Before stopping:

<img width="1131" alt="screen shot 2015-11-23 at 22 54 16" src="https://cloud.githubusercontent.com/assets/2362916/11352593/3525b33e-9235-11e5-8adc-e968a78f412a.png">

After stopping:

<img width="1127" alt="screen shot 2015-11-23 at 22 54 30" src="https://cloud.githubusercontent.com/assets/2362916/11352598/3a69b296-9235-11e5-91ce-c6492beb7a67.png">

**Comment by 2opremio** [comment]
In fact, shouldn't we still be getting status info about the container? Like that it's stopped and that the image it's running?

**Comment by tomwilkie** [comment]
This is happening as we filter out stopped containers, and we don't show
details for nodes that disappear. Ie when you stop a container the node
disspears.

**Comment by 2opremio** [comment]
@tomwilkie makes sense, then I guess we should hide the details panel when we stop it.

**Comment by tomwilkie** [comment]
We used to do that, but an issue was filled saying that it was unintuitive
behaviour, if I recall correctly.

I think current behaviour is surprising too, so this does need a rethink.
We could not filter out stopped container by default, but that has the
potential to fill up the view with lots of unconnected containers (docker
does tend to leave lots of stopped containers around). We could have a
grace period, and show containers that were stopped in the last 30s, for
instance, but that could be even more confusing.  Any other ideas?

**Comment by 2opremio** [comment]
Can't the details panel still have access to the details of the container so long as it's open?

**Comment by tomwilkie** [comment]
Right now the details panel can only show details of nodes in the current
view (ie not ones which have been filtered out).   We could change that,
and make the endpoint for fetching node details ignore the filters.  This
could be unintuitive for other reasons, but does sound least worse.
@davkal, thoughts?

**Comment by tomwilkie** [comment]
@davkal mind if I take this?
