### ISSUE TITLE
Dr. 1.9 + Archlinux: we've 1.3 + scope 0.10: whole machine dies

### ISSUE THREAD

**Issue by faddat** [weaveworks/scope#699]
Hey guys I imagine you don't get many of these so here it is I have a so-called showstopper bug. My entire system collapses everytime I run we've and/or weave plus scope and I'm going to test to find out if there is a combination that likes or doesn't like right now but I wanted to let you know because it's a full system crash mouse stops responding everything dies. Talk to you guys soon!

**Comment by tomwilkie** [comment]
Hi Jacob; not much to go on here; I suggest issues like this are handled via the weave-users@weave.works group, where we can more interactively help you with these kind of problems.
