### ISSUE TITLE
Cannot show unconnected nodes

### ISSUE THREAD

**Issue by davkal** [weaveworks/scope#713]
In the application view, there is no option to show unconnected nodes. In other views the options allow to show/hide nodes. That is inconsistent.

![screen shot 2015-12-01 at 15 58 30](https://cloud.githubusercontent.com/assets/859729/11505460/bf61860c-984a-11e5-85cc-78f38adff958.png)

**Comment by tomwilkie** [comment]
This is intentional; on any given system there are bound to be tons of unconnected processes, and it will just swamp the UI if we allow users to see them.  

Whats the motivation (beyond consistency) for wanting to see them?

**Comment by tomwilkie** [comment]
As discussed, working as intended.
