### ISSUE TITLE
Document how to debug scope

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#714]

**Comment by tomwilkie** [comment]
I assume you mean:
- how to get the probe to dump the stats it gathers?
- how to get the app / probe to dump stack traces?

Currently the app/probe will exit when you send it the signal to dump stack; I'd like to include the code from weave to stop this.  Sound good, @paulbellamy?

**Comment by paulbellamy** [comment]
The specific instance was that there was no data showing up, no errors in scope logs, and no information on how the user should go about debugging that.

**Comment by tomwilkie** [comment]
Okay, in that case a stack dump is really all I'd recommend.  Sounds like something might have got locked up, or we're swallowing an error somewhere.  Hard to provide general purpose debugging steps TBH.

**Comment by paulbellamy** [comment]
Sure, but adding and documenting how to enable debug-logs, and documenting how to get a stack dump may be useful.

**Comment by tomwilkie** [comment]
Indeed - thats what #723 (except we don't have log levels, do no debug logs).
