### ISSUE TITLE
Probe hanging with docker 1.9.1 and coreOS Alpha

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#715]
Seems to be happening for a user on coreOS, docker 1.9.1. See if we can replicate, and if it is on docker 1.9.0 as well.

**Comment by tomwilkie** [comment]
Closing in favour of #769, as there is more info there.

**Comment by paulbellamy** [comment]
For reference, user here was using xhyve, not virtualbox.

**Comment by 2opremio** [comment]
This was a different issue, there was no CPU consumption problem and the probe logs didn't show anything unusual but the UI didn't display anything.

**Comment by 2opremio** [comment]
I can reproduce it in a Vagrant VM (`'coreos-alpha' (v933.0.0)`) and `scope:latest`:

```
git clone https://github.com/coreos/coreos-vagrant.git
cd coreos-vagrant
cp user-data.sample user-data
cp config.rb.sample config.rb
vagrant up
vagrant ssh
curl -s -L https://raw.githubusercontent.com/weaveworks/scope/master/scope -o scope && chmod +x scope && ./scope launch
```

The UI shows containers for a while but then they went away and the whole system froze (in a similar way to #769 ) which I believe didn't happen when @rimusz showed us (although @rimusz was using xhyve). So, after all, this may be related or a different incarnation of #769.

**Comment by 2opremio** [comment]
I can confirm that the coreos Vagrant box enables `natdnshostresolver` causing the same problem as #769:

```
$ grep -B 1 nat ~/.vagrant.d/boxes/coreos-alpha/935.0.0/virtualbox/Vagrantfile 
    # Fix docker not being able to resolve private registry in VirtualBox
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
```

Which suggests that although `natdnshostresolver` is not enabled by default, it may be common.

However, after disabling setting those flags to `"off"`, I can launch Scope and everything works as expected (the reports from the probe are definitely reaching the app and containers are displayed).

@rimusz can you please try to reproduce again and, if you can, provide us with specific instructions on how you did it?

**Comment by rimusz** [comment]
all good on my tests with the latest alpha/beta/stable, but I'm not using `vagrant` but xhyve based coreos installs on my Mac

**Comment by 2opremio** [comment]
Closing then. Thanks @rimusz !
