### ISSUE TITLE
Consider having a "By Replication Controller" view for kubernetes

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#716]

**Comment by tomwilkie** [comment]
Should have controls for scaling up/down the RC.

**Comment by peterbourgon** [comment]
From speaking to Kelsey this week I understand ReplicationControllers are being deprecated in the general case in favor of Deployments. Perhaps it makes more sense to tackle Deployments first.

**Comment by 2opremio** [comment]
I agree

**Comment by tomwilkie** [comment]
Close this in favour of #1372
