### ISSUE TITLE
See if scope k8s client can access the api server from inside a pod using service account

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#717]
May have issues as it's in the host namespace

**Comment by 2opremio** [comment]
This is needed to simplify running Scope in Kubernetes.

**Comment by 2opremio** [comment]
A couple of remarks:

* If this works, we can automatically enable k8s support when run inside a pod without requiring any flags. If scope can access the service account then enable k8s support.

* We should deal with replicated k8s reports from the Scope probes. Initially, the simplest way is to let all probes and let merging implicitly take care of deduplication but this will put a lot of pressure in the API Server of big kubernetes clusters.
