### ISSUE TITLE
Filter kubernetes pause container as a system container

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#733]
In Kubernets every pod implicitly includes a root `pause` container, whose network namespace is referenced by the other pod containers to ensure a single, shared namespace per pod.

This containers should be considered system containers, since they don't have any app-level functionality and clutter the view.

**Comment by ankur22388-huawei** [comment]
Can these pause conatiner be updated or modified with some new configuration

**Comment by 2opremio** [comment]
@ankur22388-huawei why? What's your usecase?

**Comment by ankur22388-huawei** [comment]
I want to perform some operation on all containers running inside a pod, I was thinking if i do it directly on pause container of that pod , Will it create impact on all containers?

**Comment by 2opremio** [comment]
@ankur22388-huawei I am not sure I understand. This issue is about filtering containers in views not about performing operations on them.

**Comment by ankur22388-huawei** [comment]
Ok no problem, i will ask it in a newer discussion
