### ISSUE TITLE
Investigate simplifying node IDs

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#734]
We have node ids generated in `report/id.go` and `render/id.go`, which generate subtly different IDs. It might be possible to simplify the code either by always using the fully-scoped IDs, or by always using the un-scoped IDs.

Needs investigation...

**Comment by paulbellamy** [comment]
May also be worth investigating using a typed struct for IDs.

**Comment by tomwilkie** [comment]
@paulbellamy I believe #1204 fixed this.

**Comment by paulbellamy** [comment]
Fixed it, but not the structs for ids part.
