### ISSUE TITLE
Docker containers with `--net=host --pid=hosts` show up as uncontained

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#738]

**Comment by tomwilkie** [comment]
Could you give the example of the container you started, and the gist of /api/report?  Thanks!

**Comment by tomwilkie** [comment]
I did:

```
vagrant@ubuntu-14:~$ docker run -dti --pid=host --net=host alpine /bin/sh
cf4afccb976f2849846aae60e2e75346425998287732f0553402527c931a6839
```

And got a container, as expected:
![screen shot 2015-12-14 at 15 24 22](https://cloud.githubusercontent.com/assets/444037/11784889/c71f0f82-a276-11e5-9f15-c2864771090d.png)

@errordeveloper do you have any reproduction steps?  I'm going to close this, please reopen if you can reproduce (with master).
