### ISSUE TITLE
Pipes don't survive scope-app restarting

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#744]
Sending KILL to the scope-app should have it back up and running with pipes intact. At the moment the pipes become unusable.

> I realised there is a bug in pkill scope-app
> in that the app id changes across restarts
> so the pipe is torn down
> -Tom

**Comment by tomwilkie** [comment]
Actually I'm not sure this is going to be (easily) possible.  Even if we make the app id survive app restart, the probe is still going to kill the app client when the app goes away and it can't read the id, and currently the pipe is tied to the app client.  We could change that, but I don't think its worth the effort.
