### ISSUE TITLE
Investigate using inotify to watch for changes in /proc

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#745]
[Wikipedia claims](https://en.wikipedia.org/wiki/Inotify) `Inotify does report some but not all events in sysfs and procfs.`

We should see if we can use it to replace (or at least guide) the procWalker.

I expect this would give a performance improvement, as it should save us reading the entire procfs every time (or at all).

**Comment by paulbellamy** [comment]
See: http://unix.stackexchange.com/questions/90627/notify-of-changes-on-a-file-under-proc

**Comment by tomwilkie** [comment]
try this: `inotifywait -r -m --timefmt '%H:%M' --format '%T %w%f %e' /proc | grep net`

For me, only `somaxconn` events are recorded.
