### ISSUE TITLE
Pipes should handle window resizing (and pop-out)

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#746]
When a window resizes we should send docker `POST docker:2375/v1.21/containers/alpine/resize?h=35&w=80`, to trigger ncurses apps to redraw

Apps only redraw when the window size _actually_ changes (so the POST may have no effect). So, when we pop-out (or first open) we should send `POST docker:2375/v1.21/containers/alpine/resize?h=0&w=0`, then resize to the proper size.

There is an equivalent api endpoint for execs.

**Comment by paulbellamy** [comment]
Note: This will play interestingly (i.e. it already does), with attaches, where a real terminal is also attached.

**Comment by foot** [comment]
Resourcey

`PUT /api/pipes/:pipeId/dimensions` w/  `{"width": 80, "height": 24}`

OR, keep in sync w/ docker api is nice a simple too:

`POST /api/pipe/:pid/resize?h=0&w=0`

Anywho this is nice and straight-forward from FE. I can have a crack at the golang if @tomwilkie and @paulbellamy are busy but disclaimer I've not golang'd before.

**Comment by tomwilkie** [comment]
Yeah we could do something like this, or we could use the existing controls
rpc mechanism to do it.

Thinks.

**Comment by foot** [comment]
The FE doesn't have any "semantic" understanding off the controls: it gets a list from the server and doesn't really look inside that list.

vs. resizing which is something it is aware of in a sense.

**Comment by errordeveloper** [comment]
On the bottom end, from my understanding, we need to send `SIGWINCH`, do we have a mechanism for that part already?

**Comment by errordeveloper** [comment]
For the record, GCE terminal widget has a way of handling this.

**Comment by paulbellamy** [comment]
Docker's resize api endpoint (as mentioned above) sends `SIGWINCH` when the window size changes.

**Comment by errordeveloper** [comment]
Ah, that's nice!
