### ISSUE TITLE
Can't use top in an exec pipe - "TERM not set"

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#759]
![screen shot 2015-12-14 at 11 56 07](https://cloud.githubusercontent.com/assets/444037/11780423/b5119480-a259-11e5-9b34-ec2508155676.png)

**Comment by foot** [comment]
`top` works on all the alpine containers I have. `exec`ing or `attach`ing to containers just running `sh`.

**Comment by tomwilkie** [comment]
I think you need to do it on a container that wasn't started with -ti, such as the scope container.

**Comment by errordeveloper** [comment]
The question is how to inject `TERM` on `docker exec`... One way would be to run `/usr/bin/env TERM=xterm /bin/sh -l` instead of `/bin/sh` (as we are currently doing).

**Comment by paulbellamy** [comment]
`top` works fine on the scope container for me...
![screen shot 2016-02-11 at 14 47 41](https://cloud.githubusercontent.com/assets/250199/12979359/6dd8655a-d0ce-11e5-873c-4852efee816a.png)

But not on the elasticsearch one. Seems like it could be an issue specifically with ubuntu?

**Comment by paulbellamy** [comment]
Caused by this bug in docker: https://github.com/docker/docker/issues/9299
