### ISSUE TITLE
"Uncaught ReferenceError: webpackJsonp is not defined" when using 0.11.1

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#800]
The UI loads blank with the 0.11.1 build from dockerhub.

**Comment by tomwilkie** [comment]
Tested on my GCE and on my laptop, image on docker hub is broken.  I think its probably related to vendor.js not being found.

**Comment by tomwilkie** [comment]
I notice that make clean doesn't clean up client/build, might be related (the release process does the build in a fresh checkout, with t a clean client/build)

**Comment by tomwilkie** [comment]
Okay looks like in 0.11.1 we're not building the vendor.js file properly (I just did a fresh checkout and have the same problem).

**Comment by tomwilkie** [comment]
Weird - 0.11.1 was pre vendors.js...

**Comment by tomwilkie** [comment]
Okay this was a caching problem.  When I hit the VM with 0.11.1 with my browser, the browser loaded the HTML from the cache for master, and barfed on not being able to find vendors.js.

I think the problem is with how `esc` deals with caching.  It uses the `If-Modified-Since` header, which is clearly going to return 304 when going from an master build to a release build.  This should really be done with etags.

**Comment by tomwilkie** [comment]
Phew, glad this isn't as serious as I thought.  I was starting to think this was a real bug, and the fact no one reported it was making me question how many users scope has...

**Comment by rade** [comment]
@tomwilkie Is this still an issue?

**Comment by tomwilkie** [comment]
Yes

**Comment by rade** [comment]
@davkal is this still a problem? Why isn't the UI team running into this?

**Comment by davkal** [comment]
> is this still a problem?

We havent changed any of the headers. That's more of a webserver config issue. Changing labels.

> Why isn't the UI team running into this?

We're not having the UI served by scope, but by the dev environment.
