### ISSUE TITLE
Container labels are merged into the container image node when rendering topology

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#815]
```sh
$ docker run -dit --name alpine1 alpine /bin/sh
$ docker run -dit --name alpine2 --label=works.weave.role=system alpine /bin/sh
```

Then go to container-by-image, and you will see that the "alpine" container image is considered a `system` image, because all metadata (including labels) has been merged up from the container nodes.

**Comment by peterbourgon** [comment]
But from the perspective of the container-by-image view, the alpine image _is_ a system image, in the sense that containers using it are system containers. The alternative is to — split images on the axis of classification?

**Comment by paulbellamy** [comment]
> ... in the sense that containers using it are system containers.
If *all* of the containers using it were system containers, I could see that, but in this case they aren't.

Container Images should only be "system" if they themselves have that label.

**Comment by tomwilkie** [comment]
> Container Images should only be "system" if they themselves have that label.

+1

The logic for merging the image labels should be being inherited by this rendered, so this is a structural bug in the code.  Easy to fix.

**Comment by paulbellamy** [comment]
Actually, the whole determination of whether a container image is "stopped" or "running" is just a random selection from one container.

**Comment by tomwilkie** [comment]
Yeah we should remove those filters from that view, they make little sense.

**Comment by paulbellamy** [comment]
Stopped makes sense to me, as it's sort of "show only images in use by >= 1 running containers"

**Comment by tomwilkie** [comment]
I don't mind either way.

**Comment by rade** [comment]
Here's how I ran into this...
```
$ docker run --name=foo -ti alpine /bin/true
$ docker run --name=bar -dti alpine /bin/sh
```
which gives me one stopped and one running container.

When showing 'By Image' and 'stopped' or 'running', a) the count of the image node is 2, when it should only be 1, and b) the node occasionally vanishes (Paul reckons that depends on which branch "won" the merge).

**Comment by tomwilkie** [comment]
For pods/services, we use a different prefix for their labels (to prevent this).  Could do the same for containers & images.
