### ISSUE TITLE
Allow dismissing a disconnected pipe w/ <esc>

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#818]
1. attach
2. do stuff
3. <kbd>ctrl-d</kbd> to disconnect.
4. *move mouse over to close button and click close*

Would be nicer to be able to dismiss disconnected pipe w/ a whack to <kbd>esc</kbd>

**Comment by 2opremio** [comment]
Wouldn't it be better (from the usability point of view) to implicitly disconnect on <kbd>ctrl-d</kbd> ?

**Comment by foot** [comment]
Thats a fun thought!

But:
- Not every disconnected pipe is a initiated by a <kbd>ctrl-d</kbd>. In these other cases we should leave the terminal open w/ an explanation rather than surprisingly closing it.
- Possible to hack this but would rather not:
 - If a pipe is disconnected within 2s of a <kbd>ctrl-d</kbd> being sent consider that a cause and effect.

I think a quick and easy tap to <esc> to close the window is a nice compromise for now.
