### ISSUE TITLE
containers-by-image view collapses all images provided by a docker registry on non-standard port

### ISSUE THREAD

**Issue by kawaja** [weaveworks/scope#820]
When using images from a docker registry on a non-standard port, it looks like the logic to collapse multiple versions of the same image is also collapsing all containers from the registry.

e.g.

    docker-registry.domain.name:5000/image1
    docker-registry.domain.name:5000/image2

are both displayed as docker-registry.domain.name in the containers-by-image view.

adding a version doesn't help:

    docker-registry.domain.name:5000/image3:latest

is also collapsed into docker-registry.domain.name.

**Comment by tomwilkie** [comment]
@kawaja good catch, thanks for the report!  I'll fix this right away.
