### ISSUE TITLE
Missing pod names in kubernetes' pod view

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#822]
<img width="1324" alt="screen shot 2016-01-15 at 3 46 36 pm" src="https://cloud.githubusercontent.com/assets/2362916/12357365/5dcd28b0-bb9f-11e5-8514-7eb481175636.png">

**Comment by tomwilkie** [comment]
Just ran 0.13 with a k8s report and this was not the case.  There is also no report attached.  I think we can probably close this one...

**Comment by tomwilkie** [comment]
I would close but I have witnessed this myself.

**Comment by paulbellamy** [comment]
Could be containers being mapped to an unknown pod?
