### ISSUE TITLE
Add ping/pong protocol to control websocket

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#828]
Reverse proxies like Nginx will close connections (including websockets) after certain application-level inactivity (i.e. tcp keepalive is not good enough). 

In order to avoid this we should add a ping/pong keepalive protocol to the control websocket.

References:

* [Websockets in Ngninx](https://blog.martinfjordvald.com/2013/02/websockets-in-nginx/):

> WebSockets are still affected by proxy_read_timeout which defaults to 60 seconds. This means that if you have an application using WebSockets but not sending any data more than once per 60 seconds you either need to increase the timeout or implement a ping message to keep the connection alive. 

* https://www.reddit.com/r/golang/comments/3bt1ej/gorilla_websockets_start_closing_after_20_clients/cspc6st

**Comment by tomwilkie** [comment]
(I'm not actively working on this, sorry for sitting on the ticket /cc @2opremio)

**Comment by paulbellamy** [comment]
Is this an actual thing we've observed, or just hypothesized?
