### ISSUE TITLE
Web application becomes unresponsive at higher container counts

### ISSUE THREAD

**Issue by bdentino** [weaveworks/scope#830]
I've got scope v0.11.1 (running locally, not using web service) set up on a cluster of 5 hosts, with ~60-70 containers and the web ui seems to be completely unresponsive. The initial scope page loads, but immediately causes the browser tab to lock up and start consuming >100% cpu. I've noticed that this problem goes away when I run on only 1 or 2 hosts (so the container count is only around 20).

Has anyone else seen similar client-side performance issues with larger topologies? 

Relevant Info:
```
Docker version: Docker version 1.9.1, build a34a1d5
Weave version: 1.4.2
Scope command: docker run --privileged -d --name=weavescope --net=host --pid=host -v /var/run/docker.sock:/var/run/docker.sock weaveworks/scope:0.11.1 --probe.docker true
Browser: Chrome version 47.0.2526.106 (64-bit)
```

**Comment by tomwilkie** [comment]
Hi Brian - thanks for the bug report.  We'll take a look at it right away.  /ping @foot

**Comment by foot** [comment]
Thanks for the bug report!

**Comment by bdentino** [comment]
Wow you guys are fast :stuck_out_tongue_closed_eyes: Thanks for the quick fix! Looking forward to the next release

**Comment by tomwilkie** [comment]
Thanks Bryan! We're working on getting the next release out asap.
