### ISSUE TITLE
Uptime monitoring for containers

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#844]
It'd be very cool to see uptime and restart counts expose, Docker API exposes `State.StartedAt` and `RestartCount` which can be used for this quite easily.

**Comment by tomwilkie** [comment]
So easy to add, I might just do it now.  Or do you fancy having a go, @errordeveloper?  Take a look at https://github.com/weaveworks/scope/blob/master/probe/docker/container.go#L308 and https://github.com/weaveworks/scope/blob/master/render/detailed/metadata.go#L23
