### ISSUE TITLE
Confirm user wishes to shutdown `weavescope` container

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#846]
Mention the consequences: Won't be able to use scope anymore!

**Comment by tomwilkie** [comment]
I'm a little worried about hard coding special cases in the UI.

**Comment by foot** [comment]
Yes, true, the UI isn't really "aware" of the controls is it... so it would make sense to implement this in the BE if we were gonna.[0]

Is this an issue for service though? Can you go in and shut down the weavescope container and then be unable to start it again?

[0]
```
{
    probeId: "foo",
    nodeId: "bar;<container>",
    id: "docker_stop_container",
    human: "Stop",
    icon: "fa-stop",
    warning: "Are you sure you want to stop this container? Scope will no longer we accessible" 
}
```
