### ISSUE TITLE
Container ID and Image ID are very long in the details panel

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#864]
<img width="437" alt="screen shot 2016-01-27 at 17 35 30" src="https://cloud.githubusercontent.com/assets/250199/12622270/6635f62c-c51c-11e5-8e17-c55e6164428a.png">

**Comment by tomwilkie** [comment]
Did you do anything special to reproduce this?  I don't see it with master:

<img width="490" alt="screen shot 2016-01-27 at 13 36 37" src="https://cloud.githubusercontent.com/assets/444037/12629081/07fdb41c-c4fb-11e5-9ae4-bd864c18d02d.png">

**Comment by paulbellamy** [comment]
Weird. I do see it on master, with chrome 48.0.2564.97 (64-bit)
