### ISSUE TITLE
UI misbehaves when deploying new version of the App

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#868]
To test the 0.12 release in ECS, I started by deploying the current stable version (0.11.1), opening the UI to see everything was working properly and then deployed the 0.12 candidate **without closing the browser**.

This is the UI talking to version 0.1.1

<img width="1636" alt="screen shot 2016-01-28 at 10 59 22" src="https://cloud.githubusercontent.com/assets/2362916/12642667/2810f3d6-c5af-11e5-9e00-e6993ba00190.png">

This is what happened after deploying the 0.12 candidate without manually reloading the UI. The version tag in the UI updated but the detail panel doesn't work (there's an infinite spinning wheel) because the detail panel data structures changed in 0.12 but the the javascript files were not reloaded (i.e. the browser still had the ones from 0.11.1):

<img width="1620" alt="screen shot 2016-01-28 at 11 02 52" src="https://cloud.githubusercontent.com/assets/2362916/12642773/d35fa692-c5af-11e5-882e-808aec5471a1.png">

This is understandable to certain extent, but the UI didn't work after reloading the page either. 

I needed to do an "Empty Cache and Hard-reload" in Chrome to make it work, which is strange because I see that all the javascript files (at least in 0.12) are served with `cache-control:no-cache`

An easy solution would be forcing a UI-reload when a version change is detected but I don't know if that would solve the caching problem.

**Comment by davkal** [comment]
Yeah, that is an important issue. Let's do bundle fingerprinting and display an info message when a change in version in `/api` is detected.

**Comment by pidster** [comment]
Would it be preferable to consider this to be part of an API versioning & compatibility problem?

**Comment by 2opremio** [comment]
This is still a problem when upgrading the app, even after #1354 

In the example below, the app is using Scope 0.15, which introduced the search-bar. However, the search bar is missing ...

<img width="1692" alt="screen shot 2016-05-20 at 4 50 26 pm" src="https://cloud.githubusercontent.com/assets/2362916/15435357/a5967788-1eb3-11e6-9948-f0682e80b72e.png">

... and it only started appearing after wiping the cache and hard reload.

This is particularly important for the service, during the upgrade of the user apps from 0.13.1 to 0.15 the UI completely stopped working.

**Comment by davkal** [comment]
Stand-alone scope is not affected anymore. Having a look at the nginx config...
