### ISSUE TITLE
Internet node disappears intermitently

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#869]
While testing the 0.12 release candidate with the demo from the [ECS guide](http://www.weave.works/guides/service-discovery-and-load-balancing-with-weave-on-amazon-ecs-2/), I noticed that the Internet node appears and disappears intermittently.

With the internet node:

<img width="1635" alt="screen shot 2016-01-28 at 11 30 56" src="https://cloud.githubusercontent.com/assets/2362916/12643773/14eb2374-c5b6-11e5-81b4-14c0cea575c2.png">

Without the internet node:

<img width="1639" alt="screen shot 2016-01-28 at 11 33 07" src="https://cloud.githubusercontent.com/assets/2362916/12643792/3fe76a56-c5b6-11e5-8080-46c1bb98c116.png">

Reports:  https://gist.github.com/2opremio/ade096664382800cf38b

**Comment by rade** [comment]
Is this simply due there not being any connections from the Internet for the duration of the app window? If so, #1674 and #1676 should address that.

**Comment by 2opremio** [comment]
Related to https://github.com/weaveworks/scope/issues/1846 ?

**Comment by rade** [comment]
I don't think there's more to this than there simply not being any connections or only short-lived connections, in which case it's a dup of #1250.
