### ISSUE TITLE
Incorrect container counts in 'By Hostname' view

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#870]
While testing the 0.12 candidate with the [ECS guide](http://www.weave.works/guides/service-discovery-and-load-balancing-with-weave-on-amazon-ecs-2/) demo I've noticed that the container-count labels of the nodes from the 'By Hostname' view is wrong.

There are 3 containers mapped to `httpserver.weave.local` and another 3 mapped to `dataproducer.weave.local`, but the labels read `7 containers` and `9 containers`:

<img width="1628" alt="screen shot 2016-01-28 at 12 10 26" src="https://cloud.githubusercontent.com/assets/2362916/12644082/433fe8fc-c5b8-11e5-8ae6-3b090d784abf.png">

<img width="1621" alt="screen shot 2016-01-28 at 12 13 48" src="https://cloud.githubusercontent.com/assets/2362916/12644189/02f06a3c-c5b9-11e5-9d31-8ead5383312a.png">

Note how the detail panes correctly list 3 containers each.

Report: https://gist.github.com/2opremio/0cf5a67a4bd56717b9ea

Container view:

<img width="1630" alt="screen shot 2016-01-28 at 12 08 36" src="https://cloud.githubusercontent.com/assets/2362916/12644220/4a8437d4-c5b9-11e5-8faf-70d2bfee95a6.png">

**Comment by tomwilkie** [comment]
This need to be fixed before 0.12 goes out.  I'll have a stab today.

**Comment by 2opremio** [comment]
In case it helps, the 'By image' view is also affected:

<img width="1630" alt="screen shot 2016-01-28 at 16 23 31" src="https://cloud.githubusercontent.com/assets/2362916/12650656/85118ae2-c5db-11e5-9eba-90e9be1ba002.png">
