### ISSUE TITLE
Mismatching details pane color for host nodes

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#871]
I found this while testing the 0.12 candiate. Note how the nodes are redish and the details pane is purple:

<img width="1617" alt="screen shot 2016-01-28 at 12 37 52" src="https://cloud.githubusercontent.com/assets/2362916/12644648/4da6b696-c5bc-11e5-97ac-9431a1faca87.png">

I recall @davkal fixed this for all nodes in https://github.com/weaveworks/scope/issues/684 so it's probably a regression.

**Comment by 2opremio** [comment]
Report to reproduce: https://gist.github.com/2opremio/4c4abb2e11f3ed313d47

**Comment by foot** [comment]
We're not getting a `rank` in the details response for hosts, so I'm not sure if this is a BE or FE bug.

We can use the `label` in absence of `rank` but I'm not sure if thats the best way to go? @2opremio 

`http://localhost:4042/api/topology/hosts/host%3Aweave-1`:
```js
{
node: {
id: "host:weave-1",
label: "weave-1",
linkable: true,
metadata: [],
metrics: [],
controls: [ ],
children: [],
parents: []
}
}
```

vs `http://localhost:4042/api/topology/containers-by-hostname/604f4ecb0608`:

```js
{
node: {
id: "604f4ecb0608",
label: "604f4ecb0608",
linkable: false,
rank: "604f4ecb0608",
controls: [ ],
children: [],
parents: []
}
}
```

**Comment by foot** [comment]
The host topo doesn't get a rank, so I'll update our details panel color lookup stuff to behave more like the topo-node color lookup.
