### ISSUE TITLE
Add arrow heads to edges

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#872]
Feedback from Darren at Rancher.

**Comment by davkal** [comment]
Arrow heads will only look nice, if they end at the outer border of a node. Otherwise the inner node dot will be crowded. For proper arrow offset to end at the border, we need to calculate those endpoints. It's easy for circles, but more tricky for rects with rounded corners.

**Comment by pidster** [comment]
If edges are directional it makes sense to visualise this for the user to see.
If arrowheads in contact with the node are hard, a V just before the end might work.
Would be worth trying it out.

**Comment by tomwilkie** [comment]
Edges are directional.

**Comment by jml** [comment]
I didn't realize that "down" meant "connects to". Adding arrowheads (or some sort of symbol for indicating direction) could be quite helpful.

**Comment by rade** [comment]
> Arrow heads will only look nice, if they end at the outer border of a node.

As a (temporary) alternative we could render arrow heads at the mid-point of an edge.

**Comment by rade** [comment]
This can be closed, right?
