### ISSUE TITLE
Improve contrast of scope UI

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#874]
Given a lot of demos, and on most projectors and TV the scope UI is hard to see as the contrast isn't high enough.

**Comment by foot** [comment]
Which parts of the UI suffer the most? Don't have a projector you could take a quick photo? :). Wonder if you can simulate that on a mac screen... maybe there is a app for that.

**Comment by davkal** [comment]
Yeah, which parts @tomwilkie ? Contrast is a sensitive issue. If everyone screams nobody gets heard.

**Comment by tomwilkie** [comment]
Its more of just a general concern.  I don't think the grey background is helping.  I'll try and get some photos.

**Comment by foot** [comment]
A little bit related but the UI behaves itself quite well w/ browser zooming.

**Comment by tomwilkie** [comment]
I did have a few centring issues when switch topologies with zooming.
