### ISSUE TITLE
Make it clear which nodes have incoming connections and which nodes have outgoing connections when you have a node selected

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#875]
Something like this (when viewing the detail panel):

<img width="718" alt="screen shot 2016-01-28 at 17 11 10" src="https://cloud.githubusercontent.com/assets/444037/12664129/2a6c0dae-c5e2-11e5-8bfa-90edc41702e1.png">

I think this will make it super obvious what containers / process etc something is talking to, and what container / process is talking to it.

**Comment by tomwilkie** [comment]
If you combine this with some kind of semantic colouring, this might be interesting way to answer the question "why is this container sick".

What do you think @davkal @foot @paulbellamy?

**Comment by paulbellamy** [comment]
I would be more in favour of this if "incoming" vs "outgoing" was more than a guess, but even determining what that means is tricky.

**Comment by tomwilkie** [comment]
conntrack'd connections have direction: #539

**Comment by davkal** [comment]
I like it, though arrow offset will have to be calculated differently for all new shapes.

**Comment by tomwilkie** [comment]
This also came up with Darren from Rancher.

**Comment by paulbellamy** [comment]
> conntrack'd connections have direction: #539

But most connections are not conntrack'd (only short-lived ones are), no?

**Comment by tomwilkie** [comment]
Actually almost all connections are conntracked, the set of ones detected
by proc spy and not by conntrack is almost nil.

**Comment by tomwilkie** [comment]
Edge direction is now even more meaningful: we get them from conntrack.  @davkal do you think this is something we could have a go at (even without arrow heads)?

**Comment by pidster** [comment]
+1 for adding a visual indicator for direction, to edges.

**Comment by rade** [comment]
How is this different from #872?

**Comment by tomwilkie** [comment]
> How is this different from #872?

This is talking about the "selected" mode, where as #872 is in the general canvas.

Also this suggestion is about changing the location of the nodes (incoming at the top, outgoing at the bottom) when you select a node, whereas #872 is just about adding a direction indicator for edges on canvas.

**Comment by rade** [comment]
> Also this suggestion is about changing the location of the nodes (incoming at the top, outgoing at the bottom) when you select a node

I like that, and it's something that could be done independently from tackling the thorny/controversial issue of adding arrow heads.

**Comment by jpellizzari** [comment]
Related to #1636

**Comment by jpellizzari** [comment]
This is mostly accomplished by #2317. Concepts involving re-arranging the nodes were unsuccessful, as it lead to very unbalanced "sides" of the diagram which lead to difficult to read diagrams. Closing.
