### ISSUE TITLE
Wrapping of container id in details panel

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#90]

**Comment by tomwilkie** [comment]
![wrapping](https://cloud.githubusercontent.com/assets/444037/7770255/5d08836a-0084-11e5-991c-97df04bda6fe.png)

**Comment by peterbourgon** [comment]
Can we just truncate that to the first 7 characters, in the short term?

**Comment by peterbourgon** [comment]
And why is one Origin Process showing rows in the order (Container ID, Container name), where the other has the order (Container name, Container ID)? Origin Process tables should be deterministic and stable, in fact we rely on that to deduplicate. Is it from an earlier version where you maybe had implemented the rows as maps?

**Comment by tomwilkie** [comment]
> Can we just truncate that to the first 7 characters, in the short term?

The fix has the browser do the truncate for you.

> And why is one Origin Process showing rows in the order...

The screenshot is from before you fixed that.

**Comment by peterbourgon** [comment]
> The fix has the browser do the truncate for you.

:100:

> The screenshot is from before you fixed that.

Whew :relieved:
