### ISSUE TITLE
Details panel number renders

### ISSUE THREAD

**Issue by foot** [weaveworks/scope#902]
Round the memory renderer

![screen shot 2016-02-02 at 14 40 59](https://cloud.githubusercontent.com/assets/22008/12751036/18d4a768-c9bb-11e5-9c73-ca16afcaa98d.png)

**Comment by foot** [comment]
![screen shot 2016-02-02 at 14 43 47](https://cloud.githubusercontent.com/assets/22008/12751100/7baac886-c9bb-11e5-91c0-54599dec3e0a.png)

**Comment by davkal** [comment]
This was fixed by #795
