### ISSUE TITLE
Add "container" topology

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#91]
Group together processes in the same container.

**Comment by peterbourgon** [comment]
How would you like to deal with processes that aren't in a container? Show them individually, hide them altogether, or group them on another criteria?

**Comment by tomwilkie** [comment]
Not sure.  Thinking it through:
- show them individually will be confusing, as you've just selected "containers" and now we're showing you containers and processes.  
- group under "other" tends to be a bad answer in general

So I guess not showing them.  Although I guess this should probably be the default view, in which case we might want to rethink?

**Comment by peterbourgon** [comment]
- Group them all together under "Uncontained" — this name amuses me
- Group them by origin host, maybe annotate/highlight somehow to indicate they're not containers...

**Comment by tomwilkie** [comment]
Would also be nice to add an images topology (ie group everything together that uses the same docker image)

**Comment by tomwilkie** [comment]
Of course, there are other links you could add for images (docker images --tree)

**Comment by peterbourgon** [comment]
A rendered topology (or rather, the MapFunc used to render it) may optionally be _grouped_, meaning the cardinality of the output set is further reduced. In the Applications topology, if you make it grouped, we throw away the PID information and render nodes based on process name. So all your Javas are one process, all your Chromes, etc. We can leverage that in the Container topology, too: I propose that the grouped mode will combine all containers running the same container image. Sound good?

**Comment by tomwilkie** [comment]
SGTM
