### ISSUE TITLE
Host detail panel needs improvement

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#910]
<img width="420" alt="host-details" src="https://cloud.githubusercontent.com/assets/303151/12780215/693acfda-ca64-11e5-8c52-5afa2897770d.png">

There's a link in the header "default" under the title "Default" that doesn't do anything. This should be removed.

The networks listed in the info table are truncated.

The current ordering of parts in the Host detail panel is:
- Status: sparklines
- Status: info table
- Container image list
- Containers
- Applications

In my case, this places a long list of (in some cases dormant)
 container images above the list of containers that are actually running. What problem does this solve?

This whole panel needs a rethink.

**Comment by paulbellamy** [comment]
> There's a link in the header "default" under the title "Default" that doesn't do anything. This should be removed.

That's a bug

> The networks listed in the info table are truncated.

Sure, we could move them to a separate table, but most of the info you need from this might be contained in a set of connection summary information.

> Container image list is not useful (or less useful than others)

Agreed

> This whole panel needs a rethink.

Seems like an overreaction

**Comment by tomwilkie** [comment]
> There's a link in the header "default" under the title "Default" that doesn't do anything. This should be removed.

#917

> The networks listed in the info table are truncated.

#927 - not obvious what to do here (separate table vs something else) so broken it out on to another ticket for discussion.

> Container image list is not useful (or less useful than others)

#923
