### ISSUE TITLE
Make it more obvious which topology you're looking it

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#915]
#884 will help here, but we could also make the topology selection at the top more visible.

Matthias said "when watching somebody use scope, I am confused as to whether I am looking at processes, containers, images, hosts"

**Comment by davkal** [comment]
weaveflux styles decided on a highlighting that I will use

![screen shot 2016-02-05 at 16 06 20](https://cloud.githubusercontent.com/assets/859729/12849961/95a7f39e-cc22-11e5-89cc-311fb7ef3b87.png)
