### ISSUE TITLE
CPU/Memory usage stats do not agree with the children

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#922]
Need to figure out what top does - ie I think tops takes a 5 second moving average, and we take a 1 sec moving average.

**Comment by paulbellamy** [comment]
Probably worth looking at what https://github.com/uber-common/cpustat does

**Comment by tomwilkie** [comment]
Dupe of #1133 

(Generally I close the later, but in this case #1133 has more info & discussion, so closing this one).
