### ISSUE TITLE
Get coverage metrics for client code

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#93]

**Comment by davkal** [comment]
Do you mean test coverage?

**Comment by tomwilkie** [comment]
Yes

**Comment by davkal** [comment]
Cool, I can set up https://github.com/karma-runner/karma-coverage
Where is this output supposed to go?

**Comment by tomwilkie** [comment]
Ideally you'd merge it into the coverage output from bin/test, if possible.

**Comment by davkal** [comment]
This could be the way forward: https://github.com/deepsweet/istanbul-instrumenter-loader
