### ISSUE TITLE
Launching a terminal fails with "Content-Type specified (plain/text) must be 'application/json'"

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#942]
Since the Docker 1.10, Compose 1.6 update, and with this example project: [https://github.com/pidster/apache-geode-docker](https://github.com/pidster/apache-geode-docker), launching a terminal on any container node fails with the above content-type error message.

pidster@tachyon:pidster/apache-geode-docker/v2 (master u=)$ docker version
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d510
 Built:        Fri Feb  5 08:21:41 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 19:55:25 2016
 OS/Arch:      linux/amd64

pidster@tachyon:pidster/apache-geode-docker/v2 (master u=)$ docker-compose version
docker-compose version 1.6.0, build unknown
docker-py version: 1.7.0
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zg 14 July 2015

<img width="1199" alt="content-type-error" src="https://cloud.githubusercontent.com/assets/303151/12885469/2042a264-ce5e-11e5-965b-d74e8cf84e26.png">

**Comment by peterbourgon** [comment]
I'm also experiencing this buggy bug.

**Comment by foot** [comment]
Issue is in go-dockerclient, has been fixed there https://github.com/fsouza/go-dockerclient/issues/455. Needs a version bump in `scope/vendor`.
