### ISSUE TITLE
Docker labels are too verbose when first opening the details panel

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#945]
Relative to their usefulness, they take up a lot of space.

We should either have a collapsed table, or put them into some sort of collapsed row.

Should probably be handled similarly to "Ports", "IPs", and "Local Networks".

**Comment by paulbellamy** [comment]
We could also:
b) move them to the bottom of the panel
c) remove them (are they ever useful?)

**Comment by paulbellamy** [comment]
@pidster opinions?

**Comment by foot** [comment]
Mmm, the label itself is really a value. A table like the process one might make one sense, which is co-incidentally less white-space heavy.

label | value
---------|---------
| WORKS.WEAVE.ROLE | system

We could also chuck em down them bottom

**Comment by paulbellamy** [comment]
@davkal is this fixed then? or being closed in favour of something else?

**Comment by davkal** [comment]
Fixed via #941

**Comment by paulbellamy** [comment]
That only moves the container-images table down to the bottom. The docker labels are still prominent and verbose.
