### ISSUE TITLE
Empty 'processes by name' view

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#947]
My "processes by name" view is empty whilst I don't think it should.

<img width="1501" alt="screen shot 2016-02-09 at 10 11 39" src="https://cloud.githubusercontent.com/assets/2362916/12913280/a5b33c44-cf15-11e5-9e89-36e27998730e.png">

Report: https://gist.github.com/2opremio/e6a9751b1bdc7e08e7e0

**Comment by foot** [comment]
`lodash`, the dagre dep [0] is trying to be a bit fancy w/ `_.has`, it interprets the leading . as a path and fails to initialise its "rank" property (internal to dagre not our rank).

In this dump the conflicting nodes are: `./hyperkube` and `/hyperkube`.

`lodash` tries to be clever if it thinks the key looks like a path[1]. It is doubtful we can easily get a nice change back into `dagre` promptly, the hack would be to make the keys only use \w+. Base64 encode/decode is an option... Having a think about others.

```javascript
_.has({"/a":1 }, "./a")
true
```

[0]
```JSON
"dependencies": {
    "graphlib": "^1.0.5",
    "lodash": "^3.10.0"
}
```

[1]
```javascript
var reIsPlainProp = /^\w*$/;

function isKey(value, object) {
  var type = typeof value;
  if ((type == 'string' && reIsPlainProp.test(value)) || type == 'number') {
    return true;
  }
  if (isArray(value)) {
    return false;
  }
  var result = !reIsDeepProp.test(value);
  return result || (object != null && value in toObject(object));
}
```
