### ISSUE TITLE
Crash on weave tagger

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#955]
```
panic: runtime error: slice bounds out of range

goroutine 42 [running]:
github.com/weaveworks/scope/probe/overlay.(*Weave).Tag(0xc82012eb80, 0xc8213d5380, 0xc8213d53b0, 0xc8213d53e0, 0xc8213d5410, 0xc8213d5440, 0xc820fc6510, 0xc820fc6540, 0xc820fd66f0, 0xc820fd6840, ...)
        /go/src/github.com/weaveworks/scope/probe/overlay/weave.go:139 +0x85a
github.com/weaveworks/scope/probe.(*Probe).tag(0xc8200a59e0, 0xc8213d5380, 0xc8213d53b0, 0xc8213d53e0, 0xc8213d5410, 0xc8213d5440, 0xc820fc6510, 0xc820fc6540, 0xc820fd66f0, 0xc820fd6840, ...)
        /go/src/github.com/weaveworks/scope/probe/probe.go:160 +0x200
github.com/weaveworks/scope/probe.(*Probe).spyLoop(0xc8200a59e0)
        /go/src/github.com/weaveworks/scope/probe/probe.go:111 +0x184
created by github.com/weaveworks/scope/probe.(*Probe).Start
        /go/src/github.com/weaveworks/scope/probe/probe.go:85 +0x58
```

**Comment by 2opremio** [comment]
I don't get this behavior with 26ccb4918b15d363c50fd206421dc21feffd2c17 so it was introduced in #867

**Comment by paulbellamy** [comment]
How did you generate a container node without a container ID?

**Comment by 2opremio** [comment]
I am not sure. This was done with kubernetes on the service (Docker 1.7.1). Maybe the problem comes from the docker library upgrade?

**Comment by 2opremio** [comment]
BTW, the Kubernetes cluster is not running Weave,

**Comment by 2opremio** [comment]
Actually, @errordeveloper reports it happens on 0.12 too, same line https://github.com/weaveworks/scope/blob/v0.12.0/probe/overlay/weave.go#L214 

See https://weaveworks.slack.com/files/ilya/F0MKVV6M9/scope_log.txt

I believe he is using Kubernetes with Weave Net and Docker 1.10

I am using Kubernetes without Weave. I didn't see it until #867 because that change enables the weave tagger by default  in case Weave gets started after Scope. Before that, the tagger would only run if a Weave network is detected on startup (which is @errordeveloper's scenario). 

We obviously need to fix that lookup and slice-size assumption but it would be good to investigate why this is failing in specifically in Kubernetes. I will take it up

**Comment by errordeveloper** [comment]
Besides `slice bounds out of range`, I've also seen some `invalid memory address or nil pointer dereference`. You might like to take at the [complete log that I've captured](https://weaveworks.slack.com/files/ilya/F0ML19W9W/scope-1455661827.log.xz).

**Comment by 2opremio** [comment]
@errordeveloper That's a separate issue I have just created https://github.com/weaveworks/scope/issues/977

**Comment by 2opremio** [comment]
@errordeveloper Actually, now that I think about it, #977 may be caused as a side-effect of this crash. We should be resilient towards empty events. but it would be good if you could test #976 and see if #977 goes away.

**Comment by errordeveloper** [comment]
> Actually, now that I think about it, #977 may be caused as a side-effect of this crash.

Makes a lot of sense.

**Comment by errordeveloper** [comment]
@2opremio as you aske for Docker version on Slack, it's 1.10 (don't recall whether I have bumped to 1.10.1 at the time or it was still 1.10.0).

**Comment by 2opremio** [comment]
yep, I knew:

> I believe he is using Kubernetes with Weave Net and Docker 1.10
