### ISSUE TITLE
restarting containers shown as 'running'

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#970]
running 0.12...

![screenshot from 2016-02-17 14 00 47](https://cloud.githubusercontent.com/assets/109109/13111659/e072e5c2-d57e-11e5-9d58-bc0ab9e861a9.png)

Notice how the state is shown as 'running', yet there is none of the information - metrics, applications, etc - I'd expect to see of a running container. And the reason is that the container isn't *actually* running. It was started with
```
$ docker run --restart=always -dti ubuntu sleep 0.2
```
and is currently restarting.

`docker inspect` shows

```
...
        "State": {
            "Status": "restarting",
            "Running": true,
            "Paused": false,
            "Restarting": true,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-02-17T14:01:45.304670287Z",
            "FinishedAt": "2016-02-17T14:01:45.521808095Z"
        },
...
```

NB: State.Status is a new(ish) field; older Dockers don't have it.

**Comment by paulbellamy** [comment]
State.Status is also not present in the docker client library we're using, so probably want to update that.

**Comment by rade** [comment]
The alternative is to look at the combination of State.Running and State.Restarting, since that works across versions. That's what we are doing in Weave Net.

**Comment by paulbellamy** [comment]
and State.OOMKilled, and State.Dead....

**Comment by rade** [comment]
> and State.OOMKilled, and State.Dead....

I am pretty sure State.Running=false for these.

**Comment by paulbellamy** [comment]
ah. Will check what docker does

**Comment by paulbellamy** [comment]
Docker has a nice function for converting the container state into a human-readable string (used in `docker ps`). So we *could* show the state as: e.g. `Restarting (0) 17 seconds ago`, and `Up 23 hours`. Or we could show something like: `running`, `paused`, `restarting`, etc...
Either way we have to update the go-dockerclient library. I quite prefer the more human-readable versions for display in the UI.
