### ISSUE TITLE
Compile ugorji/go/codec with -tags unsafe for higher performance

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#972]
Followup of https://github.com/weaveworks/scope/pull/916 . 

Using `codecgen` with flag `-u` like we are doing may be sufficient, but it may be worth investigating if building `ugorji/go/codec` with `-tags unsafe` on top of that helps. It currently breaks encoding though.

See:
* https://github.com/ugorji/go/issues/141#issuecomment-185130876
* https://github.com/weaveworks/scope/pull/916#issuecomment-183289718

**Comment by ugorji** [comment]
@2opremio please re-sync and try again. I just pushed 2 changes that should carry you over (see ugorji/go#141 ).

There are 2 places that -tags=unsafe comes into play:
- stringView: called when decoding a struct field name, where we read a []byte, and don't want to incur unnecessary conversion/copy
- bytesView: called when encoding a string AS-IS, passing it to a io.Writer.Write([]byte) method, but we don't want to incur an unnecessary conversion/copy

We have 2 versions of a helper class: helper_(not_)unsafe.go . By default (without the -tags=unsafe), the conversion is done regularly. With -tags=unsafe, we just use unsafe to do a convert without copy.

Beyond this, codecgen can use unsafe for same reason as stringView above, when you pass it the -u flag.

Do the following:
- go install -tags=unsafe github.com/ugorji/go/codec
- codecgen -u ...

If you still see issues, please tag me and say what "this garbage" is, and give me something concrete that I can make some blind but educated guesses based off of. I wouldn't have cycles to wade through weaveworks, so will need you to do some of that analysis to isolate where the issue may be.

Hope this helps.

**Comment by 2opremio** [comment]
Closing this since, although @ugorji was kind enough to fix the "garbage" problem in https://github.com/ugorji/go/commit/9f21f8ea305046b8d17a799e2c73069533a99d24 ,I tested compiling with `-tags unsafe` and it doesn't reduce the CPU consumption. 

It doesn't help us because we are already using `codecgen -u` and we implement Selfers for all the interfaces we generate. See https://github.com/ugorji/go/issues/141#issuecomment-185481673

**Comment by 2opremio** [comment]
Reopening since https://github.com/ugorji/go/issues/143 shows it will remove some garbage.
