### ISSUE TITLE
Remove dependency on github.com/2opremio/go-1/codec

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#973]
As a followup on https://github.com/weaveworks/scope/pull/916#issuecomment-185168685

**Comment by 2opremio** [comment]
@ugorji Has very efficiently solved all the bugs I reported and changed the selfer-generation behaviour of codecgen so that we don't need the `// codecgen: skip` of github.com/2opremio/go-1/codec.

In particular he has implemented *"do not create Selfer for types which already have implemented"* (https://github.com/ugorji/go/commit/5d64d76d3ac4d5450009b0f5fa1530b790fccc71), which is great but, due to the detection being reflection-based, it can break serialization of embedded-types if the code-generation is not done in a careful order.

See https://github.com/ugorji/go/issues/141#issuecomment-185450157

The solutions to this are:
* Being super careful about the code-generation order, always removing all the previously generated files before re-generating any of them.
* Stop using embedded types in our code.

@peterbourgon , @paulbellamy Thoughts?

**Comment by peterbourgon** [comment]
I wish I had caught the introduction of embedding in JSON-serialized types at PR review, I would have flagged it. tl;dr: it is a category error to use embedding in types that will be JSON serialized (AFAIK this was an invariant prior to the controls work) and we should absolutely eliminate all embedding in all types that will be serialized.

**Comment by 2opremio** [comment]
I agree. That's the solution @ugorji was implicitly suggesting.

**Comment by 2opremio** [comment]
Alright, I will:

* Bump ugorji to get the fixes
* Remove the embeddings (I can't still believe how broken Golang is in this respect)
* Remove github.com/2opremio/go-1/codec

@peterbourgon Sounds good?

**Comment by 2opremio** [comment]
Also, Golang doesn't seem to have have any tags to inline JSON (e.g. Jackson's [`@JsonUnwrapped`](http://fasterxml.github.io/jackson-annotations/javadoc/2.0.0/com/fasterxml/jackson/annotation/JsonUnwrapped.html), so removing the embedding will change the JSON schema and will require changes in the UI. 

@foot Would you mind helping me out with this?
