### ISSUE TITLE
streamline bug submission from UI

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#988]
We often ask a user to capture the JSON report for their current view.

Similar to, or perhaps using the new 'bug' button, this could be automated for the user and submitted either to a private hosted service (to protect potentially sensitive details) or encrypted and appended to an auto generated bug report as an attachment.

- [x] Download report as doc / zipped JSON
- [ ] Optionally auto-submit to a Weave service

**Comment by errordeveloper** [comment]
Currently taking a screenshot and submitting may result in different data in the report, as it may have changed while user gone a fetched the report after taking a screenshot.

**Comment by errordeveloper** [comment]
Looks like we should be able to use anonymous gists (subject to size limits), if gitreports.com cannot do it.

**Comment by rade** [comment]
There's a button in the UI now for downloading the JSON report.

So I think this issue should be about streamlining the bug submission process, e.g. automatically attach json and screenshot.

**Comment by rade** [comment]
dup of #992.
