### ISSUE TITLE
Filtered nodes in Processes cause frustration

### ISSUE THREAD

**Issue by davkal** [weaveworks/scope#991]
From peter and matthias:

> "Unconnected nodes hidden - 16 nodes (332 filtered)" - how do I unhide them? The UI language rather suggests that unhiding/unfiltering should be possible.
> 
> I agree that we should change that to e.g. "16 nodes (332 unconnected nodes hidden)" or something
> Or just show "16 nodes" and only show "16 nodes visible, 332 unconnected nodes invisible" on hover or something

We should change the text to clarify why they are hidden, and why they cant be shown.

**Comment by rade** [comment]
See also #713.

**Comment by davkal** [comment]
How about:

10 NODES (115 FILTERED)
[Unconnected nodes hidden]

changed to:

10 NODES (115 FILTERED)
[Unconnected nodes filtered]

w/ tooltip: "Unconnected processes are automatically filtered."

**Comment by tomwilkie** [comment]
With the new ui optimisations, could we add an option for show unconnected
nodes?
