### ISSUE TITLE
Upgrade to go 1.6

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#999]
Release notes: https://golang.org/doc/go1.6

* lint will break as they fixed a bug in gofmt (golang/go#12066).
* Adds HTTP2 support.
* ~~The reflect package changes might break the json encoding~~ (not as per https://github.com/ugorji/go/issues/144)

**Comment by tomwilkie** [comment]
Lets do this after 0.13.

Change should be as simple as changing the build container.

**Comment by paulbellamy** [comment]
:+1:
